### ISSUE TITLE
AppendChild method in 3.1.1

### ISSUE THREAD

**Issue by chaitanya509** [anshooarora/extentreports-java#1000]
Hi,

I am looking for AppendChild method in 3.1.1 but looks like it is deprecated, could be please let me know how to append child to the parent test ?

Thanks 
Chaitanya

**Comment by karthikbhatnagar** [comment]
That was in version 2.  You need test.createNode in version 3. Refer docs.

**Comment by email2vimalraj** [comment]
@chaitanya509 : Hope @karthikbhatnagar comment helped you. Closing this issue, kindly re-open in case you have further issues.
