### ISSUE TITLE
'But' keyword does not show up in report.

### ISSUE THREAD

**Issue by aukevanleeuwen** [anshooarora/extentreports-java#1002]
## Summary

`But` keyword does not show up in report.

## Expected Behavior

Steps with `But` keyword should end up in the report.

## Current Behavior

Using the following formatter plugin for `cucumber-jvm`: https://github.com/sitture/cucumber-jvm-extentreport I don't see the steps using the keyword `But` in the report. It also fails with the following error: `Something went wrong while trying to parse the Gherkin keyword for this step: java.lang.ClassNotFoundException: com.aventstack.extentreports.gherkin.model.But`. 

Although the error is probably from the cucumber-jvm plugin, the model is taken from this repository as far as I can see. It does seem to be lacking.

---

I've tried to quickly fix this in a PR, but I had a bunch of tests failing. I don't quite understand why but it appears that there are more tests running in my IDE as there are on the commandline. Have a look at the tests that are run with `mvn`, it doesn't include, for example, `com.aventstack.extentreports.api.GherkinKeywordTests`.

**Comment by karthikbhatnagar** [comment]
But is not a model keyword right now so you can add it by sending pull req. 
https://github.com/anshooarora/extentreports-java/tree/master/src/main/java/com/aventstack/extentreports/gherkin/model

**Comment by anshooarora** [comment]
@aukevanleeuwen are you picking this feature?  If not, I will start working on it.

**Comment by aukevanleeuwen** [comment]
@anshooarora sorry I currently don't have time for this yet. I've looked into it a bit. Adding the class is not the issue, but I saw lots of test cases and javadoc that were mentioning the other classes (`And`, `Given`, ...) so that'll take a bit too much time at the moment.
