### ISSUE TITLE
Change screen capture thumbnail width?

### ISSUE THREAD

**Issue by brianbautista** [anshooarora/extentreports-java#1006]
## Summary

Is there a way to change the default width of 10% to something to my liking?  10% is far too small for my screenshot thumbnails.
Currently, it is hardcoded to 10% as shown below in the permalink.

https://github.com/anshooarora/extentreports-java/blob/9737f27f0ce7549c4eec6845d08cd4db87d79bb3/src/main/java/com/aventstack/extentreports/model/ScreenCapture.java#L11

## Environment Details

* Extent report Version used: v3.1.2
* Operating System and version: High Sierra 10.13.2
* JDK Version: n/a

**Comment by karthikbhatnagar** [comment]
I think it is possible with JavaScript. 
Css may not work because width is applied to the element.
@anshooarora - can we remove width and add a class to it?

**Comment by brianbautista** [comment]
Indeed I was able to override the thumbnail size via CSS :)

Add the following to the styles section
>  .step-details > img { width: 30%; }
