### ISSUE TITLE
Same screenshot for all steps in ExtentReport

### ISSUE THREAD

**Issue by akhiljosephk** [anshooarora/extentreports-java#1011]
In the ExtentReportHelper class, for  every step I am trying to take a screen shot and attach to the same step, unlike to add as `test.log(Status.INFO, screenshot);`

```
public  void StepPass(String Description) throws IOException {
       if (test != null) {
            test.pass("Pass - " + Description +  ,MediaEntityBuilder.createScreenCaptureFromPath(captureScreenShot()).build());         
  }     
 }
```
In the local report that gets created after execution, the screenshots are attached correctly.(Refer Screenshot: Local.png)

But when I see the same report in ExtentX, for all the steps, the last taken screenshot is getting attached(Refer : ExtentX.png)
![local](https://user-images.githubusercontent.com/29649102/34828483-b1aaafec-f703-11e7-80ee-a41acf6fe2ab.png)
![extentx](https://user-images.githubusercontent.com/29649102/34828494-b887fd60-f703-11e7-88a5-b1b87c7d1734.png)

**Comment by akhiljosephk** [comment]
@anshooarora  Looking forward for your help here !!

**Comment by anshooarora** [comment]
ExtentX is no longer supported.  Please upgrade to 3.1.2 of the API and latest version of Klov.
