### ISSUE TITLE
How to add screenshot at each step in the same test case?

### ISSUE THREAD

**Issue by vvd619** [anshooarora/extentreports-java#1013]
I am using TestNG framework and I have a test case where I am taking screenshot at each step and pushing to report. But when report is generating I am unable to see attached snapshot at each step instead they are at the bottom aligning in a single line.

## Expected Behavior
I am expecting screenshot should get attached at each step
## Current Behavior
Screenshot getting attached at the bottom aligning in a single line.

## My code:
package Automation.CET;

import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import utilities.GenericUtility;

public class Test1 {
   public WebDriver driver;
   public ExtentHtmlReporter htmlextent = null;
   public ExtentReports report = null;
   public ExtentTest log = null;

    @BeforeTest
    public void beforetest(){
	System.setProperty("webdriver.chrome.driver",GenericUtility.getPropertyFileValue("globalVariables", "Driverpath")+"chromedriver.exe");
	driver = new ChromeDriver();
	htmlextent = new ExtentHtmlReporter("D://Automation_Reports//extentdemo.html");
	report = new ExtentReports();
    }
    @BeforeMethod
    public void beforemethod(){
	report.attachReporter(htmlextent);
    }
    
    @Test
    public void testcase2(){
	log = report.createTest("testcase2");
	driver.get("https://www.google.com/");
	try {
	    log.log(Status.INFO, "Google Page opened"+log.addScreenCaptureFromPath(captureScreen()));
	    log.log(Status.PASS, "Passed test 2"+log.addScreenCaptureFromPath(captureScreen()));
	} catch (Exception e) {
	    e.printStackTrace();
	}
    }
    
    @AfterTest
    public void aftertest(){
	driver.quit();
	report.flush();
    }
    public String captureScreen() throws IOException {
	TakesScreenshot screen = (TakesScreenshot) driver;
	File src = screen.getScreenshotAs(OutputType.FILE);
	String dest ="D://Automation_Reports//screenshots//"+getcurrentdateandtime()+".png";
	File target = new File(dest);
	FileUtils.copyFile(src, target);
	return dest;
}
    public String getcurrentdateandtime(){
	String str = null;
	try{
		DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss:SSS");
		Date date = new Date();
		str= dateFormat.format(date);
		str = str.replace(" ", "").replaceAll("/", "").replaceAll(":", "");
	}
	catch(Exception e){
		
	}
	return str;
}
}

## Environment Details

* Extent report Version used: 3.1.2
* Operating System: Win 10

## Screenshots

![extent](https://user-images.githubusercontent.com/35539771/35061586-b0993cc8-fb8f-11e7-863f-893696a9c67a.png)

**Comment by anshooarora** [comment]
Instead of attaching the image to your test, simply attach it to the log.

http://extentreports.com/docs/versions/3/java/#insert-screenshots

**Comment by sanjp29** [comment]
Hello,

How to add test case details in Details column?  I am using generateRepot (implemting IReporter)

**Comment by Alaray** [comment]
@vvd619 instead of log.addScreenCaptureFromPath(captureScreen() try this:

MediaEntityModelProvider screenshot = createScreenCaptureFromPath(getScreenshot(result)).build();

and than add this to to your test step:

localTest.get().log(Status.INFO, "Screenshot on test start", screenshot);

**Comment by sanjp29** [comment]
My question was not related to screenshot...
but it was related to having more info in details column.
may be I should create a new issue?
