### ISSUE TITLE
Remove added step logs from Report

### ISSUE THREAD

**Issue by sumit-global** [anshooarora/extentreports-java#1018]
Hi,

I am implementing retry failed cases functionality in my automation test, i am using extent report for reporting.

My test look

**logger.log(LogStatus, step1, details)
logger.log(LogStatus, step2, details)**
so on...
After step 3 my test get failed and i retry test again.( it will start from step 1)
so it will again start logging from step 1 like:
**logger.log(LogStatus, step1, details)
logger.log(LogStatus, step2, details)**
Now at this time my test get passed but extent report show as failed because previously added logs make it fail.
Is there any way so i can remove all previously added log.

NOTE: I am not creating new ExtentTest object when retrying failed cases.
Any help is highly appreciated.

**Comment by anshooarora** [comment]
You can remove the previously used test by calling `removeTest`:

```
extent.removeTest(test);
```

**Comment by farhanghaffar** [comment]
Hi Anshooarora,

removeTest() is not method

**Comment by farhanghaffar** [comment]
How we remove the test from extent report if test first time fail and will add second execution?

**Comment by BeBestOf** [comment]
Hi @anshooarora , remove test is not removing the test from the report. Here's my code could you please look into it.

`package com.androidAppTest.extentReport;

import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class OneTest {
	ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter("extent.html");
	ExtentReports extent = new ExtentReports();
	ExtentTest firstTestLog, secondTestLog;

	@Test(priority=1)
	public void test() {
		// create ExtentReports and attach reporter(s)
		extent.attachReporter(htmlReporter);

		// creates a toggle for the given test, adds all log events under it    
		firstTestLog = extent.createTest("OneTest", "This is a simple test case");
		firstTestLog.log(Status.PASS, "Logged in successfully");
		extent.flush();
	}


	@Test(priority=2)
	public void runSecondTest() {
		secondTestLog = extent.createTest("SecondTest", "This is a second test case");
		secondTestLog.log(Status.FAIL, "Logged in not successfully");
		extent.flush();
	}
	
	@Test(priority=3)
	public void removeTest() {
		extent.removeTest(secondTestLog);
	}

}
`
