### ISSUE TITLE
Need to append Test Parameters in Report.

### ISSUE THREAD

**Issue by viveksoundarrajan** [anshooarora/extentreports-java#1023]
Hello All,
       I am using testng @DataProvider for test parameteres, And I am using the Extent Reporter for test automation reporting. My requirment is need to print/append Test Parameters on report for easy understanding. I've tried to append paramenter on catched exception, but it was not helpful. I need the report like this TestNG reporter generated report (screenshot) or like MethodName - Parameter (signoutOwner - John). I am using a separate listener for report generation.

Thanks,
Vivekkumar Soundararajan.
<img width="309" alt="screen shot 2018-02-14 at 12 11 45 pm" src="https://user-images.githubusercontent.com/6882542/36196893-22b394fc-1198-11e8-89d5-225e8b5374e7.png">
<img width="1680" alt="screen shot 2018-02-14 at 4 09 39 pm" src="https://user-images.githubusercontent.com/6882542/36200276-29acd7dc-11a2-11e8-8cc6-5c3d01e152ac.png">

**Comment by anshooarora** [comment]
You can create a single parent node and append all data as child nodes.   Here are the docs:

Version 2: http://extentreports.com/docs/versions/2/java/#child-tests
Version 3:  http://extentreports.com/docs/versions/3/java/#create-child-tests

PS.  Version 2 is no longer supported.  Would recommend upgrading.
