### ISSUE TITLE
The fatal icon color displayed in Standard sample report is incorrect

### ISSUE THREAD

**Issue by dineshb-qa** [anshooarora/extentreports-java#1029]
## Summary

The fatal icon color displayed in Standard sample report is incorrect

## Expected Behavior

The fatal icon color displayed in Standard sample [report](http://extentreports.com/samples/extent.html#!) should be same which we see after selecting individual test result

## Current Behavior

The fatal icon color displayed in Standard sample [report](http://extentreports.com/samples/extent.html#!) is different as compare to the one after selecting individual test result

## Sample

```java
// Sample code goes here
```

## Environment Details

Sample Report Link : http://extentreports.com/samples/extent.html#!

## Screenshots

wrong_icon_color_for_fatal_26feb.png
![wrong_icon_color_for_fatal_26feb](https://user-images.githubusercontent.com/6957604/36670558-c0d8cf0a-1b1e-11e8-85d4-a3b375f34cb1.png)

**Comment by anshooarora** [comment]
Please send in a pull request for this if possible.
