### ISSUE TITLE
Custom table in the report

### ISSUE THREAD

**Issue by Edzotech** [anshooarora/extentreports-java#1032]
## Summary
I want to add custom table in the extent report. 
In help document the sample code is missing can you please provide the sample code for creating custom table in the reports.
![table in extent reports](https://user-images.githubusercontent.com/30716119/36725438-52654d6e-1bdc-11e8-8206-e9a7f63faf65.png)

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by anshooarora** [comment]
Added section in the docs,  please see here:  http://extentreports.com/docs/versions/3/java/#markup-helpers-table

**Comment by Edzotech** [comment]
Thanks @anshooarora
