### ISSUE TITLE
Extent reports is displaying the total Tests count as 1

### ISSUE THREAD

**Issue by geethub17** [anshooarora/extentreports-java#1033]
Hi Anshooarora,

My total test cases count is 2. But in the extent report, it is displaying the latest test case name and total steps of all test cases. 
![html](https://user-images.githubusercontent.com/36916085/36780205-519ca442-1c98-11e8-890f-1956a5233583.PNG)

![extent report](https://user-images.githubusercontent.com/36916085/36786249-c06013ec-1cab-11e8-82f7-dca62de48cba.PNG)

Here i am initializing the logger in @before hook and flush reports in @after hook.

Before executing the scenario.

```
@Before         
        public void launchbrowser(Scenario s) throws IOException{

    extent = new ExtentReports("C:/Selenium/MarketHub's/Reports/"+timeStamp+" Report.html", true);

   extent.addSystemInfo("Application", "Markethub's").addSystemInfo("Environment", "QA");      

   extent.loadConfig(new File("C:/Selenium/MarketHub's/Reports/extent-config.xml"));


            String snr=s.getId().split(";")[1];
            String name=snr.replaceAll("-"," ");
            logger=Extentreports.extent.startTest(name);  

            Driver.launchbrowser();

        }
```
Below code is using to log the step to step result.

```
if(!executemethod("Automationlib."+pagename,methodname,arlist)){            
            String imagepath=utils.takescreenshot(methodname,pagename);
            logger.log(LogStatus.INFO, methodname, logger.addScreenCapture(imagepath));
            logger.log(LogStatus.FAIL, pagename,pagename+" step failed on the page "+pagename);
            utils.CustomException(utils.getErrormessage());
        }else{
            String imagepath=utils.takescreenshot(methodname,pagename);
            logger.log(LogStatus.INFO, methodname, logger.addScreenCapture(imagepath));
            logger.log(LogStatus.PASS, pagename,pagename+" step passed on the page "+pagename);
            System.out.println("****Successfully executed--> "+methodname+" from page "+pagename+"**** ");
        } 
```

After the execution, flushing the reports.

```
@After
    public void closebrowser(){

        extent.endTest(logger);
        extent.flush();
        Driver.driver.close();

}
```
Below is the feature file and it contains only two scenarios.
```

Feature: testing the jerkhin convertor class

  Scenario: Navigation to powershare

    The application is opened on the browser

    Then i will "naviagtetopowershare" from "PowerShare" page
    Then i will "clickonnewpowershare" from "PowerShare" page

@Scenario2
  Scenario Outline: Choose category

    The application is opened on the browser

    Then i will "naviagtetopowershare" from "PowerShare" page
    And i would like to "selectcategory" with data (<category>) from "PowerShare" page

    Examples: 
      | category |
      | ACTIVE   |
```
Extent reports version: 2.41.2
JRE version: 1.7

Could anyone please tell me, where am doing wrong?

**Comment by anshooarora** [comment]
I would recommend using CucumberExtentFormatter library by Vimal. 

https://github.com/email2vimalraj/CucumberExtentReporter

No extra coding would be required.

**Comment by anshooarora** [comment]
In your report, I see only 1 test.  With version 2, you need to end the test after each test method executrs.

**Comment by geethub17** [comment]
I tried as per you comment. Now also,it is displaying the last test case result only.

Below code, i have updated.

if(!executemethod("Automationlib."+pagename,methodname,arlist)){            
            String imagepath=utils.takescreenshot(methodname,pagename);
            logger.log(LogStatus.INFO, methodname, logger.addScreenCapture(imagepath));
            logger.log(LogStatus.FAIL, pagename,pagename+" step failed on the page "+pagename);
            extent.endTest(logger);
            extent.flush();
        }else{
            String imagepath=utils.takescreenshot(methodname,pagename);
            logger.log(LogStatus.INFO, methodname, logger.addScreenCapture(imagepath));
            logger.log(LogStatus.PASS, pagename,pagename+" step passed on the page "+pagename);
            extent.endTest(logger);
            extent.flush();
        } 

![image](https://user-images.githubusercontent.com/36916085/36833440-5b447bd8-1d55-11e8-95b5-7e073359825d.png)

![image](https://user-images.githubusercontent.com/36916085/36833608-03f6f4c2-1d56-11e8-894b-dd66b72a0d5f.png)
