### ISSUE TITLE
Unable to view the generated Extent Reports , the HTML is broken when i open the report.

### ISSUE THREAD

**Issue by AutomateAnywhere** [anshooarora/extentreports-java#1040]
Unable to view the generated Extent Reports , the HTML is broken when i open the report.

Do we need to change any settings in the browser?

**Comment by NaveenAutomate** [comment]
are you connected to internet when you open the report and javascript is enabled?

**Comment by AutomateAnywhere** [comment]
thanks for your reply.. Yes i am connected to internet.  i could see the below errors in the browser console.
"extent.css Failed to load resource: net::ERR_CONNECTION_RESET"
"extent.js Failed to load resource: net::ERR_CONNECTION_RESET"

Help me solve this issue? 

I am able to view the reports properly , when my "NetworkMode" is OFFLINE. But i am unable to share these reports within my team. And when is make it ONLINE , i am facing the above issue.

**Comment by NaveenAutomate** [comment]
clear cookies and try in different browsers. and check if there is any proxy issue.

**Comment by anshooarora** [comment]
Looks like th CDN is blocked in your intranet.  You may have to contact your network team to unblock GitHub CDN or use `htmlReporter.config().setResourceCDN(ResourceCDN.EXTENTREPORTS);` in your HtmlReporter.
