### ISSUE TITLE
Is there a way extent reports listener gets called after each method ?

### ISSUE THREAD

**Issue by rahulbommanaboina** [anshooarora/extentreports-java#1041]
Am running series of classes through testng XML file , my intention is to capture the screenshot if it gets failed after every method.But extent report listener class is getting called only after last method of the class is run.

do you think any configuration issue ? Please help !

Extent report code is below : 

package reports;

import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

import or.Common;
import reUsable.BaseClass;

public class ExtentReporterNG implements IReporter {
	private ExtentReports extent;
	org.openqa.selenium.winium.WiniumDriver d= null;

	public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites,
			String outputDirectory) {
		extent = new ExtentReports(outputDirectory + File.separator
				+ "Extent.html", true);

		for (ISuite suite : suites) {
			Map<String, ISuiteResult> result = suite.getResults();

			for (ISuiteResult r : result.values()) {
				ITestContext context = r.getTestContext();

				buildTestNodes(context.getPassedTests(), LogStatus.PASS);
				buildTestNodes(context.getFailedTests(), LogStatus.FAIL);
				buildTestNodes(context.getSkippedTests(), LogStatus.SKIP);
			}
		}

		extent.flush();
		extent.close();
	}

	private void buildTestNodes(IResultMap tests, LogStatus status) {
		ExtentTest test;

		if (tests.size() > 0) {
			for (ITestResult result : tests.getAllResults()) {
				test = extent.startTest(result.getMethod().getMethodName());

				test.setStartedTime(getTime(result.getStartMillis()));
				test.setEndedTime(getTime(result.getEndMillis()));

				for (String group : result.getMethod().getGroups())
					test.assignCategory(group);

				if (result.getThrowable() != null) {
					test.log(status, result.getThrowable());
					String file = System.getProperty("user.dir")+"/Screenshots/"+"FailureMethod"+result.getMethod().getMethodName()+".png";

					try {
						BaseClass.takeSnapShot(BaseClass.getDriver(), file);
					} catch (Exception e) {
						// TODO: handle exception
					}
					
					test.log(status, test.addScreenCapture(file));
					
					try {
						reUsable.After.afterMethodSteps();
						d.findElement(Common.userNameID).click();
					} catch (Exception e) {
						// TODO: handle exception
					}
				
					
				} else {
					test.log(status, "Test " + status.toString().toLowerCase()
							+ "ed");
				}

				extent.endTest(test);
			}
		}
	}

	private Date getTime(long millis) {
		Calendar calendar = Calendar.getInstance();
		calendar.setTimeInMillis(millis);
		return calendar.getTime();
	}
}

**Comment by NaveenAutomate** [comment]
try extent report as listener. Refer http://extentreports.com/docs/versions/3/java/#testng-itestlistener 
Make changes to add screenshot in below method:

`@Override
	public synchronized void onTestFailure(ITestResult result) {
		test.get().fail(result.getThrowable());
	}`

this will be called after every test method.
