### ISSUE TITLE
ExtentReports 3.1.3 Offline Mode

### ISSUE THREAD

**Issue by sivapannier** [anshooarora/extentreports-java#1049]
Hi,

I am trying to load the report in the offline mode, unfortunately it is not able to load the icons and styles.

Can you please let me know, how to do this offline setup?

Thanks,
Siva P

**Comment by anshooarora** [comment]
Sorry, this feature for offline viewing is only available in the professional version..

**Comment by sivapannier** [comment]
Hi.. how much this professional version costs?
