### ISSUE TITLE
can we able to give background color in dashboard of start time and endtime in extent report?

### ISSUE THREAD

**Issue by Amitptr** [anshooarora/extentreports-java#1054]
## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by anshooarora** [comment]
Yes, this can be done by adding CAS to your config.xml or using `htmlReporter.config().setCSS`.

**Comment by Amitptr** [comment]
Thanks Anshoo for your input.
