### ISSUE TITLE
Extent reports are generating with broken UI or no css/js

### ISSUE THREAD

**Issue by avinashkandukuri** [anshooarora/extentreports-java#1055]
Extent reports are generating with broken UI or no css/js is loaded 
I am creating the extent reports offline, here is the sample screen shot of the extent report

![image](https://user-images.githubusercontent.com/25835213/38390553-467a7b5a-38e7-11e8-82eb-e29a317b796d.png)

**Comment by anshooarora** [comment]
Sorry, this feature for offline viewing is only available in the professional version..
