### ISSUE TITLE
How to add more information in report?  Allow only last run test's status when run via Retry feature.

### ISSUE THREAD

**Issue by ansonliao** [anshooarora/extentreports-java#106]
Hi Anshoo Arora, 
The extend report is fresh to me in TestNG, and I studying it.
For my project now, my current report is customized and I would like to try to move to extent report, and some information I would like merge to extent report.
1.
In my testng test case, have retry function in test case (@Test) fail, for my current report, have a column to display the test case re-run count "Re-Run Count".
So I would like to know, how I can add this test information to extent report?

2.
In my testng test class, have annotation "author", in order to trace the fail test cases's assigner more easier.
I would like to know, how I can add this test information to extent report?

3.
I would like put test log as text file to report, and add a column and each test case in this column cell, will have a hyper link and download button, for result checker to review the test log.
I would like to know how I can do it?

Thanks.

**Comment by anshooarora** [comment]
1 - can you add the retry info to the test name?  When you search by test-name, you will see the tests and the retry info will be displayed also.

![retry](https://cloud.githubusercontent.com/assets/4107384/10642521/b73b06a6-77e3-11e5-943f-311a2657bd4d.png)

2 - This is one of the attributes (<a href='https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/model/Author.java'>here</a>) that is yet to be implemented.  This can be added to the structure (no ETA though)

3. Simply insert a link with your log using:  http://extentreports.relevantcodes.com/java/version2/docs.html#insert-custom-html

**Comment by ansonliao** [comment]
Hi Anshooarora,
Sorry to reply so late.
For add retry information, I think this is not so easy to add.
As you know, TestNG have Retry listener and the retry I talked is method level.
after the method was fail, the retry listener will trigger and will retry the fail method some times.

For this case, I think not just add the retry count label or indicator to test name, also need to handle the total tests/method run count.

For example, a test class includes 2 methods, and 1 method finally was fail, and this fail method, the retry time is 3 times (total 4 times run).
finally, the test summary information is expected: 1 class run, 2 methods run, 1 passed, 1 fail.

Please advise.

**Comment by anshooarora** [comment]
Ok.  So, from the API design, what should be a good approach to allow this to happen?

**Comment by jawlitkp** [comment]
Hi Anshoo,

For me management wants to see real number of test cases in the report not including count of retries,so I would say if same test case is getting executed multiple times it should not report as new test case but over ride existing ,it would be even awesome if we can report retry number or iteration number

Thanks

**Comment by ansonliao** [comment]
Hi Anshoo, 
I find how to handle the retry case in TestNG, please check it below, I think you are well known in TestNG.
http://stackoverflow.com/questions/13131912/testng-retrying-failed-tests-doesnt-output-the-correct-test-results

**Comment by VinitSandesara** [comment]
Hi Anshoo, Any update on this enhancement ? what is ETA we should expect ?

Thanks
Vinit

**Comment by anshooarora** [comment]
It will be included in the upcoming version.  I am not sure how to enable this feature though, still working on that - should this be done via config.xml or in instantiation?  I don't want to enable this feature by default as it may cause confusion for users who are used to keeping retrials.

**Comment by karthikbhatnagar** [comment]
@anshooarora - will it be working for child and parent tests both?

**Comment by anshooarora** [comment]
The feature of replacing a test with a retry will not be available.  The original test along with all retries will show up in the report across all versions.  On the ExtentX side - it will be possible to view the history of a given test across multiple reports to see how that test performed.
