### ISSUE TITLE
Getting Null Pointer exception for extent reports

### ISSUE THREAD

**Issue by connectbobby1** [anshooarora/extentreports-java#1074]
## Summary

I am getting null pointer exception when I try to run extent reports using selenium with Java

## Expected Behavior

System should not display Null Pointer exception and should display the extent report log for each step in the html page.

## Current Behavior

System is displaying Null Pointer exception

## Sample

Main Test

import java.io.IOException;
import java.lang.reflect.Method;

import org.openqa.selenium.support.events.EventFiringWebDriver;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;
import com.relevantcodes.extentreports.ExtentReports;

import y.bi.create.reports.charts.ColumnFormattingPage;
import y.bi.create.reports.charts.ContentMenuButton;
import y.bi.create.reports.charts.ReportChartBuilder;
import y.bi.create.reports.charts.ReportFormat;
import y.bi.create.reports.charts.SectionFormattingPage;
import y.bi.create.reports.charts.Sections;
import y.bi.create.reports.charts.ViewForReport;
import y.bi.login.loginPage;
import y.bi.logout.Logout;
import y.bi.navigation.Browse;
import y.bi.screenshots.Screenshots;
import y.bi.utils.Printscreen;
import y.bi.utils.BrowserFactory;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class ColumnFormatting {
	private EventFiringWebDriver driver;
	private loginPage login;
	private Logout logout;
	private Browse browse;
	private ContentMenuButton createContentMenuButton;
	private ViewForReport reportView;
	private ReportChartBuilder createChart;
	Printscreen ps;
	private Sections sections;
	private ColumnFormattingPage columnFormattingPage;
	public ExtentReports extent;
	public ExtentTest extentTest;
	
	@BeforeSuite(enabled = true)
	public void setUpTheTest() {
		driver = (EventFiringWebDriver) BrowserFactory.selectBrowser("chrome");
	}
	
	
	@BeforeTest
	public void setExtent(){
		extent = new ExtentReports(System.getProperty("user.dir")+"/test-output/ExtentReport.html", true);
		extent.addSystemInfo("Host Name", "Calcutta");
		extent.addSystemInfo("User Name", "Admin");
		extent.addSystemInfo("Environment", "QA");		
	}
	
	@AfterMethod
	public void tearDown(ITestResult result) throws IOException {
		
		if(result.getStatus()==ITestResult.FAILURE){
			
			//to add name in extent report
			extentTest.log(LogStatus.FAIL, "TEST CASE FAILED IS "+result.getName()); 
			 //to add error/exception in extent report
			extentTest.log(LogStatus.FAIL, "TEST CASE FAILED IS "+result.getThrowable());
			String screenshotPath = Screenshots.getScreenshot(driver, result.getName());
			//to add screenshot in extent report
			extentTest.log(LogStatus.FAIL, extentTest.addScreenCapture(screenshotPath)); 
			
		}
		else if(result.getStatus()==ITestResult.SKIP){
			extentTest.log(LogStatus.SKIP, "Test Case SKIPPED IS " + result.getName());
		}
		else if(result.getStatus()==ITestResult.SUCCESS){
			extentTest.log(LogStatus.PASS, "Test Case PASSED IS " + result.getName());
		}
		extent.endTest(extentTest); 
	}
	
	
	
	@Parameters({ "yellowfinURL" })
	@BeforeTest(enabled = true)
	public void instantiatePages(String url) {
		driver.get(url);
		login = new loginPage(driver);
		logout = new Logout(driver);
		browse = new Browse(driver);
		createContentMenuButton = new ContentMenuButton(driver);
		reportView = new ViewForReport(driver);
		createChart = new ReportChartBuilder(driver);
		ps = new Printscreen(driver);
		sections = new Sections(driver);
		columnFormattingPage = new ColumnFormattingPage(driver);
	}
	
		
	@Parameters({ "userName", "passsword", "viewName", "rf1", "rf2", "rf3", "rf4", "rf5", "SectionItem1", "DecimalValue", "FontType", "FontSize", "MetricScreenShot"})
	@Test(testName = "ValidateMetrics", enabled = true, priority = 1, groups = {"Column Formatting"})
	public void Metric(String username, String password, String viewName, String r1, String r2, String r3, String r4, String r5, String SecItem, String DecVal, String FonType, String FonSize, String SShot)  {
		
		extentTest = extent.startTest("ValidateMetrics");
		
		login.loginToTenant(username, password);
		// select view from content menu button
		createContentMenuButton.setContentMenuButton();
		// choose view
		reportView.selectView(viewName);
		// create the report in report builder
		createChart.createReport(r1, r2, r3, r4, r5);
		
		columnFormattingPage.DisplayForMetrics(SecItem, DecVal);	
		columnFormattingPage.Data(FonType, FonSize);	
		columnFormattingPage.Border();	
		columnFormattingPage.Summary(SShot);	
		logout.performLogout();

	}
	
	@Parameters({ "userName", "passsword", "viewName", "rf1", "rf2", "rf3", "rf4", "rf5", "SectionItem2", "DecimalValue", "FontType", "FontSize", "DateScreenShot"})
	@Test(testName = "ValidateDate", enabled = false, priority = 2, groups = {"Column Formatting"})
	public void Date(String username, String password, String viewName, String r1, String r2, String r3, String r4, String r5, String SecItem2, String DecVal, String FonType, String FonSize, String SShot)  {
		
		extentTest = extent.startTest("ValidateDate");
		
		login.loginToTenant(username, password);
		// select view from content menu button
		createContentMenuButton.setContentMenuButton();
		// choose view
		reportView.selectView(viewName);
		// create the report in report builder
		createChart.createReport(r1, r2, r3, r4, r5);
		columnFormattingPage.DisplayForDate(SecItem2);
		columnFormattingPage.Sorting();
		columnFormattingPage.Data(FonType, FonSize);	
		columnFormattingPage.Border();	
		columnFormattingPage.Summary(SShot);	
		logout.performLogout();

	}
	
	@Parameters({ "userName", "passsword", "viewName", "rf1", "rf2", "rf3", "rf4", "rf5", "SectionItem3", "DecimalValue", "FontType", "FontSize", "DimensionScreenShot"})
	@Test(testName = "ValidateDimension", enabled = false, priority = 3, groups = {"Column Formatting"})
	public void Dimension(String username, String password, String viewName, String r1, String r2, String r3, String r4, String r5, String SecItem3, String DecVal, String FonType, String FonSize, String SShot)  {
		
		extentTest = extent.startTest("ValidateDimension");
		
		login.loginToTenant(username, password);
		// select view from content menu button
		createContentMenuButton.setContentMenuButton();
		// choose view
		reportView.selectView(viewName);
		// create the report in report builder
		createChart.createReport(r1, r2, r3, r4, r5);
		columnFormattingPage.DisplayForDimension(SecItem3);
		columnFormattingPage.Sorting();
		columnFormattingPage.Data(FonType, FonSize);	
		columnFormattingPage.Border();	
		columnFormattingPage.Summary(SShot);	
		logout.performLogout();
	
	}
	
	@AfterTest
	public void endReport(){
		extent.flush();
		extent.close();
		driver.quit();
	}	
		
}

Method

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.Select;

import com.relevantcodes.extentreports.LogStatus;

import y.bi.screenshots.Screenshots;
import y.bi.test.ColumnFormatting;

public class ColumnFormattingPage extends ColumnFormatting {
	
	WebDriver driver;
	static long d = 2000;
	String workingDir = System.getProperty("user.dir");
	ColumnFormat cf = new ColumnFormat();
	Screenshots screenshot = new Screenshots();
	
	
	
	public ColumnFormattingPage(WebDriver driver) {
		
		this.driver = driver;
		
	}
	
	
	public void DisplayForMetrics(String SectionItem1, String DecimalVal)
	
	{   
		try {
		
		extentTest.log(LogStatus.INFO, "Test");
		//click on column format
		cf.OpenColumnFormatting(driver);
		//click on the the Report Field
		driver.findElement(By.xpath("//div[@class='selectFieldDiv ']//child::div[contains(text(), '"+SectionItem1 +"')]")).click();	
		//Select the Format
		Thread.sleep(d);
	    new Select(driver.findElements(By.xpath("//div[@class='styledSelect customSelect']")).get(2).findElement(By.tagName("select"))).selectByVisibleText("Percentage");
	    Thread.sleep(d);
		//Enter the decimal value
		driver.findElement(By.xpath("(//td[@class='optionViewControlTd ']//input[@type='text'])[2]")).sendKeys(DecimalVal);
		Thread.sleep(d);
		//Select the Rounding
		new Select(driver.findElements(By.xpath("//td[@class='optionViewControlTd ']//child::div[@class='styledSelect customSelect']")).get(1).findElement(By.tagName("select"))).selectByVisibleText("Round Up");
		Thread.sleep(d);
		//CLick on Suppress Duplicates
		driver.findElement(By.xpath("(//div[@class='controlContainer']//child::div[@id='toggle'])[3]")).click();
		}
		
	catch(Exception e)	
		
		{
		e.printStackTrace();
		
		}
		
	}

## Environment Details

* Extent report Version used: 2
* Operating System and version: Windows 10
* JDK Version:

**Comment by connectbobby1** [comment]
Can somebody please help ?

**Comment by connectbobby1** [comment]
No help received

**Comment by ranadinesh786** [comment]
issue :
=====
 How to solve NULLPOINTEREXCEPTION while using grouping concepts in POM with Extends Reporting ?


Solutions: 
======
	       1. Use below parameters to all the configuration annotations which we are using i.e. in base test;
		(alwaysRun = true)
		2. Use valid try catch block inside the page class and don’t use throws [incorrect exception]
		3. Use parameterized values instead of taking hardcode values inside the page or script.
