### ISSUE TITLE
New Feature request- Ability to apply multiple filters option

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports-java#110]
Hi Anshoo,

Could you please add feature where user can apply multiple filter options.

Thanks 
Jwalit

**Comment by karthikbhatnagar** [comment]
you did not specify the other filters...

**Comment by jawlitkp** [comment]
So basically as shown in below screenshot ,i am able to filter test case by only once option e.g. safari or Pilot script but i want to apply two filter criteria so i should be able to filter test case by safari and Pilot script both 

<img width="106" alt="screnhsot" src="https://cloud.githubusercontent.com/assets/9873362/10766948/442d751e-7cb0-11e5-8a62-f130256826ae.png">

**Comment by anshooarora** [comment]
The list box that Extent uses is a custom implementation and so it will not support multi-select.  There will be some changes required to the element itself to implement this feature.  Will have to research this and find a way to use the regular select and still keep the overall look and feel.

**Comment by jawlitkp** [comment]
Hi Anshoo,

Would you be able to deliver this feature ?

Thanks 
Jwalit

**Comment by anshooarora** [comment]
Will try to add this, but I would have to revamp the filtering completely so it will be included in one of the later versions..

**Comment by jawlitkp** [comment]
Thank you, looking forward!

**Comment by email2vimalraj** [comment]
@anshooarora : Is this enhancement request still valid? I do see that the search feature had been improved and went through different changes. Can we close this if it is irrelevant?

**Comment by anshooarora** [comment]
@email2vimalraj - thanks, yes, this can now be closed.
