### ISSUE TITLE
Is there way to close Node within Test

### ISSUE THREAD

**Issue by ishah09** [anshooarora/extentreports-java#1102]
I want to have single Test Section includes multiple nodes. 

## Summary

When we create Node under test, It will create as defined. When create another node within same Test then it will create under Node. 

Test -> 1st Node
Test -> 1st Node -> 2nd Node

## Expected Behavior

There should be provision to close 1st node, To create 2nd node within same Test. 

Like: 
Test -> 1st Node
Test -> 2nd Node

## Current Behavior

It is creating under Node. 

## Environment Details

* Extent report Version used: 3.1.5
* Operating System and version: Win-10 64bit
* JDK Version: 10.0.2

## Screenshots

![image](https://user-images.githubusercontent.com/32862749/43503022-0f289d8a-957b-11e8-9589-14dc099114a1.png)

**Comment by anshooarora** [comment]
Please share your code. Extent allows creating multiple nodes at any level so there must be something going on in your usage causing this

**Comment by ishah09** [comment]
Code is something like just calling different method. Every method is containing first line of extent report code.  But still I do share the way I have created. 

testlog = extentReport.createTest("Add Rule");
testlog = testlog.createNode("Delete User");

Where testlog(ExtentTest) and extentReport(ExtentReports) are objects.

Yes Its creating multiple nodes. As we can see in screenshot, "Delete User" and "Delete Device"  both are nodes of on of the Test, which are currently created as Nested flow. 

![image](https://user-images.githubusercontent.com/32862749/43519435-144c915e-95ad-11e8-9728-e11aee1fb061.png)

If needed, can share HTML report.

**Comment by anshooarora** [comment]
Issue is with testlog.

```
testlog = extentReport.createTest("Add Rule");
testlog = testlog.createNode("Delete User");
```

Try:

```
ExtentTest parent = extentReport.createTest("Add Rule");
testlog = parent.createNode("Delete User");
testlog = parent.createNode("Delete Device");
```

**Comment by ishah09** [comment]
Yes, And its worked as expected. 
Thanks a lot ! Appreciated.
