### ISSUE TITLE
Hide report logs or disable the expansion of report

### ISSUE THREAD

**Issue by rishika6191** [anshooarora/extentreports-java#1117]
**Summary**

Extent Report : 3.1.5

We are implementing reporting with extent report and facing an issues in that. We are creating parent child relationship in extent report
o	Test class – Parent in extent report eg. LoginTest
o	Test Method – Child in parent created previously eg verifyLogin()
o	Business Keywords – child in test method eg. loginToEspo

We are creating reports for 3 type of user - automation tester, business user, test manager.

For automation user it will be complete report with all the parent and child and all the test steps.
But for business and test manager there will not be any test steps.

Now, the issue is status of report will be correct when we include all the test steps but for business user, is there any way that those test steps will not be visible or is it possible to restrict the expansion of the child section where test steps lie.

Screenshot for the automation tester report.
![image](https://user-images.githubusercontent.com/43602016/46069039-3ac55200-c198-11e8-9868-2bdc61158eef.png)

Is there any way where the expansion of loginToEspo can be restricted and report look like 
![image](https://user-images.githubusercontent.com/43602016/46069122-72cc9500-c198-11e8-8540-4b32cc8a9979.png)

**Comment by anshooarora** [comment]
It is possible by replacing the toggle class on document.ready. This will prevent the default result of click action on the accordion.
