### ISSUE TITLE
Test description do not display HTML tag elements and JavaScript tag

### ISSUE THREAD

**Issue by gitweeyah** [anshooarora/extentreports-java#1119]
## Summary

HTML tag elements such as` </html>`, `</b>` and  JavaScript tag such as `</script>` are not display at the description. However, in TestNG, it does display.

## Sample

```java
extentTest.info("Executing test case with the data: "+ Arrays.toString(fields));
```

## Environment Details

* Extent report Version used: 3.0.3
* JDK Version: JavaSE-1.8

## Screenshots
TestNg:
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/LXMBkNTz/Picture2.png' border='0' alt='Picture2'/></a>

ExtentReport:

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/hvByjK6R/ddd.png' border='0' alt='ddd'/></a>

Is there a way for me to display such tags?

**Comment by anshooarora** [comment]
Please use MarkupHelper.createCodeBlock to add code, especially markup.
