### ISSUE TITLE
HTML Report showing some french characters as question mark (?) 

### ISSUE THREAD

**Issue by rajasekharbora** [anshooarora/extentreports-java#1120]
## Summary
We are running selenium java scripts on French converted UI. When HTML report is generated, french characters are showing with ?
Ex: Siège social, Showing as Si�ge social

## Expected Behavior

French characters should be displayed as it is insted of question mark in the html report.

## Current Behavior

? Showing for some french characters.

## Environment Details

* Extent report Version used: 3.1.5
* Operating System and version: Win 10
* JDK Version: 1.8.0_121

**Comment by anshooarora** [comment]
You can set encoding using config.xml or Java using:

```
reporter.config().setEncoding();
```
