### ISSUE TITLE
Unable to generate report using version 3.1.5

### ISSUE THREAD

**Issue by AyushAgarwalVmock** [anshooarora/extentreports-java#1121]
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

//import com.aventstack.extentreports.HTMLReporter;
import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.markuputils.ExtentColor;
import com.aventstack.extentreports.markuputils.MarkupHelper;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.configuration.ChartLocation;
import com.aventstack.extentreports.reporter.configuration.Theme;

public class Reporting extends TestListenerAdapter {
	public ExtentHtmlReporter htmlReporter;
	public ExtentReports extent;
	public ExtentTest logger1;
	public ExtentTest childlog;
	public ExtentTest parentlog;
	
	
	@BeforeTest
	public void onstart(ITestContext testContext)
	{
		String timestamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new Date());
		String repName= "Test-Report-"+timestamp+".html";
//		 File OutputFolder = new File("./test-output");
//		 if (!OutputFolder.exists()) {
//			 if(OutputFolder.mkdir()) {
//		         System.out.println("Directory is created!");
//			 }
//			 else  {   System.out.println("Failed to create Directory");
//		      } 
//		  }else {System.out.println("Diretory already exists");
//		  }
		htmlReporter = new ExtentHtmlReporter(System.getProperty("user.dir")+"/test-output"+"/"+repName);
		htmlReporter.loadXMLConfig(System.getProperty("user.dir")+ "/extent-config.xml");

		extent = new ExtentReports();

		extent.attachReporter(htmlReporter);
		extent.setSystemInfo("Host Name", "LocalHost");
		extent.setSystemInfo("Environment", "Test");
		extent.setSystemInfo("User", "QA");

		htmlReporter.config().setDocumentTitle("VMock");
		htmlReporter.config().setReportName("Functional Testing");
		htmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
		htmlReporter.config().setTheme(Theme.DARK);
	}
	
	public void onTestSuccess(ITestContext Ts)
	{
		
		logger1= extent.createTest(Ts.getName());	//.startTest(Ts.getName());		//create new entry in report
		logger1.log(Status.PASS, MarkupHelper.createLabel(Ts.getName() + " - Test Case Passed", ExtentColor.GREEN));	
		
	}
	
	public void onTestFailure(ITestContext Ts)
	{
		logger1= extent.createTest(Ts.getName());	//create new entry in report
		logger1.log(Status.FAIL, MarkupHelper.createLabel(Ts.getName() + " - Test Case Failed", ExtentColor.RED));
		String screenshotPath= System.getProperty("user.dir")+"\\screenshotPath\\"+ Ts.getName() + ".png";
		File f = new File (screenshotPath);
		if(f.exists()) {  
			try {
			 logger1.fail("Screenshot is below"+ logger1.addScreenCaptureFromPath(screenshotPath));  //addScreenCapture(screenshotPath));
			}
			catch(Exception e)
			{e.printStackTrace();
		 }
	}
	}
	
	public void onTestSkip(ITestContext Ts)
	{
		logger1= extent.createTest(Ts.getName());	//create new entry in report
		logger1.log(Status.SKIP, MarkupHelper.createLabel(Ts.getName() + " - Test Case Skip", ExtentColor.YELLOW));
	}
	 @AfterMethod
	 public void getResult(ITestResult result){
	 if(result.getStatus() == ITestResult.FAILURE){
	 //logger.log(Status.FAIL, "Test Case Failed is "+result.getName());
	 //MarkupHelper is used to display the output in different colors
	 logger1.log(Status.FAIL, MarkupHelper.createLabel(result.getName() + " - Test Case Failed", ExtentColor.RED));
	 logger1.log(Status.FAIL, MarkupHelper.createLabel(result.getThrowable() + " - Test Case Failed", ExtentColor.RED));
	 }else if(result.getStatus() == ITestResult.SKIP){
	 //logger.log(Status.SKIP, "Test Case Skipped is "+result.getName());
	 logger1.log(Status.SKIP, MarkupHelper.createLabel(result.getName() + " - Test Case Skipped", ExtentColor.ORANGE)); 
	 }
	 }
	 @AfterTest
	 public void endReport(ITestContext testContext){
		 extent.flush();
	    }
	 

}

Below is test case:

import org.testng.Assert;
import org.testng.annotations.Test;
import com.VMock.pageObject.LoginPage;
import com.VMock.utils.Reporting;
import com.aventstack.extentreports.Status;

public class TC_LoginPage extends BaseClass {
	
				
	
				@Test
				public void LoginTest() throws Exception
				{
					LoginPage lp= new LoginPage(driver);
					lp.clickLogin();
					lp.setUserName(Username);
					//System.out.println("Username entered");
					Thread.sleep(5000);
					lp.setUserPassword(password);
					//System.out.println("Password entered");
					lp.clickSubmit();
					//System.out.println("Logged in");
					Thread.sleep(5000);
					if (driver.getTitle().equalsIgnoreCase("Vmock"))
					{
						//System.out.println("Login Test Passed");
						Assert.assertTrue(true);
						//logger.log(Status.PASS, "Browser is open");//assertLog(Status.INFO, "Browser is open");//log(Status.PASS, "Browser is open");
						//logger1.logger1.log(Status.INFO, "Pass");//log(Status.INFO, "Pass");
						
					}
					else
					{
						
					//	System.out.println("Login Test Failed");
						Assert.assertTrue(false);
					//	logger.log(Status.FAIL, "Test Case failed");
						captureScreen(driver,"LoginTest");
					}
					
			}
				
			
}

**Comment by anshooarora** [comment]
Please properly post your query and only the relevant parts. I am closing this. Please reopen if you still need assistance.
