### ISSUE TITLE
removeTest(extentTest) doesn't remove the test from the extent report

### ISSUE THREAD

**Issue by BeBestOf** [anshooarora/extentreports-java#1122]
## Summary
removeTest(extentTest) method doesn't remove the specific test case from the extent report. 

I would like to re-run the failed test cases and first fail test case result should not be shown in the report whereas its re-run result should be shown in the report (whatever the test case result will be either Pass/Fail in the second attempt just wanted to not to show first failed test case result into the extent report)

## Expected Behavior
If calling removeTest(extentTest) method, extentTest test case result should be removed from the generated extent report.

## Current Behavior
After calling removeTest(extentTest) method, specific test case result intact in the generated extent report.

## Sample

```java
// Sample code goes here
package com.androidAppTest.extentReport;

import org.testng.annotations.Test;
import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;

public class OneTest {
	ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter("extent.html");
	ExtentReports extent = new ExtentReports();
	ExtentTest firstTestLog, secondTestLog;

	@Test(priority=1)
	public void test() {
		// create ExtentReports and attach reporter(s)
		extent.attachReporter(htmlReporter);

		// creates a toggle for the given test, adds all log events under it    
		firstTestLog = extent.createTest("OneTest", "This is a simple test case");
		firstTestLog.log(Status.PASS, "Logged in successfully");
		extent.flush();
	}


	@Test(priority=2)
	public void runSecondTest() {
		secondTestLog = extent.createTest("SecondTest", "This is a second test case");
		secondTestLog.log(Status.FAIL, "Logged in not successfully");
		extent.flush();
	}
	
	@Test(priority=3)
	public void removeTest() {
		extent.removeTest(secondTestLog);
	}

}

```

## Environment Details
ExtentReport Version : 3.1.5
Language: Java
Editor: Eclipse
Testing Framework: TestNG

* Extent report Version used: 3.1.5
* Operating System and version: Windows 7
* JDK Version: 1.8.0_161

## Screenshots
![extentremovetestmethod](https://user-images.githubusercontent.com/17232533/46918200-ccccb780-cfec-11e8-9ca4-d8ca6bfea5a7.JPG)

**Comment by anshooarora** [comment]
Issue has been fixed. Please upgrade to version 4.
