### ISSUE TITLE
why extentTest.log(LogStatus ls, String testStep, String testDescription) method removed in version 3.1.5??

### ISSUE THREAD

**Issue by BeBestOf** [anshooarora/extentreports-java#1123]
## Summary
Not able to find extentTest.log(LogStatus ls, String step, String description) method in current version 3.1.5 whereas it was present in past release version 2.41.2

extentTest.log(LogStatus ls, String step, String description) method is very useful I am missing this method in version 3.1.5, this is a very descriptive method which allow us to print step name and its description. Please add this step in version 3.

## Expected Behavior
extentTest.log(LogStatus ls, String step, String description) method should be present into version 3.1.5. A very useful method looks good when step and its description print in the report. Please add it.

## Current Behavior
extentTest.log(LogStatus ls, String step, String description) method is not present into version 3.1.5. It was there in past release 2.41.2. While updating the extent version this specific method is not present, so need to update the framework completely. Not expected from the extent, it was already implemented by many people. Please think on it to add it again, looking forward to favorable actions.

## Sample

```java
// Sample code goes here
// Extent Version : 2.41.2
extentTest.log(LogStatus.PASS, "Step to login", "Login has been successfully");

// Extent Version: 3.1.5
extentTest.log(LogStatus.PASS, "Step to login");
```

## Environment Details

* Extent report Version used: 3.1.5
* Operating System and version: Windows 7
* JDK Version: 1.8.0_161

**Comment by foursyth** [comment]
This was removed to keep uniformity across all reporters and many were not utilizing this additional column. 

There were also some issues where columns were breaking due to a few steps with 2 and others with 3 args usage.

**Comment by anshooarora** [comment]
The main issue is #2 as mentioned by @foursyth.

**Comment by BeBestOf** [comment]
Hi @anshooarora , thank you for replying. But this log step is very useful for showing brief step activity and description. And as far as concern about issues with column breaking we can resolve in extent-config.xml style section just like below few lines:
 <styles>
            <![CDATA[
                .step-name, .step-details, .test-name {white-space: nowrap;}
            ]]>
        </styles>
I think if it is added into version 3 and 4, then it is useful for those who has used in version 2 and now they are planning to upgrade to version 3 and 4, else they have to change code in bulk.

**Comment by foursyth** [comment]
@BeBestOf I would recommend creating an enhancement for version 4.
