### ISSUE TITLE
Trying to generate extent report by putting the listener at suite level but the report only displays the last test case ran in the report

### ISSUE THREAD

**Issue by DipikaMishra13** [anshooarora/extentreports-java#1124]
Please let me know how can i modify either my listener or my suite xml so that my extent report has all the cases present in my suite.

Note: If i have listener in testng xml it generates the report with all the testcases. But as i have many cases i have divided then into test suites and now when i put the listener in suite level it generates the report only with last testcase ran

**Comment by DipikaMishra13** [comment]
package CustomTestListener;
import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.configuration.ChartLocation;
import com.aventstack.extentreports.reporter.configuration.Theme;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;


/**
 * Created by ID850378 on 17/07/2017.
 */
public class CustomTestListener implements ITestListener {

    private static String dateTimeFormat = "yyyy-MM-dd_kk-mm";
    private static String executionReportsHome = "target";
    private static String FILE_NAME = "Report_%s.html";
    private static ExtentReports extent;
    private static ExtentHtmlReporter htmlReporter;
    private static ExtentTest currentTest;

    private String getDateString(){
        Date now = Calendar.getInstance().getTime();
        SimpleDateFormat format = new SimpleDateFormat(dateTimeFormat);
        return format.format(now);
    }

    public void onStart(ITestContext iTestContext) {

        //	making sure paths are in place
        FILE_NAME = String.format(FILE_NAME, "Dipika");

        //	configuring the extent reporter

        htmlReporter = new ExtentHtmlReporter(executionReportsHome+"/"+FILE_NAME);


        htmlReporter.config().setDocumentTitle("ExtentReports - Created by TestNG Listener");
        htmlReporter.config().setReportName("ExtentReports - Created by TestNG Listener");
        htmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
        htmlReporter.config().setChartVisibilityOnOpen(true);
        htmlReporter.config().setTheme(Theme.STANDARD);


        extent = new ExtentReports();
        extent.attachReporter(htmlReporter);
        extent.setReportUsesManualConfiguration(true);
    }

    private void assignCategories(ITestResult iTestResult){

        ArrayList<String> labels = new ArrayList<String>();
       String className = iTestResult.getTestClass().getRealClass().getName();
        //String methodName = iTestResult.getMethod().getMethodName();
        String[] groupName = iTestResult.getMethod().getGroups();

        //labels.addAll(Arrays.asList(className.split("\\.")));
        labels.addAll(Arrays.asList(className));
        labels.addAll(Arrays.asList(groupName));
      //labels.addAll(Arrays.asList(methodName.split("\\.")));


        for (String label : labels) {
            currentTest.assignCategory(label.toLowerCase());
            //currentTest.assignAuthor(label.toLowerCase());

        }
    }


@BeforeSuite
    public void onTestStart(ITestResult iTestResult) {

        try {
            String testName = iTestResult.getMethod().getMethodName();
            String[] test = iTestResult.getMethod().getGroups();
            currentTest = extent.createTest(testName);

            assignCategories(iTestResult);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void onTestSuccess(ITestResult iTestResult) {
        currentTest.pass("<strong>TEST PASSED!!!!!!!</strong>");
        currentTest.getClass().getPackage();
        currentTest.getModel().getDescription();
    }

    public void onTestFailure(ITestResult iTestResult) {

        try {
            String testName = iTestResult.getMethod().getMethodName();
            String screenshotName = testName+".jpg";
            if(null != iTestResult.getThrowable()){
                currentTest.fail( iTestResult.getThrowable().getMessage() );
                //currentTest.fail(iTestResult.getThrowable().getStackTrace().toString());
                currentTest.fail( iTestResult.toString());
                Throwable exception = iTestResult.getThrowable();
                if(exception!=null)
                {
                    StringWriter sw = new StringWriter();
                    PrintWriter pw = new PrintWriter(sw);
                    exception.printStackTrace(pw);
                    currentTest.fail(sw.toString());
                }

            }else {
                currentTest.fail("Could not get cause!!!");
            }
            currentTest.addScreenCaptureFromPath(screenshotName);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void onTestSkipped(ITestResult iTestResult) {
        try {
            if(null == iTestResult.getThrowable()){
                currentTest.skip("<strong>TEST SKIPPED!!!!!!!</strong>");
            }else {
                currentTest.skip(iTestResult.getThrowable().getMessage());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void onTestFailedButWithinSuccessPercentage(ITestResult iTestResult) {
        try {
            onTestFailure(iTestResult);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

@AfterSuite
    public void onFinish(ITestContext iTestContext) {
        try {
            htmlReporter.flush();
            htmlReporter.stop();
            extent.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by DipikaMishra13** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<suite name="Suite4" parallel="false">
  <test name="Mcs_Res_Au">
    <groups>
      <run>
        <include name="My Products"/>
        <include name="My Usage"/>
        <include name="My Overview"/>
        <include name="My Bill"/>
      </run>
    </groups>
    <classes>
      <class name = "ittmicroservice.Mcs_Res_Au"/>
    </classes>
  </test>
  <test name="Fls_Se_Ur">
    <groups>
      <run>
        <include name="My Products"/>
        <include name="My Usage"/>
        <include name="My Overview"/>
      </run>
    </groups>
    <classes>
      <class name = "ittmicroservice.Fls_Se_Ur"/>
    </classes>
  </test>
  <listeners>
    <listener class-name="CustomTestListener.CustomTestListener"/>
  </listeners>
</suite>

**Comment by DipikaMishra13** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<suite name="Suite4" parallel="false">
  <test name="Mcs_Res_Au">
    <groups>
      <run>
        <include name="My Products"/>
        <include name="My Usage"/>
        <include name="My Overview"/>
        <include name="My Bill"/>
      </run>
    </groups>
    <classes>
      <class name = "ittmicroservice.Mcs_Res_Au"/>
    </classes>
  </test>
  <test name="Fls_Se_Ur">
    <groups>
      <run>
        <include name="My Products"/>
        <include name="My Usage"/>
        <include name="My Overview"/>
      </run>
    </groups>
    <classes>
      <class name = "ittmicroservice.Fls_Se_Ur"/>
    </classes>
  </test>
  <listeners>
    <listener class-name="CustomTestListener.CustomTestListener"/>
  </listeners>
</suite>

**Comment by foursyth** [comment]
Did you see the examples section already for ITestListener?

http://extentreports.com/docs/versions/3/java/

It should work as-is and you can customize it to output the info you have in the code
