### ISSUE TITLE
Extent Report shows me all the TestStep Info of Second Test Case in the First Test Case

### ISSUE THREAD

**Issue by kamaleshrnp** [anshooarora/extentreports-java#1126]
I am using Extent Report Version 3.1.3 using Appium for Mobile Automation Testing

## Summary

Basically, I am invoking First Test inside the Second Test Method using TestNG Framework! So, whenever the Test Method is executed, the first test  executes and the second test is executed. 

## Expected Behavior

The Second test Info should go into the Second Test!

## Current Behavior
In the Extent Report Html, I am seeing two times the First Test Case is executed and second test case is executed once!

All the test information of the second test is recorded into First Test! 

## Sample
 @BeforeSuite
    public void initReport(){ TestReportSetup(); }

    @BeforeMethod
	public void init(Method method) {

    // testInfo = extentReports.createTest(method.getName());

        logger.info("Entering @BeforeMethod - TestRunner.init");
	    SelectCountryPage selectCountryPage = new SelectCountryPage();
        DJSelectPage djSelectPage = new DJSelectPage();
        if(wd.getCapabilities().getCapability("platformName").toString().equalsIgnoreCase("ios"))
        {
            djSelectPage = selectCountryPage.selectCountryClickOkBtn();
            logger.info("Successfully Select the Country(US) and Clicked on the Okay Button(IOS)");
        }else{
            logger.info("Successfully Select the Country(US) and Clicked on the Okay Button(Android)");
        }

        logger.info(" Successfully Exiting @BeforeMethod- TestRunner.init Method");
	}

    @Parameters ("platformName")
    @BeforeTest
    public void setUp(String platformName){
        logger.info("Entering @BeforeTest- TestRunner.setUp");
        setup(platformName);

        logger.info("Successfully Set-up Driver for Platforms and Exiting  @BeforeTest- TestRunner.setUp Method");
    }

    @Test(priority = 1)
    public void onboardingDJTest(){

        logger.info("Entering TestRunner.onboardingDJTest");

        testInfo = extentReports.createTest("Onboarding DJ Test", "");
        DJSelectPage djPage = new DJSelectPage();
      //  Assert.assertFalse(djPage.verifyDJSelectPage(),"Title is Validated");

        djPage.verifyDJSelectPage();
        djPage.selectThreeDJs();
        ArtistSelectPage artistSelPage = new ArtistSelectPage();
        artistSelPage = djPage.clickContinueBtn();

        logger.info("Exiting the TestRunner.onboardingDJTest");
	}

    @Test(priority = 2)
    public void onboardingArtistTest() {

        logger.info("Entering TestRunner.onboardingArtistTest");
        testInfo = extentReports.createTest("Onboarding Artist Test", "Select Three Favorite Artist and Click on Done Bu");

        logger.info("Starting the Execution of TestRunner.onboardingDJTest");
         onboardingDJTest();
        logger.info("Finished the Execution of  TestRunner.onboardingDJTest");
        ArtistSelectPage artistSelPage = new ArtistSelectPage();
        artistSelPage.waitForPageLoad();
        artistSelPage.verifyArtistSelectPage();
        artistSelPage.selectThreeArtists();
        artistSelPage.clickDoneBtn();

        if (wd.getCapabilities().getCapability("platformName").toString().equalsIgnoreCase("android")) {
            artistSelPage.enableLocationServices();
            logger.info("Successfully Enabled Location Services(Android)");

        }
        logger.info("Exiting the TestRunner.onboardingArtistTest");
    }

 @AfterMethod
        public void cleanup(ITestResult result) {
        logger.info("Entering the AfterMethod: TestRunner.cleanup");
        ExtentReporterNG.getResults(result,wd);
        wd.resetApp();
      //  service.stop();
        //new method to log the captured ext results
        logger.info("Successfully Captured Result for Test Case, Resetted the App to initial State and Exiting the AfterMethod: TestNG.cleanup");
    }

    @AfterSuite
    public void reportFlush(){
        logger.info("Entering the @AfterSuite - TestRunner.reportFlush");
        extentReports.flush();
        logger.info("Successfully flushed the reports and  Exiting the  @AfterSuite - TestRunner.reportFlush");
    }

public static void getResults(ITestResult result, AppiumDriver driver){
		String testDescription;

		try{
			//testDescription = result.getMethod().getDescription();
			if (result.getStatus() == ITestResult.SUCCESS){
				BaseClass.testInfo.log(Status.PASS,  "TestCase Passed");
			}else if (result.getStatus() == ITestResult.FAILURE)
			{
				BaseClass.testInfo.log(Status.FAIL,"Test Case Failed");
                BaseClass.testInfo.log(Status.ERROR, "Error Stacktrace here:"+result.getThrowable());
				BaseClass.testInfo.log(Status.FAIL, testInfo.addScreenCaptureFromPath(TouchTunesUtilities.capture(driver))+ "Test Failed");

			}else {
				BaseClass.testInfo.log(Status.SKIP,"Test Case Skipped");
			}
		}catch(Exception ex){
			ex.printStackTrace();
		}

public static ExtentReports TestReportSetup(){
        logger.info("Entering BaseClass.TestReportSetup");
        htmlReporter = new ExtentHtmlReporter(new File("/Users/kpalanisamy/Documents/TouchTunes_V1/test-output/Test_Report_Extent.html"));
        htmlReporter.setAppendExisting(false);
        htmlReporter.loadXMLConfig(new File("/Users/kpalanisamy/Documents/MobileAutomationPoC/And_PoC_ReportTesting/extent-config.xml"));
        htmlReporter.config().getChartVisibilityOnOpen();

        extentReports = new ExtentReports();
        extentReports.setSystemInfo("Env", "QA");
        extentReports.attachReporter(htmlReporter);
        logger.info("Successfully created the Report File in the Specified Path, loaded the XML Config File and exiting the method");

        return extentReports;

    }

## Environment Details

* Extent report Version used: 3.1.3
* Operating System and version: MAC 10.3
* JDK Version: Java 8

## Screenshots

![screen shot 2018-10-19 at 3 58 03 pm](https://user-images.githubusercontent.com/30329297/47240906-d02ebd00-d3b7-11e8-9b98-9499f949985e.png)
![screen shot 2018-10-19 at 3 58 11 pm](https://user-images.githubusercontent.com/30329297/47240908-d2911700-d3b7-11e8-98f2-2522384b07b5.png)

**Comment by BeBestOf** [comment]
Hi @kamaleshrnp this is not a bug, in @test method onboardingDJTest priority=1 you created a test using extent test testInfo which you have not end it, and in your second @Test onboardingDJTest again you created another test but passed referred same existing created instance as testInfo and writing logs using the same instance testInfo, then how sperate log will generate for each @test methods. 
Try this: end testInfo reference at @AfterTest method which executes after every @Test method.

**Comment by kamaleshrnp** [comment]
@BeBestOf Thanks for your reply. Fixed in my code!

**Comment by kamaleshrnp** [comment]
> Hi @kamaleshrnp this is not a bug, in @test method onboardingDJTest priority=1 you created a test using extent test testInfo which you have not end it, and in your second @test onboardingDJTest priority=2 again you created another test but passed referred same existing created instance as testInfo and writing logs using the same instance testInfo, then how sperate log will generate for each @test methods.
> Try this: end testInfo reference at @AfterTest method which executes after every @test method.

Thanks
