### ISSUE TITLE
How to Customize image size in extentreport

### ISSUE THREAD

**Issue by kashyapmanisha** [anshooarora/extentreports-java#1127]
Extent report: I want to have customized images(e.g. specific height and width ) in my html report file for every step execution. As of now images are of some default size, so how to change size of it.Could you please guide how to achieve this?

* Extent report Version used: 2.41
* Operating System and version: Windows 7
* JDK Version: 8.1

**Comment by BeBestOf** [comment]
You can use css style configuration in extent-config.xml in styles tag you can change the width of image. Like below example in extent-config.xml file:

        
        <styles>
            <![CDATA[
                .report-img {   border: 1px solid #f6f7fa;   cursor: zoom-in;    width: 75px; }
            ]]>
        </styles>
