### ISSUE TITLE
Not able to change date/time format by customizing config file

### ISSUE THREAD

**Issue by ImmunePete** [anshooarora/extentreports-java#1130]
Hi,

I'm using Extent Report version 4.0.1 and I want to change some settings in the report by customizing the config file. One of the changes I want to make is concerning the date and time format. 

I tried to change the format by adjusting the config file.
Config file:
        < dateFormat >dd-MM-yyyy< /dateFormat >
        < timeFormat >HH:mm:ss< /timeFormat >

But the current output is as follows: 
Nov 19, 2018 4:00:00 PM

The output as I wish it to be is something like this:
19 november 2018, 16:00

Is a date/time format like this possible? And if yes, how should I configure the config file?

**Comment by foursyth** [comment]
Hello @ImmunePete 

Please open this issue here:

https://github.com/extent-framework/extentreports/issues

Everything version 4 had moved to the extent-framework org.

**Comment by foursyth** [comment]
Also, please let us know which reporter?

**Comment by foursyth** [comment]
@anshooarora this can be closed
