### ISSUE TITLE
My screenshot is not adding to the extent report.

### ISSUE THREAD

**Issue by ChetanNarendra** [anshooarora/extentreports-java#1136]
I am able to generate the extent report and able to capture the screenshot for the failure cases but when i am trying to add the screenshot to the extent report only console errors are displaying instead of screenshot.

## Expected Behavior

Screenshot is not adding to the Extent report.

## Current Behavior

Console Message is showing in the Extent report failure step.

## Environment Details

* Extent report Version used:  
<dependency>
    <groupId>com.vimalselvam</groupId>
    <artifactId>cucumber-extentsreport</artifactId>
    <version>2.0.2</version>
</dependency>

<dependency>
    <groupId>com.relevantcodes</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.0</version>
</dependency>

<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.1.1</version>
</dependency>

* Operating System and version:

Mac: 10.14
* JDK Version: 1.8
## Screenshots
<img width="1440" alt="screenshot 2018-12-12 at 5 03 07 pm" src="https://user-images.githubusercontent.com/28891641/49867282-fc067600-fe2f-11e8-857f-31ef397bba09.png">
##Code
@After()
	 public void teardown(Scenario scenario) throws IOException 
	{
		
		
			if (scenario.isFailed()) 
			{
			 screenshotName = scenario.getName().replaceAll(" ", "_");
				try {
					TakesScreenshot ts = (TakesScreenshot) driver;
					File sourcePath = ts.getScreenshotAs(OutputType.FILE);
					File destinationPath = new File(System.getProperty("user.dir") + "/target/" + screenshotName + ".png");
					FileUtils.copyFile(sourcePath, destinationPath);   
					Reporter.addScreenCaptureFromPath("./target/"+screenshotName+".png");
					
					
				} catch (IOException e) {
				} 
			}		
	}

**Comment by anshooarora** [comment]
This generally happens when the path is not resolved by the report.  Either pass a path relative to the report, or upgrade to version 4 and use setting as mentioned in [this post](https://github.com/extent-framework/extentreports/issues/15#issuecomment-446662200).
