### ISSUE TITLE
I am using this Extentreport  But i am not able to Put log for different tests, Can you please help me out to put Log using this Extentreports

### ISSUE THREAD

**Issue by poojaghosh47** [anshooarora/extentreports-java#1137]
## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by anshooarora** [comment]
I would suggest upgrading to version 4 and using the [testng-adapter](https://github.com/extent-framework/extentreports-testng-adapter) which allows retrieving the current instance (in a thread-safe manner) to which you can add additional logs.  The other way is to see the current implementation in the adapter and customize it for use with version 3.
