### ISSUE TITLE
Using ExtentReports as a listener and logger simultaneously

### ISSUE THREAD

**Issue by madhavanrakesh** [anshooarora/extentreports-java#151]
Hey Anshoo,

First of all, Cheers for the awesome plugin to generate reports. Works like a charm!

My question is : I’m using the ExtentReports as a listener in TestNG. Can i use it as a logger as well at the same time? I'd like to append/log all the sysout statements I've provided in my selenium script to the final report generated by the Extent. I run my tests only through testng.xml file and hence I've to use the Extent as a listener only. Any way to make this happen?

**Comment by guneetgarg** [comment]
i too using  ExtentReports as a listener in TestNG with log4j for log..
But as there is currently no way we can add our log in report except the default logger method provided in extent

**Comment by madhavanrakesh** [comment]
Hey Guneet,

Thanks for the response. How do we use the default logger method? Can you provide me a code sample? I've initially created the listener class of ExtentReports and then tried creating an instance of the listener in classes which contain the test cases and then used the logger method. This approach isn't working for me. Shows a nullPointerException. Any help would be much appreciated! Thanks in advance.

**Comment by guneetgarg** [comment]
Check below code
http://extentreports.relevantcodes.com/java/version2/docs.html#basic-usage-example

But this won't help you much when you are using testNg listener

**Comment by madhavanrakesh** [comment]
Thanks for the response, Guneet! If u use Reporter.log() provided by TestNG instead of log4j for logging, ExtentReports does display the logs!

**Comment by guneetgarg** [comment]
But while using Reporter.log() we will see logs in TestRunner Logs instead of in test case

So there is no benefit to use Reporter.log()

**Comment by anshooarora** [comment]
Guneet -  since you are using log4j - how do you expect those logs to appear under Extent?  

You would have to create a wrapper that reports to log4j and Extent at the same time.. `ExtentTestManager` below would be responsible for managing each ExtentTest. 

```java
class Logger {
    static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger();

    public void info(String message) {
        log.info(message);
        ExtentTestManager.getTest().log(LogStatus.Info, message);
    }
}

public class ExtentTestManager {  // new
    static Map<Integer, ExtentTest> extentTestMap = new HashMap<Integer, ExtentTest>();
    private static ExtentReports extent = ExtentManager.getInstance();

    public static synchronized ExtentTest getTest() {
        return extentTestMap.get((int) (long) (Thread.currentThread().getId()));
    }

    public static synchronized void endTest() {
        extent.endTest(extentTestMap.get((int) (long) (Thread.currentThread().getId())));
    }

    public static synchronized ExtentTest startTest(String testName) {
        return startTest(testName, "");
    }

    public static synchronized ExtentTest startTest(String testName, String desc) {
        ExtentTest test = extent.startTest(testName, desc);
        extentTestMap.put((int) (long) (Thread.currentThread().getId()), test);

        return test;
    }
}
```

ExtentTestManager ref:  #102.

**Comment by madhavanrakesh** [comment]
//But while using Reporter.log() we will see logs in TestRunner Logs instead of in test case

//So there is no benefit to use Reporter.log()

Can you be more specific, Guneet? I'm using Reporter.log() inside my test cases and it works just fine. All the logs are showing up in ExtentReports log including the screenshots taken on test failure. So, i didn't get you. Am i missing something here?

PS : I'm using ExtentReports 2.10

**Comment by ansonliao** [comment]
Hi Anshoo,
Is it possible that, let extent report catch any exception implicitly when the TestNG test case running?
I study the extent report usage, and found that try to catch the exception via try...catch function, explicitly.

As you know, sometimes the code is works, but next time maybe crash, for example, array index out of boundary, maybe programmer reduced the webelement of page suddenly.

please advise.

**Comment by ansonliao** [comment]
Hi Anshoo, 
I found someone post here that how to add exception in extentreport.
https://github.com/anshooarora/extentreports/issues/102

**Comment by RahulVermaAutomation** [comment]
Hi Anshu,

Thanks for your help. I am using Extent report version 2.40.1 using maven pom. But report which is generating for me is not according to the report that you have published in the github file name: TestNgSeleniumExample.html.

Could you please tell me how would i able to change the look and feel of my report according to your report. Report generated in my case is attached in this comment.

[extent_report.txt](https://github.com/anshooarora/extentreports/files/101375/extent_report.txt)

Thanks,
Rahul

**Comment by RahulVermaAutomation** [comment]
Hi Anshoo,

I am using Extent report for the reporting purpose as of now. But now I want it to use Log4j logs and display it in the reports. I am using Log4j for the logging and dont want to add any other code for logging on my scripts. I am using the same code which you have given above in github. Could you please provide me code of integrating log4j with extent reports.

Thanks,
Rahul

**Comment by email2vimalraj** [comment]
@RahulVermaAutomation : You cannot log the `Log4j` logs directly into the extent report unless you write your own logger and start storing your logs in some memory object and then push those logs to extent report.

It is as simple as like you cannot do the same with even the default TestNG report, so the extent report.

I'm closing this issue, kindly feel free to re-open in case you need further help.
