### ISSUE TITLE
ExtentReports seems to only collect results from 1 suite file when multiple suites are run in parallel

### ISSUE THREAD

**Issue by testphreak** [anshooarora/extentreports-java#154]
TestNG supports running multiple suites in parallel either via command line or via the pom in the failsafe plugin section. I was trying that today and I'm not sure if it's the way I'm set up or a limitation with the report, ExtentReports only reported results from 1 suite file even though Maven ran both suites.

Is this something you're aware of Anshoo or have a solution for? Let me know if you're able to reproduce it too. ReportNG support this.

**Comment by anshooarora** [comment]
If the Extent instance is shared between the 2 suites, then the report should be generated with both.  I will test this soon and update.

**Comment by testphreak** [comment]
Hey @anshooarora , I noticed you started labelling issues, which is a good thing. Could you label mine or add a comment, so I get a sense about it's priority or when it may make it into a release? They are #149, #150, #153, #154. No rush. Thanks!

**Comment by email2vimalraj** [comment]
@testphreak and @anshooarora : I believe this is very old thread and now the extent report has the capability to create as many nodes needed by the user.

Hence I'm closing it. Kindly re-open in case you want further help.
