### ISSUE TITLE
Video content doesn't playback

### ISSUE THREAD

**Issue by karenpetrie** [anshooarora/extentreports-java#208]
Using the AddScreencast functionality, I have tried multiple video formats but the Extent Reports page doesn't replay them.

The video is saved to the location I have specified and plays back fine.

**Comment by anshooarora** [comment]
What is the format of your video?

PS.  There are plenty of video formats which is why this area still remains largely untested.

**Comment by karenpetrie** [comment]
I've tried .mp4, .wmv, .avi

**Comment by anshooarora** [comment]
Only MP4.

**Comment by anshooarora** [comment]
Only MP4.

The current impl uses the `video` tag which may be the culprit.  I believe `iframe` or `object` may work for all, but would have to research this more.  Feel free to contribute if you find a solution.

**Comment by karenpetrie** [comment]
Do you have an example of this at all?

Below is what I am currently using


String videoName = scj.OutputScreenCaptureFileName;
                test.Log(LogStatus.Info, "Screencast: " + test.AddScreencast(videoName));

**Comment by anshooarora** [comment]
Are you able to load the video in your browser using the path from `scj.OutputScreenCaptureFileName` manually, or does it open a dialog asking where to open the file?

Example: see the following <a href='http://relevantcodes.com/Tools/ExtentReports2/issues/208/208.html'>link</a>.

```
test.Log(LogStatus.Pass, "Step Info " + test.AddScreencast("vid.avi"));
test.Log(LogStatus.Pass, "Step Info " + test.AddScreencast("vid.mov"));
test.Log(LogStatus.Pass, "Step Info" + test.AddScreencast("vid.mp4"));
```

Only the last one works - .mp4 format.

**Comment by karenpetrie** [comment]
The last one works in your example so I'm not sure what I've done wrong.

scj = new ScreenCaptureJob();
            string currTime = DateTime.Now.ToString(@"yyyy-MM-dd-HH-mm-ss");
            scj.OutputScreenCaptureFileName = @"C:\Users\karenp\Documents\Selenium\Screenshots\Web_RentTab_" + currTime + ".mp4";
            scj.Start();
//Steps are here
test.Log(LogStatus.Info, "Screencast: " + test.AddScreencast(videoName));

**Comment by anshooarora** [comment]
Try this:

```
scj.OutputScreenCaptureFileName = "C:/Users/karenp/Documents/Selenium/Screenshots/Web_RentTab_" + currTime + ".mp4";
```

**Comment by karenpetrie** [comment]
I've tried your suggestion and a few other possible changes but unfortunately still not fixed.
I had a look at the code from your example and I see it's being picked up from a URL and not from a folder location so think this is the issue.

**Comment by anshooarora** [comment]
I referenced the video as a file on my system before uploading it to the ftp and it worked.  Can you share the source from your browser of the video tag?  This is what I have locally:

![src](https://cloud.githubusercontent.com/assets/4107384/11844027/29a48dd8-a3d2-11e5-9a98-c4cedaca94e9.png)

**Comment by karenpetrie** [comment]
![image](https://cloud.githubusercontent.com/assets/16258312/11844277/cb375206-a405-11e5-94cb-2390afd222f3.png)

**Comment by karenpetrie** [comment]
Just checking if there's any update on this?

**Comment by anshooarora** [comment]
Haven't had a chance to work on this but this is one of the items to be fixed for the upcoming release.  Will update this post when I have more info around this topic.  If you find something, or any technique to link local video files, do share.

**Comment by anshooarora** [comment]
I did find this though:  http://stackoverflow.com/questions/18246053/how-can-i-create-a-link-to-a-local-file-on-a-locally-run-web-page

**Comment by email2vimalraj** [comment]
@karenpetrie : Did the solution provided by @anshooarora worked for you?

Feel free to re-open in case you need further help.
