### ISSUE TITLE
Provide the ability to log to console

### ISSUE THREAD

**Issue by testphreak** [anshooarora/extentreports-java#244]
I like a running commentary on the console as my tests are running. ExtentReports currently doesn't support this feature to my knowledge. I am aware of the setTestRunnerOutput method, but that is still after the fact, i.e. I need to wait for the tests to finish before I can view the log in the report file.

Currently to do that with ExtentReports, I have a wrapper method in a wrapper class called TestLogger which my tests use to log, both to standard output (console) and to the report.

``` java
TestLogger.java
public static void log(final String message) {
        Reporter.log("<Thread-id: " + Thread.currentThread().getId() + "> " + message, true);
        ExtentReporter.getTest().log(LogStatus.INFO, message + "<br>");
    }
```

This method uses TestNG's Reporter.log to output to console with the "true" flag. Then I use ExtentReport's logger to log to report. Previously with ReportNG I could use TestNG's Reporter to output both to console and to a report.

Perhaps, there were some design choices made in the beginning to have a separation of concerns, but I think it would be neat to evolve ExtentReports into a true logger by leveraging TestNG's Reporter or log4j to provide the ability to log to console as well.

This may help logging performance for large WebDriver projects that use ExtentReports, as they don't need to have multiple static methods to do the job. i.e. tests call static TestLogger.log which then calls static Reporter.log and static synchronized ExtentReporter.getTest()'s log method.

**Comment by anshooarora** [comment]
This feature is available in the upcoming pro version, along with an EmailReporter and several other features not available in the community version.  More details will be available soon.
