### ISSUE TITLE
Enhancement to be able to show/hide log depending on status

### ISSUE THREAD

**Issue by JonathanAstre-accor** [anshooarora/extentreports-java#315]
Hi, thank you for your work, the generated report are amazing.

But I really appreciate to be able to show/hide the log in a specific test in order to be able to show only error and validate step or more (warning, unknow, info, ...) in case of debugging.

**Comment by karthikbhatnagar** [comment]
+1

this would be a good feature to add

**Comment by MbenaissaAccor** [comment]
Hi all,
This is can be an excellent and very util enhancement. In fact, in my test code I can drive my logs by level and in the report I can filter them. It is important to see only infos or errors and hide all the debug lines from my report for example. 
Waiting this feature

**Comment by adilmi** [comment]
very good idea, it responds to one of my questions

**Comment by anshooarora** [comment]
ER complete.  This has been added for the next release.

**Comment by anshooarora** [comment]
This feature is available starting 2.41.0-beta1 (now available for download).

**Comment by JonathanAstre-accor** [comment]
Hi, 

Thank you for this feature.
I test it in the beta4 and works well, however, only partially meets my actual requirement. I think this feature will be better if user is able to select multi status (for example like a checklist).

**Comment by MbenaissaAccor** [comment]
Thank you anshooarora for this wonderful feature, I tested it also and I think that it will be better to be able to select multi log level (like a filter). In fact in my log, I have functional(info) and technical(unknown) logs but also I want to see the errors or warnings or the passed status; So I join Jonathan to enhance this new feature to be completely useful.

**Comment by pankaj-sukale** [comment]
Hi @anshooarora,
There is a attachment shared for this feature in issue https://github.com/anshooarora/extentreports/pull/384. Which gives an example for this feature to expand and collapse test step. It looks like it is a cucumber report. 
Can we use it for normal Extent report? Could you please let us know how to enable this feature.
