### ISSUE TITLE
At top of execution report "ExtentReports" hyperlink is there? 

### ISSUE THREAD

**Issue by jain-pulkit** [anshooarora/extentreports-java#461]
"ExtentReports" hyperlink and text is present in the execution report at top. Which does not look good while sending reports to client.

Is there a way to remov/update "ExtentReports" hyperlink?

Please help?

![image](https://cloud.githubusercontent.com/assets/16830625/15038623/d8e6c66c-12c2-11e6-99db-5f1578911057.png)

**Comment by karthikbhatnagar** [comment]
As this is open source and the devs don't make any financial benefit
The only means for them is to maintain attribution as the product is given for free when people come and want to pass the product on as their own.bwhy not create your own reports?

**Comment by perwez123** [comment]
It would be really great if there is a possibility to overwrite this
hyperlink .

On Thu, May 5, 2016 at 5:33 PM, Karthik <notifications@github.com> wrote:

> As this is open source and the devs don't make any financial benefit
> The only means for them is to maintain attribution as the product is given
> for free when people come and want to pass the product on as their own.bwhy
> not create your own reports?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/461#issuecomment-217136730>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by jain-pulkit** [comment]
Still, it should be considered for review. Better to have a config to override it. It will be more beneficial to Devs of ExtentReport.

**Comment by anshooarora** [comment]
I will add a configuration via config.xml to disable this link, marking as an enhancement.

**Comment by sethisandeepsethi** [comment]
Although I agree with @karthikbhatnagar that proper credit must be given to the developer of these nice open-source report (i.e. @anshooarora ) but that is true that clients/PMs would ask what is the link.

@jain-pulkit  Idid following to replace the link:
1. Create extent-configuration XML
2. Use following custom Javascript:
` 
		<scripts>
            <![CDATA[
                $(document).ready(function() {
                	$(".logo-content").hide();
                	$(".logo-container").html("Some Small HTML text" );
                });
            ]]>
		</scripts>`

This will replace ExtentReports link with Some Small HTML text. This is an HTML so can also provide the </a href=''> tag to link some project specific URL.


@anshooarora  I don't think you need to make the change.Thanks for the reports
Enjoy
Sandeep
