### ISSUE TITLE
extent report with JUnit

### ISSUE THREAD

**Issue by akshking** [anshooarora/extentreports-java#478]
Hi Anshu,

As per our earlier discussion have applied logic from here - http://www.kieftsoft.nl/extentreports-review/
Even i got success in getting the report but in the report it is showing me only test suite name , It is not listing down all the test scripts & steps count ?? Anything where i made a mistake ?

Can we add screenshot of steps in the report ? How ?

Can you please review my code & provide me guidelines ?

**Comment by anshooarora** [comment]
So you are not able to view logs in your tests?  Can you share a sample?

I am not sure about the screenshots as I mostly use TestNG, so have little idea of how to correctly create this framework around JUnit.

**Comment by akshking** [comment]
Please attached herewith code , i have written a @rule annotation in the test suite class & running all the test using it. You can see the results inside the folder.

Now if you see the result you will find that it is only suite level result.
also as shown on your site & tutorials , It should show multiple tabs report of pie chart etc but in my case it is not happening.

Can you please tell me ..where is the mistake.

**Comment by akshking** [comment]
Please find the project here - 

It's uploaded on my google drive - 

https://drive.google.com/open?id=0B6WwGPbXgaRkYWpMSy1Pal9FWk0

**Comment by akshking** [comment]
Hi anshu - Did you manage to get the attachment , Please let me know.

**Comment by akshking** [comment]
Hi Anshoo - Can you please look into my query ?

**Comment by anshooarora** [comment]
Can you add `extent.endTest(test)` right after you are doing test.log() and check?  Adding it while flushing will not give the correct picture of when the test was really finished.

```
@Override
protected void succeeded(Description description) {
	ExtentTest test = extent.startTest(description.getDisplayName());
	test.log(LogStatus.PASS, "Test Run Successful");
        extent.endTest(test);
	testList.add(test);
}

// Likewise in case of failure
@Override
protected void failed(Throwable e, Description description) {
	ExtentTest test = extent.startTest(description.getDisplayName());
	test.log(LogStatus.FAIL, "Test Failure: " + e.toString());
        extent.endTest(test);
	testList.add(test);
}
```

**Comment by akshking** [comment]
Hi Anshoo - I have made changes as per your advise but it didn't work.

Can you please download this project & run it in maven - 

https://drive.google.com/folderview?id=0B6WwGPbXgaRkNzMwNERGUmF6Nmc&usp=sharing

**Comment by chayanikaghosh** [comment]
I  am facing issue to integrate extent report with JUNIT 5. Has anyone tried this. Can anyone share the sample code of the same.
