### ISSUE TITLE
Extent Report Saves Entire History of Ran tests. I only want test from that one session.

### ISSUE THREAD

**Issue by Aswilli4** [anshooarora/extentreports-java#479]
When I run a suite of tests how do I keep only the current run of the entire suite?
If I use

```
ExtentReports extent = new ExtentReports(file-path);
```

It only saves only the last test ran. *(But I want the entire suite of that session)

If I use

   ExtentReports extent = new ExtentReports(file-path, false);

It saves all of the tests as I want it to (entire suite), but its saving the entire history. I only want that run session. Is there a way to distinguish this?

**Comment by anshooarora** [comment]
The first usage you have shared is correct for a single run session.  Are you creating multiple instances of extent?  That may cause the issue you are having where only the last test gets saved.

**Comment by Aswilli4** [comment]
@anshooarora  Realized it was simple as Saving the html file else where and the next session had a clean set of tests displayed. I have ran into another issue though. I am using the .net (C#) version of Extent Reports. Everything is working fine but once I added Parallel Testing in I am only saving the last instance (test) of the report ran. I am running my extent.Flush() in my base class under a [OneTimeTearDown] Attribute but it seems to be called still after every test. How can I call this flush after all my tests have ran so it logs everything?

**Comment by anshooarora** [comment]
Even if it runs everytime, all tests should be logged.  Are you creating an instance of extent each time a test is run?  That may be the reason why you are only seeing 1 test.

**Comment by Aswilli4** [comment]
@anshooarora 

I hope this is helpful. I have my instance of extent set up in a Base Class

`       protected ExtentReports extent;
            protected ExtentTest test;
        
        [OneTimeSetUp]

            public void FixtureInit()
            {
                extent = ExtentManager.Instance;
                extent = new ExtentReports(FPATH(), false);
            }`

So objects extent and test are both referenced in the base class. I am using N Unit 3 so I placed the instance as well as the FilePath to report to in a [OneTimeSetup] Attribute, is this correct? Please let me know if any other information is needed and thank you for looking into this.

**Comment by anshooarora** [comment]
You are creating a new instance of extent in OneTimeSetup after getting the instance from the Singleton.  Do you think that might be causing this?

**Comment by anshooarora** [comment]
So basically, what you should do is:

```
[OneTimeSetUp]
public void FixtureInit()
{
  extent = ExtentManager.Instance;
}
```
