### ISSUE TITLE
.net    Converting Console.WriteLine to  test.Log()

### ISSUE THREAD

**Issue by Aswilli4** [anshooarora/extentreports-java#493]
@anshooarora   

I have my Test Structured in Such a way it includes:

Base Class
Object Repository Class (where I am calling many of my methods for the tests)
Test Classes

At the Object Repository Level I have written many Test Steps to Console.writeline(). The only way I am currently report the Test steps into my test class is to set the content of each Console.Writeline() to a String value and then in the test class calling each test.Log(String) in order to see those test steps completed. While this does work it is incredibly inefficient. Is there any simple method of converting all Console.Writeline in an Object Repository class to test.Log so I can simply call it in my Tests?

**Comment by anshooarora** [comment]
I think this is more of an IDE question and since you are using Visual Studio, would a project-wide replace work?
