### ISSUE TITLE
request to make extenttest serializable

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#495]
Getting below exception when i am trying to pass the extent object from one jvm (automation frameclient) to another jvm (automation framework server).

**java.rmi.MarshalException: error marshalling arguments; nested exception is: 
    java.io.NotSerializableException: com.relevantcodes.extentreports.ExtentTest**

**Scenario:**
Framework has 2 components. Client and Server. (currently both running in same machine).
Client side initiates parallel threads, extent report common for all threads, send the test operations requests to server, call extentclose once all the threads completed.
Server side executes the tests, do logging and reporting.

**Comment by gsaimadhu** [comment]
I have downloaded the code with this fix. But while building with maven i see errors. 

C:\Users\ganma\Downloads\extentreports-master\extentreports-master\java\extentreports>
mvn package -DskipTests
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ExtentReports for Selenium 2.41.0
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/ant/ant/1.7.0/ant-1.7.0.jar
Downloading: http://repo.maven.apache.org/maven2/org/apache/ant/ant-launcher/1.7.0/ant-launcher-1.7.0.jar
Downloading: http://repo.maven.apache.org/maven2/org/testng/testng/6.9.9/testng-6.9.9.jar
Downloading: http://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/ant/ant-launcher/1.7.0/ant-launcher-1.7.0.jar (12 KB at 7.1 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar (263 KB at 89.1 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/testng/testng/6.9.9/testng-6.9.9.jar (850 KB at 147.8 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/apache/ant/ant/1.7.0/ant-1.7.0.jar (1260 KB at 160.8 KB/sec)
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ extentreports ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 34 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ extentreports ---
[INFO] Compiling 48 source files to C:\Users\ganma05\Downloads\extentreports-master\extentreports-master\java\extentreports\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] C:\Users\ganma05\Downloads\extentreports-master\extentreports-master\java\extentreports\src\main\java\com\relevantcodes\extentreports\model\Test.java:[99,12] e
[ERROR] C:\Users\ganma05\Downloads\extentreports-master\extentreports-master\java\extentreports\src\main\java\com\relevantcodes\extentreports\model\Test.java:[133,12]
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.187 s
[INFO] Finished at: 2016-06-02T12:28:48+05:30
[INFO] Final Memory: 12M/244M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project extentreports: Compilation failure: Compilatio
[ERROR] C:\Users\ganma05\Downloads\extentreports-master\extentreports-master\java\extentreports\src\main\java\com\relevantcodes\extentreports\model\Test.java:[99,12] e
[ERROR] C:\Users\ganma05\Downloads\extentreports-master\extentreports-master\java\extentreports\src\main\java\com\relevantcodes\extentreports\model\Test.java:[133,12]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
C:\Users\ganma\Downloads\extentreports-master\extentreports-master\java\extentreports>

**Comment by anshooarora** [comment]
This is what I see with the same build:

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ExtentReports for Selenium 2.41.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ extentreports ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 34 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ extentreports ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 48 source files to C:\Users\Anshoo\Desktop\extentreports-master\java\extentreports\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ extentreports ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Anshoo\Desktop\extentreports-master\java\extentreports\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ extentreports ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to C:\Users\Anshoo\Desktop\extentreports-master\java\extentreports\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ extentreports ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ extentreports ---
[INFO] Building jar: C:\Users\Anshoo\Desktop\extentreports-master\java\extentreports\target\extentreports-2.41.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.334 s
[INFO] Finished at: 2016-06-02T22:15:05-04:00
[INFO] Final Memory: 20M/375M
[INFO] ------------------------------------------------------------------------
```

**Comment by gsaimadhu** [comment]
The previous error says that remove method is not overridden in Test.java. When i added the following line 'public void remove(){}' in class LogIterator and class TestAttributeIterator, the build went success.

I tried with the current jar you shared. **Getting exceptions. Need to make all variables in ExtentReports Serialized.**

java.rmi.MarshalException: error marshalling arguments; nested exception is: 
	java.io.NotSerializableException: com.relevantcodes.extentreports.model.Test
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:157)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:194)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:148)

**Comment by gsaimadhu** [comment]
Anshoo,
Unable add the ZIP file to the issue.
So posting it.
Only Serializing ExtentTest was not sufficient. Got errorrs. I have added
Serializable for the required classes. Attached the changes for your
reference.

Thanks
Madhu

**Comment by gsaimadhu** [comment]
filenames:
**com.relevantcodes.extentreports**
ExtentReports.java
LogStatus.java

**com.relevantcodes.extentreports.model**
ExceptionInfo.java
Log.java
Test.java
TestAttribute.java

**Comment by gsaimadhu** [comment]
After the above classes are serialized, i am able to pass the ExtentTest object to framework server. And the test report is coming with all the logs and test status info.
BUT, the child tests are duplicated. And the duplicates are on the LHS of the report with Unknown status.

![extent_report_snapshot](https://cloud.githubusercontent.com/assets/8359360/15778083/a0d939b6-29b1-11e6-90a2-1edf4e94bd42.jpg)

[ExtentHTMLTestReportWriter.txt](https://github.com/anshooarora/extentreports/files/297516/ExtentHTMLTestReportWriter.txt)

**Comment by gsaimadhu** [comment]
Anshoo, did u got chance to look into this issue?

**Comment by gsaimadhu** [comment]
I have moved childTest start to the Server side of Framework. With this workaround, i have overcome the issue. 
Can you please add Serializable to the required classes as mentioned in above comments, so that newer versions of Extent i can directly use.

**Comment by anshooarora** [comment]
You can send in a pull request with these changes and I will merge.

**Comment by gsaimadhu** [comment]
Anshoo, I am getting permission error while commit
$ git push origin gsaimadhu
Username for 'https://github.com': gsaimadhu
Password for 'https://gsaimadhu@github.com':
remote: Permission to anshooarora/extentreports.git denied to gsaimadhu.
fatal: unable to access 'https://github.com/anshooarora/extentreports.git/': The requested URL returned error: 403

Please provide permissions,

Thanks

**Comment by anshooarora** [comment]
Hmm, don't commit directly.. send in a pull request.

**Comment by anshooarora** [comment]
See this for example:  https://github.com/blog/1969-create-pull-requests-in-github-for-windows

**Comment by gsaimadhu** [comment]
I am unable to create pull request. 
I am attaching the error screenshot and patchdiff file.
[patch-diff.txt](https://github.com/anshooarora/extentreports/files/320552/patch-diff.txt)

![pull request failing to push local changes](https://cloud.githubusercontent.com/assets/8359360/16151971/22918952-34bd-11e6-94b7-a41e57b61c1c.jpg)

**Comment by anshooarora** [comment]
Please try using the Github desktop application instead:  https://desktop.github.com/

If it still doesn't work, I will do it manually but would ideally like you to get credit for your commit.

**Comment by gsaimadhu** [comment]
Thanks Anshoo. I did pull request successfullly.
Please review and let me know if any info is required.

**Comment by anshooarora** [comment]
Closing, see #495 for commit details.

**Comment by gsaimadhu** [comment]
Anshoo, 
There are multiple classes that need to be serialiazed. But the 2.41.1 shows serializable only for ExtentTest.
I have pulled the following changes also, but they are not visible in 2.41.1
gsaimadhu commented on Jun 3 • edited
Classes that needs to be Serialized
com.relevantcodes.extentreports
ExtentReports.java
LogStatus.java

com.relevantcodes.extentreports.model
ExceptionInfo.java
Log.java
Test.java
TestAttribute.java
ScreenCapture.java

**Comment by gsaimadhu** [comment]
Anshoo, Any updates on this?

**Comment by anshooarora** [comment]
All models have been serialized,  please check with this: https://github.com/anshooarora/extentreports-java/commit/11268f35c96b6e2b98de32f32afc6de9e9e81906

If it looks good, we can have a release version in the upcoming week.

**Comment by gsaimadhu** [comment]
Anshoo,
I have downloaded the zip, I verified. 
**Serialziation requried for following classes**:
-------------------------------------------------
**com.relevantcodes.extentreports**
ExtentReports.java //Please add Serialization
LogStatus.java //i didnot find this file. Is there a change from 2.41.0 to current version?

**com.relevantcodes.extentreports.model**
ScreenCapture.java //Please add Serialization

**Also, This current downloaded i could not compile. Getting compilation error**
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.3/maven-shared-utils-0.3.jar (152 KB at 127.5 KB/sec)
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 14 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ extentreports ---
[INFO] Compiling 71 source files to C:\Users\ganma05\Downloads\extentreports-java-master\extentreports-java-master\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
javac: invalid target release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.115 s
[INFO] Finished at: 2016-09-25T12:09:06+05:30
[INFO] Final Memory: 10M/244M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project extentreports: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 1.8
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

FYI,

**Comment by anshooarora** [comment]
Master is upcoming version 3.0.  

Use the branch:  https://github.com/anshooarora/extentreports-java/tree/2.41.2?files=1

**Comment by gsaimadhu** [comment]
Anshoo,
I tried with 2.41.2 link, I am getting **2 serialization exceptions**:
java.io.NotSerializableException: com.relevantcodes.extentreports.HTMLReporter 
java.io.NotSerializableException: freemarker.ext.beans.SimpleMapModel 

How to fix, java.io.NotSerializableException: freemarker.ext.beans.SimpleMapModel ?

Please look into these issues and let me know if any info is required.

Thanks
Madhusudhan G

**Comment by anshooarora** [comment]
SimpleMapModel is part of the freemarker API, not sure why the issue came up here and in HTMLReporter.. these will stay and work on the host machines instead of nodes.

**Comment by anshooarora** [comment]
PS.  This was the most recent commit with all models now serializable:  https://github.com/anshooarora/extentreports-java/commit/11268f35c96b6e2b98de32f32afc6de9e9e81906.

**Comment by gsaimadhu** [comment]
Anshoo, i tried both ways (default) and also by removing Serializable from SuiteTimeInfom MediaList.
The above 2 issues are still present.

Caused by: java.io.NotSerializableException: freemarker.ext.beans.SimpleMapModel
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1777)
	at java.util.HashMap.writeObject(HashMap.java:1354)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1777)
	at java.util.HashMap.writeObject(HashMap.java:1354)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at sun.rmi.server.UnicastRef.marshalValue(UnicastRef.java:294)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:153)
	... 9 more
error marshalling arguments; nested exception is: 
	java.io.NotSerializableException: freemarker.ext.beans.SimpleMapModel

Thanks
Madhusudhan G
