### ISSUE TITLE
Do we have any Extent Interface to fetch the Test Summary Info from Extent Test report?

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#504]
**Usecase:**
To give the clear picture of current status of testing, I need to send the Test Summary information in the body of our AutomatedTest notification mail as part of Continuous Integration.
Please see the screenshot attached (taken from current extent test report)

**Are there any APIs to fetch the information related to:**
1. Total Tests, Number of Tests Passed, Number of Tests failed, 
2. Pie chart representing this info
3. Test Categories

![test summary](https://cloud.githubusercontent.com/assets/8359360/15851597/1765f91e-2cbb-11e6-96b4-4fb0bd0fc506.jpg)

**Comment by anshooarora** [comment]
This is currently not possible, but the email template is in progress.  Once ready, would that work?  I am not sure if the pie chart will work once sent over email, but I am still researching this aspect.

**Comment by gsaimadhu** [comment]
Email template should work if it contains the above information.
Can you share the details like what is planned as part of email template?

**Comment by gsaimadhu** [comment]
Anshoo,
Can you share any info on email template availability and feature details on how it looks, etc?

Thanks

**Comment by gsaimadhu** [comment]
Since Automated Notification Emails will be shared with Higher management, can we get email template with **SNAPSHOT of the pie charts** ?

**Comment by anshooarora** [comment]
The email template will be available in version 3, and it currently does not have pie charts as its not completely straight-forward as attaching the image.  Generally, the image is served from a server and downloading by the client.  I am not sure how attachments would work across different email clients though.

**Comment by saikrishna321** [comment]
@anshooarora typically can get these Test SUmmary after the report is flushed or before the report is flush

**Comment by anshooarora** [comment]
Email template is in progress, since the pre-release version 3 is out, i will focus on the email template and tests as these 2 pieces need to be finalized soon.

**Comment by nsharma-git** [comment]
@anshooarora Seems this is in high demand. I just started with 3.0.0. If you can point me to code / sample to generate email, that would be great. I'm using Extent as TestingNG listener. Thanks.

**Comment by anshooarora** [comment]
Update:  The email template will only be available as part of the pro-version.  The community version will not have this template.
