### ISSUE TITLE
How to use stacktrace in MSTest

### ISSUE THREAD

**Issue by dssauto** [anshooarora/extentreports-java#508]
Hi,
I am using MSTest but I was not able to implement this part of the code:
`var stacktrace = string.IsNullOrEmpty(TestContext.CurrentContext.Result.StackTrace)
                    ? ""
                    : string.Format("<pre>{0}</pre>", TestContext.CurrentContext.Result.Message);`

How can I grab my exception message into stacktrace "TestContext.CurrentContext.Result.Message"  using MSTest?
Thank you.

**Comment by anshooarora** [comment]
This might help:  http://stackoverflow.com/questions/9666562/how-to-get-the-unit-test-method-name-at-runtime-from-within-the-unit-test

```
public string GetTestMethodName()
{
    try
    {
        // for when it runs via TeamCity
        return TestContext.CurrentContext.Test.Name;
    }
    catch
    {
        // for when it runs via Visual Studio locally
        var stackTrace = new StackTrace(); 
        foreach (var stackFrame in stackTrace.GetFrames())
        {
            MethodBase methodBase = stackFrame.GetMethod();
            Object[] attributes = methodBase.GetCustomAttributes(
                                      typeof(TestAttribute), false); 
            if (attributes.Length >= 1)
            {
                return methodBase.Name;
            }
        }
        return "Not called from a test method";  
    }
}
```
