### ISSUE TITLE
New feature request for Email-able report - User should be able to insert the URL into Emailable report 

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports-java#51]
## UAC

1.User should be able to insert the URL 
(Extent report ) into Email-able report .
2.When user click on the URL , they should be navigated to the URL they hit .

Description -
This feature will be nice to have  , and all the recipient of the report can click on the link provided on the report to look onto the extent report or Testing Application URL 

For example 

Click on the link given below to view detail report (or some meaningful message)
Report Link -http://10.98.1.62:8181/extentreport/IAPTestingReport.html#!

Testing Application Link - https://www.googlee.com

**Comment by anshooarora** [comment]
Adding enhancement, the template is currently in progress.

**Comment by anshooarora** [comment]
Emailable report will be available in the upcoming pro version of ExtentReports.
