### ISSUE TITLE
how to scale base64 image in the report

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports-java#512]
@anshooarora @email2vimalraj i have attached the base64 image to the report, but clicking the image its really large.can we have it scaled to a certain %

<img width="1440" alt="screen shot 2016-06-10 at 3 00 04 pm" src="https://cloud.githubusercontent.com/assets/4045041/15960144/206fa876-2f1c-11e6-9232-e620e4ba83a0.png">

**Comment by saikrishna321** [comment]
we need to set the width and height here 
https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/view/ScreenshotHtml.java#L22

**Comment by email2vimalraj** [comment]
Sent a PR #514

**Comment by email2vimalraj** [comment]
#514

**Comment by saikrishna321** [comment]
@email2vimalraj looks good to me.. @anshooarora can you please review and merge.... 

my project is depending on this release now.. would be great if we can have a release

**Comment by anshooarora** [comment]
merged, I will release this build very soon..

Been busy working on version 3, lots and lots of changes there so will include this fix there as well.

**Comment by saikrishna321** [comment]
Awesome .... any timeline for the release dude ??

**Comment by anshooarora** [comment]
Will try by end of this week or early next.

**Comment by saikrishna321** [comment]
@anshooarora the idea of having the images to base64 is that the report could be emailed, do you think doing this for like 200 screenshots would get the report.html size bigger ?

**Comment by email2vimalraj** [comment]
It will be definitely. But lesser than attaching the png files.

**Comment by saikrishna321** [comment]
@anshooarora any updates on release 2.41.1

**Comment by anshooarora** [comment]
@saikrishna321 - new version is now available on the website and nexus

**Comment by anshooarora** [comment]
PS.  Version 3 snapshots also available on the website.

**Comment by saikrishna321** [comment]
@anshooarora when is the release to the maven repo planned ?

**Comment by anshooarora** [comment]
@saikrishna321  -  v2.41.1 is available in maven repo.  

v3 will be available sometime around early-to-mid August.
