### ISSUE TITLE
Defects Tab of extent report doesn't show the exception logged in the Child test

### ISSUE THREAD

**Issue by HaridasNayak** [anshooarora/extentreports-java#518]
@anshooarora , I have appended the child test for my test where child test failed and Throwable of that child test contains the exceptions but  Defects tab of the extent report doesn't show the exception from child test.

**Comment by HaridasNayak** [comment]
@anshooarora

**Comment by anshooarora** [comment]
This is a known limitation (to be fixed in the next version).  It will currently show parent test only.

**Comment by HaridasNayak** [comment]
@anshooarora ,  when is the next release? approximate date.!! Waiting for this particular enhancement!!

**Comment by anshooarora** [comment]
most probably mid-August - it will be a pre-release, very early alpha and there are breaking changes so would like to have good documentation before launching it officially.

**Comment by anshooarora** [comment]
This feature is included in v3, now available as pre-release: [3.0.0-dev branch](https://github.com/anshooarora/extentreports-java/tree/3.0.0-dev)
