### ISSUE TITLE
Latest Extent Reports not working with framework 4

### ISSUE THREAD

**Issue by parttrapqa** [anshooarora/extentreports-java#523]
@anshooarora   I am using Selenium c# with .net Framework 4 (Since I have used entity framework also for exception handling which works only in ver 4 or higher). I tried to configure the extent reports but while compiling the code I get a build error like following:

> The primary reference "RelevantCodes.ExtentReports, Version=1.4.9.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0". PosUsingWebDriver

Please help. Do I need to try with older version of extent reports ?

**Comment by anshooarora** [comment]
enhancement:  Release dll targeting multiple versions (4, 4,5).

**Comment by saiparth** [comment]
I am also facing this issue. any ETA on this? I can't upgrade my framework to 4.5.
Regards,
Partha

**Comment by anshooarora** [comment]
The minimum version targeted will be 4.5 since that is the minimum version supported by MongoDB.
