### ISSUE TITLE
problem with sorting

### ISSUE THREAD

**Issue by Ramsescz** [anshooarora/extentreports-java#525]
Hi all,

please can help me anyone?

I have problem with sorting, see image:
![sort](https://cloud.githubusercontent.com/assets/19989911/16175899/7e7b3334-35fe-11e6-87ba-4bf1926e2fe1.png)

i run same test for few times, always sort differently. In this case a run same test for three times, with same result, but sort differently.

i need sort all tests (irrespective of the result) by start test time. Any solution?

i used this code:
`report = new ExtentReports(ReportFileLoc, false, DisplayOrder.NEWEST_FIRST);`

extentreports v. 2.41.0, testng 6.9.9

**Comment by Ramsescz** [comment]
sorry, but what you mean listener? i just use extent reports(library ExtentReports and ExtentTest)...

class started:
`logger = report.startTest(SetUp.getCas() + " " + getEnv() + " Environment Version");
logger.assignCategory("EnvironmentVersion", "SystemCheck", dateEnv, getEnv(), getBrowser(), UsersENUM.getUserName());
logger.log(LogStatus.INFO, "Test create by", UsersENUM.getUserName());
...`

and end:
`...
report.endTest(logger);
report.flush();
		  
driver.get(ReportFileLoc);`

**Comment by anshooarora** [comment]
The tests will appear in the order they were started.  Which TeatRunner are you using?  Can you set test priority and check if the same behavior persists?
