### ISSUE TITLE
How can i count only a child nodes in total test.

### ISSUE THREAD

**Issue by madlado** [anshooarora/extentreports-java#526]
Hi.

Im trying to use your report but i only want count the child test (DataProvider) using two level structure test.

ParentTestOne
        ParentTestTwo
                ChildTest

I only want count the child tests.

Thanks.

**Comment by anshooarora** [comment]
There are inbuilt settings to count:

Parent tests only (appearing in the left-side container)
Child tests only (appearing in the right-side container)
Parent + Child tests

If you want to count tests only at the 3rd level, its not possible.  It is possible to count tests 2nd level onwards though.

**Comment by madlado** [comment]
This is not correct.

Because the result is not the same as TestNG.

Help Please.

**Comment by anshooarora** [comment]
This is similar to #536.  This implementation will be possible v3 onwards, to be launched very soon.

**Comment by anshooarora** [comment]
This implementation comes in-built with version 3.
