### ISSUE TITLE
Issue in Tests View. Incorrect number of failures Impacting the Pass percentage and developer confidence.

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#536]
I have Parent and child tests configured in 3 levels:
Usecase/TestCase/TestStep
If 1 teststep is failed in  a test case, then tests view shows 2 failures. 
If 2 teststeps faied in a test case, then test view shows 3 failures.

Expected is to show, only the actual test step failures.

Currently the number of failures are: number of test step failures + number of test case failures.
This impacting the Pass percentage. 

Each test case failure is the result of 1 or more test step failures. So again test case failure should not be considered in total failures.

**Comment by gsaimadhu** [comment]
Anshoo, any comments on this request?

**Comment by gsaimadhu** [comment]
OK thanks Anshoo. Any update on version 3 release plan?

**Comment by anshooarora** [comment]
Will be uploading the alpha sources in a few days, along with the maven pre-release.  A lot of new features have been added including the one you mentioned in the OP.

**Comment by anshooarora** [comment]
This feature is available in version 3.  Please consider upgrading if haven't already.
