### ISSUE TITLE
How do i print individual results in extent report

### ISSUE THREAD

**Issue by manishbhatia7** [anshooarora/extentreports-java#539]
Hi Anshoo,
I have a test case where i need to check whether a user id exists or not.
I have link the test case to excel sheet where in excel sheet will feed the test case with user id's
I want to know how many user id's exist and how many not from the extent report.
Is it possible to do.

**Comment by anshooarora** [comment]
Link Excel file from the report?  Depending upon the browser, this may/may-not be possible.  Chrome/Firefox will not allow you to link to an Excel file like this, but IE would.  If both the report and Excel file are on a server, then it will be possible for all browsers.

So the question is:  where is the Excel file stored?

**Comment by manishbhatia7** [comment]
Hi Anshoo,
Its stored in local system.
But how will extent print individual test steps
