### ISSUE TITLE
Filters in graph

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports-java#551]
Hi, the list of LogStatus for filter graph is wrong. Appear all LogStatus, not only the exists.

![filtrosextent](https://cloud.githubusercontent.com/assets/7159779/16874309/e91ad512-4a6e-11e6-97a4-03106350d1ad.jpg)

**Comment by anshooarora** [comment]
Thanks,  will remove the unused logs from here.  Marking this as an enhancement.

**Comment by anshooarora** [comment]
Closing as this feature was included in 3.0.0.
