### ISSUE TITLE
Implements xml in report

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports-java#552]
My idea is implements a xml in the report for show response of web service for example.

**Comment by anshooarora** [comment]
You can do that by wrapping the XML response in pre tags:

```
test.log(pass, "<pre>" + xml + "</pre>");
```

**Comment by MaxiTalenti** [comment]
Mmmm, only the data appears not knowing that field belongs, for that I need to show the whole xml. I passed a small catch (for confidentiality) of as they appear.
![xmlextentreprots](https://cloud.githubusercontent.com/assets/7159779/16990246/aa41f00c-4e6d-11e6-908e-d286d838d07f.jpg)

**Comment by anshooarora** [comment]
@MaxiTalenti  - in version 3, there is a feature to insert a `CodeBlock` which will automatically wrap all your markup in a textarea so it will not be parsed as regular HTML/XML.
