### ISSUE TITLE
Need to Add more status to LogStatus enum for DataFailure and Environment Failure

### ISSUE THREAD

**Issue by sriapul** [anshooarora/extentreports-java#561]
Hi Anshoo,

I am planning to specifically tell the failure details in more details, Can you add more LogStatus such as DataFail,EnvironmentFail etc

Regards,
Sridhar

**Comment by anshooarora** [comment]
In the failure log, you can add labels to indicate the type of failure.  Example:

```
test.log(LogStatus.FAIL, "<span class='label fail'>Environment</span> Reason for failure");
```

This feature is too specific and there can be N number of additions, which will not be possible to add.  I would recommend to use labels to indicate this as shown above.
