### ISSUE TITLE
Skip status

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports-java#562]
I'm doing a test which use replaceExisting = false and when the tests are OK I appear as Skip..

Use some skip past but not because the test appears as skip . what your behavior?

![skipbugextent](https://cloud.githubusercontent.com/assets/7159779/17064252/1981724e-5012-11e6-8545-8f18eac43fb7.jpg)

**Comment by anshooarora** [comment]
Even if 1 log in the entire test has skip status, the entire test will be skipped as skip has a higher priority than pass.
