### ISSUE TITLE
how to append multiple testcases in one log

### ISSUE THREAD

**Issue by Sumathichn123** [anshooarora/extentreports-java#564]
Hi,
I have one worksheet which has one module.
Eg : Personal Information. 
Within this worksheet i have multiple testcases to be executed.
So i want to create extent.startTest and append all testcases results within this folder.
I want 'Personal Information' folder and inside this folder, i want all results[First Testcase name followed by results, Second testcase name followed by results..]
Anyone please let me know how to do this in java.

**Comment by giang-hai-nguyen** [comment]
I guess your answer is in [here](http://extentreports.relevantcodes.com/java/#examples)

**Comment by anshooarora** [comment]
You can see the documentation section for child tests as this scenario would fit nicely there.
