### ISSUE TITLE
ExceptionInfo is not working for child test

### ISSUE THREAD

**Issue by pwielgolaski** [anshooarora/extentreports-java#566]
if test is not a child and will be closed by `endTest` and later added as child it will work.

```
  extent.endTest(scenarioTest);
  featureTest.appendChild(scenarioTest);
```

if I skip endTest it will not work.

Another connected case is when I want to aggregate this report, information about exception are lost as child test are not much with exception in TestConverter (also seems to be missing id)

Also line 
https://github.com/anshooarora/extentreports-java/blob/188abc4172a93d0aa818ec9e72871efda781cde4/src/main/java/com/relevantcodes/extentreports/Report.java#L382
should be outside of if to collect instances of exception

**Comment by anshooarora** [comment]
Which test-runner are you using?  TestNG for example allows you to mark the test correctly even if its skipped.  Also, if you are treating a test as a child, you don't have to call `endTest` on it.  

Also, in v3, `endTest` is completely going away.  The API will track the status automatically so the new usage will be similar to:

```
// example 2
extent.createTest("My First Test").pass("pass");

// example 2: nodes
ExtentTest test = extent.createTest("Test With Nodes");
ExtentTest child = test.createNode("Node 1").assignCategory("Nodes");
child.pass("pass");

// example 3: nodes shorthand
test.createNode("Node 2").assignCategory("Nodes").pass("pass");
```

Please send in a pull request for TestConverter.
