### ISSUE TITLE
Using Extentreports in Protractor framework

### ISSUE THREAD

**Issue by Arunagnz** [anshooarora/extentreports-java#567]
Hi Anshoo,

For the passed couple of weeks, I have been working on Protractor to test AngularJS application. Framework is almost over. I am working in reporting part now. I want to use extent reports in my framework. I have been scripting in javascript.

Is there any way i can use extent report in Protractor(javascript) framework ?
Can we import jar as package and do our scripting ?

Any sort of help is appreciable. Thanks in advance.

**Comment by anshooarora** [comment]
The question is more of using a jar file via js.  I don't know much about it but you can see [here](http://stackoverflow.com/questions/24579750/can-javascript-use-classes-from-a-jar-file-non-internet-use).
