### ISSUE TITLE
How can I edit the script.js file

### ISSUE THREAD

**Issue by GayathriB1010** [anshooarora/extentreports-java#573]
For configuring the parent child results in dashboard, I added the below script in extent-config.xml
$(document).ready(function() {
			$('#childNodes').click();
			$('#test-count-setting .modal-action').click();
			});
This is not clicking the save button. Do I have to change something here or is it possible to edit the script.js file in the extentreports jar

**Comment by anshooarora** [comment]
You must load the config file after modifying it.  See `loadConfig` [here](http://extentreports.relevantcodes.com/java/#configuration).
