### ISSUE TITLE
Report does not give proper results when using Selenium Grid

### ISSUE THREAD

**Issue by sukhvinderh** [anshooarora/extentreports-java#574]
Using Grid to test couple of tests i.e. 1, 2, 3 on FF and Chrome

The report just shows that only 3 tests ran, it should be giving a break of the tests as:

Chrome
Test 1, Test 2, Test 3
FireFox
Test 1, Test 2, Test 3

This is the way it is displayed on TestNG and ReportNG reports

Any thoughts on this will be helpful

**Comment by anshooarora** [comment]
It depends on your usage.  Are you creating an extent instance more than once?
