### ISSUE TITLE
Dash board showing incorrect total tests 

### ISSUE THREAD

**Issue by GayathriB1010** [anshooarora/extentreports-java#575]
I tried giving the configuration in the dashboard for child tests only. Its giving wrong information in total tests. Its counting both parent and child. I have attached the screenshot
![child tests issue](https://cloud.githubusercontent.com/assets/20083154/17328174/d79e4f20-58d9-11e6-9bb7-45900b6d3e03.png)
Here, I have 2 parent nodes and 4 child nodes. In the graph view, its showing correct information. While as in Total tests, its showing 6

**Comment by anshooarora** [comment]
Please upgrade to 2.41.1, this was one of the fixes.

**Comment by GayathriB1010** [comment]
I upgraded to 2.41.1. I am still getting the same report
