### ISSUE TITLE
Incorrect count for errors in Defects tab

### ISSUE THREAD

**Issue by manishgdev** [anshooarora/extentreports-java#576]
I had written a small testng example to learn Extent-Reports.

Extent Reports :- v2.41.1
Freemarker :- 2.3.23
TestNG :- v6.8
Java :- v1.8.0_91

Everything works fine. In my example I had 7 tests and out of which 4 were passed and 3 were failed. 

Out of the 3 failed test 2 were of type AssertionError and 1 is of type RuntimeException. In the report in DEFECTS tab the report is listing out the different Exceptions/Errors occurred.

For AssertionError it is showing 1 and for RuntimeException also it is showing 1.

It should show 2 in front of AssertionError and on clicking the AssertionError it should show 2 errors log.

Source Code of Project can be found at :- https://github.com/manishgdev/MyJavaProjects/tree/master/ExtentReportsProject/SimpleTestNG

Attached :- HTML_Report.zip (contains only one html report)

Please correct me for any of my misunderstanding regarding above mentioned comment.

[HTML_Report.zip](https://github.com/anshooarora/extentreports-java/files/398812/HTML_Report.zip)

**Comment by anshooarora** [comment]
I see 2 of this type in exception-view.  You can rename the below file to .html:

![report-03-45-2016-10-45-53](https://cloud.githubusercontent.com/assets/4107384/17369775/9bf1f3a8-5967-11e6-94b2-0175d3a40a2f.png)

**Comment by manishgdev** [comment]
I can see the count 2 for AssertionError and 1 for RuntimeException in your report, and the report which you have sent is also created from ExtentReports v2.41.1 

But the strange thing is everytime when I am executing it I am getting the count as 1 only
I am working with :- 
Extent Reports :- v2.41.1
Freemarker :- 2.3.23
TestNG :- v6.8
Java :- v1.8.0_91

Can you suggest any way to track this difference in behavior. 

Please rename the report to .html this is still showing 1 only
![report-05-08-2016-08-09-31](https://cloud.githubusercontent.com/assets/10989007/17424712/49218bb0-5ae4-11e6-8311-0df86fd83fa4.png)

**Comment by anshooarora** [comment]
I would suggest upgrading to version 3 as the counts are calculated before information is sent to the view.  In version 2.x, the counts are calculated using javascript.
