### ISSUE TITLE
Extent Report not able to update report when there is failure and where to use close function? please help!!

### ISSUE THREAD

**Issue by kunals4u** [anshooarora/extentreports-java#577]
package com.*

import java.io.*;

public class BaseTest extends TestListenerAdapter {

	ExtentReports report;
	ExtentTest test;
	protected WebDriver driver;
	
	

	public static String filePath="some path";

	@BeforeSuite
	public void extentSetup(ITestContext context) {
		ExtentManager.setOutputDirectory(context);
		report = ExtentManager.getInstance();
	}

	@BeforeMethod
	public void startExtent(Method method,ITestContext context) throws Exception{		

		File file = new File("./resources/drivers/chromedriver.exe");
		System.setProperty("webdriver.chrome.driver", file.getCanonicalPath());
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		capabilities.setCapability("chrome.switches", Arrays.asList("--start-maximized"));

		ChromeOptions options = new ChromeOptions();
		options.addArguments("allow-outdated-plugins", "--kiosk");

		driver = new ChromeDriver(options);		
		driver.get("http://localhost/index2.php");

		driver.manage().timeouts().pageLoadTimeout(100, TimeUnit.SECONDS);
		Thread.sleep(5000);

		ExtentTestManager.startTest(ExtentManager.getSuiteName(context)+"_"+method.getName());

	}

	@AfterMethod
	public void afterMethod(ITestResult result) {
		if (result.isSuccess()) {
			ExtentTestManager.getTest().log(LogStatus.PASS, "Test passed");
		}
		else if (result.getStatus() == ITestResult.FAILURE) {
			String imagePath= ExtentManager.createScreenshot(driver);
			String image=test.addScreenCapture(imagePath);
			ExtentTestManager.getTest().log(LogStatus.FAIL,result.getThrowable().toString(),image);
		}
		else if (result.getStatus() == ITestResult.SKIP) {
			ExtentTestManager.getTest().log(LogStatus.SKIP, "Test skipped");
		}

		ExtentTestManager.endTest();
		ExtentManager.getInstance().flush();
		
		driver.quit();
		
	}

	@AfterSuite
	public void afterSuite() {
		ExtentManager.getInstance().flush();
		
		
	}

}

The above code doesn't report when there is a failure. 
Where shall i use ExtentManager.getInstance().close()
 Please need your help??

**Comment by anshooarora** [comment]
Can you debug to see if the code comes inside this condition:

```
else if (result.getStatus() == ITestResult.FAILURE) {
```

**Comment by kunals4u** [comment]
sorry couldn't get you!....i have already implemented the code given by you in the code i shared earlier.

**Comment by anshooarora** [comment]
Can you debug and see if in AfterMethod, the failed condition is executed

**Comment by anshooarora** [comment]
Closing as there was no response. Feel free to reopen this or create a new post.

**Comment by kunals4u** [comment]
Sorry to update on this a little late! It's working for me now Anshoo..Thanks for your help!
