### ISSUE TITLE
How to combine multiple test reports together? Anyone can help with sample code?

### ISSUE THREAD

**Issue by SandipanBhattacharjee** [anshooarora/extentreports-java#579]
Hi, I have 2 test files, in the @BeforeClass I am initializing the extentReport. passing an instance of extentTest to all my pageobjects from my @Test methods, and in @AfterClass I am ending all extent tests and flushing.  The first test class runs fine, but for second test class, screen shots are also coming but it is throwing exceptions too in the report. 

Now, for two test scripts there are 2 reports created is there any way to create a single report? any help, link to a code is highly appreciated. I am new to extent reports, please help..

![image](https://cloud.githubusercontent.com/assets/17218413/17465654/997a1f56-5cc3-11e6-91ee-4d73de2ccb00.png)

**Comment by SandipanBhattacharjee** [comment]
To anyone facing this issue:  The exceptions go when you stop using the reports.close(); and the functionality is not impacted. 

Thanks Anshoo for suggesting this.

**Comment by anshooarora** [comment]
Initialize in `@BeforeSuite`.  Initializing in `@BeforeClass` will only show you results of that class, and will overwrite results of the other.
