### ISSUE TITLE
Skip PASS test case from FinalReport

### ISSUE THREAD

**Issue by akshayru** [anshooarora/extentreports-java#587]
My script generates close to 15K results, and total file size is close 22MB. When i am opening file in browser is damn slow, is there way i can skip the PASS results from details view and just have it at count level. I tried using filters, it does work fast for other filters except pass. As i don't want PASS details, i just wanted to skip them from main report and just have it at count level.

**Comment by anshooarora** [comment]
A test not part of the report will not be included in the dashboard.  So basically, in your scenario, you will have a report with only failed tests and dashboard showing numbers associated with those.

**Comment by akshayru** [comment]
Thanks Anshoo, 
Looks like i didn't explained in detail, i want my report to display Step and Test View, but remove "PASS" from the TEST view (second screenshot). Is there way i can achieve this?
Here is my scanario:
![image](https://cloud.githubusercontent.com/assets/17482625/17674326/aff49f90-62ea-11e6-98b1-7e8f45baf7bc.png)

![image](https://cloud.githubusercontent.com/assets/17482625/17674393/f60b8fd4-62ea-11e6-89e4-0315c82495d7.png)

**Comment by anshooarora** [comment]
This is not possible.

**Comment by akshayru** [comment]
Thanks Anshoo,
If i have to update source code, will it be possible for you to guide me which class and method write in this file. I will try to see if i can comment that out and check. I did looked at source code but didn't got idea which class and method write these PASS lines in HTML file.

**Comment by anshooarora** [comment]
You will have to use this branch based on your version:  https://github.com/anshooarora/extentreports-java/tree/2.41.1

Here is the template:  https://github.com/anshooarora/extentreports-java/blob/2.41.1/src/main/resources/com/relevantcodes/extentreports/view/Extent.ftl

**Comment by akshayru** [comment]
Thanks Anshoo,
I was able to disable PASS in detailed executions, but it is impacting the Test View also. How does those Test View graph build, do they read from template or any java class? I have attached my template file.

**Comment by akshayru** [comment]
Never mind i was able find out issue, in Extent.ftl it was pointing to different java script than the local one.  If anyone else want to use this code, please use attached ftl and  javascript file with the one attached here. Let me know if you get any issues...

Steps to be followed -
1 - Get the source code for 2.41.1
2 - Replace the Extent.ftl file with attached one. (Make sure to rename file)
3 - In Extent.ftl file provide the attached js file location at line 690.
4 - Build the code and add maven dependency to local jar file.
5 - All set now on Step-view you will see all passed steps counted but in the dashboard view passed steps will not be displayed.

The only purpose of this is to avoid filesize issue, our script does close to 100K validation and it become impossible to go over those.
[extentjavascript.txt](https://github.com/anshooarora/extentreports-java/files/422945/extentjavascript.txt)

[Extent.txt](https://github.com/anshooarora/extentreports-java/files/422938/Extent.txt)
