### ISSUE TITLE
Attached screenshot not displayed for extent reports

### ISSUE THREAD

**Issue by sarada-akurathi** [anshooarora/extentreports-java#590]
Hi,
I tried to implement extent reports in my project but message is displaying but not the image.

Attaching the screenshot  with syntax below
```
String screenShot_Path = GenericUtilLibrary.takeScreenShot(driver, "registrationDone_"+screenShotName);
extentLog.log(LogStatus.INFO, "Customer Registrated"+extentLog.addScreenCapture(screenShot_Path));
```

takeScreeShot method will take driver object and image path, takes screenshot and returns the path.

code is as below:

```
public static String takeScreenShot(WebDriver driver,String screenShotName) throws Exception
	{
		
```

		Date now = new Date();
		DateFormat shortDf = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT);
		
		String currentDate = shortDf.format(now).toString().replace("/", "_");
		currentDate = currentDate.toString().replace(" ", "_");
		currentDate = currentDate.toString().replace(":", "_");
		
		System.out.println("current Date "+currentDate);
					
		TakesScreenshot ts = (TakesScreenshot)driver;

		File source = ts.getScreenshotAs(OutputType.FILE);

		String dest = "./Screenshots/" + screenShotName +"_"+currentDate+".png";

		File destination = new File(dest);

		FileUtils.copyFile(source, destination);

		return dest;

	}

screenshot name will come by appending current date..

Need help on this

![screenshot](https://cloud.githubusercontent.com/assets/21073433/17724540/92b7fb08-6460-11e6-8722-80ac246f15f5.png)

**Comment by anshooarora** [comment]
Use a path relative to the report.  Similar threads:  #100, #468.

Also,  [Version 3.0](https://github.com/anshooarora/extentreports-java/blob/master/README.md) has the ability to create relative paths automatically using the below setting:

```
// allow automatic saving of media files relative to the report
htmlReporter.config().setAutoCreateRelativePathMedia(true);
```

**Comment by rajanathan24** [comment]
Hi Anshoo, I was using  2.40.2 , but when tried to upgrade to 3.0 my pom.xml is throwing error, sayingfailed to read the details..., then i reverted back to old version , can i manually add the JAR in my Maven project  to solve the conflict to get get my extent report working with screen shot

**Comment by SwathiNallan** [comment]
@sarada-akurathi 

Try below code
public String CaptureScreen(WebDriver driver, String imageName)
    {
        File sourceFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
        String encodedBase64 = null;
        FileInputStream fileInputStreamReader = null;
        try {
            fileInputStreamReader = new FileInputStream(sourceFile);
            byte[] bytes = new byte[(int)sourceFile.length()];
            fileInputStreamReader.read(bytes);
            encodedBase64 = new String(Base64.encodeBase64(bytes));

            String screenShotDestination = createScreeshotFolderStructure()+"/"+
                    imageName.trim().replace(" ","_") + ".png";

            File destination = new File(screenShotDestination);
            FileUtils.copyFile(sourceFile, destination);

        } catch (IOException e) {
            e.printStackTrace();
        }
        return "data:image/png;base64,"+encodedBase64;
    }

**Comment by rahulbommanaboina** [comment]
Even am not able to view the screenshots:, below is the code i have used in the listener class:



		ExtentTest test;

		if (tests.size() > 0) {
			for (ITestResult result : tests.getAllResults()) {
				test = extent.startTest(result.getMethod().getMethodName());

				test.setStartedTime(getTime(result.getStartMillis()));
				test.setEndedTime(getTime(result.getEndMillis()));

				for (String group : result.getMethod().getGroups())
					test.assignCategory(group);

				if (result.getThrowable() != null) {
					test.log(status, result.getThrowable());
	String file = System.getProperty("user.dir")+"/Screenshots/"+"FailureMethod"+result.getMethod().getMethodName()+".png";

					try {
						BaseClass.takeSnapShot(BaseClass.getDriver(), file);
					} catch (Exception e) {
						// TODO: handle exception
					}
					
					test.addScreencast(file);
					
				} else {
					test.log(status, "Test " + status.toString().toLowerCase()
							+ "ed");
				}

				extent.endTest(test);
			}
		}

**Comment by rahulbommanaboina** [comment]
test.log(status, test.addScreenCapture(file)); this helped me , its working !!

**Comment by shitalap** [comment]
I cannot generate screenshot, I am using C# extent report version 3.1.2

**Comment by shitalap** [comment]
Thanks for your help, Now it is working
