### ISSUE TITLE
How can I separate each execution run in a single report.

### ISSUE THREAD

**Issue by nitinEd** [anshooarora/extentreports-java#591]
First thing!!
Awesome Reporting tool!!

I am using extentreports for my regression suite.I am appending latest result with last result with this code:
ExtentReports report = new ExtentReports("Report_Path",false,DisplayOrder.NEWEST_FIRST); 

However,  I am not able to distinguish between last execution run and latest execution run. Is there any feature so that I can see report for each execution separately. As of now I am able to see tests from all runs in one go.

Can I generate separate HTML file for each execution run.

Thanks in advance.

**Comment by anshooarora** [comment]
Yes, you will have to change the `replaceExisting` flag to true, or create a new report by changing name.

```
ExtentReports report = new ExtentReports("Report_Path",true,DisplayOrder.NEWEST_FIRST);

// or, using a dynamic file-name so a new report is created each time
ExtentReports report = new ExtentReports("Dynamic_Report_Path",true,DisplayOrder.NEWEST_FIRST);
``

Note:  `replaceExisting=true` will overwrite the existing report (if any).  See [this section](http://extentreports.relevantcodes.com/java/#basic-usage) for details.
