### ISSUE TITLE
[3.0] Wrong width for columns in (markup) table

### ISSUE THREAD

**Issue by ille** [anshooarora/extentreports-java#595]
Version: 3.0.0 Snapshot
columns dont get  proper witdh in a html table, 
expected is same witdh for all columns,
but all columns have their own width

![extent30_table_screen_icon](https://cloud.githubusercontent.com/assets/551892/17767312/c780c1c4-652f-11e6-84ef-5361248eb06e.png)

**Comment by anshooarora** [comment]
Creating enhancement to allow equal column width.
