### ISSUE TITLE
[3.0] Allow screenshots to be shown at log level

### ISSUE THREAD

**Issue by ille** [anshooarora/extentreports-java#596]
Version: 3.0.0 Snapshot
expexted logged screenshots (images) to be shown at the position they where logged
now they are shown at the end of the node

![extent30_table_screen_icon](https://cloud.githubusercontent.com/assets/551892/17767450/51adf240-6530-11e6-902c-6ba554179cb7.png)

**Comment by anshooarora** [comment]
This is by design and will allow gallery/slideshow of images for tests as in #489.  Creating it at the log level will prevent this.  Would like to hear your thoughts on this.

**Comment by ille** [comment]
The gallery is good when you want to go through step by step. But we need at least a link at step position so we see which image belongs to the step.

**Comment by mingleipei** [comment]
agree with ille! I thinks the log style in 2.4 is better than 3.0

**Comment by GorooJ** [comment]
gallery/slideshow option doesnt seems good unless we have hyperlink at step level to open related screenshot. Currently not able to correlate Step with Screenshot. Suppose I have 30 steps and I am taking SS for each step. Now i want to check screenshot of 24th step. It is painful for management.

I would suggest:
1. Provide option to continue 2.4 format
2. Provide Hyperlink at each step to screenshot in gallery/slideshow
