### ISSUE TITLE
Want to customized ExtentReports V2.10

### ISSUE THREAD

**Issue by rganjare** [anshooarora/extentreports-java#598]
Hi Anshoo,
Implemented extentReport V2.10 in my project, I thing Steps View section is of no use. I just want to replace Steps View section of Dashboard with Total Test, Test Passed, Test Failed, Suite Start Time and Suite End Time on Dashboard.

![step view section](https://cloud.githubusercontent.com/assets/20878371/17856183/d9ea9ce6-6899-11e6-8955-18fc4e3ea031.PNG)

How can i achive it, plz guide me.

Thank You
Rahul Ganjare

**Comment by anshooarora** [comment]
You would have to use css or js to hide the element.  

```
extent.config().insertJs("your_js");
// or:
extent.config().insertCustomStyles("your_styles");
```
