### ISSUE TITLE
Images are not expanding or zoomed in

### ISSUE THREAD

**Issue by samuelrmz** [anshooarora/extentreports-java#599]
Hi Good day!

When I tried to attached an image a miniature of if is displayed in report;
![capture1](https://cloud.githubusercontent.com/assets/21181550/17868726/aeb833b8-6875-11e6-95d5-57917113cda9.JPG)

but if I tried to click on it image never is displayed:
![capture2](https://cloud.githubusercontent.com/assets/21181550/17868754/cf979902-6875-11e6-94bf-d02d32a50fa4.JPG)

Why is this happening?
I've tried absolute and relative paths

"_test.log(LogStatus.PASS, "Log In successfully to IS page: "+URL+test.addScreenCapture("./attachments/"+num+".png"));_"

"_test.log(LogStatus.PASS, "Log In successfully to IS page: "+URL+test.addScreenCapture("C:\Users\IS_Automation\Reports\attachments\"+num+".png"));_"

Please help, I'm new using ExtentReports

Thanks and good day

**Comment by anshooarora** [comment]
Version?

**Comment by samuelrmz** [comment]
version of ExtentReports is 2.41.1

Thanks for all your help!!!!!

**Comment by anshooarora** [comment]
Can you share a sample that I can use with relative paths?  I am unable to reproduce this behavior.

**Comment by samuelrmz** [comment]
Sure,
I'm using this for relative path:
"test.log(LogStatus.PASS, "Log In successfully to IS page: "+URL+test.addScreenCapture(**"./attachments/"+num+".png"**));"

Full path is C:\Users\User\Tests\Automation\Reports\attachments

![capture](https://cloud.githubusercontent.com/assets/21181550/17984515/273b0f32-6ad7-11e6-8648-de7c40473133.JPG)


As you can see attachments are in a sub folder

**Comment by anshooarora** [comment]
As I said, I am unable to reproduce this behavior and there are no other reports of users experiencing this either.  Since the image is displayed in the log and not in the lightbox, I am not sure what is causing it.  I would need to look at a sample to be sure.
