### ISSUE TITLE
Integration with POSTMAN/NEWMAN for API testing 

### ISSUE THREAD

**Issue by hgill21** [anshooarora/extentreports-java#600]
Hi,
I am looking to find a way from which we can integrate postman/newman API test runs in extent reports.

Also,any way we can export these test runs into extent reports would be great too.
Any help around this would be great.  

Kind Regards,

**Comment by anshooarora** [comment]
Extent is an API so as long as you can make calls to it,  the report will be created.  I am not sure how this will be done from Postman, if Java/.Net is supported or if it is even possible.  

I checked here: http://blog.getpostman.com/2014/03/07/writing-automated-tests-for-apis-using-postman/ and it seems js is used, and this is the only language supported then no, it won't be possible.
