### ISSUE TITLE
Want to customized ExtentReports V2.10

### ISSUE THREAD

**Issue by rganjare** [anshooarora/extentreports-java#601]
Hi Anshoo,
Thank You for your quick responce on my previous question.

I customized V2.10 by using "extent.config().insertCustomStyles(CustomStyle);". but i stuck at Charts.
I don't want Steps View Chart, 
Test View and Steps View both class (class="col s12 m6 l4 fh") is having same properties, if i make any customization that will be applicable to both charts.
From Steps View chart it is possible to remove (id="step-analysis" , #step-status-filter, #step-status-filter, s-pass-count, s-fail-count and s-other-count) as these elements either have id or unique class name but rest as shown in screen shot, are not able to remove as they having common properties in a class (class="col s12 m6 l4 fh") 
![step view section1](https://cloud.githubusercontent.com/assets/20878371/17891795/9cae3b22-695b-11e6-80a9-902b8c9961dd.PNG)
How can i achive it?

Also i want Total Tests, Suite Start Time and Suite End time at the same place of Step View Chart.
How can i achive it?

Waiting for your responce.

Thank You
Rahul Ganjare
07774051226

**Comment by anshooarora** [comment]
How would you identify this item in your Selenium script? :)  Use the same css selector as you would with Selenium to hide it.

For example, in 2.41.1:

```
.charts > .col:nth-child(2) {
    display: none;
}
```
