### ISSUE TITLE
Count configuration for Parent Tests /Child tests

### ISSUE THREAD

**Issue by AnilReddy219** [anshooarora/extentreports-java#602]
Hi Sir,
I need count for Parent Tests and Child nodes separately.
or at least only parent tests count should display on my report.

but for now , Tests  Pass/fail count is showing  ParentTests+childTests.

Please help me this.

**Comment by anshooarora** [comment]
There are inbuilt settings to configure count:

Parent tests only (appearing in the left-side container)
Child tests only (appearing in the right-side container)
Parent + Child tests

![setting](https://cloud.githubusercontent.com/assets/4107384/18028979/fcab1e78-6c58-11e6-8dfe-27a556797f8a.png)

It can be done via config (by placing inside the scripts tag), using:

```
$('#parentWithoutNodes').click();
$('#test-count-setting .modal-close').click();
```
