### ISSUE TITLE
Implement Extent Report with SoapUIPro

### ISSUE THREAD

**Issue by SoapUiPro** [anshooarora/extentreports-java#604]
Hi Anshoo,

First wanted to appreciate your effort and beautiful report you have given to the community.

I am using SoapUI Pro for API testing and would be interested to implement Extent Report there.
Questions:
1. Is that possible to implement?
2. If yes, please give some direction to implement the same.

Many thanks for your suggestion and time.

Thanks.

**Comment by anshooarora** [comment]
I believe there are a few people already doing this with soapui and groovy, so I would say yes.

How it is being done, I am not sure as I don't use SoapUI + Extent.  You will hvae to research this to be sure.
