### ISSUE TITLE
2.10 customization

### ISSUE THREAD

**Issue by rganjare** [anshooarora/extentreports-java#605]
Hi Anshoo,

Thank You for Your response,
I customized V2.10 as per my requirement, Now waht i want when i Enabled Dashboard i want it should be look like as below, (I need those last 4 boxes should be disply with report values)
![screen shot](https://cloud.githubusercontent.com/assets/20878371/18008681/ab740e30-6bc6-11e6-9b2c-ee1cc4964a41.png)
How can i do it? Plz guide me.

Thank You
Rahul Ganjare

**Comment by anshooarora** [comment]
You would have to either modify the template to do this or use javascript + css to place these boxes in the correct position and order.  I am unable to support requests for customization of the UI, and it is up to the user to approach such changes.  Changing the template would be an easier alternative though.  You can start here:

[v 2.10 template](https://github.com/anshooarora/extentreports-java/blob/34697d90bd7b85495530b948d3f311701af03af3/java/extentreports/src/main/java/com/relevantcodes/extentreports/source/ExtentTemplate.html#L626)
