### ISSUE TITLE
Could not see system Info on reports when used with extentx server

### ISSUE THREAD

**Issue by simpleTesting** [anshooarora/extentreports-java#606]
Hi,

I really appreciate all the work you guys did for bringing up this wonderful reports. I am currently facing a problem with System Info details. When I used the latest java pre release of extentreports with 0.2.1 alpha extentx server, upon completion of the tests, I decided to send the test execution details. Here is what I wanted to display on the reports that will show where the tests are executed-
1. OS name
2. browser name
3. browser version

When I have these lines of code:
extent.setSystemInfo("Operating System: ", System.getProperty("os.name"));
extent.setSystemInfo("Desktop Browser: ", browserName);
extent.setSystemInfo("Desktop Browser Version: ", browserVersion);

I could see all the details of what I wanted but not the system info. Was there any thing else I need to configure or add?

Thanks
Naveen

**Comment by anshooarora** [comment]
System info is currently not added to the server.  However, you can open an enhancement in the extentx repo.
