### ISSUE TITLE
Screenshots are missing on ExtentX Report

### ISSUE THREAD

**Issue by srikanthvejendla** [anshooarora/extentreports-java#607]
When i generate local extent report, screenshots are shown fine.

But when i connect the report to extentx server running locally, screenshots are missing in the report.

extent=new ExtentReports(System.getProperty("user.dir")+"/target/MyReport.html",true);
extent.x("127.0.0.1",27017); 

![image](https://cloud.githubusercontent.com/assets/1727652/18023888/447bb8c0-6bb4-11e6-889e-3572897268c3.png)

**Comment by srikanthvejendla** [comment]
@anshooarora Any inputs on whats happening?

**Comment by anshooarora** [comment]
This feature is supported with ExtentReports 3.0 & ExtentX 0.21.0-alpha only.  

In the demo site, it won't work because I have not uploaded images.
