### ISSUE TITLE
showing null pointer exception for the second class in test suite 

### ISSUE THREAD

**Issue by Vishwajeet-Mishra** [anshooarora/extentreports-java#608]
[ExtentReport.zip](https://github.com/anshooarora/extentreports-java/files/446486/ExtentReport.zip)
![error](https://cloud.githubusercontent.com/assets/6533253/18117476/a2a8443e-6f6c-11e6-9ade-28a2d8f68c30.png)

**Comment by anshooarora** [comment]
Remove `extent.close();` and replace with `extent.flush();`.  Change `BeforeSuite` and `AfterSuite` to `BeforeClass` and `AfterClass` as you want the instance to be valid for each class as a whole, not just the 1st.
