### ISSUE TITLE
Duplicate,Invalid  reports are getting generated with ExtentReports 2.41.1

### ISSUE THREAD

**Issue by chaitraJagirdar** [anshooarora/extentreports-java#610]
Hi sir,
I have a report-"CP" in my "Report" folder. i delete all contents of my target "Report" folder. set 2 tests to run in my framework.
After run is completed  am expected to have 2 tests in 1 report in "Report" folder.

Issue: i Have 3 reports generated in "Report" folder.
         1>Valid report with recently run 2 tests.
         2>CP report [which was deleted previously from this folder][Time of this report generation is also updated to latest][ This test execution never happened recently after deletion of the same report priorly] 
         3>1 of the tests refering point 1 in a separate report.

More info: Am using ExtentReport 2.41.1

Please suggest...This is causing huge problem.

**Comment by anshooarora** [comment]
Please refer to [this section](http://extentreports.relevantcodes.com/java/#basic-usage) and [examples](http://extentreports.relevantcodes.com/java/#examples).  A few tips:

1. ensure you are creating only 1 instance of ExtentReports if you want 1 report
2. you can keep `replaceExisting=true` in case you do not want to append to an existing report

The above information is also available in the docs section.
