### ISSUE TITLE
Html-encode stack trace details

### ISSUE THREAD

**Issue by kenston** [anshooarora/extentreports-java#612]
When using the `ExtentTest.log(LogStatus logStatus, Throwable t)` method, the stack trace message of the passed throwable may contain some HTML tags. However, HTML-encoding (conversion to HTML entities) was not performed.

A sample stacktrace
```text
Sample issue
Caused by: IllegalArgumentException: String [<td></td>] is not allowed.
	at com.sample.test(Sample.java:31)
	at com.sample.test(Sample.java:21)
```

will simply be included in the reports as

```html
<tr>
<td class='status error' title='error' alt='error'><i class='mdi-alert-error'></i></td>
<td class='timestamp'>17:50:33</td>
<td class='step-details'><pre>Sample issue
Caused by: IllegalArgumentException: String [<td></td>] is not allowed.
	at com.sample.test(Sample.java:31)
	at com.sample.test(Sample.java:21)
</pre></td>
</tr>
```

The HTML part `<td></td>` will be rendered and may affect/deface the report presentation.

**Comment by anshooarora** [comment]
The ability to add HTML needs to be added.  For now, is it possible to replace:

`<` with `&lt;`
`>` with `&gt;`

before adding the log?  This will prevent malformed markup.

**Comment by kenston** [comment]
For logging using the method `log(LogStatus logStatus, String details)` this seems OK; however with `log(LogStatus logStatus, Throwable t)` this means we have to alter the exception message to make it work.

**Comment by anshooarora** [comment]
Working on the fix, will be released in the next version (targeting this week).

**Comment by anshooarora** [comment]
Can you please try with the attached jar file and let me know if it works?

[extentreports-java-2.41.2.jar.zip](https://github.com/anshooarora/extentreports-java/files/459647/extentreports-java-2.41.2.jar.zip)

I have kept converting of `log(LogStatus logStatus, String details)` manual, as users may have HTML tags they would like to inject here.

This `log(LogStatus logStatus, Throwable t)` will enclose any HTML/XML tags in a textarea so the page does not become malformed.

**Comment by kenston** [comment]
@anshooarora it fixes the issue. May I suggest that we enable horizontal scrolling (rather than wrapping) when we style the textarea? Thanks!
