### ISSUE TITLE
Set the Timetag of steps

### ISSUE THREAD

**Issue by flmge** [anshooarora/extentreports-java#614]
Hello Anshoo

I have a custom recorder that keeps track of events and date of a set of tests. 
I integrated Extent Report which is a great tool :+1: 
However when using the test.log() methods the timetag taken is the one being called at run time
Therefor i end up with : 
Test started monday 8AM-Finished monday 9PM
With all the steps being tagged at monday  9PM

Is there anyway to set the date when calling test.log() ??

See below example 
![image](https://cloud.githubusercontent.com/assets/22007507/18251103/77449788-7387-11e6-95ff-bfa991b524e3.png)

Thx for your help

**Comment by anshooarora** [comment]
Its possible, but a little difficult as the log-collection is a list.

```
ExtentTest test;
test.getTest().getLogList();
test.getTest().getLogList().get(0).setTimestamp(dt);
```

You can traverse the log-list and set the desired time for each.

**Comment by flmge** [comment]
Thx 
I will try this.

**Comment by flmge** [comment]
Forgot to say that this solves the issue :)
