### ISSUE TITLE
Logger not capturing for all methods 

### ISSUE THREAD

**Issue by joseph873** [anshooarora/extentreports-java#616]
Intitiation Script :+1: 

package com.IDES.autotest.TestCase.IJL;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.BeforeTest;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import com.relevantcodes.extentreports.common.ExtentManager;

@SuppressWarnings("unused")
public class InitizationIJLWebsite {
	
	ExtentReports report;
	ExtentTest logger;
	private WebDriver driver;

	public static final String FILE_IJL_UI_REPORT = "\\\\ijldev.iltest.illinois.gov\\IJL_Regression\\TestReports\\extent.html";
	public static final String Application_Password = "WinsonRules";
	public static final String FILE_IJL_UI_SCREENSHOT = "\\\\ijldev.iltest.illinois.gov\\IJL_Regression\\TestReports\\";

	// Application Password Page

	@FindBy(name = "application_usage_password")
	WebElement Application_Usage_Password;

	@FindBy(name = "access")
	WebElement Acess_btn;

	private Object selenium;
	private WebDriver lSheet1;

/*
	@BeforeSuite
    public void beforeSuite() {
		report = ExtentManager.getReporter("C:\\test\\extent.html");
    }*/
	@AfterMethod
    protected void afterMethod(ITestResult result) {
        if (result.getStatus() == ITestResult.FAILURE) {
        	logger.log(LogStatus.FAIL, result.getThrowable());
        } else if (result.getStatus() == ITestResult.SKIP) {
        	logger.log(LogStatus.SKIP, "Test skipped " + result.getThrowable());
        } else {
        	logger.log(LogStatus.PASS, "Test passed");
        }
        
       report.endTest(logger);        
      // report.flush();
    }
    
   
    
    @BeforeMethod
    protected void afterSuite() {
    	report.endTest(logger);
    }
/*    
    @BeforeTest
    
    public void statusreport () {
    	
        report = new ExtentReports("C:\\test\\extent.html", true);
   	 logger= report.startTest("InitizationIJLWebsite");
   	report.addSystemInfo("HostName", "Joseph");
 	report.addSystemInfo("Environment", "QA");
    report.loadConfig(new File("C:\\test\\extent.html"));
    }*/

	public InitizationIJLWebsite() {
		//ExtentReports extent = new ExtentReports(FILE_IJL_UI_REPORT,true);
    report = new ExtentReports("C:\\test\\extent.html", true);
	 logger= report.startTest("InitizationIJLWebsite");
		/*	logger = ExtentReports.get(InitizationIJLWebsite.class);
		SimpleDateFormat sd = new SimpleDateFormat("yyyy_MM_dd_HH_mm_ss");
		Calendar Calender = Calendar.getInstance();
		Calender.setTimeInMillis(System.currentTimeMillis());
		Calender.add(Calendar.DAY_OF_MONTH, -1 * Calendar.DAY_OF_WEEK);*/
		//logger.log(LogStatus.INFO, "Getting Current Date and Time from system");
		//logger = ExtentReports.get(InitizationIJLWebsite.class);
		//logger.init(FILE_IJL_UI_REPORT + sd.format(Calendar.getTime())
		//		+ ".HTML", true);
		
	
		
		logger.log(LogStatus.INFO, "IJLwebsite script initiation");

		//logger.log(LogStatus.INFO, "Initializing the Chrome Browser");
		System.setProperty("webdriver.chrome.driver",				"C:\\Selenium\\Chrome 32\\chromedriver.exe");
		this.driver = new ChromeDriver();
		PageFactory.initElements(driver, this);
		logger.log(LogStatus.PASS, "Initializing the Chrome Browser",
				"Invoked Successfully");
		driver.manage().window().maximize();
		
		logger.log(LogStatus.PASS, "Maximizing the Chrome Browser",
				"Chrome Browser maximized Successfully");
		driver.get("https://ijldev.iltest.illinois.gov/ada/");
		logger.log(LogStatus.PASS, "IJL Website entered into URL",
				"IJL website Invoked Successfully");
		
		Application_Usage_Password.sendKeys(Application_Password);
		Acess_btn.click();
		
	}

	public void takingScreenshot(String placeHolders) throws IOException {
		File scrFile = ((TakesScreenshot) driver)
				.getScreenshotAs(OutputType.FILE);
		// Now you can do whatever you need to do with it, for example copy
		// somewhere
		FileUtils.copyFile(scrFile, new File(FILE_IJL_UI_SCREENSHOT
				+ placeHolders + ".jpg"));
	}
	

	public ExtentTest getLogger() {
		return logger ;
	}

	public void setLogger(ExtentTest logger) {
		this.logger=logger;
	}

	public WebDriver getDriver() {
		return driver;
	}

	public void setDriver(WebDriver driver) {
		this.driver = driver;
	}

	public ExtentReports getReport() {
		return report;
	}

	public void setReport(ExtentReports report) {
		this.report = report;
	}
	
	
	// new instance

	//ExtentReports extent = new ExtentReports(FILE_IJL_UI_REPORT 		+ ".HTML", true);
	
	//extent= new ExtentReports(FILE_IJL_UI_REPORT+ ".HTML", true);
}

Test Suite follows
package com.IDES.autotest.suite.IJL;

import java.io.IOException;

import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

import com.IDES.autotest.TestCase.IJL.IJLHomepagelinkexist;
import com.IDES.autotest.TestCase.IJL.InitizationIJLWebsite;
import com.IDES.autotest.TestCase.IJL.LoginPage;

public class IJLAutoregtestsuitenew extends InitizationIJLWebsite{
	
	//ExtentReports logger = null;

	
	

	public IJLAutoregtestsuitenew() {
		super();
	
	}

	@Test
	public void ijlpostinganewresume() throws InvalidFormatException, IOException, InterruptedException {
		
		new IJLHomepagelinkexist().verifyIJLhomePagelinkExists(super.getDriver(),super.getLogger(),super.getReport());
		new LoginPage().ClickonLoginbutton(super.getDriver(),super.getLogger(),super.getReport());
		/*new LoginPage().JobSeekerLoginPageWebElementExists(super.getDriver(),super.getLogger(),super.getReport());
		new LoginPage().loginCredentials(super.getDriver(),super.getLogger(),super.getReport());
		new SelfServiceListPage().SelfServiceListlinksverification(super.getDriver(),super.getLogger(),super.getReport());
		new SelfServiceListPage().ClickonMyresumelink(super.getDriver(),super.getLogger(),super.getReport());
		new MyResumes().myresumepagevalidation(super.getDriver(),super.getLogger(),super.getReport());
		new MyResumes().ClickonCreateAnotherResume(super.getDriver(),super.getLogger(),super.getReport());
		new NewResumePage().NewResumePageValidation(super.getDriver(),super.getLogger(),super.getReport());
	    new NewResumePage().NewResumedataentry(super.getDriver(),super.getLogger(),super.getReport());
	    new SelectOccupationPage().SelectOccupationpagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new SelectOccupationPage().ClickonFirstOccupation(super.getDriver(),super.getLogger(),super.getReport());
	    new ObjectiveStatement().SelectObjectivestatementpagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new SummaryOfQualifications().summaryofQualificationpagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new SummaryOfQualifications().summaryofQualificationdata(super.getDriver(),super.getLogger(),super.getReport());
	    new AddressbookPage().Addressbookpagevalidaiton(super.getDriver(),super.getLogger(),super.getReport());
	    new AddressbookPage().ClickonIhavenomoretoaddbtn(super.getDriver(),super.getLogger(),super.getReport());
	    new ReviewSelectionsPage().reviewselectionpagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new ReviewSelectionsPage().clickonnewworkexplink(super.getDriver(),super.getLogger(),super.getReport());
	    new NewWorkExpPage().newworkexppagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new NewWorkExpPage().verifyworkexperiencepage(super.getDriver(),super.getLogger(),super.getReport());
	    new SelectOccupationcode().SelectOccupationcodePageValidation(super.getDriver(),super.getLogger(),super.getReport());
	    new SelectOccupationcode().ClickonFirstOccupationcode(super.getDriver(),super.getLogger(),super.getReport());
	    new TalentsforWorkTitle().TalentsforWorkTitlepagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new TalentsforWorkTitle().TalentsforWorkTitledata(super.getDriver(),super.getLogger(),super.getReport());
	    new PrimaryTalentsPage().PrimaryTalentsPagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new PrimaryTalentsPage().PrimaryTalentsPagedata(super.getDriver(),super.getLogger(),super.getReport());
	    new ToolsandTechnologies().verifyselectingthetoolsandtechnologies(super.getDriver(),super.getLogger());
	    new AddNewEducationLink().ClickonAddNewEduExp(super.getDriver(),super.getLogger(),super.getReport());
        new NewEducationPage().NewEducationPageValidation(super.getDriver(),super.getLogger(),super.getReport());
        new NewEducationPage().NewEducationPagedata(super.getDriver(),super.getLogger(),super.getReport());
	    new CarrerProgram().CarrerProgramPageValidation(super.getDriver(),super.getLogger(),super.getReport());
	    new CarrerProgram().CarrerProgramPageValidationdata(super.getDriver(),super.getLogger(),super.getReport());
	    new EducationExpDescription().EducationExpDescriptionPageValidation(super.getDriver(),super.getLogger(),super.getReport());
	    new EducationExpDescription().EducationExpDescriptionPageValidationdata(super.getDriver(),super.getLogger(),super.getReport());
	    new EducationExpDescription().EducationPageValidation(super.getDriver(),super.getLogger(),super.getReport());
	    new EducationExpDescription().ClickonIhavenomoretoaddbuttonbtn(super.getDriver(),super.getLogger(),super.getReport());
	    new ReviewSelectionsPage().clickonAddaNewCertificationlink(super.getDriver(),super.getLogger(),super.getReport());
	    new AddaLicenseorCertification().AddaLicenseorCertificationPageValidation(super.getDriver(),super.getLogger(),super.getReport());
	    new AddaLicenseorCertification().AddaLicenseorCertificationPageValidationdata(super.getDriver(),super.getLogger(),super.getReport());
	    new AddaLicenseorCertification().LicenseandCerticationconfirmationpagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new AddaLicenseorCertification().ClickonIhavenomoretoaddbutton(super.getDriver(),super.getLogger(),super.getReport());
	    new ReviewSelectionsPage().clearfieldsonstatementsandqualification(super.getDriver(),super.getLogger(),super.getReport());
	    new ReviewSelectionsPage().clickonSaveandcontinuebtn(super.getDriver(),super.getLogger(),super.getReport());
	    new ResumePreview().ResumePreviewpagevalidation(super.getDriver(),super.getLogger(),super.getReport());
	    new ResumePreview().ClickonProceedanywaybtn(super.getDriver(),super.getLogger(),super.getReport());
	    new ResumePreview().detailedResumePreviewpagevalidation(super.getDriver(),super.getLogger(),super.getReport());*/
	}

	

	/*public ExtentReports getLogger() {
		return logger;
	}

	public void setLogger(ExtentReports logger) {
		this.logger = logger;
	}*/
	
	
	
	@AfterSuite(alwaysRun=true)
    protected void afterSuite() {
		//super.getReport().endTest(super.getLogger());
		super.getReport().flush();
		super.getReport().close();
		super.getDriver().quit();
    }
	
	
	
	

}

**Comment by joseph873** [comment]
Could u please help me why my logger not working .. am getting below error in extent report(2.41.1) 


com.relevantcodes.extentreports.ExtentTestInterruptedException: Close was called before test could end safely using EndTest.
	at com.relevantcodes.extentreports.Report.terminate(Report.java:421)
	at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:920)
	at com.IDES.autotest.suite.IJL.IJLAutoregtestsuitenew.afterSuite(IJLAutoregtestsuitenew.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:329)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

**Comment by anshooarora** [comment]
Please format your posts properly so they area readable.  You can view the [documentation](http://extentreports.relevantcodes.com/java/#basic-usage), it has all the information you need to setup your scripts, including examples.  Remove any call you have to the close method and replace it with `flush()`.
