### ISSUE TITLE
ExtentReports show Skipped Tests as Passed

### ISSUE THREAD

**Issue by malavparekh** [anshooarora/extentreports-java#619]
I have a framework based on TestNG which based on certain conditions will skip a test.

I'm using TestNGListener's onTestStart method
public void onTestStart(ITestResult testResult)
{
  if(condition is false){
     throw new SkipException("Skipping " + testResult.getTestContext().getName());
  }
}

However when I see the ExtentReports - it shows that the test has passed and when I check the emailable-report of sure-fire plugin, it shows the correct number of test passed, failed, skipped.

**Comment by anshooarora** [comment]
You can add the status in:

```
public void onTestSkipped(ITestResult result) {
    test.log(LogStatus.SKIP, result.getThrowable());
}
```
