### ISSUE TITLE
Blank Test case details are getting displayed.

### ISSUE THREAD

**Issue by nitinEd** [anshooarora/extentreports-java#620]
I ran my sanity script. Report has been generated. Some of the test cases results are getting blank only. Only pass and fail icons are getting displayed.
Attached are the screenshot and Report.
![screen shot 2016-09-09 at 5 02 30 pm](https://cloud.githubusercontent.com/assets/19796842/18385684/ba62d964-76af-11e6-98bd-64dc716537cf.png)
[Archive.zip](https://github.com/anshooarora/extentreports-java/files/463852/Archive.zip)

**Comment by anshooarora** [comment]
I used the attached report but unable to repro.

![img](https://cloud.githubusercontent.com/assets/4107384/18390548/9275aa6c-7678-11e6-990e-c86abc1c2ba1.PNG)

**Comment by saikrishna321** [comment]
@nitinEd pls refresh the page and u should see the results
