### ISSUE TITLE
How can i append the log information in the new ExtentReport V3?

### ISSUE THREAD

**Issue by qasurent** [anshooarora/extentreports-java#621]
Hi Anshoo,
   First of all thanks for this wonderful report.....Loved it... I planned to try out the new ExtentReport V3 and created the parent and child node. But i am stuck on how to log the information int to the child node.Currently all the log info are not appending into the child node.

And it would be really helpful to some of us who are beginner to the Automation and Extent Reporting if there is some docs and example on how to proceed with the reporting....
Thanks

**Comment by anshooarora** [comment]
Its in the [https://github.com/anshooarora/extentreports-java/blob/master/README.md](readme):

```
ExtentTest test = extent.createTest("Test With Nodes");

ExtentTest child = test.createNode("Node 1").assignCategory("Nodes");
child.pass("pass");

test.createNode("Node 2").warning("warning");
```
