### ISSUE TITLE
Users be able to add mutiple columns on the dashboard as per their requirement

### ISSUE THREAD

**Issue by vijaykamagar** [anshooarora/extentreports-java#622]
Hi Anshoo,

I want to add couple more columns on the dash board for my project requirement.Could you please let me know if i can add those and if yes, could you please let me know how.

Thanks in Advance
Vijay

**Comment by anshooarora** [comment]
Which other columns?  A few custom values can be added to the system-info.

**Comment by vijaykamagar** [comment]
Hi Anshoo,

Thanks for your reply.

In place of TimeStamp ,StepName,Details, I want to add FieldNames, ExpectedResult,ActualResult,Mach/Unmatch.

Is it possible to add these custom columns in the dashboard and if yes, how can I add them.Please let me know.

Thanks In advance

Vijay

**Comment by Jobvdb** [comment]
I too have been looking for this feature. I haven't been able to add new table heads `<th>` to add column headers, but my workaround is to add extra HTML in the form of a table in the details `<td>.` This allows you to add multiple extra columns, but it is not recommended.
Hope this helps!

Job

**Comment by anshooarora** [comment]
Its currently not possible to add this info directly as part of the log.  What you can do however is, insert an HTML table in the log with your desired columns.

PS.  In version 3, stepName column will not be available but it will very easy to insert HTML tables via standard logs.

**Comment by rnuniyal** [comment]
Hi Anshoo,

It seems bit tricky, I can add data under details columns which i achieved using MarkupHelper class. But I am not able to enhance column label to stepName and stepDesc. Currently, it is Details.

**Comment by rnuniyal** [comment]
I did it like...
String[][] data = new String[1][2];
		data[0][0] = strStepName;
		data[0][1] = strStepDes;
m =MarkupHelper.createTable(data);
MobileDriver.objExtentReports.log(Status.PASS, m);

By this, I got both stepname and description columns under the same header Details.
Is it possible to change column names?
