### ISSUE TITLE
Full integration with TestNG

### ISSUE THREAD

**Issue by juherr** [anshooarora/extentreports-java#624]
Hi,

I didn't find the answer, so I'm asking it here: 

Currently, it looks that ExtentReports is a stand alone test logger framework (no deep integration with a test framework).
But some boilerplate code could be removed with a deep integration.
For example, with TestNG, you will be able to use ExtentReports as an integrated reporter without changing any lines of tests by implementing appropriate TestNG listeners and by working with `Reporter` (maybe everything is not possible for the moment, but we can improve it). 

We can imagine an `extentreports-testng` module for that integration (and let the current module as it is).

Is something like that already planned?

**Comment by email2vimalraj** [comment]
@juherr : People already found out how to couple the ExtentReport with the TestNG Listener. Kindly read this post: http://www.ontestautomation.com/using-the-extentreports-testng-listener-in-selenium-page-object-tests/

@anshooarora : This link is dead from the documentation page - http://relevantcodes.com/testng-listener-using-extentreports/

**Comment by juherr** [comment]
Thanks for the link. Then why is it not supported out of the box ?

**Comment by anshooarora** [comment]
@juherr - I would like to keep ExtentReports as generic as possible and let the community work on integrations.  For example, @email2vimalraj to has created an extension for Cucumber, and there is already very tight integration with TestNG in multiple ways:  ReportListener, ITestListner, and as part of test setup and teardown.

Below is an example of the TestNG listener with ExtentReports 3.0:

```
public class ExtentTestNGListener implements IReporter {
    
    private static final String OUTPUT_FOLDER = "test-output/";
    private static final String FILE_NAME = "Extent.html";
    
    private ExtentReports extent;

    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        init();
        
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults();
            
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                
                buildTestNodes(context.getFailedTests(), Status.FAIL);
                buildTestNodes(context.getSkippedTests(), Status.SKIP);
                buildTestNodes(context.getPassedTests(), Status.PASS);
                
            }
        }
        
        for (String s : Reporter.getOutput()) {
            extent.setTestRunnerOutput(s);
        }
        
        extent.flush();
    }
    
    private void init() {
        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(OUTPUT_FOLDER + FILE_NAME);
        htmlReporter.config().setDocumentTitle("ExtentReports - Created by TestNG Listener");
        htmlReporter.config().setReportName("ExtentReports - Created by TestNG Listener");
        htmlReporter.config().setTestViewChartLocation(ChartLocation.BOTTOM);
        htmlReporter.config().setTheme(Theme.STANDARD);
        
        extent = new ExtentReports();
        extent.attachReporter(htmlReporter);
        extent.setReportUsesManualConfiguration(true);
    }
    
    private void buildTestNodes(IResultMap tests, Status status) {
        ExtentTest test;
        
        if (tests.size() > 0) {
            for (ITestResult result : tests.getAllResults()) {
                test = extent.createTest(result.getMethod().getMethodName());
                
                for (String group : result.getMethod().getGroups())
                    test.assignCategory(group);

                if (result.getThrowable() != null) {
                    test.log(status, result.getThrowable());
                }
                else {
                    test.log(status, "Test " + status.toString().toLowerCase() + "ed");
                }
                
                test.getModel().setStartTime(getTime(result.getStartMillis()));
                test.getModel().setEndTime(getTime(result.getEndMillis()));
            }
        }
    }
    
    private Date getTime(long millis) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(millis);
        return calendar.getTime();      
    }
}
```

The above can be created in a plugin but I am unable also. 

@email2vimalraj - relevantcodes.com has closed down,  and I am working on getting such content available on the extentreports site.  It will be available soon and will update links.

**Comment by juherr** [comment]
@anshooarora It makes sense. Thanks for the answer :)
