### ISSUE TITLE
Unable to take screenshot along with an alert popped up on the web application

### ISSUE THREAD

**Issue by lekha3188** [anshooarora/extentreports-java#625]
Hi @anshooarora ,

In my application i get an alert pop up (Ajax) which is not expected. I am trying to take a screenshot and place in the report but the pop up is not captured and i get an error at the code line `MainMethod.test.log(LogStatus.FAIL, "Could not perform click to "+MainMethod.tcdes+" due to exception "+e + "Snapshot below: " + MainMethod.test.addScreenCapture(Reports.CaptureScreen(MainMethod.driver,"C:/Users/E001038/workspace/SynovusBpm/Failed")));`

I tried using Robot class but the pop up is almost transparent in the screenshot captured. Kindly suggets on what can be done. Am using 2.41.1

`	catch (UnhandledAlertException e) {
			System.out.println("***** in unhandled Exception");
			BufferedImage image = new Robot().createScreenCapture(new Rectangle(Toolkit.getDefaultToolkit().getScreenSize()));
		    ImageIO.write(image, "png", new File("C:/Users/E001038/workspace/SynovusBpm/Failed/"+MainMethod.tcdes+".png"));
		    driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);
		    driver.switchTo().alert().accept();
		    MainMethod.test.log(LogStatus.FAIL, "Could not perform "+MainMethod.methodname+" to "+MainMethod.tcdes+" due to exception "+e );
			MainMethod.test.log(LogStatus.INFO, "Snapshot below: " + MainMethod.test.addScreenCapture("C:/Users/E001038/workspace/SynovusBpm/Failed/"+MainMethod.tcdes+".png"));
			return null;
		}`

![image](https://cloud.githubusercontent.com/assets/21359893/18672047/15df260a-7f64-11e6-86c5-75422ba0b2d6.png)

Also if am using Robot class i had to keep the screen active,else it is capturing irrelevant screens

**Comment by anshooarora** [comment]
I am not sure about this as its not related to ExtentReports, I would recommend checking at stackoverflow.com.
