### ISSUE TITLE
java.lang.NullPointerException on choosing replaceExisting as false

### ISSUE THREAD

**Issue by DeepKataria** [anshooarora/extentreports-java#628]
Hi Anshoo, 

I'm trying to implement ExtentReports ina basic program and ran into nullpointerexception. I'm using the jar - 2.41.1. Also, I don't face this issue in case:

1. I delete the report before running the code again.
2. I mention 'true' instead of 'false' in the initialization line of code.

**Error Stacktrace:**

Exception in thread "main" java.lang.NullPointerException
	at com.relevantcodes.extentreports.converters.TestConverter.createTestList(TestConverter.java:81)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:92)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:374)
	at com.seleniumExtentReports.ExtentReport.main(ExtentReport.java:27)
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files\HP\Unified Functional Testing\bin\java_shared\classes";"C:\Program Files\HP\Unified Functional Testing\bin\java_shared\classes\jasmine.jar"

**Code:**

`package com.seleniumExtentReports;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class ExtentReport {
	
	public static String Location = "D:\\ExtentReportsKshop\\ExtentReportsSample.html";
	public static String url = "https://www.google.com";
	
	public static void main(String[] args) {

		ExtentReports extent = new ExtentReports(Location, false);
		WebDriver driver = new FirefoxDriver();

		//***************Test Case 1 - We're assuming that all steps are passing in this test case, hence the final status of this test case will be 'PASS' in the report*************//*
		
		//Once you have initialized an instance, you can start a new test as below
		ExtentTest test;
		
		test = extent.startTest("Test Case 1", "Success Sample").assignCategory("Regression Test", "Google Home Screen");
	
		// At each step where you want to log the step result, use below syntax. Possible values for LogStatus are – ERROR,FAIL,FATAL,INFO,PASS,SKIP,UNKNOWN,WARNING

		//1. Open Google Home
		driver.get(url);	
		
		//2. Log the step
		test.log(LogStatus.PASS, "Step 1 - Opened Google Home Successfully");		
	
		// Flush at each step, so that in case the test fails at any step, all previous steps are logged
		extent.flush(); 		
		
		//3. Click on 'Sign In' button
		driver.findElement(By.id("gb_70")).click();				
		
		//4. Log the step
		test.log(LogStatus.PASS, "Step 2 - Clicked on Sign In Button Successfully");		
		
		// Flush at each step, so that in case the test fails at any step, all previous steps are logged
		extent.flush(); 		
		
		//5. Click on 'Next' button
		driver.findElement(By.id("next")).click();		
		
		//6. Log the step - Assume it met the success conditions
		test.log(LogStatus.PASS, "Step 3 - Clicked on Next Button Successfully");		
		
		//7. Log the step - To Add Snapshot. Here we're assuming that the framework being used has captured
		// 	 the screenshot already and the screenshot is placed at the path - D:\ExtentReportsKshop\TestImage1.png
		test.log(LogStatus.INFO, "Step 4 - Insert Snapshot: " + test.addScreenCapture("D:\\ExtentReportsKshop\\TestImage1.png"));

		
		// Flush at each step, so that in case the test fails at any step, all previous steps are logged
		extent.flush(); 				
		
		// Once all your test steps are executed, use below syntax to end a test
		extent.endTest(test); 		
		
		// Finally use below syntax to write all captured results to report
		extent.flush(); 
		extent.close();

		driver.quit();
        	        
	}

}
`

**Comment by anshooarora** [comment]
There are several reasons why this can happen:

1. The last report is empty
2. The last report has invalid information
3. The last report was not ended correctly, ie. The tests were not ended, or failed to end

I would recommend using testng or junit to ensure these methods always get called even when exceptions are raised.

**Comment by ranadinesh786** [comment]
issue :
=====
 How to solve NULLPOINTEREXCEPTION while using grouping concepts in POM with Extends Reporting ?


Solutions: 
======
	       1. Use below parameters to all the configuration annotations which we are using i.e. in base test;
		(alwaysRun = true)
		2. Use valid try catch block inside the page class and don’t use throws [incorrect exception]
		3. Use parameterized values instead of taking hardcode values inside the page or script.
