### ISSUE TITLE
Extent screenshot blank

### ISSUE THREAD

**Issue by preetish1234** [anshooarora/extentreports-java#629]
hi anshooarora,
My prblm is when my test case fail it takes the screenshot,, 
but in my Extent Report the the screenshot is white page , there is no image,, some time its soing, some tym it not showing
how to solve

**Comment by anshooarora** [comment]
Is it a path issue or the image itself is not valid?

**Comment by PaulSh84** [comment]
hi anshooarora,
I have the same issue.
Seems like the path to image is not provided in html.

see the screenshot. 
![blank_pop_up](https://cloud.githubusercontent.com/assets/11867456/18748849/e69cbb80-80dc-11e6-97cc-0f4f5c142115.png)

**Comment by anshooarora** [comment]
Please see [here](http://extentreports.relevantcodes.com/java/#insert-screenshots).

```
String screenCapturePath = test.addScreenCapture("screenshot-path");
test.log(LogStatus.INFO, "Snapshot below: " + screenCapturePath);
```

**Comment by preetish1234** [comment]
Can u plzs identify where I am getting wrong-

public void TearDown(ITestResult result){
 try {
  if (ITestResult.FAILURE==result.getStatus()){
String screenshot_path =util.captureScreenShot(driver, result.getName());
String image= logger.addScreenCapture(screenshot_path);
logger.log(LogStatus.FAIL,"ScreenShot"+image );
        }

**Comment by PaulSh84** [comment]
@preetish1234 ,
This issue is closed. Create a new one.

**Comment by PaulSh84** [comment]
My problem has been fixed. Thnx @anshooarora

**Comment by preetish1234** [comment]
Can u plzs identify where I am getting wrong-

public void TearDown(ITestResult result){
 try {
  if (ITestResult.FAILURE==result.getStatus()){
String screenshot_path =util.captureScreenShot(driver, result.getName());
String image= logger.addScreenCapture(screenshot_path);
logger.log(LogStatus.FAIL,"ScreenShot"+image );
        }

**Comment by preetish1234** [comment]
u r telling that it must be the path problm but i dnt think so 
this is my screen shot method
public static String captureScreenShot(WebDriver driver,String screenshotName){
				try {
				TakesScreenshot ts = (TakesScreenshot)driver;
		
   			    File sources = ts.getScreenshotAs(OutputType.FILE);
		
			    String dest= "./ScreenShots/"+screenshotName+".png";
		        
			    File destination = new File(dest);
			   
		        FileUtils.copyFile(sources,destination );
			   
			    System.out.println("ScreenShot taken");
			   
			    return dest;   
				} catch (Exception e) {
			
		System.out.println("Exception while taking screenshot"+e.getMessage());
				
					return e.getMessage();
				}
		}

**Comment by preetish1234** [comment]
how cn i come the image issue
this is my extent report code
public static ExtentReports Instance() {
	 try {
			ExtentReports report;      
			 String Path = "./ScreenShots/2.html";
			 System.out.println(Path);
			 report = new ExtentReports(Path, true);
			 report.config().documentTitle("Automation Report")
			                .reportName("Regression");
			                return report;
		} catch (Exception e) {
			e.printStackTrace();
		}
	return null;
}
}
