### ISSUE TITLE
How can I attach my code coverage results in extentreport

### ISSUE THREAD

**Issue by saorabh-singh** [anshooarora/extentreports-java#630]
Hi,

Actually I want to attach my code coverage report/results along with automation test results.
How can I achieve this?

Regards,
Saorabh

**Comment by anshooarora** [comment]
Is the code coverage report an HTML file? If yes, you can just create a link to it.

**Comment by saorabh-singh** [comment]
Yes it's a HTML file,
How can I create a Link??

**Comment by anshooarora** [comment]
Do you want to link it in the log, or elsewhere?

**Comment by saorabh-singh** [comment]
It would be really nice if I can display some values for code coverage in
summary page & then a link attached to it for detailed report.

This would give us the clear idea as how my automation tests are performing
with time wrt code coverage of product.

**Comment by anshooarora** [comment]
Adding code coverage to the log is straight-forward, example:

```
test.log(INFO, "<a href='local/code/coverage.html'>Coverage report</a>");
```

If you want to include it in the report name, simply add the link in the reportName tag in `config.xml`.

If elsewhere in the report, you will have to rely on javascript via `config.xml`, top-right nav for example:

```
$('ul.nav-right').append('<li><a href=''>Code coverage</a></li>');
```
