### ISSUE TITLE
Issue: Custom JS are not executed

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentreports-java#631]
JS code:
String js="$(document).ready(function(){$(\"a.brand-logo\").attr(\"href\", \"http://google.com\");$(\"a.brand-logo\").text(\"Google\");});";
htmlReporter.config().setJS(js);

Any suggestions??

**Comment by anshooarora** [comment]
fixed.

also fixed the css issue.

:)

**Comment by pthewizard** [comment]
great!!!
