### ISSUE TITLE
extent.flush() stops the script execution

### ISSUE THREAD

**Issue by SumathiChn** [anshooarora/extentreports-java#633]
Hi,

calling extent.flush(), end the script execution without throwing any exception.

Refer the code 
extentTest  = extent.startTest(clientName+"---"+strScenarioName+"-"+strTestCaseName,strTestCaseName);
extentTest.log(LogStatus.PASS, resultmsg);
extentTest.log(LogStatus.INFO, "Snapshot : " +extentTest.addBase64ScreenShot("data:image/png;base64," + resultsnap));
extent.endTest(extentTest);
extent.flush();

**Comment by anshooarora** [comment]
Please provide adequate steps and information to reproduce the issue (if any), or refer to the [docs](http://extentreports.relevantcodes.com/java/) for usage examples.
