### ISSUE TITLE
Top Failed/Passed always shows from all projects

### ISSUE THREAD

**Issue by sisillV** [anshooarora/extentreports-java#636]
Hi Anshooarora,
I create second .cs file and all tests from there I assigned to different project name.
I use the same folder to store the html files.
in Extend X I see the folder icon and I can select different project.
But when I select it: Top Passed; Top Failed; Categories stay the same - we see for the both reports not only for selected one. The charts and last 5 Reports table are correct.
In Reports view I see for: Total Tests;  Tests Passed; Tests Failed; Total Steps; Steps Passed; Steps Failed- again for both projects.
I've done something wrong but I don't know what...

Can you please help.

I use .NET and ExtendX 2.0
BR,
Stanislava

**Comment by anshooarora** [comment]
This feature is available in ExtentX 0.2.1-alpha, with ExtentReports 3.0 Java only.

.NET version is currently in development and will be available next month.

https://github.com/anshooarora/extentx/issues/43
https://github.com/anshooarora/extentx/commit/4e8ec61c652b96b7cb30dff5a05802fb95d4d457

**Comment by sisillV** [comment]
Thank you very much!
