### ISSUE TITLE
Screenshots from reports in non local machines displays blank

### ISSUE THREAD

**Issue by chaitraJagirdar** [anshooarora/extentreports-java#637]
Have captured screenshots in my reports in one machine.
If i open my reports in other machines, the screenshot in report is displayed blank.

Sir, how do i make my screenshots in reports visible in any machine, irrespective of on which machine i generated report???

**Comment by anshooarora** [comment]
Store the snapshots in a location that is accessible by all - for example, on a shared drive.

**Comment by chaitraJagirdar** [comment]
Sir, html pages can be embedded with images have heard.[Independent of file location]

What happens with situation, if i want to send reports to client?[ He can't have acccess to shared folder in service provider network]. As of now client cannot see any of the screenshots.

Sir, is there a way out , the images can be embedded on to html reports?So that reports are not dependant on any shared folder for screenshots.
