### ISSUE TITLE
DashBoard is broken when making it default

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports-java#638]
@anshooarora i have made changes as discussed and i see the dashboard breaking on chrome and works fine on safari 

```
<script src='https://cdn.rawgit.com/anshooarora/extentreports/43cee84f5f223ef7dbbe0ee521f21a1b1c4066ab/cdn/extent.js' type='text/javascript'></script>

        <script>$(document).ready(function() { $('.logo span').html('ExtentReports'); });</script>
        <script>



                $(document).ready(function() {
                $('#enableDashboard').click();
                });



        </script>
    </body>

```

<img width="1433" alt="screen shot 2016-09-29 at 12 32 15 pm" src="https://cloud.githubusercontent.com/assets/4045041/18944576/e38e8c7c-8643-11e6-9835-d6630b6450b1.png">

**Comment by anshooarora** [comment]
What OS and version?  I am unable to repro on Ubuntu 14/Chrome 53 & Win7/Win10 Chrome 52.  If it happens on one browser and not the other, its probably not a client side script issue.  Could be a timing one though. 

Does it happen every time?  If not, add a setTimeout to check:

```
$(document).ready(function() {
    setTimeout(function() { 
        $('#enableDashboard').click();
    }, 500);
});
```

Any luck?

**Comment by saikrishna321** [comment]
@anshooarora its mac OS 10.10.X and chrome the latest, i can reproduce this on my build agent. I will try to reproduce this on monday n update the ticket.

**Comment by anshooarora** [comment]
@saikrishna321  -  are you still facing this issue?

**Comment by saikrishna321** [comment]
@anshooarora with v3.0 and above css its fixed.. closing
