### ISSUE TITLE
.jpg format screenshots are shown blank in reports (v2.41.1)

### ISSUE THREAD

**Issue by ragunagu** [anshooarora/extentreports-java#639]
Hi Anshu,

I have implemented extent reports in our junit framework. I am trying to associate a screenshot to in my report, but when i associate a .jpg/.jpeg format it throws a blank image in our report. But when i associate .png images it is loaded fine in reports.

I tried both the methods of ExtentTest - addScreenCapture  , addBase64ScreenShot.
no luck :-(
please let me know how to use .jpg.

Below is the piece of code where i am associating the screenshot:

test.log(LogStatus.INFO, "Failure Snapshot below : " +'\n'+ " " + test.addBase64ScreenShot("." +relativeScreenPath));

Regards,
Ragu

**Comment by chemanth** [comment]
Are you using Chrome Browser for test execution? @ragunagu

**Comment by ragunagu** [comment]
@chemanth, yes I am using chrome browser. But I guess this issue exists even on other browser. And it could not be a browser specific issue?

**Comment by chemanth** [comment]
Are you able to see screenshots when you run scripts on your local machine? or even in local, you are getting blank screenshots. Because, i have seen this issue when i run scripts inside a remote machine using jenkins, but not on my local machine.

**Comment by ragunagu** [comment]
I am able to see the screenshots in the screenshot folder. But it doesn't get associated to report since it is .jpg, it shows a blank image associated to the report.

**Comment by chemanth** [comment]
Could you mind telling if the screenshots are blank with black screen or the image itself is missing in the reports?

**Comment by ragunagu** [comment]
![blank image](https://cloud.githubusercontent.com/assets/22541357/19070276/139b0cc6-8a48-11e6-91bd-a973abe4f7f3.png)

This is how the blank image is seen in the rep;ort, pfa shared above.

**Comment by ragunagu** [comment]
adding to that, the address url of the screen shot is taken properly in the report, yet the images are not associated properly.

**Comment by nadvolod** [comment]
Hello, not sure if this is related, but for me, my report doesn't include screenshots at all using C#. Not .jpg or .png. I don't see anything there. I tried .png and .jpg with no luck in either. Here is a sample code:

_currentTest.AddScreenCapture((@"C:\Users\nillo\Desktop\2016 - 09 - 22_1849.png"));

**Comment by anshooarora** [comment]
@ragunagu - can you spy on the image and check the path?

@nadvolod - try using forward slash:

```
_currentTest.AddScreenCapture((@"C:/Users/nillo/Desktop/2016 - 09 - 22_1849.png"));
```

**Comment by ragunagu** [comment]
When I check the image path, it is taking absolute path - 
file:///C:/Users/user1/workspace/project1/TestResults/Report/screenShots/createRecord_test-2016_18_10_11_00_07_896.jpg

Same path will be accepted for .png as well but .png images are loaded fine in the reports and .jpg images are not loaded.

**Comment by ragunagu** [comment]
@anshooarora -

When I check the image path, it is taking absolute path - 
 file:///C:/Users/user1/workspace/project1/TestResults/Report/screenShots/createRecord_test-2016_18_10_11_00_07_896.jpg

Same path will be accepted for .png as well but .png images are loaded fine in the reports and .jpg images are not loaded.

**Comment by ragunagu** [comment]
@anshooarora - 

The .jpg image is not shown when the report is opened in IE (I am using IE10), but in chrome and Mozilla, .jpg images are displayed properly.

**Comment by anshooarora** [comment]
Are you using the above absolute path for all browsers?

**Comment by ragunagu** [comment]
@anshooarora - 
sorry for the confusion, I have given the relative path for the screenshots. When I check the screenshot in view source I can see relative path taken as - "../screenShots/createRecord_test-2016_18_10_11_00_07_896.jpg" for all 3 browser (IE,Chrome & FF) it is showing the same relative path. But in IE (IE10 is my version) the snapshot is shown blank as attached in one of the above mentioned comments.

My folder structure is under Report folder I have 2 subfolder a)Reports b) screenShots
So as per my code the relative path taken is - "../screenShots/createRecord_test-2016_18_10_11_00_07_896.jpg"

**Comment by anshooarora** [comment]
Hmm, it should work as I am unable to repro this on my IE/10/Edge. 

![ie](https://cloud.githubusercontent.com/assets/4107384/19524758/cdc25280-95ec-11e6-8182-c831425e0755.png)
