### ISSUE TITLE
Link to file in local machine from ExtentX report

### ISSUE THREAD

**Issue by sisillV** [anshooarora/extentreports-java#642]
Hi Anshooarora,
I try to create a link in ExtentX that open an file from my computer. The ExtentX is too on my computer.
In HTML reports the link work, but extentX report the link don't work.

If enter the file directly in the link:

`"<a href='C:/Users/...../Documents/Visual Studio 2015/Projects/NUnitEsTaxDemo/NUnitEsTax/EsTaxTestMethods.cs'>open file</a>"`

When I click the link from ExtentX nothing happened.

If I use javascript:
`"<a href='javascript: void(open_file())'>Run JavaScript Code</a><script> function open_file(){var file_path = 'C:/Users/sstoykova/Documents/Visual Studio 2015/Projects/NUnitEsTaxDemo/NUnitEsTax/EsTaxTestMethods.cs';window.open(file_path);} </script>"`

In console I see that cannot find open_file(). This code works for the HTML reports.

Can you please give me advice if this is possible to create a link in ExtentX report to local file.

Best Regards,
Stanislava

**Comment by anshooarora** [comment]
This will not work, due to security..  The server will only be able to immediately display files in the `.tmp/public/' directory.
