### ISSUE TITLE
How to retrieve console data and pass the value in extent log

### ISSUE THREAD

**Issue by vivethaC** [anshooarora/extentreports-java#643]
Please let me know how to get all println statements from TestCase and append with extent log.

Below script will give status of TC whether it is passed or failed. 
My requirement is to get all println statements given in Test case and to append it with logstatus without hardcoding the value.So when TC pass/fail it should give me all println status in extent report.
 if ( failureTracker?.failed ) {
            TestUtils.takeScreenshot("testimg", "png", driver)
            ExtentReports extent = createReport()
             ExtentTest test = extent.startTest(gebReportingSpecTestName.getMethodName(), "Test failed, click here for further details")
            // step log
            test.log(LogStatus.FAIL, "Failure : " + test.addScreenCapture(".testimg.png"))
            flushReports(extent, test)
        } else {
            ExtentReports extent = createReport()
            //extent.x(new ServerAddress("aemcq05:27017"))
            ExtentTest test = extent.startTest(gebReportingSpecTestName.getMethodName(), "Test Passed")
            test.log(LogStatus.PASS, "Passed")
            test.log(LogStatus.INFO, "Passed"+report("Label"))
            flushReports(extent, test)
        }
Please suggest solutions.

**Comment by vivethaC** [comment]
@anshooarora  please help me its very urgent and I'm not getting any solution.

**Comment by email2vimalraj** [comment]
@vivethaC : I believe using the `println` in the test case is a bad idea. If you need the `println` statements in the extent report, you could simply use the `setTestRunnerOutput` method. Refer the javadoc here: http://extentreports.relevantcodes.com/java/doc/com/relevantcodes/extentreports/ExtentReports.html#setTestRunnerOutput-java.lang.String-

Also refer the example given in the demo page here: http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html#!

**P.S**: Going forward try to format the code while adding in the github. It is difficult to understand  :)

**Comment by vivethaC** [comment]
Thanks Vimal.

As said we are using Spock for testing and JUnit as a runner. 
Is there any way to get a result in Spock or JUnit.
                     for(String s :Reporter.log())
                          {
                          extent.setTestRunnerOutput(s)
                          }
Instead of Reporter in above code is there any equivalent method in spock or Junit.
Please suggest solutions.

**Comment by garora23** [comment]
@email2vimalraj @vivethaC How to use this setTestRunnerOutput method and log the println statements of reports in the extent report?
