### ISSUE TITLE
Log method is printing only 2 values.

### ISSUE THREAD

**Issue by kiransweng** [anshooarora/extentreports-java#644]
Hi,

I have used the code "Parallel Classes" for Extent Report generation , it is not printing "Step Name" string when log method provided with 3 values (status , step name,  step details). It is displayed only status and step detail.

Could you please check this?

Regards,
Kiran Edupuganti
![extenttest](https://cloud.githubusercontent.com/assets/10164779/19244522/3cfb026e-8f3a-11e6-8bf8-9ed3185e6812.png)

**Comment by anshooarora** [comment]
StepName will only be printed if all the steps (starting with the 1st) use this field.  See [here](http://extentreports.relevantcodes.com/java/#create-step-logs) for more info.

**Comment by kiransweng** [comment]
Hi Anshoo,

Thanks for quick update on this. I got cleared now...

Regards,
Kiran Edupuganti
