### ISSUE TITLE
Extent Report with Jenkins

### ISSUE THREAD

**Issue by kiransweng** [anshooarora/extentreports-java#646]
Hi Team,

I have Selenium Project solution running with Maven and TestNG , like to see Advanced reports integration. I am referring 2.41 v , working fine locally and able to generate Extent Report. But same report I like to see in Jenkins Job  results.
Do you have any guideline which refers ExtentReports Integration with Jenkins. When I run the job from Jenkins I should see Extent Report in the Jenkins Job portal like TestNG report. I am referring TestNG in the Maven surefire plugin in the "POM.xml" , May I know any such Integration guidelines.

Regards,
Kiran

**Comment by anshooarora** [comment]
See [here](http://stackoverflow.com/questions/35054298/ci-integration-with-extent-reports-using-htmlpublisher) and [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwiboMmHo9PPAhWCcD4KHW5uB0cQtwIILzAD&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DVLYzEjRCHjM&usg=AFQjCNHPFSdbgsVxfzTUCdadTxQ7M8rqqA).
