### ISSUE TITLE
2nd Level Category is not considered

### ISSUE THREAD

**Issue by email2vimalraj** [anshooarora/extentreports-java#648]
@anshooarora : I've been playing around and found that the categories of the parent and one child level is being displayed, whereas the 2nd level of child is not displayed. Consider the following code:

```
public static void main(String[] args) {
        ExtentReports reporter = new ExtentReports("report.html");
        ExtentTest suite = reporter.startTest("Suite");
        suite.assignCategory("Suite Group");

        ExtentTest testInstance = reporter.startTest("TestInstance");
        testInstance.assignCategory("Test Instance Group");
        suite.appendChild(testInstance);

        ExtentTest test = reporter.startTest("Test");
        test.assignCategory("Test Group");
        testInstance.appendChild(test);

        reporter.endTest(test);
        reporter.endTest(testInstance);
        reporter.endTest(suite);
        reporter.flush();
    }
```

`Suite` is the parent has a category called `Suite Group`
`TestInstance` is the child of `Suite` has a category called `Test Instance Group`
`Test` is the child of `TestInstance` has a category called `Test Group`

The report displays only the `Suite Group` and `Test Instance Group`. The `Test Group` seems missing. Attaching the report for reference.

![screencapture-file-users-vimalrajselvam-development-testngextentreporter-output-report_1-html-1476244854378](https://cloud.githubusercontent.com/assets/1214686/19297022/9cd6d49a-905e-11e6-9cf1-e615dfc5bd79.png)

**Comment by anshooarora** [comment]
This was a bug fixed in v3 - the release is ready and will be uploaded to nexus hopefully today.

**Comment by anshooarora** [comment]
@email2vimalraj - 3.0 release is now available.
