### ISSUE TITLE
Deferred or lazy loading of images

### ISSUE THREAD

**Issue by kenston** [anshooarora/extentreports-java#649]
Some reports may have at least 25 test cases with each test case having at least 10 images. The browser seems to load all 250 images even without navigating to all test cases. Is is possible for us to defer or lazily loading the images until the actual test case is browsed or until we scroll to the view containing the image?

**Comment by anshooarora** [comment]
Are these base64 images?

**Comment by kenston** [comment]
No, they are `<img src="...` tags.

**Comment by anshooarora** [comment]
In the static HTML report, having so many images should not make a huge difference unless they are loaded from a remote location.  Is that the case?  How many tests does your report have?  Several logs per test?  

My concern is mainly the size of the actual file and if the images are being loaded from a location which is slowing down the process.

**Comment by kenston** [comment]
Yes, they are loaded from a remote location. We're integrating it with Jenkins. We currently have 10 tests in a report, but we're expecting to have around 70 cases perhaps. Each case may have 5-10 images.

**Comment by anshooarora** [comment]
I will mark this as an enhancement as a possible JavaScript impl.  The other issue this poses is, when you open a test that has an image served from a remote location, it will take some time to load the test itself.  So there will be a tradeoff in performance when you are browsing the report as opposed to when you open it initially.

**Comment by anshooarora** [comment]
This commit will be part of the upcoming version 3.0.1.
