### ISSUE TITLE
Extent Report Emailing - New Feature

### ISSUE THREAD

**Issue by amitjaincoer191** [anshooarora/extentreports-java#650]
Hi Anshoo,

I am emailing extent report generated using the maven postman plugin.
I emailed all generated files like .css,.js, *.* files as an attachment
But when I open it as an email attachment it does not display css,js etc

What I understood is that html file is not able to read css,js files attached in email
Is it possible to generate a single file which contains all resources,css,js etc so that HTML file appears fine..

Please let me know if it possible I am using bit older version

Below are pom.xml entries  reportversion,report jar,postman to send email

1. <version.extentreports>2.05</version.extentreports>
2. <dependency>
			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>${version.extentreports}</version>
</dependency>
3. <plugin>
				<groupId>ch.fortysix</groupId>
				<artifactId>maven-postman-plugin</artifactId>
				<version>0.1.6</version>
				<executions>
					<execution>
						<id>send a mail</id>
						<phase>package</phase>
						<goals>
							<goal>send-mail</goal>
						</goals>
						<inherited>false</inherited>
						<configuration>
							<from>amjain.abc@gmail.com</from>
							<subject>Automation Testing Report</subject>
							<failonerror>true</failonerror>
							<mailhost>smtp.gmail.com</mailhost>
							<mailport>465</mailport>
							<mailuser>amjain.abc@gmail.com</mailuser>
							<mailAltConfig>true</mailAltConfig>
							<mailpassword>mypasswordforEmail</mailpassword>
							<mailssl>true</mailssl>
							<receivers>
								<receiver>amjain.abc@gmail.com</receiver>
							</receivers>
							<fileSets>
								<fileSet>
									<directory>${basedir}</directory>
									<includes>
										<include>*.html</include>
									</includes>
								</fileSet>
							</fileSets>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by anshooarora** [comment]
The current HTML report is very heavy on external JS/CSS which most (if not all) email clients will not support due to security.  The only way is to create an email template specifically for this, and it will be available in ExtentReports 3.0-pro version only.  The open-source/community version will only have the standard HTML reporter and support for ExtentX server.

**Comment by amitjaincoer191** [comment]
Is this version "ExtentReports 3.0-pro version" is free / paid ?
Till when it will be released ?

**Comment by anshooarora** [comment]
It will be paid.  Release date will probably be around end of this year.  Its a huge upgrade and so is the upcoming ExtentX.
