### ISSUE TITLE
Difference Between LogStatus.ERROR/LogStatus.FAIL

### ISSUE THREAD

**Issue by chandu554** [anshooarora/extentreports-java#657]
Hi, 
I am confused between Logstatus.Error and logstatus.fail.  What is the difference between them and when should we use.

Logstatus.Error does not have an option to throw the exception.
In my method/actions if i get any exception I am throwing them in catch block.

So after I throw the exception in method will that cause testNG test to failure?

**Comment by anshooarora** [comment]
Extent is generic so a few extra status are available which may not be available in your test runner.  You can choose the status that fits your needs better.  With TestNG, you can use Pass, Fail and Skip.
