### ISSUE TITLE
extent.flush gives NullPointerException if any test is not created using extent.createTest(). This should be handled.

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentreports-java#659]

**Comment by anshooarora** [comment]
Please provide steps to reproduce.

**Comment by anshooarora** [comment]
There is a test that builds the report without any content, runs without issues:

https://github.com/anshooarora/extentreports-java/blob/master/src/test/java/com/aventstack/extentreports/api/BuildsReportWithoutTests.java

**Comment by anshooarora** [comment]
Closing as existing test does not throw any exceptions and steps are required to repro.  Please update this or open a new request if you are still having issues.
