### ISSUE TITLE
setAutoCreateRelativePathMedia() is not found in html reporter

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentreports-java#661]
This is required to copy the entire report folder to apache so that we can view the report on a different server

**Comment by anshooarora** [comment]
This feature was removed due to a few issues and will only be released under the pro version.  A simple workaround is to create your report structure this way:

```
root
    Extent.html
    /media
        img.png
        img.jpg
```

and in the actual report ,use relative path such as:

```
media/img.png
media/img.jpg
```

**Comment by pthewizard** [comment]
thanks for the suggestion

**Comment by pthewizard** [comment]
@anshooarora the solution you provided is not working for ExtentX. Images are not uploaded to the server with relative path. I have configured ExtentX in a docker container. So while running tests, it gives an error stating **error processing request: http://myserver:1337 media/img.png.**
