### ISSUE TITLE
how can I store screenshot in extent x server

### ISSUE THREAD

**Issue by saorabh-singh** [anshooarora/extentreports-java#663]
Whenever I attach screenshot in extent report(saved locally) that screen shot is not present in extent x server.
So how can I see this screenshot in extentX server?

**Comment by anshooarora** [comment]
What version of ExtentReports and ExtentX?

**Comment by saorabh-singh** [comment]
com.relevantcodes:extentreports: 2.41.1
extentx-0.2-alpha

**Comment by saorabh-singh** [comment]
The latest one, I have started using extent report from last 1 month.

**Comment by anshooarora** [comment]
Snapshots are possible starting version 3 and ExtentX 0.2.2.
