### ISSUE TITLE
How to Add new Html Report to existing report in 3.0.0 Version

### ISSUE THREAD

**Issue by rajeshpemmasani** [anshooarora/extentreports-java#665]
In 3.0.0 version we don't see any option to append the new html report to existing report.

Can you please advise how can i append the new report to existing report.

**Comment by anshooarora** [comment]
This option is only available for the upcoming pro version.  The community version (from github) does not currently have this feature..

**Comment by anshooarora** [comment]
Feature was added in 3.0.1.

**Comment by anshooarora** [comment]
Feature was added in 3.0.1.
