### ISSUE TITLE
The supplied file C:\...report.html is not a valid Extent file

### ISSUE THREAD

**Issue by Dgotlieb** [anshooarora/extentreports-java#667]
Hi,

I encounter the following error:
The supplied file C:\...report.html is not a valid Extent file.  Parsing failed, tests from the supplied file will not be listed in the current report.

Any idea why?

**Comment by anshooarora** [comment]
Version? Probably an issue with the previously created file.  Can you share a small sample code to reproduce?

**Comment by Dgotlieb** [comment]
All i did was:

`private static ExtentReports extent =new ExtentReports("C://3.html",false);

private static ExtentTest test = extent.startTest("stores test", "description");`

I did use it in a java application and not in jUnit, maybe that is the reason (never tried it before..).

**Comment by anshooarora** [comment]
This would happen if 3.HTML is an existing file not created by ExtentReports or an unsupported version of it.

**Comment by Dgotlieb** [comment]
Yap, bad Html file.
Thanks.
