### ISSUE TITLE
How to append to existing report?

### ISSUE THREAD

**Issue by lehoanglu0ng** [anshooarora/extentreports-java#668]
On v2.4x.x+ I used replaceExisting = false to append to my existing report. But how can I do that on v3.0?

**Comment by anshooarora** [comment]
This feature will only be available in the upcoming pro version.  The community version may not have this feature, but I am marking this as an enhancement in case someone is able to include it.

**Comment by lehoanglu0ng** [comment]
Thanks for your answer, I think I should switch back to v2.

**Comment by karthikbhatnagar** [comment]
Anshoo can you add this to the community also? This feature is most basic so will be helpful.

**Comment by anshooarora** [comment]
This feature will be included in upcoming 3.0.1.

**Comment by anshooarora** [comment]
This feature is included with bcf95c9f8b98517a8e50497ca158c76596388cf0.  Please check with the next version.

**Comment by anshooarora** [comment]
Feature included in 3.0.1.  Release available on central.

**Comment by shirishnagarnz** [comment]
Hi Anshoo,

1st time using this portal so don't know much navigation paths.

Can you please share location for latest or 3.0.1?

Thanks,
-Shirish
