### ISSUE TITLE
How can I edit date and time format?

### ISSUE THREAD

**Issue by lehoanglu0ng** [anshooarora/extentreports-java#669]
On v2.4x.x+ I can edit the date and time format via xml config file. But it didn't work on v3.0.

**Comment by anshooarora** [comment]
This feature will not be available in version 3 as it was causing issues parsing back the report as some users had customized this feature causing the parsing mechanism to break.

There is a way to workaround this: using JavaScript as part of config.XML and looping each date element.

Example:  http://stackoverflow.com/questions/13459866/javascript-change-date-into-format-of-dd-mm-yyyy
