### ISSUE TITLE
Screenshots are not displaying when the html reports are opening in other systems

### ISSUE THREAD

**Issue by anushadavuluri** [anshooarora/extentreports-java#670]
Hi,
A Html report is generated successfully with screenshots in local..But when try to open in other systems screenshots are not displaying.. used following code and version 2
public class Sample {
	
	    ExtentReports report;
	     ExtentTest logger; 
	WebDriver driver; 
	@Test
	public void verifyLogin() throws IOException, InterruptedException
	{
	report=new ExtentReports("/home/anusha/Eclipse_Reports/VisitorTracking.html");
	 logger=report.startTest("VerifyLogin");
	 driver=new FirefoxDriver();
	 driver.manage().window().maximize(); 
	logger.log(LogStatus.INFO, "Browser started ");
	driver.get("192.168.2.98:8080/BusinessCard/#/login");
	driver.manage().timeouts().implicitlyWait(5000,TimeUnit.SECONDS);
	logger.log(LogStatus.INFO, "Application is up and running");
	 String title=driver.getTitle();
	Assert.assertTrue(title.contains("Login")); 
	 logger.log(LogStatus.PASS, "Title verified");
	 String  screenshotpath=Utility.takescreenshot(driver,"Login");
          logger.log(LogStatus.PASS, "Snapshot below: " + logger.addScreenCapture(screenshotpath));
          report.endTest(logger);
	report.flush();
	driver.get("/home/anusha/Eclipse_Reports/VisitorTracking.html");
}
}

**Comment by anshooarora** [comment]
Are you moving the screenshots with the report? If not, then you should otherwise other systems will not be able to access them.
