### ISSUE TITLE
Please I need in details on how to setup extend reporting in Selenium java

### ISSUE THREAD

**Issue by devperera** [anshooarora/extentreports-java#671]
Hi All,

          I use this reporting system one year before, but when I try its not working properly. 
          Can anyone send me the details setup on how to set this works in Selenium java.
          I am using java 1.8.0_73 and selenium 3.0.1

........................
Thanks
Dev

**Comment by anshooarora** [comment]
What version of Extent? Did you check the docs?

**Comment by devperera** [comment]
Hi Anshooarora,
                         Its version 3.0 (extentreports-java-3.0.0).

............................
Thanks
Dev

**Comment by anshooarora** [comment]
Docs are currently in progress.  Please use the readme for now. 

https://github.com/anshooarora/extentreports-java/blob/master/README.md

**Comment by devperera** [comment]
Hi Anshooarora,

Thanks for the reply, once docs publish let me know.
Sure I will go through the link you provided.

.......................
Thanks
Dev Chaminda Perera
