### ISSUE TITLE
Need LogStatus.DEBUG in v2.41.2

### ISSUE THREAD

**Issue by Prakash-Saravanan** [anshooarora/extentreports-java#672]
I have the following requirement.
Debug messages must be added to the report and must be hidden initially. On pressing Ctrl+Alt+e, it will toggle between hiding and showing of the debug messages.

Currently I have implemented this using LogStatus.UNKNOWN. It will be good to have LogStatus.DEBUG and a separate filter icon for that.

**Comment by anshooarora** [comment]
Marking this as an enhancement, but for version 3 as no new features will be added to version 2 moving forward.
