### ISSUE TITLE
Need readable test cases list view in v2.41.2

### ISSUE THREAD

**Issue by Prakash-Saravanan** [anshooarora/extentreports-java#673]
I am executing nearly 1500 test cases which makes it difficult to find the required test case in the report. Though search functionality helps to an extent, when I have same test name for test cases from different suites/classes, I could not differentiate between the tests.

It will be good to show the test cases as tree like menu(collapsible and expandable) ordered by class/suites.

**Comment by anshooarora** [comment]
This is more of a usage scenario. You can add each executing method as part of a class, which will present the structure as:

1. Classes on the left hand side of the view
2. Methods belonging to the class on the right, as collapsible nodes

To achieve this:  

1. Start the parent test in @BeforeClass
2. Start the child tests in @BeforeMethod
3. Append each child to parent in @BeforeMethod
