### ISSUE TITLE
Getting error while running tests on a vm

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentreports-java#674]
I am creating an RPM using maven and installing that RPM in a VM. But when I run the tests it is giving me this error:

java.lang.UnsupportedClassVersionError: com/aventstack/extentreports/reporter/ExtentHtmlReporter : Unsupported major.minor version 52.0

VM has the latest jdk installed and code was also compiled with latest jdk i.e 1.8

**Comment by anshooarora** [comment]
Does the path also point to JDK8? This is a versioning issue with incorrect JDK.

**Comment by pthewizard** [comment]
yes it is path issue.

**Comment by DarshQa** [comment]
Hi Prasanta,

Can u comment the steps as how to resolve this issue.
