### ISSUE TITLE
Potential index out of range issue in Table.java - Should be data[row].length

### ISSUE THREAD

**Issue by hejhj** [anshooarora/extentreports-java#676]
for(int row = 0; row < data.length; row++){
            sb.append("<tr>");
            for(int col = 0; col < data[0].length; col++){ // Should be data[row].length
                sb.append("<td>" + data[row][col] + "</td>");
            }
            sb.append("</tr>");
       }

**Comment by anshooarora** [comment]
Thanks,  this will be fixed in the upcoming 3.0.1.
