### ISSUE TITLE
[Extent 3] Filters are not working as expected

### ISSUE THREAD

**Issue by SrinivasanTarget** [anshooarora/extentreports-java#679]
Filter works at class level but doesn't filter the failed methods inside it. Apply Fail filter filters failed classes but doesnt filter failed methods inside it.
<img width="1350" alt="screen shot 2016-11-09 at 3 44 06 pm" src="https://cloud.githubusercontent.com/assets/8896549/20134987/82cd3e68-a693-11e6-8649-515a6de8fb19.png">

**Comment by SrinivasanTarget** [comment]
@anshooarora

**Comment by anshooarora** [comment]
The filters currently work only for the parent level.  Child-level filters are yet to be integrated.

**Comment by SrinivasanTarget** [comment]
👍

**Comment by dhirenmudgil** [comment]
@anshooarora Can we fix this..?

**Comment by yael-lorenzo-olx** [comment]
Watch it here @dhirenmudgil https://github.com/anshooarora/extentreports-java/pull/764/files.
