### ISSUE TITLE
Dash Board: Pass percentage removed

### ISSUE THREAD

**Issue by HaridasNayak** [anshooarora/extentreports-java#681]
HI  @anshooarora,

  I could see that pass percentage has been removed from the Dash board (in version 3 Sample report). I feel that pass percentage is a good info to have on the Dash board.  Is it possible to add the pass percentage on the Dashboard in version 3?

Thanks ,
Haridas

**Comment by anshooarora** [comment]
Available starting version 3.0.4.  You will have to hover over the value to see the percentage values.
