### ISSUE TITLE
Question: Is it posible to have Category within the Category

### ISSUE THREAD

**Issue by HaridasNayak** [anshooarora/extentreports-java#682]
Hi @anshooarora ,

  I have test suite contains test cases from different module of the application and have categorized the features of the modules. Now i want to report a test cases or categorize like following.
Module A(Category)
         => Feature A(Sub category)
         => Feature B(Sub category)
Module B(Category)
         => Feature A(Sub category)
         => Feature B(Sub category)

 Can we achieve the above reporting structure ?. Can you please help on this.

**Comment by anshooarora** [comment]
Nested categories are not supported.

**Comment by HaridasNayak** [comment]
how can i create hierarchy? can you give a example.
