### ISSUE TITLE
[Extent 3] Cannot add 64base image

### ISSUE THREAD

**Issue by danilosouzajesus** [anshooarora/extentreports-java#685]
In version 2.x we have a addBase64ScreenShot method. Using the version 3.x i can do the same ?

**Comment by anshooarora** [comment]
This feature was dropped for version 3 because base64 strings take up space and drastically increase the size of the static HTML file.  This in-turn causes slowness to load, filter, view and renders the report unusable.  This also has similar negative effects on the ExtentX server.
