### ISSUE TITLE
How to remove the left hand corner 'Extent Reports' from the reports in Extent Report

### ISSUE THREAD

**Issue by Mradulkapoor** [anshooarora/extentreports-java#687]
How to remove the left hand corner 'Extent Reports' from the reports in Extent Report @anshooarora

**Comment by soniyamalini** [comment]
Hi Mradulkapoor,
     Extent Reports tab in the left hand corner contains a link which will navigate to relevantscode.com
Even I found it deviating to my report.So below are the codes I used hope it helps you

One way:
 
       .logo-container {
    display: none;  }

Add this line in your config.xml file, in custom styles after     <![CDATA[
  
The second method:
  You can directly add it in your code by 

String css = " .logo-container {display: none;  }";
extent.config().insertCustomStyles(css);

**Comment by doshipranavs** [comment]
hi @soniyamalini 
I tried first option for this by adding detail in config file but doesn't works.
I am using latest version of 3.0.2 so extent.config() is obsolete 

Can you please advise best possible way to configure this to remove EXTENT from left corner

Thanks 
PD
