### ISSUE TITLE
Improvement: Set timestamp display format

### ISSUE THREAD

**Issue by waquarazam2** [anshooarora/extentreports-java#688]
I use extentreports to generate reports that are viewed by people from different timezone. It leads to confusion. It will be nice to have a feature where I can add text after the time that is displayed in the report to indicate timezone.

**Comment by email2vimalraj** [comment]
@waquarazam2 : With the latest version of extent report, now you can define your own timestamp. Please refer [here](http://extentreports.com/docs/versions/3/java/#whats-new-1)
