### ISSUE TITLE
extentreports-java Version 3.0.3

### ISSUE THREAD

**Issue by Jethina** [anshooarora/extentreports-java#689]
On setting category .Individual test Tests are not shown.
'
Code:-
        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter("D:\\extent.html");
        htmlReporter.setAppendExisting(true);
        // create ExtentReports and attach reporter(s)
        
        ExtentReports extent = new ExtentReports();
        extent.attachReporter(htmlReporter);
       // ExtentTest test = extent.createTest("MyFirstTest", "Sample description");
     
        ExtentTest parent = extent.createTest("Test5");
        parent.assignCategory("FLIGHT");;
        ExtentTest pc1= parent.createNode("child1");
        pc1.log(Status.PASS, "child1 description");
        ExtentTest pc2= parent.createNode("child2");
        pc2.log(Status.PASS, "child2 description");
        ExtentTest pc3= parent.createNode("chil3");
        pc3.log(Status.PASS, "child3 description");
        ExtentTest pc4= parent.createNode("child4");
        pc4.log(Status.PASS, "child4 description");
        
        extent.flush();

Issue:-
a.User is not able to see all the test in category filter.
b.same has impact in dashboard pass,fail count
![screen2](https://cloud.githubusercontent.com/assets/23483958/20318011/8a0dd91c-ab8e-11e6-83ef-4acabd85e480.png)
![screen1](https://cloud.githubusercontent.com/assets/23483958/20318012/8a15b60a-ab8e-11e6-8a00-643c1d2c2541.png)
![screen1](https://cloud.githubusercontent.com/assets/23483958/20318029/9899d30a-ab8e-11e6-8290-8a459d0ad188.png)
![screen2](https://cloud.githubusercontent.com/assets/23483958/20318030/98a196ee-ab8e-11e6-9d6b-fa3f10a872fb.png)

**Comment by anshooarora** [comment]
You will have to assign the category to each test.  Assigning it to the parent only will not automatically assign the children the same category.
