### ISSUE TITLE
Count shown is wrong in dashboard for tests and steps

### ISSUE THREAD

**Issue by Jethina** [anshooarora/extentreports-java#690]
Total test count shown is wrong also steps

I have onl
![screen1](https://cloud.githubusercontent.com/assets/23483958/20318200/511f0d78-ab8f-11e6-9299-2a52732af200.png)
y two test 

![screen3](https://cloud.githubusercontent.com/assets/23483958/20318170/35eebaee-ab8f-11e6-9b78-a424ed6a7d83.png)

**Comment by anshooarora** [comment]
It will count the child tests, not parent which is why the counts are off.  If the child nodes are not tests, I would recommend you to use logs instead of `createNode` to create a child.

**Comment by arunprakash** [comment]
@anshooarora : 
Is it possible to remove the Node from count..? May be within the code is also fine. 
Also can you say little more on creating Node with log..?

**Comment by anshooarora** [comment]
This is the same as #708, an enhancement is already added to allow using the parent could in the dashboard.
