### ISSUE TITLE
3.0.1 doesn't populate the Filter menu list

### ISSUE THREAD

**Issue by mdfaller** [anshooarora/extentreports-java#695]
When I use 3.0.1, the Filter menu doesn't list any statuses.  When I back down to 3.0.0 with the same code the menu lists: Pass, Fail, Error, Warning, Skip.

**Comment by anshooarora** [comment]
I have marked this as a bug, but I am unable to repro on my side.  I do see all the status appear in the list that are in the report.  Can you share an example?

**Comment by mdfaller** [comment]
![2016-11-17 11_34_20-greenshot](https://cloud.githubusercontent.com/assets/6668303/20398260/b8bad800-acba-11e6-86ab-b00e455ab747.png)

**Comment by anshooarora** [comment]
In my tests, this is what I see:

![img](https://cloud.githubusercontent.com/assets/4107384/20398554/d88b037a-acbb-11e6-9f00-bc57e7811d7b.png)

Did you download the jar from the website or via central/maven/gradle?

**Comment by mdfaller** [comment]
Maven dependency:
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.0.1</version>
</dependency>

We are running it as a TestNG listener if that is useful to know.

**Comment by anshooarora** [comment]
I see,  IReporter (hooks at the end of suite) or ITestListener (hooks after each test/method)?

**Comment by mdfaller** [comment]
ITestListener after each test method

**Comment by anshooarora** [comment]
Hmm, still no luck in reproducing this.  I ran [this ITestListener test](https://github.com/anshooarora/extentreports-java/blob/master/src/test/java/com/aventstack/extentreports/listenertests/ListenerTestsITestListener.java) and it does populate the status in filter.
