### ISSUE TITLE
How to add the chart to extent report?

### ISSUE THREAD

**Issue by Praveen431** [anshooarora/extentreports-java#696]
Hi Anshoo Arora,

In my project,when the exception comes,we are dividing that exception into different issues(Like Product issue,Environment issue,Script issue).Now i am displaying in the each failure case.Now i want display the count (How many product,script,environment issues) or pie chart in the extent report.Can you please help me on this.

**Comment by anshooarora** [comment]
This feature will probably not be included in the static file but is available in ExtentX server already (pro-only, the community version will probably not have this feature).

If you would like to add this to the existing report, [here](https://github.com/anshooarora/extentreports-java/blob/master/src/main/resources/com/aventstack/extentreports/view/html-report/test-view/test-view-charts.ftl) is the test view for charts, and the [exception view](https://github.com/anshooarora/extentreports-java/blob/master/src/main/resources/com/aventstack/extentreports/view/html-report/exception-view/exception-view.ftl) which you can modify as per your needs to add the relevant charts.
