### ISSUE TITLE
Latest offline jar of extentreports for java

### ISSUE THREAD

**Issue by manavarora92** [anshooarora/extentreports-java#699]
Hi
I'm using the extentreports 2.41.0 jar for my project right now and there are a few tabs on the right side of the main screen in the offline mode. Is there any way to hide them or is there any latest jar in which these tabs are auto -hidden or something like that.
![offline_snapshot](https://cloud.githubusercontent.com/assets/23649415/20511901/ec3a8172-b0a1-11e6-85d7-45cefeee510b.PNG)

**Comment by anshooarora** [comment]
Which tabs are you referring to?

**Comment by manavarora92** [comment]
The tabs on the left side of the window.
![offline_snapshot](https://cloud.githubusercontent.com/assets/23649415/20550778/2b98e148-b15f-11e6-91f8-55f3801943fc.PNG)

**Comment by email2vimalraj** [comment]
@manavarora92 : Those tabs will only appear if there is data. If no data, then those tabs will not even be displayed. Debug whether you are adding atleast any empty data.

**Comment by anshooarora** [comment]
@email2vimalraj is correct.  These get enabled automatically depending upon the data you add to the report.  

For example, 1. if you add a category, the category tab gets enabled.  2. if you add an Exception, the bug tab gets enabled.
