### ISSUE TITLE
User Should have option to add additional columns like time for execution, and other details like data inputs

### ISSUE THREAD

**Issue by hsupadrasta** [anshooarora/extentreports-java#70]
User Should be given option to add additional columns according to the need keeping the standard columns intact.

Like Status, details should remain constant others can be added as per req.

**Comment by anshooarora** [comment]
Hari

Please feel free to send a pull request.  I with be pushing the 2.10 beta-2 sources very soon, you can use those.  It is now very easy to make report modifications.

**Comment by anshooarora** [comment]
Starting version 3+, user will be able to add tables to the test, but the existing table for log would remain as-is.

**Comment by anshooarora** [comment]
Version 3 provides the ability to add extra details via a MarkupHelper object.  However, the existing markup of the test/log will not change.
