### ISSUE TITLE
How to run selenium project which has Extent reports in cmd or batch file?

### ISSUE THREAD

**Issue by sangeethr** [anshooarora/extentreports-java#700]
I want to use jenkins to run a selenium project which includes extent reports. For this i have created a batch file to run the project in jenkins. But when i add extent report codes to my projects, the automation is getting stopped (the cmd is getting closed automatically). When the extent reports codes are taken off from the project, then we are able to run the batch file . 
How do i overcome this?
Please guide me on this.

**Comment by email2vimalraj** [comment]
@sangeethr : Kindly share the code on how you are attaching the extent report code to your existing project. Without that it would be hard to help you further. Hope you understand.

**Comment by anshooarora** [comment]
Closing issue as there was no response from OP.
