### ISSUE TITLE
Looking for extra details on extent reports

### ISSUE THREAD

**Issue by OliveDeb** [anshooarora/extentreports-java#703]
Unable to get the Skip and Fail per cent as we get for pass percentage
Unable to display the number of PASSED/FAILED/SKIP tested on the PIE chart
Unable to see all the views ( left hand side icons). I have only two, one displays the tests and the other displays the pie chart

**Comment by OliveDeb** [comment]
@anshooarora .. can you please help?

**Comment by anshooarora** [comment]
1. This can be added in version 3 - enhancement, please open a new ticket for this

2. These are already displayed, can you elaborate on what is missing?

3. These tabs get enabled as you add relevant information to your report. For example, 1. if you add a category, the category tab gets enabled. 2. if you add an Exception, the bug tab gets enabled.
