### ISSUE TITLE
java.lang.NoSuchFieldError: VERSION_2_3_23

### ISSUE THREAD

**Issue by NirmalAyyappan** [anshooarora/extentreports-java#704]
Hi,

I'm getting "java.lang.NoSuchFieldError: VERSION_2_3_23" error while creating object for extentreport object. 

I'm using extent report in my maven project [Jbehave+selenium+maven]
Extent version: 2.41.2.

**Comment by email2vimalraj** [comment]
This is usually happens when you have openjdk instead of Oracle JDK. Also, try setting the PATH with your java path.

**Comment by anshooarora** [comment]
@NirmalAyyappan - also make sure you have all dependencies added, freemarker 2.3.23 in this case.
