### ISSUE TITLE
ParentTest count only in Test count

### ISSUE THREAD

**Issue by M-Sr** [anshooarora/extentreports-java#708]
Hi Anshoo,

First of all would like to appreciate for all the hard work you have put in Extent Report.

My find below my query with respect of latest version(v3.0.1):
1) I want to have only the parent test count on the Dashboard.
2) The above problem is solved in v2 with an option that allows the user to select the test results as: With Parents Only. Is there something we have in v3 or a workaround to achieve this.
![v2 screenshot](https://cloud.githubusercontent.com/assets/21166930/20709333/b2382c18-b65a-11e6-9f08-53220ba267ff.JPG)
![version 3 screenshot](https://cloud.githubusercontent.com/assets/21166930/20709332/b2362936-b65a-11e6-97ca-2ba25fc095f8.JPG)

Thanks,
Mayank

**Comment by anshooarora** [comment]
Having only a certain level of test count is currently not possible.  It goes by the same logic as TestNG to count the tests, but it can be added.  Marking this as an enhancement for future version.

**Comment by anshooarora** [comment]
Starting version 3.0.4, you can select an [AnalysisStrategy](http://extentreports.com/docs/versions/3/java/#analysis-strategy) that enables this.

You are looking for either the `SUITE` or `CLASS` strategy.
