### ISSUE TITLE
How to end a test?

### ISSUE THREAD

**Issue by Prakash-Saravanan** [anshooarora/extentreports-java#709]
In version 3.0.1, ExtentTest.endTest is missing. End time for all the tests are set when calling flush which is the present time of calling flush not the actual end time of the test.

How to end only one test alone?

**Comment by email2vimalraj** [comment]
The moment you do any one of the following will eventually end your test:

```
test.pass(logmessage);
test.fail(logmessage);
test.skip(logmessage);
```
