### ISSUE TITLE
Categories results are not updated properly

### ISSUE THREAD

**Issue by Prakash-Saravanan** [anshooarora/extentreports-java#710]
In version 3.0.1, test fails but category is passed.
![ice_screenshot_20161129-191444](https://cloud.githubusercontent.com/assets/22522670/20711969/3f19846c-b668-11e6-9ef0-9100f9551712.jpeg)
![ice_screenshot_20161129-191516](https://cloud.githubusercontent.com/assets/22522670/20711972/3f1bc664-b668-11e6-8550-3ac8b87b8f1c.jpeg)
![ice_screenshot_20161129-191537](https://cloud.githubusercontent.com/assets/22522670/20711971/3f1b71c8-b668-11e6-8d33-e6a992321bda.jpeg)

**Comment by joeljohnson00** [comment]
I too have the same problem.Please fix this

**Comment by email2vimalraj** [comment]
@Prakash-Saravanan or @joeljohnson00 : Help us with the sample code which we can reproduce your problem. The screenshots alone may not help us very much. Hope you guys understand.

**Comment by Prakash-Saravanan** [comment]
```
public static void main(String[] args) {
		ExtentReports report = new ExtentReports();
		report.attachReporter(new ExtentHtmlReporter("ExtentReport.html"));
		report.createTest("test").assignCategory("smoke").assignAuthor("author").fail("fail");
		report.createTest("test2");
		report.flush();
	}
```

**Comment by Prakash-Saravanan** [comment]
```
public static void main(String[] args) {
		ExtentReports report = new ExtentReports();
		report.attachReporter(new ExtentHtmlReporter("ExtentReport.html"));
		ExtentTest test = report.createTest("Class1");
		ExtentTest test1 = test.createNode("Test1").assignCategory("smoke", "regression", "integration").assignAuthor("author");
		test.createNode("Test2").fail("fail");
		test.createNode("Test2").fail("fail");
		test.createNode("Test2").fail("fail");
		test.createNode("Test2").fail("pass");
		test.createNode("Test3").fail("fail");
		test1.fail(new Exception("Intentional"));
		report.flush();
	}
```

**Comment by email2vimalraj** [comment]
@Prakash-Saravanan - This is a bug.

@anshooarora - Kindly verify and mark it as a bug.

**Comment by anshooarora** [comment]
Thank you.

Fix will be available in the next version.
