### ISSUE TITLE
Tests are being Overwritten when using Mutilthreading for Extent Reports

### ISSUE THREAD

**Issue by hanumanthuhemanth** [anshooarora/extentreports-java#711]
Hello @anshooarora,

I calling the below class which receives data from different class( which is a thread class) all my selenium code works individually with the given data for each thread. But when coming to Extent Reports it is overwriting my tests, suppose if i create three threads for a single run to call the below method then last thread is only seen and rest two are overwritten. Can you help on this ?
`public class MainTestClass
{	
	public  void MainTest(DataReader DTRead,String TRName) 
	{
		WebDriver MyDriver=null;

		System.out.println(Thread.currentThread().getName() + " is in Main Test");
		
		String extentReportFile = "D:\\Extent_Report_Results" + "\\extent.html";
		String extentReportImage = "D:\\Extent_Report_Results" + "\\extentReportImage.png";
		String configfile = "D:\\Extent_Report_Results\\extent-config.xml";
		ExtentTest ExTest;
		ExtentReports ExFile;
		ExFile = new ExtentReports(extentReportFile, false);
		ExFile.loadConfig(new File(configfile));
		ExTest = ExFile.startTest(DTRead.TestName, DTRead.TestDesc);
		
		ExTest.assignAuthor(DTRead.TestAuthor);
                ExTest.log(LogStatus.INFO, "Browser Launch Successful");
                 ExTest.log(LogStatus.PASS, "Title verified");
                System.out.println(ExTest.getDescription()+" is about to end");
		ExFile.endTest(ExTest);
		ExFile.flush();
		ExFile.close()
         }
}
`

**Comment by hanumanthuhemanth** [comment]
I have updated to 3.0.1 and changed the code accordingly but still having the same issue.. can you help me on this ?kind of urgent.

**Comment by email2vimalraj** [comment]
@hanumanthuhemanth : If I understand you correctly, you are trying to execute your `MainTest` in parallel. The report is displaying only the last thread's results.

If my understanding is correct, then that is obvious. Because, you are creating new ExtentReports instance for every thread and it tends to overwrite the same file again and again.
