### ISSUE TITLE
Source for Sample Report at http://extentreports.com/os/3/extent.html

### ISSUE THREAD

**Issue by mmtmohit** [anshooarora/extentreports-java#712]
Hi Anshoo,
request you to please share the source code of the extent report sample on your github page : 
http://extentreports.com/os/3/extent.html#!
Particularly need this for the media screenshot test cases.
This would really help everyone who wants to implement your API in their automation frameworks

Rgds,
Mohit

**Comment by anshooarora** [comment]
Please see the [docs](http://extentreports.com/docs/versions/3/java/#insert-screenshots) for 2 examples for logs and tests.
