### ISSUE TITLE
How not to show the unknown/skipped results in report

### ISSUE THREAD

**Issue by nidzz** [anshooarora/extentreports-java#713]
I am using RetryAnalyzer in selenium code, wherein if a test case fails in first execution, retryAnalyzer would again execute it. In my case, if first time execution fails and second time execution passes, I want to show the results of only second execution in Extent Reports. But I am getting both the test case results in the report.

Below is my code.
ExtentTest test;
int maxRetryCount = 1;
@AfterMethod
	protected void afterMethod(ITestResult result) {
	boolean firstTry = true;	

		if(maxRetryCount>0){
			if (result.getStatus() == ITestResult.FAILURE && firstTry == true) { 
				firstTry = false;
			} else if (result.getStatus() == ITestResult.SKIP) {
				test.log(LogStatus.SKIP, "Test skipped " + result.getThrowable());
			} else if (result.getStatus() == ITestResult.FAILURE && firstTry == false) {
				test.log(LogStatus.ERROR, test.addScreenCapture(imgPath));
				test.log(LogStatus.FAIL, result.getThrowable());
			} else {
				test.log(LogStatus.PASS, "Test passed");
			}
		}else{
			if (result.getStatus() == ITestResult.FAILURE) { 
	        	test.log(LogStatus.ERROR, test.addScreenCapture(imgPath));
	            test.log(LogStatus.FAIL, result.getThrowable());
	        } else if (result.getStatus() == ITestResult.SKIP) {
	            test.log(LogStatus.SKIP, "Test skipped " + result.getThrowable());
	        } else {
	            test.log(LogStatus.PASS, "Test passed");
	        }
		}`

in this case, if the test case fails in first execution, it shows the status of that test case as "unknown", and suppose the execution passes in retry(second time execution), the pass percentage is shown as 50%, not 100%, because it counts the unknown's percentage as well.

What changes should i do in below loop condition, so that result of this test case are not shown in the report.
`if (result.getStatus() == ITestResult.FAILURE && firstTry == true) { }`

Please suggest.

**Comment by email2vimalraj** [comment]
So you know that if the `result.getStatus != ITestResult.PASS`, it will definitely retry. So keep a flag of retry count and add to `Extent` only if retry count is > 1. Till that don't add into Extent.

**Comment by nidzz** [comment]
Ideally, only those test cases which are retried, and whatever the result is there 2nd time, should be shown in the report, but by default, it shows it as "unknown", and is considered in the report. We can't control over adding/removing it from extent. Because if even if tell not to show pass/fail/skip, it will show it as unknown.

I assume that we need to do some changes in the listener of Extent Report. Do you have any idea that which listener is being used for Extent?

**Comment by anshooarora** [comment]
I believe you are using version 2.x.  The concept of retrials has not been implemented in any version of this reporting, all tests that have been executed will be displayed.  Why the 2nd run gets an Unknown status - I am not sure.  Can you share a small sample that I can use to check?

**Comment by rakall123** [comment]
I am also facing the same issue.
Think that we have a test case with name reportTest() and I have a retryAnalyzer count of 3.
If test got failed in first 2 runs and passed in 3rd run.
Extent Report is showing it as 3 testcases instead of 1. with the same name (first two as skip and 3rd as pass)
<img width="1440" alt="screen shot 2017-03-21 at 12 57 59 pm" src="https://cloud.githubusercontent.com/assets/15662008/24167994/0c2205c2-0e36-11e7-9d75-cb140ca98329.png">

**Comment by nidzz** [comment]
I got it fixed. Could you share your code where you are initializing the
extent and where you have written the scenario of showing pass/fail/skip?

Nidhi

**Comment by rakall123** [comment]
TestClass
================

`public class TestTest extends BaseTest{
	
	
	@Test
	public void retryTest(){
		startTest("D_Login");
		getCurrentLogger().log(LogStatus.INFO, "Test");
		Assert.assertEquals(true, false);
		
	}`

In BeforeMethod I am initializing the reports
`public synchronized void startTest(String testName) {
		ExtentTest test = reports.startTest(testName, testName);
		if (testName.split("_").length > 2) {
		}
		test.assignCategory(testName.split("_")[1]);
}`

In AfterMethod I am 

`switch (result.getStatus()) {
			case ITestResult.SKIP:
	
				getCurrentLogger().log(LogStatus.SKIP, "Test Verification", image);
				break;
			case ITestResult.FAILURE:
				
				getCurrentLogger().log(LogStatus.FAIL, "Exception Message", result.getThrowable());
				break;
			case ITestResult.SUCCESS:
			
				getCurrentLogger().log(LogStatus.PASS, "Test is successul");`

**Comment by nidzz** [comment]
Try by initializing report in after method itself, when it's a success.
Don't initialize when test skips/fails. Hope that works.

**Comment by rakall123** [comment]
If I do that, whatever the logging I am doing in between will be lost right?
I need to log each and every step

**Comment by nidzz** [comment]
Try by initializing report in the after method itself, when it's a success.
Don't initialize the report when test skips/fails. Hope that works.
