### ISSUE TITLE
Extent Report does not show test as fail if it fails before logging pass status of test to extent report OR if extent end test is not executed

### ISSUE THREAD

**Issue by amitjaincoer191** [anshooarora/extentreports-java#717]
If my test FAILS before assertion due to selenium or binding language error or logical error then extent report show the test as pass in report. 

It just shows the icon 'i' saying extent report end test is not executed so something is wrong with test case but it is shown as PASS.

Is it possible to show these kind of failures in extent report correctly.

Thanks....

**Comment by anshooarora** [comment]
A failed step will be shown as such if it is reported correctly.  Can you share a sample with me that I can test with?

**Comment by Shroet** [comment]
For example, you have 3 steps in your test:
1) Open Homepage with Log ( "User open home page")
2) Add an item "A" to cart with Log ( "Item was added")
3) Click Ok to end shopping with Log ( status. Pass, "Test is ended").
But in step 2 there was not an item "A" ( NoSuchElementPresent Exception) and your test were immediately ended. But if you will look to report this Test case will have status PASS. 
So, the question is: How to make test status fail if the test was ended before the final log? Thank you.

**Comment by anshooarora** [comment]
@Shroet - several examples here:  http://extentreports.com/docs/versions/3/java/#testng-examples

Basically, you need to catch and report the exception right after the test method ends (ie `@AfterMethod` of testng).

**Comment by shivalingesh** [comment]
Test case is showing as pass even though its failing
![image](https://cloud.githubusercontent.com/assets/29087545/26621912/1d84921e-4606-11e7-8b6e-e27a2f864667.png)

**Comment by alexandlazaris** [comment]
Glad to see others have experienced this issue too. I have tests that report as failures in Eclipse (through logs and TestNG) yet in ExtentReports, all green ticks and charts 🤔

**Comment by anshooarora** [comment]
Can you please open a new ticket and provide information on how to reproduce?  Thanks.

**Comment by mh-qytera** [comment]
The ticket wasn't opened, am I wrong? Because I didn't find a ticket reflecting this point.  I also have this issue: 
A button is not found so the test stops but it is reported as passed.

**Comment by Shroet** [comment]
Hello there. To avoid this step use try/catch ecxeptions and in case if you’ll caught exception, add log with the result ERROR.

**Comment by ayan56321** [comment]
Hi @Shroet I have tried by providing the status as ERROR , but this is not working
I have added the caught Exception

 catch (NoSuchElementException ex)
            {              
                test.Log(LogStatus.Error, reportVal + " is Not Present" + test.AddScreenCapture(GenericUtilities.Capture(driver, reportVal, newFolder)));
            }
