### ISSUE TITLE
Filters icons in Details page is not working_version 2.41.2

### ISSUE THREAD

**Issue by SuganyaNatarajan** [anshooarora/extentreports-java#718]
I have added the jars of 2.41.2 version and generated a report. Filters icons(pass,fail,skip,clear filters,etc) in the Details page of a test is not working. PFA the screenshot. Highlighted the icon which is not working.
![issue1](https://cloud.githubusercontent.com/assets/24624150/21288051/e497ccb6-c49e-11e6-8b98-8f767f462165.png)

**Comment by email2vimalraj** [comment]
I also have the same issue.

ping @anshooarora

**Comment by anshooarora** [comment]
I checked the sample here: http://extentreports.com/os/3/extent.html but filters do seem to be functional.  Can you confirm if the above report works for you?  

PS.  I will check with the latest code also and fix if broken.

**Comment by SuganyaNatarajan** [comment]
Report attached in the above mail works fine. Also I have generated another
report from my side and it works good. Not sure why it wasn't working last
day. Anyway thanks for the reply and sorry for the trouble.

**Comment by yael-lorenzo-olx** [comment]
@SuganyaNatarajan here is the reason https://github.com/anshooarora/extentreports-java/pull/764
