### ISSUE TITLE
Issues in version 2.41.2

### ISSUE THREAD

**Issue by SuganyaNatarajan** [anshooarora/extentreports-java#719]
**Issue 1:** No labels displayed in pie chart. PFA the screenshot. 

![image](https://cloud.githubusercontent.com/assets/24624150/21288148/6b05a1ea-c4a1-11e6-8d22-2f0494f6d7ed.png)

**Issue 2:** Blank page in some views. PFA the screenshot.

![image](https://cloud.githubusercontent.com/assets/24624150/21288167/bc485a34-c4a1-11e6-9fa2-9cab8dfc3c24.png)

![image](https://cloud.githubusercontent.com/assets/24624150/21288169/c774cba4-c4a1-11e6-9c7f-bfa08be811ef.png)

![image](https://cloud.githubusercontent.com/assets/24624150/21288174/cf41fb86-c4a1-11e6-92a1-49c9c59f1a7d.png)

**Issue 3:** Name of the view(eg:- Dashboard view) is not displayed while hovering on the icon in the left pane.

![issue3](https://cloud.githubusercontent.com/assets/24624150/21288200/8f09782c-c4a2-11e6-95de-e9caa438ebb6.png)

**Comment by anshooarora** [comment]
Would it be possible to share this report with me?  I would like to repro.  Also, does this issue always happen or is intermittent?  Does it happen on only certain systems or all?

**Comment by SuganyaNatarajan** [comment]
I don't have the report with me. But I generated a report today and I got
entirely different report. Issue 1 is fixed. PFA the report generated
today.

**Comment by anshooarora** [comment]
Nothing came through, can you please reattach?
