### ISSUE TITLE
How to update status of parent node

### ISSUE THREAD

**Issue by GayathriB1010** [anshooarora/extentreports-java#720]
I have a parent node in the extent report. There are 3 child nodes.
Child1 - pass
Child2 - skip
Child3 - Fail
I have appended all the childnodes to the parent. How should i update the parent node status as fail? Would it get updated automatically?

**Comment by email2vimalraj** [comment]
Is it not getting updated automatically?

**Comment by GayathriB1010** [comment]
No..Its not getting updated

**Comment by email2vimalraj** [comment]
Could you please post some sample to reproduce?

**Comment by anshooarora** [comment]
@GayathriB1010  - Please share a sample for us to reproduce.

**Comment by GayathriB1010** [comment]
I have given below a sample for reproducing the issue
public void extentReportSkipTesting()
 {

  Date dNow = new Date();
  SimpleDateFormat ft = new
SimpleDateFormat("dd-MM-yyyy_hh'H'_mm'M'_ss'S'");
  String strTimeOfExecution = ft.format(dNow);
  System.out.println("Entered Method"+strTimeOfExecution);

  String
filePath="C:\\Backup\\Stella\\SeleniumWorkSpace\\SeleniumLearning\\QTestDay2\\ExtentReports\\";
  // new instance
  ExtentReports extent = new ExtentReports(filePath+ "Report" +
strTimeOfExecution + ".html", true);
  ExtentTest parent = extent.startTest("Parent");

  ExtentTest child = extent.startTest("Child ");
  child.log(LogStatus.SKIP, "Skip");

  ExtentTest child1 = extent.startTest("Child 1");
  child1.log(LogStatus.PASS, "Pass");

  ExtentTest child2 = extent.startTest("Child 2");
  child2.log(LogStatus.PASS, "Pass");


  extent.endTest(child);
  extent.endTest(child1);
  extent.endTest(child2);

  parent
   .appendChild(child)
      .appendChild(child1)
      .appendChild(child2);


  extent.endTest(parent);

  extent.flush();
 }

Regards,
Gayathri

**Comment by anshooarora** [comment]
You can remove these lines of code as `.appendChild` does exactly that:

```
extent.endTest(child);
extent.endTest(child1);
extent.endTest(child2);
```

**Comment by mukulsehra** [comment]
@anshooarora : Hi!
We are using extentReport in our project, we want to get the cumulative result i.e PASS/FAIL of each test case i.e having multiple assertion points. Please see the screenshot. **I have highlighted the cumulative result of a test**. 
![cumulativeresult](https://cloud.githubusercontent.com/assets/2979526/23357543/42926d60-fd04-11e6-816d-f8ac34c8d5b2.PNG)

**Please answer ASAP, it would be really helpful**, because right now what we are doing is, creating a arrayList containing the results of all the child nodes and then calculating the cumulative results which is I think a bad approach.
\cc @email2vimalraj

**Comment by anshooarora** [comment]
The childNode failed so did the parent.  Looks correct to me..

**Comment by mukulsehra** [comment]
@anshooarora : I know that the result is correct, but my question is different.
We want to get the value of that cumulative result in a variable.
e.g : Lets say there is a Test Case TC_1 having 4 assertions points in which  3 passed and 1 failed. So, the cumulative result of this test case would be FAILED. We want to capture this value(FAILED) in a variable programmatically after execution of TC_1 ends.

How to get this ?

**Comment by anshooarora** [comment]
How about:

```
parentTest.getRunStatus();
childTest.getRunStatus();
```

**Comment by mukulsehra** [comment]
@anshooarora : It returns Unknown.
Will check it once again and let you know.
Thanks :)

**Comment by anshooarora** [comment]
You are using version 2, the status is returned after endTest.

**Comment by mukulsehra** [comment]
@anshooarora : Thanks, It worked when I used getRunStatus() after endTest(). :+1:
