### ISSUE TITLE
Long test suite mess up the report html

### ISSUE THREAD

**Issue by yardening2** [anshooarora/extentreports-java#721]
Hello @anshooarora , 

First I have to say that this is a great tool! so easy to generate a great report!
Now to my issue. I use version 2.41.2 and run a suite of selenium tests using testng parallel classes.
The report comes out great but when I run a big suite (160 test classes) my report is all meesed up.

This is the generated report:
![untitled](https://cloud.githubusercontent.com/assets/16079781/21322242/e2d01b62-c620-11e6-898a-41dda0d7708a.jpg)

Also none of the buttons resopnd. This issue happens only with a big suite of tests.

Is there anything I can doo?

thanks!

**Comment by anshooarora** [comment]
This shouldn't happen regardless of the tests size.  Are you adding some HTML in your report that is causing the report to break?  Either there is some custom JavaScript that may be causing this or HTML, but its going to be difficult to know without looking at the report.  Would it be possible to share a sample of the broken output?

**Comment by yardening2** [comment]
No extra data was added. No JS and no HTML.

this is the result html file:

http://www.filedropper.com/newsanityreport

**Comment by anshooarora** [comment]
Line 89057 is the culprit:

```
Changing text of Custom HTML/JavaScript textfield to <script>('Hello!')
```

The `<script>` tag is breaking the flow.

**Comment by yardening2** [comment]
Thanks alot man!! you saved me!!
