### ISSUE TITLE
Modify the ExtentReport Dashboard

### ISSUE THREAD

**Issue by jim-cherian** [anshooarora/extentreports-java#722]
Hi I have a couple of change that needs be done in the extent report.

1. I want to disable step view from the dashboard
2. Bring the pass percentage to 'step view' position.
3. Modify the Test view picture in dashboard to something which shows how many percent has passed ,skipped and failed. PLUS the text beside it with number of percentage
4. Disable Total test and Total steps options as well in the Extent report.

Please let me know if it possible to attain the same and what are the changes that needs to be add to the config.xml

**Comment by jim-cherian** [comment]
![image](https://cloud.githubusercontent.com/assets/16185832/21394254/f3f6e080-c7bd-11e6-980b-6d7261c8865d.png)

I need point 3 to be like the image attached in the place of Test view  and step view. Please help with the code.

**Comment by anshooarora** [comment]
These customizations are out of scope for the API, but you can easily customize the report as per your needs via the templates:

https://github.com/anshooarora/extentreports-java/tree/master/src/main/resources/com/aventstack/extentreports/view/html-report

**Comment by vijayendraswamy** [comment]
@jim-cherian  you can replace <scripts> tag in **extent-config.xml** with below one to hide Step View 
`<scripts>
       <![CDATA[$(document).ready(function() {$('.dashboard-view').click();});$('.col.s12:nth-child(2) .card-panel.nm-v').hide();$('.col.s2:nth-child(2)').hide();$('.col.s12:nth-child(1)').css('width', '100%');$('.row .col.s2').css('width', '25%');]]>
    </scripts>`
