### ISSUE TITLE
Extent Reports v2.41.0 with NUnit v3.5.0 C# Unable to pull screenshots to the report. 

### ISSUE THREAD

**Issue by Aznariy** [anshooarora/extentreports-java#724]
Noticed this recently. If the most first step at the report is not a screenshot (presume just a message), then none of the remaining screenshots from other test steps are being inserted to the reports. If first step at the report is the screenshot, then all rest is OK.

**Comment by anshooarora** [comment]
Are you adding the screenshot as a step, or details?  Can you share a sample that I can repro?

**Comment by Aznariy** [comment]
Anshoo, 

Yes, I'm trying to add screenshots as Test Step, not details. 

![image](https://cloud.githubusercontent.com/assets/13661965/21524064/4ab52d96-cce1-11e6-86a7-a23403890bba.png)

This is my _Logger.takeScreenShot_ method:
            **String currentTimeStamp = DateTime.Now.ToString("yyyy_MM_dd_HH_mm_ss");
            String imageAbsolutePath = ReportPath + currentTimeStamp + ".png";
            String imageRelativePath = currentTimeStamp + ".png";
            var fileName = new StringBuilder(imageAbsolutePath);
            var screenShot = ((ITakesScreenshot)webDriver.getDriver(driver)).GetScreenshot();
            screenShot.SaveAsFile(fileName.ToString(), ImageFormat.Png);
            return imageRelativePath;**

This is my _logger.screenshotFail_ method:

 **test.Log(LogStatus.Fail, test.AddScreenCapture(Logger.takeScreenShot()), "<b><font color = 'red'>" + details + "</font></b>");**

And this is my just _logger.info_ method:

**test.Log(LogStatus.Info, details);**

So, as I said in my initial issue post, if the first step at the report will be _logger.screenshotFail_ , (basically any method, that generates screenshot) then all the rest test steps (assume another screenshot.Fail, screenshot.Pass, screenshot.Warning) generate screenshots normally. However, if I call just logger.info method at the beginning of my report, then none of _logger.screenshot*_ methods generate images to the report, only displaying details messages.

**Comment by anshooarora** [comment]
This is by design to prevent malformed tables.  If the 1st step is empty, the table will result in only 3 columns.  

See here:  http://extentreports.relevantcodes.com/net/#create-step-logs

> There are 2 ways logs can be created: one that creates 3 columns and other that creates 4. Always use only 1 type of log for the test otherwise the table will become malformed.
