### ISSUE TITLE
test.addScreenCapture is getting a java.lang.NullPointerException

### ISSUE THREAD

**Issue by gaponte1985** [anshooarora/extentreports-java#727]
I have  a base class in this base class a have a method: takeScreenShot();

Went I call this method from another class I am getting a java.lang.NullPointerException in the line test.addScreenCapture((System.getProperty("user.dir")+"/screenshots/"+screenshotFile)); (please see below). 

	public void takeScreenShot(){
		// fileName of the screenshot
		Date d=new Date();
		String screenshotFile=d.toString().replace(":", "_").replace(" ", "_")+".png";
		// store screenshot in that file
		File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		try {
			FileUtils.copyFile(scrFile, new File(System.getProperty("user.dir")+"//screenshots//"+screenshotFile));
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			test.log(LogStatus.INFO, "Unable to log screenshot");

		}
		
		
		String img = test.addScreenCapture((System.getProperty("user.dir")+"/screenshots/"+screenshotFile));
		test.log(LogStatus.INFO,"Screenshot-> "+ img);
		
	
	}
	
---------------------------------------------------------------------------------------------------------------------------------------------------------
public class DummyTestB extends BaseTest{
	private static Properties prop = BaseTest.getProperties();
	private static ExtentReports screenshotFile;
	public static ExtentReports rep = ExtentManager.getInstance();
	private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(DummyTestB.class.getName());
		
			ExtentTest test;
		
	
	@Test
	public void testB1() throws IOException, InterruptedException{
		
		 test = rep.startTest("Dummy TestB");
		 test.log(LogStatus.INFO, "Starting the test");
		 
		 test.log(LogStatus.FAIL, "Failing the test");

		 
		 openBrowser("browser");
		
		log.debug("urlKey");
    	log.info("urlKey world");
		test.log(LogStatus.INFO, "Open the browser ");
	
		
		url("url");
	
		
		test.log(LogStatus.INFO, "input the url");
	
		test.log(LogStatus.INFO, "input the email");

		test.log(LogStatus.PASS, "Test B Passed");
		takeScreenShot();
	
		
		
		quit("appurl");		
	}
	@AfterTest
	public void testB2() throws IOException{
	
		
		rep.endTest(test);
		rep.flush();

	}

}

**Comment by anshooarora** [comment]
Please format your post correctly, it is very difficult to understand improperly indented code.  See here:  https://guides.github.com/features/mastering-markdown/

Closing this ticket, feel free to reopen or create a new ticket.
