### ISSUE TITLE
Cant get Screenshot attached to reports(Failed to load resource: net::ERR_FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by balaramc** [anshooarora/extentreports-java#729]
Hello, 
here is  my code 

This class used to capture the screen shot:
import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;

public class Utility {
	public static String captureScreenshot(WebDriver driver, String screenshotName) throws IOException {

		
			TakesScreenshot ts = (TakesScreenshot)driver;
	        File source = ts.getScreenshotAs(OutputType.FILE);
	        String dest = System.getProperty("user.dir") +"\\Screens\\"+screenshotName+".png";
	        File destination = new File(dest);
	        FileUtils.copyFile(source, destination); 

			System.out.println("Screenshot taken");
			return dest;
		} 
}

and 
This is t store:
 public String click(String obj,String data,String description)throws IOException
	  {
		  try
		  {
			  Thread.sleep(6000);
			  WebDriverWait wait=new WebDriverWait(driver,20);
			  wait.until(ExpectedConditions.elementToBeClickable(By.xpath(obj)));
			  driver.findElement(By.xpath(obj)).click();
			  
			  logger.log(LogStatus.PASS, description,description+"clicked");
			  return "Pass";
		  }
		  catch(Exception e)
		  {
			  System.out.println(description+" failed");
			  logger.log(LogStatus.FAIL, description,description+"not clicked");
			  String screeshotpath = Utility.captureScreenshot(driver,description+" failed");
			  
			  logger.log(LogStatus.FAIL, "Snapshot below: "+ logger.addScreenCapture(screeshotpath));
			  //closeBrowser(obj, data,description);
			  //Assert.fail(description+" failed");
			  return "Fail";
		  }
	  }

PIC:
![error](https://cloud.githubusercontent.com/assets/15925139/21600985/57e255fc-d1aa-11e6-969e-5153712e744d.png)

**Comment by paul-barton** [comment]
Issue is you need to use a relative path, I experienced same in all versions. 

I fixed the issue by converting my screenshot path to a relative path of the report file URI. Read [http://stackoverflow.com/a/3054692](http://stackoverflow.com/a/3054692) to see a solution you can modify to get the relative path for the screenshot/cast. Note that if you have tried using the relativize() method it will only relativize URIs when one is a prefix of the other, so the link I provided resolved all my concerns
