### ISSUE TITLE
Need some Help in customizing report

### ISSUE THREAD

**Issue by sandeepmummoji** [anshooarora/extentreports-java#732]
Hi Anshoo,
First of all thanks for spending time to create such a wonderful report which is picking up the pace to use it where ever possible. I'm stuck with few things to customize the report, hope you have some time to help me out or give some suggestion.

1. I want to display only the error with line where it failed, not like whole log. I want to keep the whole log in the 1st tab if the test is failed, but i want to display only the exception in bug tab like in sample reports.
![bug_tab](https://cloud.githubusercontent.com/assets/22115154/21718260/4ff83f8e-d43c-11e6-957a-25b2610e76fd.png)
instead of which am generating as 
![my_issue](https://cloud.githubusercontent.com/assets/22115154/21718382/17efeef6-d43d-11e6-82c5-264a86c6dc2d.png)

2. Also i'm unable to understand even if am trying to skip the test case intentionally, the test case is getting under passed count. Please try to make me understand where am i going wrong.

The code Example: 
@Test(expectedExceptions = SkipException.class, groups = "skip")
	public void skipTest() {
		System.out.println("This test is Skipped Intentionally");
		throw new SkipException("Intentionally skipped test.");
	}

But the test is showing passed under category skip as below.
![skip_issue](https://cloud.githubusercontent.com/assets/22115154/21718437/8c9ce650-d43d-11e6-9fa8-f4b104ca4a57.png)

3. I want to print the **"@Test method names"** under a Class, unlike Suite name & the **"@Test method names under it"** please find the over view of issues in the below image.
![report_overview](https://cloud.githubusercontent.com/assets/22115154/21718641/c23169b6-d43e-11e6-842c-6e4b32391528.png).

I'm using the listener in the pom.xml triggering it directly.
Listener Class that i'm using is:

package com.reports.listener;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.IReporter;
import org.testng.ISuite;
import org.testng.ISuiteListener;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.TestNG;
import org.testng.xml.XmlSuite;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.configuration.ChartLocation;
import com.aventstack.extentreports.reporter.configuration.Theme;
import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.reports.util.EmailReporter;
import com.reports.util.NodeName;
import com.reports.util.SystemInfo;

/**
 * This class houses the listener for the TestNG which generates the html report
 * by using Extent Report.
 */
public class ExtentWithTestNGListener implements ISuiteListener, ITestListener,
		IInvokedMethodListener, IReporter {

	/*
	 * Initializations and Declaration Reporting Attributes
	 */
	private static final String REPORTER_ATTR = "extentTestNgReporter";
	private static final String SUITE_ATTR = "extentTestNgSuite";

	private static String ipAddress = null;
	private static Map<Object, String> map = new HashMap<Object, String>();

	private ExtentReports reporter;
	private List<String> testRunnerOutput;
	private Map<String, String> systemInfo;
	private Map<Object, String> sysprop;
	private ExtentHtmlReporter htmlReporter;
	private static ExtentWithTestNGListener instance;

	public ExtentWithTestNGListener() {

		setInstance(this);
		testRunnerOutput = new ArrayList<>();

		/*
		 * File Path Where the reports will be generated.
		 */
		String reportPathStr = System.getProperty("user.dir") + File.separator
				+ "Reports";

		Reporter.log("Reports Path : " + reportPathStr);

		File reportPath;
		sysprop = getSystemProperties();

		try {
			reportPath = new File(reportPathStr);
			Reporter.log("Report Path Created at : " + reportPath);
		} catch (NullPointerException e) {
			reportPath = new File(TestNG.DEFAULT_OUTPUTDIR);
			Reporter.log("Report Path Created at : " + reportPath);
		}

		if (!reportPath.exists()) {
			if (!reportPath.mkdirs()) {
				throw new RuntimeException(
						"Failed to create output run directory");
			}
		}

		File reportFile = new File(reportPath, "report.html");
		File emailReportFile = new File(reportPath, "emailable-report.html");

		htmlReporter = new ExtentHtmlReporter(reportFile);
		htmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
		htmlReporter.config().setChartVisibilityOnOpen(true);
		htmlReporter.config().setTheme(Theme.DARK);
		htmlReporter.config().setDocumentTitle("Automation Report");
		htmlReporter.config().setEncoding("utf-8");
		htmlReporter.config().setReportName("Report" + getTime(5000));

		EmailReporter emailReporter = new EmailReporter(emailReportFile);

		reporter = new ExtentReports();

		reporter.setSystemInfo("OS : ", sysprop.get("os.name"));
		reporter.setSystemInfo("OS Architecture : ", sysprop.get("os.arch"));
		reporter.setSystemInfo("Java Version : ", sysprop.get("java.version"));
		reporter.setSystemInfo("User Name : ", sysprop.get("user.name"));
		reporter.setSystemInfo("Machine Name : ", sysprop.get("machine.name"));
		reporter.setSystemInfo("IP Address : ", sysprop.get("machine.address"));

		reporter.attachReporter(htmlReporter, emailReporter);

		reporter.setReportUsesManualConfiguration(true);

	}

	/**
	 * Gets the instance of the {@link ExtentWithTestNGListener}
	 *
	 * @return The instance of the {@link ExtentWithTestNGListener}
	 */
	public static ExtentWithTestNGListener getInstance() {
		return instance;
	}

	private static void setInstance(ExtentWithTestNGListener formatter) {
		instance = formatter;
	}

	public void onStart(ISuite iSuite) {

		ExtentTest suite = reporter.createTest(iSuite.getName());

		String configFile = iSuite.getParameter("report.config");

		if (!Strings.isNullOrEmpty(configFile)) {
			htmlReporter.loadXMLConfig(configFile);
		}

		String systemInfoCustomImplName = iSuite.getParameter("system.info");
		if (!Strings.isNullOrEmpty(systemInfoCustomImplName)) {
			generateSystemInfo(systemInfoCustomImplName);
		}

		iSuite.setAttribute(REPORTER_ATTR, reporter);
		iSuite.setAttribute(SUITE_ATTR, suite);
	}

	private void generateSystemInfo(String systemInfoCustomImplName) {
		try {
			Class<?> systemInfoCustomImplClazz = Class
					.forName(systemInfoCustomImplName);
			if (!SystemInfo.class.isAssignableFrom(systemInfoCustomImplClazz)) {
				throw new IllegalArgumentException(
						"The given system.info class name <"
								+ systemInfoCustomImplName
								+ "> should implement the interface <"
								+ SystemInfo.class.getName() + ">");
			}

			SystemInfo t = (SystemInfo) systemInfoCustomImplClazz.newInstance();
			this.systemInfo = t.getSystemInfo();
		} catch (ClassNotFoundException | InstantiationException
				| IllegalAccessException e) {
			throw new IllegalStateException(e);
		}
	}

	public void onFinish(ISuite iSuite) {
	}

	@Override
	public void onTestStart(ITestResult iTestResult) {

	}

	@Override
	public void onTestSuccess(ITestResult iTestResult) {

	}

	@Override
	public void onTestFailure(ITestResult iTestResult) {

	}

	@Override
	public void onTestSkipped(ITestResult iTestResult) {

	}

	public void onTestFailedButWithinSuccessPercentage(ITestResult iTestResult) {

	}

	@Override
	public void onStart(ITestContext iTestContext) {
		ISuite iSuite = iTestContext.getSuite();
		ExtentTest suite = (ExtentTest) iSuite.getAttribute(SUITE_ATTR);
		ExtentTest testContext = suite.createNode(iTestContext.getName());
		iTestContext.setAttribute("testContext", testContext);
	}

	@Override
	public void onFinish(ITestContext iTestContext) {
		ExtentTest testContext = (ExtentTest) iTestContext
				.getAttribute("testContext");
		if (iTestContext.getFailedTests().size() > 0) {
			testContext.fail("Failed");
		} else if (iTestContext.getSkippedTests().size() > 0) {
			testContext.skip("Skipped");
		} else {
			testContext.pass("Passed");
		}
	}

	@Override
	public void beforeInvocation(IInvokedMethod iInvokedMethod,
			ITestResult iTestResult) {
		if (iInvokedMethod.isTestMethod()) {
			ITestContext iTestContext = iTestResult.getTestContext();
			ExtentTest testContext = (ExtentTest) iTestContext
					.getAttribute("testContext");
			ExtentTest test = testContext.createNode(iTestResult.getName());
			iTestResult.setAttribute("test", test);
		}
	}

	@Override
	public void afterInvocation(IInvokedMethod iInvokedMethod,
			ITestResult iTestResult) {
		if (iInvokedMethod.isTestMethod()) {
			ExtentTest test = (ExtentTest) iTestResult.getAttribute("test");
			List<String> logs = Reporter.getOutput(iTestResult);
			
			for (String log : logs) {
				test.info(log);
			}

			int status = iTestResult.getStatus();
			if (ITestResult.SUCCESS == status) {
				test.pass("Passed");
			} else if (ITestResult.FAILURE == status) {
				test.fail(iTestResult.getThrowable());
			} else if (ITestResult.SKIP == status) {
				test.skip(iTestResult.getThrowable());
			} else {
				Reporter.log("Please check the script..!!");
			}

			for (String group : iInvokedMethod.getTestMethod().getGroups()) {
				test.assignCategory(group);
			}
		}
	}

	/**
	 * Adds a screen shot image file to the report. This method should be used
	 * only in the configuration method and the {@link ITestResult} is the
	 * mandatory parameter
	 *
	 * @param iTestResult
	 *            The {@link ITestResult} object
	 * @param filePath
	 *            The image file path
	 * @throws IOException
	 *             {@link IOException}
	 */
	public void addScreenCaptureFromPath(ITestResult iTestResult,
			String filePath) throws IOException {
		ExtentTest test = (ExtentTest) iTestResult.getAttribute("test");
		test.addScreenCaptureFromPath(filePath);
	}

	/**
	 * Adds a screen shot image file to the report. This method should be used
	 * only in the {@link org.testng.annotations.Test} annotated method
	 *
	 * @param filePath
	 *            The image file path
	 * @throws IOException
	 *             {@link IOException}
	 */
	public void addScreenCaptureFromPath(String filePath) throws IOException {
		ITestResult iTestResult = Reporter.getCurrentTestResult();
		Preconditions.checkState(iTestResult != null);
		ExtentTest test = (ExtentTest) iTestResult.getAttribute("test");
		test.addScreenCaptureFromPath(filePath);
	}

	/**
	 * Sets the test runner output
	 *
	 * @param message
	 *            The message to be logged
	 */
	public void setTestRunnerOutput(String message) {
		testRunnerOutput.add(message);
	}

	public void generateReport(List<XmlSuite> list, List<ISuite> list1, String s) {
		if (systemInfo != null) {
			for (Map.Entry<String, String> entry : systemInfo.entrySet()) {
				reporter.setSystemInfo(entry.getKey(), entry.getValue());
			}
		}
		reporter.setTestRunnerOutput(testRunnerOutput);
		reporter.flush();
	}

	/**
	 * Adds the new node to the test. The node name should have been set already
	 * using {@link NodeName}
	 */
	public void addNewNodeToTest() {
		addNewNodeToTest(NodeName.getNodeName());
	}

	/**
	 * Adds the new node to the test with the given node name.
	 *
	 * @param nodeName
	 *            The name of the node to be created
	 */
	public void addNewNodeToTest(String nodeName) {
		addNewNode("test", nodeName);
	}

	/**
	 * Adds a new node to the suite. The node name should have been set already
	 * using {@link NodeName}
	 */
	public void addNewNodeToSuite() {
		addNewNodeToSuite(NodeName.getNodeName());
	}

	/**
	 * Adds a new node to the suite with the given node name
	 *
	 * @param nodeName
	 *            The name of the node to be created
	 */
	public void addNewNodeToSuite(String nodeName) {
		addNewNode(SUITE_ATTR, nodeName);
	}

	private void addNewNode(String parent, String nodeName) {
		ITestResult result = Reporter.getCurrentTestResult();
		Preconditions.checkState(result != null);
		ExtentTest parentNode = (ExtentTest) result.getAttribute(parent);
		ExtentTest childNode = parentNode.createNode(nodeName);
		result.setAttribute(nodeName, childNode);
	}

	/**
	 * Adds a info log message to the node. The node name should have been set
	 * already using {@link NodeName}
	 *
	 * @param logMessage
	 *            The log message string
	 */
	public void addInfoLogToNode(String logMessage) {
		addInfoLogToNode(logMessage, NodeName.getNodeName());
	}

	/**
	 * Adds a info log message to the node
	 * 
	 * @param logMessage
	 *            The log message string
	 * @param nodeName
	 *            The name of the node
	 */
	public void addInfoLogToNode(String logMessage, String nodeName) {
		ITestResult result = Reporter.getCurrentTestResult();
		Preconditions.checkState(result != null);
		ExtentTest test = (ExtentTest) result.getAttribute(nodeName);
		test.info(logMessage);
	}

	/**
	 * Marks the node as failed. The node name should have been set already
	 * using {@link NodeName}
	 *
	 * @param t
	 *            The {@link Throwable} object
	 */
	public void failTheNode(Throwable t) {
		failTheNode(NodeName.getNodeName(), t);
	}

	/**
	 * Marks the given node as failed
	 *
	 * @param nodeName
	 *            The name of the node
	 * @param t
	 *            The {@link Throwable} object
	 */
	public void failTheNode(String nodeName, Throwable t) {
		ITestResult result = Reporter.getCurrentTestResult();
		Preconditions.checkState(result != null);
		ExtentTest test = (ExtentTest) result.getAttribute(nodeName);
		test.fail(t);
	}

	/**
	 * Marks the node as failed. The node name should have been set already
	 * using {@link NodeName}
	 *
	 * @param logMessage
	 *            The message to be logged
	 */
	public void failTheNode(String logMessage) {
		failTheNode(NodeName.getNodeName(), logMessage);
	}

	/**
	 * Marks the given node as failed
	 *
	 * @param nodeName
	 *            The name of the node
	 * @param logMessage
	 *            The message to be logged
	 */
	public void failTheNode(String nodeName, String logMessage) {
		ITestResult result = Reporter.getCurrentTestResult();
		Preconditions.checkState(result != null);
		ExtentTest test = (ExtentTest) result.getAttribute(nodeName);
		test.fail(logMessage);
	}

	/**
	 * Marks the given node as failed
	 *
	 * returns map object with Key & Value pair
	 */
	public static Map<Object, String> getSystemProperties() {

		Properties properties = System.getProperties();

		Set<Object> sysPropertiesKeys = properties.keySet();
		for (Object key : sysPropertiesKeys) {
			map.put(key, properties.getProperty((String) key));
		}

		try {
			ipAddress = InetAddress.getLocalHost().toString();
		} catch (UnknownHostException e) {
			e.printStackTrace();
		}

		map.put("machine.name", ipAddress.split("/")[0]);
		map.put("machine.address", ipAddress.split("/")[1]);

		return map;
	}

	public static String getStackTrace(Throwable t) {
		if (t == null)
			return null;

		StringWriter sw = new StringWriter();
		PrintWriter pw = new PrintWriter(sw);
		t.printStackTrace(pw);
		return sw.toString();
	}

	public static String getExceptionHeadline(Throwable t) {
		Pattern pattern = Pattern.compile("([\\w\\.]+)(:.*)?");
		String stackTrace = getStackTrace(t);
		Matcher matcher = pattern.matcher(stackTrace);

		if (matcher.find())
			return matcher.group(1);

		return null;
	}

	private Date getTime(long millis) {
		Calendar calendar = Calendar.getInstance();
		calendar.setTimeInMillis(millis);
		return calendar.getTime();
	}
}

Sample Program i'm using is:

package com.sample.testcases;

import java.io.IOException;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.SkipException;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import com.reports.listener.ExtentWithTestNGListener;
import com.sample.utilities.ScreenShots;

@Listeners(com.reports.listener.ExtentWithTestNGListener.class)
public class UpgradeProgram1 {

	WebDriver driver;
	String expected = "abc Careers";
	WebDriverWait wait;

	@BeforeClass
	public void setUp() {

		// Chrome Executable
		System.setProperty("webdriver.chrome.driver",
				System.getProperty("user.dir") + "\\Drivers\\chromedriver.exe");

		// Initializing the Driver - InternetExplorerDriver in this case
		driver = new ChromeDriver();

		wait = new WebDriverWait(driver, 3);

	}

	@Test
	public void program1() {

		// Instructing browser to open google
		driver.get("https://www.google.co.in/");

		// Maximizing the driver
		driver.manage().window().maximize();

		// Finding out the webelement to enter search text in search box
		WebElement input = driver
				.findElement(By.xpath("//input[@id='lst-ib']"));
		input.sendKeys("abc Careers");

		// --------- Can also be written as ---------//
		// driver.findElement(By.xpath("//input[@id='lst-ib']")).sendKeys("Mphasis");

		By autocompleteBox = By.xpath("//ul[@role='listbox']");

		// Explicit Wait for autocomplete box.
		wait.until(ExpectedConditions
				.visibilityOfElementLocated(autocompleteBox));

		// Getting all the options available in the auto-complete box.
		List<WebElement> options = driver.findElements(By
				.xpath("//ul[@class='sbsb_b']//div[@class='sbqs_c']"));

		// Iterating through each element & fetching the available text in it.
		// Also we are comparing the text available with our expected text.
		for (WebElement option : options) {
			if (option.getText().equals(expected)) {
				option.click();
				break;
			}
		}

		// Explicit Wait for page title change.
		wait.until(ExpectedConditions.titleContains(expected));

		// Fetching the page title.
		String pageTitle = driver.getTitle();

		// we are comparing the available page title with our expected page
		// title.
		if (pageTitle.contains(expected)) {
			System.out.println("Opened correct Page");
		} else {
			System.out.println("Selected Wrong Option");
		}

		// Assertion using testNG
		Assert.assertTrue(pageTitle.contains(expected), "Selected Wrong Option");

	}

	@Test(expectedExceptions = SkipException.class, groups = "skip")
	public void skipTest() {
		System.out.println("This test is Skipped Intentionally");
		throw new SkipException("Intentionally skipped test.");
	}

	@Test
	public void failTest() {
		Assert.assertFalse(true);
	}

	@Test
	public void trueTest() {
		Assert.assertTrue(true);
	}

	@AfterMethod
	public void tearDownMethod(ITestResult result) {
		if (result.getStatus() == ITestResult.FAILURE) {
			String screenshotPath = ScreenShots.takeScreenshot(driver);
			try {
				ExtentWithTestNGListener.getInstance().addScreenCaptureFromPath(
						result, screenshotPath);
			} catch (IOException e) {
				Reporter.log("Not able to attach Screenshot to file");
			}
		}
	}

	@AfterClass
	public void tearDownClass() { // Quitting the driver.
		driver.quit();
	}

}

Hope You have some time to help me out.
Thanks in advance.

**Comment by anshooarora** [comment]
1. You can hide the 1st and 2nd column via css or javascript, see stackoverflow for a few examples. You can inject either to extent using:

```
// add custom css
htmlreporter.config().setCSS("css-string");

// add custom javascript
htmlreporter.config().setJS("js-string");
```

2. Because it meets the expected condition = SkipException. Remove it and it should show as skipped.

3. Not sure what you mean here

**Comment by anshooarora** [comment]
Closing as no response from OP.  Please feel free to reopen this or create a new ticket if you still have issues.

**Comment by esaiuday01** [comment]
Hi Ansoo,
I need a small help in the seJs("js-string"), if i want to add one more column next to **DETAILS**, can you please give an example or guidance to do it.

Thanks,
Esai.
