### ISSUE TITLE
Full screen view of image does not display - v3.0.1

### ISSUE THREAD

**Issue by rab2215** [anshooarora/extentreports-java#733]
When clicking an image thumbnail to show the full screen view of the image, the modal just shows scrambled text.  I am using a base64 image in this example.
![screen shot 2017-01-06 at 10 57 50 am](https://cloud.githubusercontent.com/assets/6473132/21725665/100306a8-d3ff-11e6-8029-740baaaaef5a.png)
![screen shot 2017-01-06 at 10 47 11 am](https://cloud.githubusercontent.com/assets/6473132/21725395/e039f054-d3fd-11e6-901e-552086d207df.png)

**Comment by anshooarora** [comment]
duplicate #715
