### ISSUE TITLE
Add browser name & version against testmethod in report 

### ISSUE THREAD

**Issue by rahulr892** [anshooarora/extentreports-java#735]
I am performing cross browser testing of an application and each of my test method runs on 4 browsers.
I can add the first log step as browser name but I need to append browser name and version against the test method itself without going to each method.

Can you help ?
Please

**Comment by anshooarora** [comment]
Depending upon your test runner, you can pass this information to your test methods and use `assignCategory` to call out the browser name.

Version 2: http://extentreports.relevantcodes.com/java/#assign-category
Version 3:  http://extentreports.com/docs/versions/3/java/#assign-category
