### ISSUE TITLE
Assign Category method not honoring spaces like in v2.41

### ISSUE THREAD

**Issue by mlopezjr** [anshooarora/extentreports-java#736]
If I have code like getExtentTest().assignCategory("Signs User"), the "Signs User" string now appears as "SignsUser" in the report.

**Comment by anshooarora** [comment]
Your version?

**Comment by mlopezjr** [comment]
3.0.1

**Comment by anshooarora** [comment]
This is by design to allow quick and easy search of tags.  I can mark this as an enhancement to main the format.

**Comment by mlopezjr** [comment]
Ahh thanks.  Just assumed since it behaved differently from 2.x version that it was a bug.  Will advise the management team here that views the automation reports.  Thanks!
