### ISSUE TITLE
[Enhancement] Add and display test data in the report

### ISSUE THREAD

**Issue by pete2121** [anshooarora/extentreports-java#738]
Hi Anshoo, 

I would like to create a different (new) page to the report in order to log there my test-data.
Currently, I have by default the dashboard and tests pages. However, I want to create a new page in the report (with the same style etc) in order to store there my test data.  Please bear in mind that I don't mind if I don't have an icon in order to navigate to this page, I can do it by hyperlink too. 

![1](https://cloud.githubusercontent.com/assets/17945344/21927006/fff728f0-d98c-11e6-810c-bb2268edff0f.jpg)

I want the above hyperlink to navigate me to an internal new page of ExtentReport.
In this page I will use the "log(LogStatus.INFO,.." in order to log my test-data 

Thank you
Petros

**Comment by anshooarora** [comment]
Hi Petros, nice idea.  How would you like to display this data?  Would this format work:

```
Test1
Field1 | Field2
data1  | data2
data3  | data4

Test2
Field1 | Field2
data1  | data2
data3  | data4
```

**Comment by savvyaxnjxn** [comment]
This is a really great idea @pete2121! Currently I use nested nodes to try and roll-up large suites (with some large printed statements) but breaking them out into their own sub-extentReport pages would really help with readability and drill-down when trying to dig out reported problems.  I'm interested in your ideas on display as well; are you thinking of displaying a completely new page/report complete with its own dashboard and filters?  Or a more static page with just expanded info on the executed step?

**Comment by pete2121** [comment]
Hello anshooarora ,
yes this format would be OK for me. Do you have any idea?

Hello,  savvyaxnjxn 
I guess the second one for the start, with info for the test. Dashboard right now is not needed. Test data are belong to the fundamental test process and i think somehow should be displayed.

**Comment by anshooarora** [comment]
Having a separate page may make it a little cumbersome to go back and forth.  Having this information at the test level will probably be easier to use.

The only question is:  How to pass this data, and how to tie the data with the corresponding result row?

**Comment by pete2121** [comment]
I can pass the data. I don't think that this is a problem. However, I think it will be not nice to display the data as "information". I think they should be displayed in table format as you showed me in the above post. The separate page maybe is not a good idea but what about an expandable page? I mean when you click the hyperlink an expandable page will be show up. User can minimize this page. 
So I think we need three things:
a) A new icon for test data
b) An easy way for user to add a table 
c) A expandable section that will be show up when we click the hyperlink

**Comment by anshooarora** [comment]
a. will add an icon
b. table can be added as:

```
String[][] data -> 2d array
List<String[]> data -> list of rows
```

c. table will be added to an accordion/toggle

**Comment by pete2121** [comment]
Hello Anshoo,

Where I have to enter this code about table? I guess not in the class that I have failed,succeeded
Thank you in advance!

**Comment by email2vimalraj** [comment]
@pete2121 : You could do this way:

```java
String[][] data = new String[2][2];
data[0][0] = "Field 1";
data[0][1] = "Field 2";
data[1][0] = "data1";
data[1][1] = "data2";

Markup m = MarkupHelper.createTable(data);
test.info(m);
```

The above will add the table within the test node. This feature was added as part of #581 . Hope this solves your problem.

Please note that you should upgrade to the latest version of ExtentReport. Kindly re-open in case you need further help.

**Comment by seeramzan** [comment]
@email2vimalraj  Could you please guide how to pass data provider in below scenario

I have a class for data provider
public class dataProvider {


```
    @DataProvider(name = "testData")
    public  Object[][] testData(Method method) throws IOException {
--logic

return testData
}
```


In testng before invocation i am setting this testdata to my test methods. Now i don't know where i can pass this to extent report so it could show there.

**Comment by harsh976** [comment]
There are many ways.I am printing my data in extent report.
