### ISSUE TITLE
Is there any way to add metadata at the level of reports and save them in database mongo. | ExtentReports.

### ISSUE THREAD

**Issue by ndof** [anshooarora/extentreports-java#741]
I want to add some metadata along with reports detail in mongo. I will use that data directly from mongo . I have seen there is  logging feature but that is a on log level . If I am able to add at report level , my purpose will be served efficiently. How can i solve this ?

**Comment by anshooarora** [comment]
What data and to which collection?

**Comment by ndof** [comment]
I am using extentReport in my Automation Suite which will be triggered by jenkins job. I want to save its build no and some other data in report collection . 
I will latter on use that build no to fetch data of other plugins like jacocco code coverage etc.

**Comment by anshooarora** [comment]
You will have to create a separate impl to do this, but there is currently no way to do this from the report.  This ability will not be available either to keep the db clean from Extent's perspective but users can do this easily.
