### ISSUE TITLE
On Click on Image,its not displaying anything in firefox 46.0

### ISSUE THREAD

**Issue by Praveen431** [anshooarora/extentreports-java#742]
Hi Anshoo,

In my extent report,i am able to view the image in a small size,when i click on the zoom button,then its not displaying any thing only in firefox.And if i open the same html report in chrome then its displaying.Could you please help me on this issue..

![image with dom](https://cloud.githubusercontent.com/assets/13419234/22062083/fd5d788c-dd9d-11e6-87c8-f788dfc5f1df.png)
![image with zoom](https://cloud.githubusercontent.com/assets/13419234/22062084/fd65ba74-dd9d-11e6-8c93-a2b62b732435.png)

**Comment by anshooarora** [comment]
It could be a version issue.  I generally use Firefox on different OS to build this reporting and I have not been able to reproduce on any.  Can you upgrade your current version and try again, or try on another system once?  Feel free to open this or create a new ticket if issue persists.
