### ISSUE TITLE
How can extent reports be integrated in jenkins?

### ISSUE THREAD

**Issue by seema-realforce** [anshooarora/extentreports-java#743]

**Comment by anshooarora** [comment]
See here:

https://github.com/anshooarora/extentreports-java/issues/290

There isn't much to do here really. Simply use the reporting as you would and the HTML publisher plugin to do the rest.

**Comment by seema-realforce** [comment]
I had other issue publishing extent report through jenkins.
' HTML directory to archive' option works when i provide the absolute path. ie D:/Automation/Workspace/myproject/target/surefire-reports/
and it gives error when i specify a relative path (target\surefire-reports or **\target\surefire-reports)
 Specified HTML directory 'C:\Users\QA\.jenkins\workspace\myproject\target\surefire-reports' does not exist.
Build step 'Publish HTML reports' changed build result to FAILURE

I am using pom.xml to invoke the script and not custom workspace
