### ISSUE TITLE
test cases ordering in html report

### ISSUE THREAD

**Issue by mauropota** [anshooarora/extentreports-java#747]
Hi,
 is it possible to order test cases shown in html reports from the last excecuted (on the top of the list) to first executed (at the bottom of the list).
If yes, how to configure test cases ordering?

**Comment by anshooarora** [comment]
Currently, no..  The previous version had this capability by specifying the `DisplayOrder`.  

Will add this as an enhancement for this version also.

**Comment by mauropota** [comment]
thank you!

**Comment by rahulr892** [comment]
I am doing it this way for the time being...
Assign category to a test case in a test class file with test class name

Control_Policy is my test class name

public void Create_Data(Hashtable<String, String> data) throws Exception {
		String testname = "Create_Data";
		ExtentTestManager.startTest(testname + " - " + TestUtils.getTestData(data, "Browser"), "Create Data").assignCategory("Control_Policy");

There you may see some kind of ordering and might help you

**Comment by email2vimalraj** [comment]
@anshooarora : I believe this feature is part of pro only. Can you please confirm and close this if not supported in community edition.
