### ISSUE TITLE
How can I change my home page (test view page) turn to dashboard page?﻿

### ISSUE THREAD

**Issue by rogerfdeazevedo** [anshooarora/extentreports-java#748]
I need change report home page to dashboard view page.
Default page:
![p_37](https://cloud.githubusercontent.com/assets/5633177/22117619/d3eebe70-de5b-11e6-8f93-a2204aeef65e.png)

Dashboard page:
![p_38](https://cloud.githubusercontent.com/assets/5633177/22117626/d8417f4e-de5b-11e6-863f-32b963a68d59.png)

Tks,

**Comment by anshooarora** [comment]
Add this to your configuration js:

```
$('a.dashboard-view').click();
```

**Comment by rogerfdeazevedo** [comment]
Its work!
Thanks Ansho!
