### ISSUE TITLE
In version 3.0.1, charts not diplayed for values greater that 999

### ISSUE THREAD

**Issue by mauropota** [anshooarora/extentreports-java#749]
Hi,
 when values to plot are greater that 999 (for example when more that 999 tests are listed), charts are not generated (the one that refers to tests and the one that refers to test steps) and the following errors are thrown:

1) Uncaught SyntaxError: Unexpected token ,
2) Uncaught ReferenceError: statusGroup is not defined
    at drawParentChart (extent.js:456)
    at extent.js:467 

The unexpected token , refers to the following line of code in the html file:
infoChild: 1,628,
This line is part of the following set of instructions:
var statusGroup = {

				passParent: 51,
				failParent: 0,
				fatalParent: 0,
				errorParent: 20,
				warningParent: 0,
				skipParent: 0,
				exceptionsParent: 20,
				
				passChild: 0,
				failChild: 0,
				fatalChild: 0,
				errorChild: 20,
				warningChild: 0,
				skipChild: 0,
			        infoChild: 1,278,
				exceptionsChild: 20,
				
				passGrandChild: 0,
				failGrandChild: 0,
				fatalGrandChild: 0,
				errorGrandChild: 0,
				warningGrandChild: 0,
				skipGrandChild: 0,
				infoGrandChild: 0,
				exceptionsGrandChild: 0,
};

</script>

The Uncaught ReferenceError: statusGroup refers to the file extent.js

**Comment by anshooarora** [comment]
The template engine (freemarker in this case) converts this number when its written to the file.  Marked this as a bug.
