### ISSUE TITLE
SCREEN_SHOT NOT LOADING ON EXTENT REPORT 2.0

### ISSUE THREAD

**Issue by Ajmalkhan1805** [anshooarora/extentreports-java#750]
Hi Anshu, i am trying to use Extent report 2.0 with TestNG in my current project. When test fails, captured screenSHots are not loaded(invisible) properly, rather it givs me the Path of the screen shot.. Kindly, help us to resolve this issue.
![screenshot- domain - date - time](https://cloud.githubusercontent.com/assets/25317214/22238350/e9d273b0-e236-11e6-92d5-47eb640e8025.png)

**Comment by email2vimalraj** [comment]
@Ajmalkhan1805 : You should use `addScreenCapture` method to attach a screenshot. I believe you were just logging the path of the screenshot. Refer more [here](http://extentreports.com/docs/versions/3/java/#insert-screenshots).

Also, update to the latest version if possible.

Going forward, kindly add some sample code for us to reproduce in case of any issues.

Kindly re-open in case you need further help.
