### ISSUE TITLE
How to handle extent report instance in page factory class

### ISSUE THREAD

**Issue by seema-realforce** [anshooarora/extentreports-java#751]
I have a pagefactory framework to handle test and webpages. Currently i have extent report configured for tests and all the loggin is in @test methods. I want to pass this instance to wepages class and log the steps. How can this be done?

public class maintest(){
ExtentReports extent;
	ExtentTest test;
	@BeforeTest
	public void startreport(){
		//extent=new ExtentReports (System.getProperty("user.dir")+"/target/surefire-reports/Extentreport.html");
		extent= utils.ExtentManager.instance();
	}
 @Test(groups = "login")

		public void login(){
	  		test=extent.startTest("login");
			 Login LoginPage = PageFactory.initElements(driver, Login.class);
                          LoginPage.LogInaction(LoginEmail,Password);
			 test.log(LogStatus.INFO, "Login page : Login with username and password");
                         test.log(LogStatus.PASS, "Login successful");
}

@AfterMethod
public void teardown(ITestResult result) throws IOException{
	if(result.getStatus()==ITestResult.FAILURE){

		String screenshot_path=BrowserFactory.captureScreenshot(driver, result.getName());
		String image= test.addScreenCapture(screenshot_path);
		test.log(LogStatus.FAIL, result.getThrowable());
		test.log(LogStatus.FAIL, "Screenshot Below: ", image);
	}
	
		extent.endTest(test);
}
@AfterTest
public void endreport(){

	extent.flush();
	extent.close();
}

Now how can i use extent report test instance inside the login class to log reporting?

**Comment by JoseCanavire** [comment]
@seema-realforce you can look for the implementation done for tests in parallel, where they presented a way to store loggers in a map that has the thread id as key, and the logger as value. So you can get the logger that has been used in the previous steps(same thread id).

**Comment by seema-realforce** [comment]
Well, i looked at example for parallel methods under http://extentreports.relevantcodes.com/java/#parallel-methods, but with ExtentTestManager  class, i am seeing error 'Type mismatch: cannot convert from Object to ExtentTest' for  return extentTestMap.get((int) (long) (Thread.currentThread().getId()));

and error 'The method endTest(ExtentTest) in the type ExtentReports is not applicable for the arguments (Object)' for extent.endTest(extentTestMap.get((int) (long) (Thread.currentThread().getId())));

I dont think i need to type cast here as this could be proven example and not sure what i am doing wrong in above code. 

Also when you say i can use the logger, how can i pass it to my pagefactory classes?



public class ExtentTestManager {
	  static Map extentTestMap = new HashMap();
	    private static ExtentReports extent = ExtentManager.getReporter();

	    public static synchronized ExtentTest getTest() {
	   
	        return extentTestMap.get((int) (long) (Thread.currentThread().getId()));
	    }

	    public static synchronized void endTest() {
	        extent.endTest(extentTestMap.get((int) (long) (Thread.currentThread().getId())));
	    }

	    public static synchronized ExtentTest startTest(String testName) {
	        return startTest(testName, "");
	    }

	    public static synchronized ExtentTest startTest(String testName, String desc) {
	        ExtentTest test = extent.startTest(testName, desc);
	        extentTestMap.put((int) (long) (Thread.currentThread().getId()), test);

	        return test;
	    }

**Comment by JoseCanavire** [comment]
whenever you call 
```java
ExtentTestManager.getTest()
```
you will get the logger it is a public static method. And you still need to start and stop the ExtentTest objects that will be in that map. 
So logger will start in a @BeforeMethod adding an ExtentTest value to the map, and in every page object you use while being in the same thread, the get method will find the extent test created. 
 Once done you need to flush that object in an @AfterMethod and so on.
By the way I am talking about versions 2.x maybe this won't work for the newest versions of the tool.

**Comment by seema-realforce** [comment]
I can implement that, but do you know the solution for the error i had mentioned above for 
 ExtentTestManager class, i am seeing error 'Type mismatch: cannot convert from Object to ExtentTest' for return extentTestMap.get((int) (long) (Thread.currentThread().getId()));

and error 'The method endTest(ExtentTest) in the type ExtentReports is not applicable for the arguments (Object)' for extent.endTest(extentTestMap.get((int) (long) (Thread.currentThread().getId())));

**Comment by suvendu2016** [comment]
Change this line : static Map extentTestMap = new HashMap();
like : static Map<Integer, ExtentTest> extentTestMap = new HashMap<Integer, ExtentTest>();

**Comment by seema-realforce** [comment]
Appreciate your answer. I have tried implementing it the way you have mentioned, but even with static ExtentTest test, i could not access test in other class using test.getTest(). As i am new to this, it would be helpful if you elaborate on how it can be done. I have included the code,  i am currently trying to get a  report on.
  
public class myclass{
	static	ExtentReports extent;
	static ExtentTest test;

 @BeforeSuite
	    public void beforeSuite() {
	        extent = ExtentManager.getReporter(System.getProperty("user.dir")+"/target/surefire-reports/Extentreport.html");
	    }

	   @Test(groups = "login")
	   public void test1(){
		   test = ExtentTestManager.startTest(Thread.currentThread().getStackTrace()[1].getMethodName());
	       test.log(LogStatus.INFO, "Log from threadId: " + Thread.currentThread().getId());
		   }

	   @Test(dependsOnGroups = "login")
	   public void test2(){
		   test = ExtentTestManager.startTest(Thread.currentThread().getStackTrace()[1].getMethodName());
	       test.log(LogStatus.INFO, "Log from threadId: " + Thread.currentThread().getId());
	
	       Login LoginPage = PageFactory.initElements(driver, Login.class);
			 Welcome WelcomePage = PageFactory.initElements(driver, Welcome.class);
			 
			 
			 LoginPage.LogInaction("wrong","wrong");
			 WelcomePage.validateloginemail("wrongdata");
	   }

@AfterMethod
	public void afterEachTest(ITestResult result) throws IOException {
	
	if (result.isSuccess()) {
		ExtentTestManager.getTest().log(LogStatus.PASS, "Test passed");
	}
	else if (result.getStatus() == ITestResult.FAILURE) {
		ExtentTestManager.getTest().log(LogStatus.FAIL, "Test failed");
	
		String screenshot_path=BrowserFactory.captureScreenshot(driver, result.getName());
		String image= test.addScreenCapture(screenshot_path);
		test.log(LogStatus.FAIL, result.getThrowable());
		test.log(LogStatus.FAIL, "Screenshot Below: ", image);
	}
	else if (result.getStatus() == ITestResult.SKIP) {
		ExtentTestManager.getTest().log(LogStatus.SKIP, "Test skipped");
	}
	
	ExtentTestManager.endTest();
	ExtentManager.getReporter(System.getProperty("user.dir")+"/target/surefire-reports/Extentreport.html").flush();
}

  @AfterClass
  public void afterClass() {
	  extent.close();
	  driver.close();

**Comment by seema-realforce** [comment]
Its working now with above implementation. Appreciate your effort. 

I have one more question regarding logging. Is there a way where i can pass the function name under which the log statement is placed? Also i dont see the stepname being logged using the syntax ExtentTestManager.getTest().log(logStatus, stepName, details);

I get only 3 columns, status, timestamp and details.

Also how does this work when parallel tests are run?
test = ExtentTestManager.startTest(Thread.currentThread().getStackTrace()[1].getMethodName());
		test.log(LogStatus.INFO, "Log from threadId: " + Thread.currentThread().getId());
Will show me thread 2 under logs for parallel method?

**Comment by suvendu2016** [comment]
Create one Testnglistener class where u can call these static methods(startTest,getTest,endTest) in the respective overridden listener methods. 

public class Listeners extends TestListenerAdapter {
	WebDriver driver;
	
	@Override
	public void onTestStart(ITestResult tr) {
		ExtentTestManager.startTest(tr.getName());
		ExtentManager.getReporter().loadConfig(new File(System.getProperty("user.dir") + File.separator + "src"
				+ File.separator + "ConfigFiles" + File.separator + "ExtentReportConfig.xml"));

	}

	@Override
	public void onTestSuccess(ITestResult tr) {
		ExtentTestManager.getTest().log(LogStatus.PASS, "Test " + tr.getName() + " passed");
	}

	@Override
	public void onTestFailure(ITestResult tr) {
		File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
			String directoryPath = System.getProperty("user.dir") + File.separator;
			String imageName = tr.getName() + "failureScreenShot_at_" + DateUtils.getTimestampforImage() + ".png";

			String imagePath = "AutomationReports" + File.separator + "LatestResults" + File.separator + "ScreenShots"
					+ File.separator + imageName;
			FileUtils.copyFile(scrFile, new File(directoryPath + imagePath));

			// set failure screenshot to Extent reports
			ExtentTestManager.getTest().log(LogStatus.FAIL, "Test " + tr.getName() + " Failed");
			ExtentTestManager.getTest().log(LogStatus.FAIL, tr.getThrowable());
			ExtentTestManager.getTest().log(LogStatus.INFO,ExtentTestManager.getTest().addScreenCapture("..\\ScreenShots\\" + imageName));

	}

	@Override
	public void onTestSkipped(ITestResult tr) {
		ExtentTestManager.getTest().log(LogStatus.SKIP, "Test " + tr.getName() + " skipped");
	}

	@Override
	public void onFinish(ITestContext context) {

		ExtentManager.getReporter().endTest(ExtentTestManager.getTest());
		ExtentManager.getReporter().flush();

	}
}

Add this Listener class to Ur Base class as @Listener or add this to TestNG xml file using listener tag

**Comment by seema-realforce** [comment]
I will be using this as listener, but can you provide me getTimestampforImage() function under your dateutils. Also "tr" refered in String imageName = tr.getName() + "failureScreenShot_at_" + DateUtils.getTimestampforImage() + ".png"; is result right?

**Comment by suvendu2016** [comment]
@seema-realforce give me ur mail id.

**Comment by seema-realforce** [comment]
new076@gmail.com

**Comment by email2vimalraj** [comment]
@seema-realforce : Hope you were able to go ahead with the help provided by other members.

Kindly re-open in case you have any issues with the Extent Report's implementation.
