### ISSUE TITLE
Unable to view the extent report screenshot from other system

### ISSUE THREAD

**Issue by ashokkumarg** [anshooarora/extentreports-java#753]
I have used the following code to capture the screenshot and it is perfectly working but when I want to send the report to some other person. 
They are not able view the screenshot. How it could be achieved any sample code?

**CODE:**
`logger.log(LogStatus.FAIL, "Image", message + img);`

**In my system:**

![in_my_system](https://cloud.githubusercontent.com/assets/7566850/22279062/370d68a8-e2ee-11e6-9b4d-04a322ac9e1f.JPG)

**In others system:**
![in_others_system](https://cloud.githubusercontent.com/assets/7566850/22279129/a3ec4200-e2ee-11e6-84cf-32afc4808913.jpg)

**Comment by anshooarora** [comment]
If you are using a path that is inaccessible from other machines, this will naturally happen.  Use a shared path for the report + screenshots and it will work for all devices connected to that drive.
