### ISSUE TITLE
Fail is displayed as Pass in report v 3.0.1

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports-java#757]
@anshooarora when we have test failure, the report is showing as pass in the dashboard. Pls find the screenshot attached.

![screen shot 2017-01-31 at 6 41 07 pm](https://cloud.githubusercontent.com/assets/4045041/22466153/f8b98496-e7e4-11e6-9d3e-d11abfd201e1.png)

**Comment by anshooarora** [comment]
Can you provide steps to repro?  I am unable to see this behavior..

**Comment by saikrishna321** [comment]
@anshooarora pls find the repo which reproduces the issue

https://github.com/saikrishna321/extent_reports

command to run: mvn clean -Dtest=Runner test 

you will find the report in target folder

**Comment by anshooarora** [comment]
Thank you. I will get back to you shortly.

**Comment by anshooarora** [comment]
There was a fix for this a few days ago impacting another part of functionality, which seems to have fixed it.   See below:

![cat](https://cloud.githubusercontent.com/assets/4107384/22483744/80535eb8-e7cc-11e6-9901-c6d422c75020.png)

I will release this in 3.0.2 very soon.

**Comment by anshooarora** [comment]
Same as #710.  Version 3.0.2 is now out.  Please check once and and let me know if this issue is fixed?

**Comment by saikrishna321** [comment]
@anshooarora i tried with the sample provided, it works. But within the AppiumTestDistribution its still the same.Can you pls help on this

Note: report header on the right top corner shows 3.0.1

**Comment by anshooarora** [comment]
Will it be possible to create a small sample to repro the behavior of your Appium framework?  It will be hard for me to debug otherwise.. 

> Note: report header on the right top corner shows 3.0.1
Delete the local maven artifact for extentreports (.m2/com/aventstack/extentreports) dependancy on your system and let pom.xml download the new artifacts.  It should be fixed.

**Comment by saikrishna321** [comment]
@anshooarora let me try creating one and update you.

**Comment by anshooarora** [comment]
@saikrishna321 - there was another fix in #777 which would have fixed the other case from the CategoryView.  Marking this as closed. 

[release info](http://extentreports.com/2017/03/06/extentreports-java-community-version-3-0-3-released/)

**Comment by saikrishna321** [comment]
@anshooarora thanks for the fix, will test and revert back
