### ISSUE TITLE
Unable to get Cucumber Scenarios result in latest version 2.41.2

### ISSUE THREAD

**Issue by akm1967** [anshooarora/extentreports-java#761]
1) I saw your report of Version 1.0.0 which was pretty good for Cucumber Scenario result reporting. But I was unable to add screenshots and fail/pass step level details. So decided to go for Extent version 2.41.2.
2) In Extent 2.41.2 I was able to add pass/fail comments log status and link screenshots. Which is good but I want scenario report similar to version 1.0.0.
Kindly help.

**Comment by anshooarora** [comment]
Please check with @email2vimalraj here:  https://github.com/email2vimalraj/CucumberExtentReporter
