### ISSUE TITLE
With screenshot comment are not printed on report of extent 2.41.2

### ISSUE THREAD

**Issue by akm1967** [anshooarora/extentreports-java#762]
Issue: If screenshots are linked then text messages are not shown in the Extent report 2.41.2.
Kindly help.

**Comment by anshooarora** [comment]
With text, do you mean the stepName or the details text?  Can you share a sample?

**Comment by email2vimalraj** [comment]
@akm1967 : This issue is closed now since we haven't heard back from you. Kindly re-open in case you need further help.

**Comment by akm1967** [comment]
My issue was similar to https://github.com/anshooarora/extentreports-java/issues/451.
Instead of Label if we can add text next to image will be very handy for testers.
e.g "Image Icon" - "Text Message why test failed or passed for test"
