### ISSUE TITLE
How to end test for parent and child node in V 3.0.2

### ISSUE THREAD

**Issue by Vishnu1067** [anshooarora/extentreports-java#765]
Hi @anshooarora ,

I upgraded extent reports from V 2.41.1  to V 3.0.2 and i found that i cannot end the child node for each test and parent node for after class.

**Expected report:** With parent and child node with 

`ExtentManagergetInstance().endTest(parent);
  ExtentManager.getInstance().flush();`

  
<img width="1382" alt="screen shot 2017-02-07 at 9 30 59 am" src="https://cloud.githubusercontent.com/assets/13374564/22675604/4bc3b72c-ed19-11e6-84d3-62313badabd4.png">

**Actual report:**

<img width="1370" alt="screen shot 2017-02-07 at 9 31 27 am" src="https://cloud.githubusercontent.com/assets/13374564/22675616/574f5aec-ed19-11e6-8107-31ed872e43f3.png">

**Comment by anshooarora** [comment]
`endTest` is not required in version 3.  Each time you log, endTest is called internally so you always have the most up-to-date status of each test.  Also, because of this, the report can be updated after each log instead of the entire test completion.

**Comment by Vishnu1067** [comment]
If i understand correctly, for each end of `@Test`, endTest is called internally right? If so, we may get reports with each function wise separation. But report is not separated with test. In V 2.41.1 it is showing as per below screenshot.

![pasted image at 2017_02_08 10_33 am](https://cloud.githubusercontent.com/assets/13374564/22722571/b7d4489c-edea-11e6-95f5-37f2c0bc202c.png)
