### ISSUE TITLE
Can we filter test results based on the run or date/time in 2.41.2

### ISSUE THREAD

**Issue by Ratna33** [anshooarora/extentreports-java#767]
I have a script that runs daily and creates a single extent report showing the complete list of tests and their status till date. Is it possible to show the results of every run, i.e. filter results based on say current run, or last 2 runs etc or show date/time filter?

Thanks

**Comment by anshooarora** [comment]
You need to setup ExtentX for this:  http://extentreports.com/docs/extentx/.  It allows historical views of runs/tests.
