### ISSUE TITLE
How to remove "ExtentReports" link text from extent report

### ISSUE THREAD

**Issue by moinakd** [anshooarora/extentreports-java#771]
![issue](https://cloud.githubusercontent.com/assets/22813698/22962732/de23e3ce-f374-11e6-9042-4f6328a61894.png)

**Comment by moinakd** [comment]
How to remove that "Red circled" section in extent reports 2.41.2 jar

**Comment by suranjith87** [comment]
Yes.. its needful.........

**Comment by anshooarora** [comment]
You can use JavaScript or CSS to achieve this..

**Comment by moinakdutta** [comment]
Thank you anshoo.
$(document).ready(function() 
        {
        	$('.logo-container.blue.darken-2').css('display','none');
        });
this code working for my report. I think this will help others as well.
