### ISSUE TITLE
Getting null pointer exception on using extent report on MacOSX

### ISSUE THREAD

**Issue by munnamathew** [anshooarora/extentreports-java#773]
Hi,

I am using extent report for my selenium project to perform automation testing in Mac OS X. I am using community edition  of Extent Report(ver 2.41.2). I 
![screen shot 2017-02-16 at 2 58 02 pm](https://cloud.githubusercontent.com/assets/25816031/23015458/ea4631c2-f458-11e6-9dd1-5f56993c718d.png)
wanted to confirm whether Extent report is supported in Mac OS.

I have implemented the same in Mac OS and I am getting null pointer exception in startTest function itself. Please let me know whether you need more details on the same. I have attached the screenshot of the error message.

Regards,
Munna Mathew.

**Comment by anshooarora** [comment]
Yes, it is supported.  Your stacktrace does not mention `com.relevantcodes` or `com.aventstack` depending upon your version,  this isn't raised by ExtentReports.
