### ISSUE TITLE
Jenkins var statusGroup

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [anshooarora/extentreports-java#774]
Jenkins does not like the declaration of the statusGroup var in the body. I dont know all the scope of this variable. However it could be included in the extent.js file.

**Comment by anshooarora** [comment]
It can be changed to a different name, but the group must be available in the body for the script to pick these values on load.

Source: https://github.com/anshooarora/extentreports-java/blob/5e6b803173eedf915a49fcb81c21b18cbb6fbc44/src/main/resources/com/aventstack/extentreports/view/html-report/index.ftl#L53

**Comment by yael-lorenzo-olx** [comment]
I didnt mean about the name. Im sorry, I didnt explain so well. Jenkins does not like the inline scripts like <script var statusGroup = .../> only source code scripts.

**Comment by anshooarora** [comment]
This `<script>` block is present to enable passing of overall status values to the resource javascript.  Without this, the charts and aggregates will not function.  We can get rid of this block if there is another way to pass these values to the resource files.  Also, there must be a way to circumvent this security policy of Jenkins,  but I don't use it so not sure how this would be achieved..

**Comment by email2vimalraj** [comment]
@yael-lorenzo-olx : The script tag is mandatory for the report to work properly with the charts and other DOM manipulations. So kindly reach out to your Jenkins administrator to resolve this issue from the jenkins setup. Closing this issue, kindly feel free to re-open in case you need any help.
