### ISSUE TITLE
Test.log(..) replaces the existing report info

### ISSUE THREAD

**Issue by gvarun112** [anshooarora/extentreports-java#776]
Hey @anshooarora , I have 2 tests in my Java file. I use the Page Object Model and when I run the test, I only see the report about my 2nd test method. But, I see that my 1st Test runs as well. 

I have the startTest(..) in my TestNG BeforeMethod. Am I doing something wrong here?

**Comment by anshooarora** [comment]
You are probably creating a new instance of ExtentReports in `@BeforeClass` or elsewhere which is overwriting your report.  Create and use only a single instance and this issue will go away.

**Comment by gvarun112** [comment]
I actually don't. This is the structure:

xyz.java:


```
@BeforeMethod
setup(); //calling from abc.java

@Test(priority = 0)
test = extent.startTest("test 1");
//This doesn't come in the report
someMethod(); //calling from abc.java

@Test(priority = 1)
test = extent.startTest("test 2");
//This comes in the report
someMethod(); //calling from abc.java

@AfterMethod
extent.endTest(test);

@AfterTest
extent.flush();

```

abc.java:

```
setup() {
extent = new extentreports(path, replace);
extent.loadconfig(path);
test = extent.startTest("setup");
}

someMethod() {
test.log();
}
```
