### ISSUE TITLE
Category Run Details not shown on Dashboard

### ISSUE THREAD

**Issue by vicvinod** [anshooarora/extentreports-java#779]
@anshooarora  I used the same code mentioned by you in some of the post
Categories name shown but Pass fail count Details is not shown in the PAge in Dashboard
![image](https://cloud.githubusercontent.com/assets/19703631/23178767/a12d4c04-f891-11e6-8bdf-f11f23807f85.png)

**Comment by anshooarora** [comment]
This feature is available in version 3 onwards.  You need to upgrade soon :)
