### ISSUE TITLE
Time Taken for all  the test are showing in ms,How to convert to minutes .

### ISSUE THREAD

**Issue by suhasgatty** [anshooarora/extentreports-java#781]
<img width="1075" alt="screen shot 2017-02-22 at 10 44 09 pm" src="https://cloud.githubusercontent.com/assets/4695343/23248302/aba0b70a-f9c4-11e6-80b4-7533987c1a20.png">

Im using the extent report jar of 3.0.0

**Comment by anshooarora** [comment]
You can change [this](https://github.com/anshooarora/extentreports-java/blob/master/src/main/resources/com/aventstack/extentreports/view/html-report/dashboard-view/dashboard-view.ftl#L41) to your desired units and rebuild jar.
