### ISSUE TITLE
Removal of the "i" symbol from the extent reports

### ISSUE THREAD

**Issue by uddhavnaik** [anshooarora/extentreports-java#782]
hello,
i have implemented extent reports for my automation suite but there is a small issue. i want the "i" symbol to be removed somehow. the endTest() method lies in my AfterSuite annotation. i have attached an image of the symbol for your reference. kindly help me with my request :)

Thanks!
![s1](https://cloud.githubusercontent.com/assets/19701835/23301588/a7cafc2a-fab0-11e6-9dcc-48806364ff9c.png)

**Comment by anshooarora** [comment]
You can hide this element using css.  Also, it will disappear if you are ending tests correctly.
