### ISSUE TITLE
Send extent report as inline in email body from jenkins

### ISSUE THREAD

**Issue by rahulr892** [anshooarora/extentreports-java#787]
Hi Anshoo,

thanks for the extent reports....

I am sending extent reports html file after build via email ext plugin in Jenkins as inline in email body
But the css is breaking.
But it works for default TestNG html report.
![extentcss](https://cloud.githubusercontent.com/assets/23073006/23547727/4e2da4d6-002a-11e7-80d1-00d405fbf46b.JPG)

I am using extent reports version v2.41.1
Jenkins is 2.32.2
email ext plugin is 2.57

**Comment by email2vimalraj** [comment]
Ideally you should be using the Emailable report that is been introduced from 3.x version (pro only) for this.

@anshooarora Correct me if I'm wrong.

**Comment by anshooarora** [comment]
@email2vimalraj -  that's correct.  The standard HTML report has external resources, inline javascript which will be prevented by most (if not all) email clients so not recommended to send it over email.

**Comment by tanumuki** [comment]
How do i use this extent report? can someone help me with the extentReporterNG interface java file?

**Comment by tanumuki** [comment]
Is there a way we can embed this in the mail body? right now gmail is blocking the  css

**Comment by manivannanpannerselvam** [comment]
rahul- did u get the extent report solution
