### ISSUE TITLE
how to get logs in report using listener

### ISSUE THREAD

**Issue by mohd19nazim** [anshooarora/extentreports-java#788]
hi 
i am able to generate a report using listener for extent  report which uses ireporter. But, I am not been able to get logs in the report kindly help 

its my code for the listener

@Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        
    	extent = new ExtentReports(new File("extentreport").getAbsolutePath() + "/"+ "index.html", true);
        
       
        
        
        extent.loadConfig(new File(new File("config").getAbsolutePath() + "/" + "config.xml"));  
        
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults();
 
            for (ISuiteResult r : result.values()) {
                 
            	ITestContext context = r.getTestContext();
 
                buildTestNodes(context.getPassedTests(), LogStatus.PASS);
                buildTestNodes(context.getFailedTests(), LogStatus.FAIL);
                buildTestNodes(context.getSkippedTests(), LogStatus.SKIP);
              
            }
        }
 
        extent.flush();
        extent.close();
    }
 
    public  void buildTestNodes(IResultMap tests, LogStatus status) {
       
 
        if (tests.size() > 0) {
            for (ITestResult result : tests.getAllResults()) {
                test = extent.startTest(result.getMethod().getMethodName());
 
                test.getTest().setStartedTime(getTime(result.getStartMillis()));
                test.getTest().setEndedTime(getTime(result.getEndMillis()));
 
                for (String group : result.getMethod().getGroups())
                {   
                test.assignCategory(group);
                }
                
                
                message = "Test " +status.toString().toLowerCase() + "ed";
                
                if (result.getThrowable() != null)
                {
                	message = result.getThrowable().toString();//getMessage();
                        
                }
                
                test.log(status, message);
                
             
                extent.endTest(test);
                
                
                
            }
        }
    }
 
    private  Date getTime(long millis) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(millis);
        return calendar.getTime();        
    }

![image](https://cloud.githubusercontent.com/assets/26084599/23547931/21b29352-002b-11e7-9015-ae1d2e26784f.png)

i am just getting test passed but how should i get other logs 

through this i am able to run all the tests

**Comment by gitissuepost** [comment]
@mohd19nazim 
In your custom reporter, you are logging only that message in extenttest. Not sure, if you are logging anything into Reporter object, but if you are, add below snippet to your custom reporter before logging to extent test.

`List<String> reporterMessages = Reporter.getOutput(testResult);
							if (!reporterMessages.isEmpty()) {
								for (String message : reporterMessages) {
									if (message == null) {
										message = "";
									}
									test.log(status, message)
								}
							}` 

If you are looking for some solution to insert logger information to this, create a custom appender and use that in your logger configuration.

**Comment by anshooarora** [comment]
You can do this:

```
for (String s : Reporter.getOutput()) {
    extent.setTestRunnerOutput(s);
}
```

**Comment by anilkale99** [comment]
Hi Anshoo,

With the code that you have provided it just adding the new tab along with the Tests and Dashboard. As per the above query we should get the steps details on clicking the single test under Tests tab. Which is not currently happening. Your help will be really appreciated.
