### ISSUE TITLE
Not able to get node information as well as separate result details of parallel execution in Extent Report using TestNG

### ISSUE THREAD

**Issue by Ashishqa** [anshooarora/extentreports-java#789]
Hello All,

I am running my test parallel on different node(2 different system) using TestNG. I am passing node address, port, url and test data by parameters in TestNG.xml. I have integrated Extent Report for reporting.

I am not getting separate test result as well as node details in report.

Kindly help me how I get all the node information in Extent Report.

**Comment by anshooarora** [comment]
What version of ExtentReports?  How are you creating extent instance?  Can you create a gist and share?

**Comment by Ashishqa** [comment]
Hi Anshooara,

Thanks for reply, I have followed https://github.com/anshooarora/extentreports-java/issues/64 thread and achieved it.
