### ISSUE TITLE
Date time format and test duration

### ISSUE THREAD

**Issue by gitissuepost** [anshooarora/extentreports-java#791]
@anshooarora 
I understand Extent report has a defined date time format to populate start and end time and the test duration unit (default millisecond).

I think it will helpful, if these details can be configured like user can configure the required format and timeunit in extent report config xml. This will provide some flexibility around this feature.

Thanks.

**Comment by email2vimalraj** [comment]
This feature request makes sense. I'll send a PR tonight.

@anshooarora : Kindly assign this to me.

**Comment by gitissuepost** [comment]
Thanks @email2vimalraj for considering this request. I went through #793 and I understand, any valid data time format will work with the solution.

There was another request along with this regarding execution duration. By default it is in millisecond and for large test suites that runs for few hours, the value will be huge. If this can also be configured to select Second/Minute/Hours atleast as unit, it will be helpful. I am not sure if this already in your list.

Thanks again.

**Comment by email2vimalraj** [comment]
No that was not on my list. Let me look through that as well.

Thanks 
Vimalraj

**Comment by anshooarora** [comment]
Closing as the referenced PR has been merged with this enhancement.

**Comment by gitissuepost** [comment]
@email2vimalraj Is the request regarding execution duration included in this PR or you require another id on this. Thanks..

**Comment by email2vimalraj** [comment]
The PR didn't include the duration feature. I've raised a new issue #826. I'll raise a PR for the new issue created.
