### ISSUE TITLE
Log messages not displayed for BDD style report

### ISSUE THREAD

**Issue by email2vimalraj** [anshooarora/extentreports-java#792]
I've steps like as follows:

```java
// scenario
ExtentTest scenario = feature.createNode(Scenario.class, "Jeff returns a faulty microwave");
ExtentTest step1 = scenario.createNode(Given.class, "Jeff has bought a microwave for $100");
step1.info("Some message here");
step1.pass("Passed");
```

The step1 node is created in scenario and marked as pass. However, the info message that I'm logging is not displayed.

However, I'm able to log the info message if I use as follows:

```java
// scenario
ExtentTest scenario = feature.createNode("Scenario: Jeff returns a faulty microwave");
ExtentTest step1 = scenario.createNode("Given: Jeff has bought a microwave for $100");
step1.info("Some message here");
step1.pass("Passed");
```

**Comment by anshooarora** [comment]
Hi Vimal.  This is inline with how cucumber works today.  None of the pass/info messages will be displayed.  Only failures, errors.  We can add this as an enhancement for a future version.
