### ISSUE TITLE
using the css area 

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-java#797]
Are there examples of adding css to the report?

**Comment by anshooarora** [comment]
No, adding css is exactly the same as how you would to any other page.  Simply make the style changes and add it to config.xml or directly via code using `config()`.

**Comment by jloyzaga** [comment]
Hi Anshoo,


Remember me? you helped me out alot from advancedqtp


Joe Loyzaga

**Comment by jloyzaga** [comment]
possible to use with UFT?

**Comment by jloyzaga** [comment]
can you send me an example for inserting an image using both ways so I 
can understand it.


I need examples - I don't do well using theory..


Thanks


Joe
