### ISSUE TITLE
After downloading the source code into eclipse error

### ISSUE THREAD

**Issue by bajaoyy** [anshooarora/extentreports-java#798]
# 
![image](https://cloud.githubusercontent.com/assets/5927992/23791959/0537ec46-05c0-11e7-8af9-da184c85da0c.png)

**Comment by anshooarora** [comment]
Looks like the dependencies were not downloaded.  Make sure your proxy settings are correctly set if you are behind one.  You can also manually add all dependencies by downloading the zipfile from [here](http://extentreports.com/community/).
