### ISSUE TITLE
Need to add new field in extent report 3.0.3 - Dashboard view

### ISSUE THREAD

**Issue by lokesh14** [anshooarora/extentreports-java#799]
Hi,

I need to add new field in extent report (3.0.3), In dashboard view. 
I need to add a new field named as 'Url' to state in which url my test has run. Is it possible ??.

thanks in advance.

**Comment by email2vimalraj** [comment]
You can use `test.info(url)` to log the url under the test has run.

**Comment by lokesh14** [comment]
Can i have it under my dash board section as a separate field of info.? Other then displaying it under my tests.

**Comment by email2vimalraj** [comment]
You can add as a system information if your url is not different for each and every test cases.

**Comment by anshooarora** [comment]
I would also agree with this approach.  Simply add it to your system properties:

```
extent.setSystemInfo("url", "<a href='http://github.com'>link</a>");
```

**Comment by lokesh14** [comment]
Thanks a lot @email2vimalraj  @anshooarora
