### ISSUE TITLE
Report using extent I-reporter listener.

### ISSUE THREAD

**Issue by lokesh14** [anshooarora/extentreports-java#800]
-> My test cases is in such a format that each class has 20-30 @test methods. 
-> I need a report in such a format that 'Class' names should be displayed in left panel and if i click on each class its corresponding methods result should be displayed in right panel . 

-> I can do this using extent manager , But i cant do this using I reporter listener file. Is there any way to achieve this, Kindly help me on this.

**Comment by lokesh14** [comment]
@anshooarora can u plz help me on this

**Comment by email2vimalraj** [comment]
@lokesh14 : What do you mean by I Reporter listener? From where you get that?

**Comment by lokesh14** [comment]
http://extentreports.com/docs/versions/3/java/#htmlreporter-features  

TestNG i reporter .

**Comment by anshooarora** [comment]
You can have a `@BeforeClass` `ThreadLocal<ExtentTest>` object which contains the parent and adds children when `@BeforeMethod` executes.

See [here](https://github.com/anshooarora/extentreports-java/issues/652):

```
public class ExtentTestNGReportBuilder {

    private ThreadLocal<ExtentTest> parentTest;
    private ThreadLocal<ExtentTest> test;

    @BeforeClass
    public synchronized void beforeClass() {
        ExtentTest parent = ExtentTestManager.createTest(getClass().getName());
        parentTest.set(parent);
    }

    @BeforeMethod
    public synchronized void beforeMethod(Method method) {
        ExtentTest child = parentTest.get().createNode(method.getName());
        test.set(child);
    }

    @AfterMethod
    public synchronized void afterMethod(ITestResult result) {
        if (result.getStatus() == ITestResult.FAILURE)
            test.get().fail(result.getThrowable());
        else if (result.getStatus() == ITestResult.SKIP)
            test.get().skip(result.getThrowable());
        else
            test.get().pass("Test passed");

        ExtentManager.getExtent().flush();
    }
}
```
