### ISSUE TITLE
just need simple c# example to run

### ISSUE THREAD

**Issue by jloyzaga** [anshooarora/extentreports-java#801]
I'd like to try and install on Visual Studio 2015 and am a newbie at VS. So if I could just get a very simple .soln or some instructions to install and run report so as to be able to see what needs doing to get all the functionality. Can someone give me something?

Thanks
Joe

**Comment by email2vimalraj** [comment]
You should be raising this here: https://github.com/anshooarora/extentreports-csharp

**Comment by email2vimalraj** [comment]
@anshooarora : Kindly mark it as closed.
