### ISSUE TITLE
Extentreports TestNg - Getting error that Extent reports cannot be resolved

### ISSUE THREAD

**Issue by anitaippalav** [anshooarora/extentreports-java#804]
I am working on setting up Extent reports in Eclipse. I have downloaded  and imported one of the sample projects from the following links

http://www.ontestautomation.com/using-the-extentreports-testng-listener-in-selenium-page-object-tests/
I have downloaded the Java  3.0.3 – Version 3 for  extentreports.

 I am getting errors in the code as 
 The import com.relevantcodes cannot be resolved.
ExtentReports cannot be resolved to a type
LogStatus cannot be resolved to a variable
ExtentTest cannot be resolved to a type

Am I missing to add any other Jar files ? or need to import any class in the code ? to fix the above issues in code.

I have pasted the code below on which I am getting the above errors.

[listener.zip](https://github.com/anshooarora/extentreports-java/files/849499/listener.zip)

package com.ontestautomation.extentreports.listener;
import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class ExtentReporterNG implements IReporter {
    private ExtentReports extent;

    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        extent = new ExtentReports(outputDirectory + File.separator + "ExtentReportsTestNG.html", true);

        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults();

            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();

                buildTestNodes(context.getPassedTests(), LogStatus.PASS);
                buildTestNodes(context.getFailedTests(), LogStatus.FAIL);
                buildTestNodes(context.getSkippedTests(), LogStatus.SKIP);
            }
        }

        extent.flush();
        extent.close();
    }

    private void buildTestNodes(IResultMap tests, LogStatus status) {
        ExtentTest test;

        if (tests.size() > 0) {
            for (ITestResult result : tests.getAllResults()) {
                test = extent.startTest(result.getMethod().getMethodName());

                test.getTest().startedTime = getTime(result.getStartMillis());
                test.getTest().endedTime = getTime(result.getEndMillis());

                for (String group : result.getMethod().getGroups())
                    test.assignCategory(group);

                String message = "Test " + status.toString().toLowerCase() + "ed";

                if (result.getThrowable() != null)
                    message = result.getThrowable().getMessage();

                test.log(status, message);

                extent.endTest(test);
            }
        }
    }

    private Date getTime(long millis) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(millis);
        return calendar.getTime();        
    }
}

**Comment by gsaimadhu** [comment]
In 3.x, we need to use aventstack, instead of relevant codes in import package names: 

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.ExtentXReporter;

**Comment by anitaippalav** [comment]
Thanks Madhu, Really helpful.
 After I Imported  aventstack packages following errors are not displayed.
ExtentReports cannot be resolved to a type
 ExtentTest cannot be resolved to a type

But still am getting the following errors in the code  :
 LogStatus cannot be resolved to a variable
 The method startTest(String) is undefined for the type ExtentReports
The method getTest() is undefined for the type ExtentTest
The method endTest(Test) in the type Report is not applicable for the arguments (ExtentTest)

I have attatched the code below
package com.ontestautomation.extentreports.listener;

import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
 
import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;
 
//import com.relevantcodes.extentreports.ExtentReports;
//import com.relevantcodes.extentreports.ExtentTest;
//import com.relevantcodes.extentreports.LogStatus;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.ExtentXReporter;
import com.aventstack.extentreports.reporter.configuration.Theme;
 
public class ExtentReporterNG implements IReporter {
	
    private ExtentReports extent;
    private ExtentHtmlReporter htmlReporter;
    private ExtentTest test;
 
    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        extent = new ExtentReports();
 
        htmlReporter = new ExtentHtmlReporter(outputDirectory);
        htmlReporter.config().setTheme(Theme.DARK);
        
        extent.attachReporter(htmlReporter);
 
        extent.flush();
        
    }
    
    public void DemoReportPass()
    {
    	
        test = extent.createTest("AAAA");
       
        test.pass("Assert Pass as condition is True");
    }
 
    private void buildTestNodes(IResultMap tests, LogStatus status) {
        ExtentTest test;
 
        if (tests.size() > 0) {
            for (ITestResult result : tests.getAllResults()) {
                test = extent.startTest(result.getMethod().getMethodName());
 
                test.getTest().startedTime = getTime(result.getStartMillis());
                test.getTest().endedTime = getTime(result.getEndMillis());
 
                for (String group : result.getMethod().getGroups())
                    test.assignCategory(group);
 
                String message = "Test " + status.toString().toLowerCase() + "ed";
 
                if (result.getThrowable() != null)
                    message = result.getThrowable().getMessage();
 
                test.log(status, message);
 
                extent.endTest(test);
            }
        }
    }
 
    private Date getTime(long millis) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(millis);
        return calendar.getTime();        
    }
}

**Comment by anshooarora** [comment]
Version 3.0  is a complete rewrite of the API and a lot of things have changed.  Please refer to the [docs](http://extentreports.com/docs/versions/3/java/).
