### ISSUE TITLE
How to set build# for extentX with extent 2.42 sdk

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#805]
Anshoo,
I am using 2.42 version of Extent Reports. Exploring extentX. 
My reports are showing without build#. So i cannot traverse to the test results of a particular run.

i tried with below statements:
	extent.config().reportName(buildid);
	extent.addSystemInfo("BUILDID", buildid);

![image](https://cloud.githubusercontent.com/assets/8359360/24030618/e474d3ae-0b03-11e7-9728-30eef978a7f5.png)

Appreciate your quick help.

Thanks
Madhu

**Comment by anshooarora** [comment]
I would suggest using version 3+ of thr api and 1+ of the server.
