### ISSUE TITLE
ExtentX 'show history' showing failures across different projects, instead of same project

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#807]
Anshoo,
I am exploring extextX with extent reprots V3.0.3.

Multiple projects are created in extentX.
The test name PostCSV same across projects, but internal functionality different.

From the Project at right hand side, select 1 project. Select the latest run.
Click on the failures shown, In this case, PostCSV returned few failures. Now click on it, and click on Show history.

Now the list of PostCSV test cases shown are of different projects. 

![image](https://cloud.githubusercontent.com/assets/8359360/24074290/ab87d694-0c2b-11e7-83a9-7ff85b67d9cb.png)

Please let me know if you need any info.

Thanks
Madhusudhan G

**Comment by gsaimadhu** [comment]
Anshoo, any comments on this issue?

**Comment by anshooarora** [comment]
Please do not open ExtentX issues in the ExtentReports repo. It becomes very difficult to track and commit changes linking issues. I am closing this and other ExtentX tickets, please feel free to reopen these in the ExtentX repo.
