### ISSUE TITLE
Only last exception is getting logged in Exception tab

### ISSUE THREAD

**Issue by mayurgoenka** [anshooarora/extentreports-java#808]
Hi,

I am using Extent Reports by following this: 
http://extentreports.com/docs/versions/3/java/#extent-testng-report-builder

My tests had several exceptions but only last exception is showing up in exception tab. What's wrong?

Thanks for helping!

**Comment by testphreak** [comment]
@mayurgoenka Yes, I see that behavior on my side as well with v3.0.3. Only the last test failure's exception seems to be getting populated in the exception-view.

@anshooarora This wasn't an issue with v2.41.2.

**Comment by email2vimalraj** [comment]
@mayurgoenka and @testphreak : PR raised for this issue and waiting to be merged

**Comment by mayurgoenka** [comment]
Thanks @testphreak 

Thanks @email2vimalraj for the quick response and fix. Really appreciate it.

**Comment by anshooarora** [comment]
Closing as the referenced PR fixes this.

**Comment by email2vimalraj** [comment]
Keep it opened as I'm still working on this.

Thanks
Vimalraj

**Comment by email2vimalraj** [comment]
@mayurgoenka and @testphreak: The issue had been addressed as part of v3.0.5. Kindly update to the latest version.

Refer: http://extentreports.com/docs/versions/3/java/#whats-new

Feel free to reopen in case you feel the issue still exists.
