### ISSUE TITLE
Search Feature in report doesn't work intermittently

### ISSUE THREAD

**Issue by mayurgoenka** [anshooarora/extentreports-java#809]
Search feature in Extent Reports stops working intermittently. I need to refresh the page for it to make it work. What's wrong?

**Comment by email2vimalraj** [comment]
Attach your report for us to reproduce.

**Comment by anshooarora** [comment]
Please share the steps to repro also.  Which view does it fail on?

**Comment by mayurgoenka** [comment]
Check the category tab and try the search feature.

https://drive.google.com/file/d/0B2UToIzi4OOuM3d3cnRGVngxcFE/view?usp=sharing

**Comment by mayurgoenka** [comment]
The search feature stops working in the main view as well sometimes but i don't have the steps to reproduce that issue.

**Comment by anshooarora** [comment]
Thanks, I am able to repro.  Since you have opened #818,  I am closing this and marking #818 as a bug.

**Comment by mayurgoenka** [comment]
both are different issues:
one is about the search bar
other is about the category based filter in the main view

Just wanted to confirm if you understood the above. Thanks!
