### ISSUE TITLE
Pass/Fail Percentage not showing up in the new version

### ISSUE THREAD

**Issue by mayurgoenka** [anshooarora/extentreports-java#810]
In the summary dashboard page, I can't see the pass/fail percentage. How to add it?

**Comment by testphreak** [comment]
@mayurgoenka I don't see it either.

@anshooarora was it removed?

<img width="456" alt="screen shot 2017-03-18 at 10 38 37 pm" src="https://cloud.githubusercontent.com/assets/10567800/24076559/be98db84-0c2b-11e7-9c6c-27c7a98f276b.png">

**Comment by anshooarora** [comment]
Yes, it was..  I will mark this as an enhancement for next release.

**Comment by mayurgoenka** [comment]
Thanks Anshoo.

What is the ETA for the next drop?

**Comment by anshooarora** [comment]
Would showing the percentage in the chart suffice or the number should be visible when the report opens?

**Comment by mayurgoenka** [comment]
The latter would be an added advantage and will look much better if shown in proper graphics.

If the former is easy to fix, that would also suffice.

**Comment by anshooarora** [comment]
This will be part of the upcoming release, and percentages will be available as mouseovers on the relevant count.
