### ISSUE TITLE
In Dark theme, characters typed in search bar are not visible

### ISSUE THREAD

**Issue by mayurgoenka** [anshooarora/extentreports-java#811]
Hi,

When we switch to dark theme of extent reports, we can't see the characters typed in the search box. Can we fix this?

**Comment by email2vimalraj** [comment]
@mayurgoenka : PR raised and waiting to be merged.

**Comment by mayurgoenka** [comment]
Thanks @email2vimalraj  for the quick fix!

**Comment by anshooarora** [comment]
Closing this as the referenced PR has been merged.
