### ISSUE TITLE
Taken screen shot display at bottom instead of below the particular steps and package name get append after the step detail

### ISSUE THREAD

**Issue by Ashishqa** [anshooarora/extentreports-java#813]
![image](https://cloud.githubusercontent.com/assets/26184674/24080296/063c0c2c-0cc2-11e7-93a8-bd280b6ff213.png)

**Comment by email2vimalraj** [comment]
@Ashishqa : Kindly provide the sample for us to reproduce.

Also please ensure that you are not doing the `toString` on the ExtentTest object.

**Comment by anshooarora** [comment]
@Ashishqa @email2vimalraj  -  this feature has changed slightly in version 3.  Both test and logs can add screenshots.  Please see here:  http://extentreports.com/docs/versions/3/java/#insert-screenshots

```

// adding screenshots to log
test.fail("details", MediaBuilder.createScreenCaptureFromPath("screenshot.png").build());

// or:
MediaModelProvider mediaModel = MediaBuilder.createScreenCaptureFromPath("screenshot.png").build();
test.fail("details", mediaModel);	
```

```
// adding screenshots to test
test.fail("details").addScreenCaptureFromPath("screenshot.png");
```

**Comment by muralikunda** [comment]
Hi 
I have tried test.fail("details").addScreenCaptureFromPath("screenshot.png"); but still attaching the screenshots in the bottom.
public static ExtentTest logger;
if(status.equalsIgnoreCase("pass") ){
    		logger.pass(comments).addScreenCaptureFromPath(scrnshtPath);
    		//logger.log(Status.PASS, comments + " - " +logger.addScreenCaptureFromPath(scrnshtPath));
    	}else if(status.equalsIgnoreCase("fail")){
    		//logger.log(Status.FAIL, comments+ " - "+MediaEntityBuilder.createScreenCaptureFromPath(scrnshtPath).build());
    		//logger.log(Status.FAIL, comments+ " - "+logger.addScreenCaptureFromPath(scrnshtPath));
    		logger.fail(comments).addScreenCaptureFromPath(scrnshtPath);
    	}else if(status.equalsIgnoreCase("info")){
    		//logger.log(Status.INFO, comments+ " - "+logger.addScreenCaptureFromPath(scrnshtPath));
    		logger.info(comments).addScreenCaptureFromPath(scrnshtPath);
    	}

Am I doing anything wrong ??
