### ISSUE TITLE
Extent Reports 3 - TestNgListener feauture  issues

### ISSUE THREAD

**Issue by anitaippalav** [anshooarora/extentreports-java#817]
Hi,

I am  trying to generate Extent reports  Selenium Java TestNG .
I have downladed Extent reports V3.0 for Java
Is TestNGListener feature not compatible with Extent reports V3.0. ?
Do we have any feature equivalent to TestNGlistener compatible with Extent reports V3.0. If so can you please provide ?

I am getting errors on this code below

package com.ontestautomation.extentreports.listener;

import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.testng.Assert;
import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;
 
//import com.relevantcodes.extentreports.ExtentReports;
//import com.relevantcodes.extentreports.ExtentTest;
//import com.relevantcodes.extentreports.LogStatus;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.ExtentXReporter;
import com.aventstack.extentreports.reporter.configuration.Theme;
 
public class ExtentReporterNG implements IReporter {
	
    private ExtentReports extent;
    private ExtentHtmlReporter htmlReporter;
    private ExtentTest test;
    
 
    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        extent = new ExtentReports();
 
        htmlReporter = new ExtentHtmlReporter(outputDirectory);
        htmlReporter.config().setTheme(Theme.DARK);
        
        extent.attachReporter(htmlReporter);
 
        extent.flush();
                
    }
    
    public void DemoReportPass()
    {
    	
        test = extent.createTest("DemoReportPass");
        Assert.assertTrue(true);      
        test.pass("Assert Pass as condition is True");
    }
 
    private void buildTestNodes(IResultMap tests, LogStatus status) {
        ExtentTest test;
 
        if (tests.size() > 0) {
            for (ITestResult result : tests.getAllResults()) {
                test = extent.startTest(result.getMethod().getMethodName());
 
                test.getTest().startedTime = getTime(result.getStartMillis());
                test.getTest().endedTime = getTime(result.getEndMillis());
 
                for (String group : result.getMethod().getGroups())
                    test.assignCategory(group);
 
                String message = "Test " + status.toString().toLowerCase() + "ed";
 
                if (result.getThrowable() != null)
                    message = result.getThrowable().getMessage();
 
                test.log(status, message);
 
                extent.endTest(test);
            }
        }
    }
 
    private Date getTime(long millis) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(millis);
        return calendar.getTime();        
    }
}

Thanks in Advance, Anita

**Comment by anshooarora** [comment]
Version 3 has changed the API quite a bit so please refer to the documentation.


http://extentreports.com/docs/versions/3/java/#testng-ireporter
