### ISSUE TITLE
Screenshots are not showing in ExtentX1.0.1 (ExtentReports 3.0.3)

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#819]
Anshoo, 
Do we need to set any specific configuration w.r.to ExtentX?

The screenshots are shown in ExtentReports, But not showin in ExtentX.

**Extent Reports:**
![image](https://cloud.githubusercontent.com/assets/8359360/24129928/c7ee969c-0e0b-11e7-8c6c-17cdfebfe555.png)

**ExtentX Report - screenshot not shown:**
![image](https://cloud.githubusercontent.com/assets/8359360/24129976/0785cd16-0e0c-11e7-8801-94eef4062bdb.png)

Thanks
Madhusudhan G

**Comment by email2vimalraj** [comment]
@gsaimadhu : Kindly share the sample code for us to reproduce.

**Comment by gsaimadhu** [comment]
Attached sample code to reproduce the issue.
[ExtentTestQA.java.txt](https://github.com/anshooarora/extentreports-java/files/857770/ExtentTestQA.java.txt)

**Comment by gsaimadhu** [comment]
Also, from above screenshots the timestamps are not same in Extent report and ExtentX report. Do we need to set any configuration?

**Comment by anshooarora** [comment]
Please do not open ExtentX issues in the ExtentReports repo.  It becomes very difficult to track and commit changes linking issues.  I am closing this and other ExtentX tickets,  please feel free to reopen these in the ExtentX repo.

**Comment by gsaimadhu** [comment]
Sorry, i didnot realize this. Now, Logged this issue in ExtentX repository.
https://github.com/anshooarora/extentx/issues/119
