### ISSUE TITLE
Incorrect number of features and scenarios in ExtentX report ?

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#822]
Anshoo,
I am exporing ExtentX. Trying to understand the numbers shown in features and scenarios. 
Please let me know if i am missing any thing here.

I am using 3 level parent, child nodes:
**example:**
usecasetest=extent.createTest(useCaseID)
parentTest=usecasetest.createNode(testCaseDesc,testCaseID)
childTest=parentTest.createNode(operation_in_test);	

**There seems to be discrepancy in the report.** 
1. The Total Features, Total Scenarios NOT relating to the data show in the test run. //see screenshot1
2. The number of features and test scenarios info not matching with the data shown in test run and actual features and test scenarios. // please see screenshot 2.

**Screenshot1:**
![image](https://cloud.githubusercontent.com/assets/8359360/24137784/53386bae-0e3b-11e7-9ce7-97e5ba8afe0d.png)

**Screenshot 2:**
![image](https://cloud.githubusercontent.com/assets/8359360/24137883/c1b22106-0e3b-11e7-8e6f-6aea7caa48a7.png)

Thanks
Madhusudhan G

**Comment by anshooarora** [comment]
Please do not open ExtentX issues in the ExtentReports repo. It becomes very difficult to track and commit changes linking issues. I am closing this and other ExtentX tickets, please feel free to reopen these in the ExtentX repo.

**Comment by gsaimadhu** [comment]
Sorry i didnot realize the new repository for ExtentX.
Now i have logged this issue in ExtentX repository
https://github.com/anshooarora/extentx/issues/120
