### ISSUE TITLE
Incorrect information displays on the dashboard in case if the child test is skipped.

### ISSUE THREAD

**Issue by VitPer** [anshooarora/extentreports-java#825]
Vers 3.03
See attachment.
![2017-03-23_10h18_32](https://cloud.githubusercontent.com/assets/26621876/24241267/862e06f2-0fb4-11e7-825b-a53249c0c902.png)

**Comment by anshooarora** [comment]
This is as per design.  If you are having a child test, status of the child only will be considered.  

Looks to be an issue that the parent status is being shown on the left,  it shouldn't.  But the counts are correct.

**Comment by VitPer** [comment]
OK, Thanks. What happens for the test cases with more than one child, if some children was skipped, some passed, which status should be set for the parent? For the case if at least one child was failed - no problem, we can say that parent fails too. The status of the parent in my case is "fail" ( the command  .**getStatus()** returns "**fail**").  I mean, that this status should be displayed on the left.  Probably counter for children should  be on the right (STEPS) , parents - left.

**Comment by anshooarora** [comment]
This is the hierarchy that will be used:  https://github.com/anshooarora/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/Status.java#L55

Parent will get the highest status from the children automatically.

**Comment by email2vimalraj** [comment]
@VitPer : The issue had been addressed as part of v3.0.5. Kindly update to the latest version.

Refer: http://extentreports.com/docs/versions/3/java/#whats-new

Feel free to reopen in case you feel the issue still exists.
