### ISSUE TITLE
Seeing Number Of Steps and Number of tests as same number in extent reports

### ISSUE THREAD

**Issue by ravindrababukalvala** [anshooarora/extentreports-java#829]
Hi Anshoo,

As I can see in extent reports step and test numbers are displaying the same in dash board.
can we see the tests passed as 1 instead of same number as steps.

please help me asap

**Comment by anshooarora** [comment]
Please refer to the [issue template[(https://github.com/anshooarora/extentreports-java/blob/master/ISSUE_TEMPLATE.md) and provide additional details.

**Comment by ravindrababukalvala** [comment]
## Summary
The issue is with reports Dahs Board section.
When we look at the steps executed and tests executed.The report is shown like same number of steps and same number of tests.
but there is only one test ran which has 4 steps but it is showing 4 tests ans 4 tests

## Expected Behavior
The expected behaviour should be only one test and 4 steps executed


## Current Behavior
Current  behaviour is 4 tests and 4 steps executed
## Environment Details
* Extent report Version used:extentreports-3.0.1.jar
* Operating System and version:Windows 7 ,64 Bit
* JDK Version:1.8

## Screenshots
![issue73](https://cloud.githubusercontent.com/assets/3984957/24594600/7d0565b6-184c-11e7-90d7-828d8480b051.png)
![issue73_2](https://cloud.githubusercontent.com/assets/3984957/24594605/833be248-184c-11e7-93a1-078658a633b6.png)

**Comment by ravindrababukalvala** [comment]
Hi Team,

Any update on this issue.

Thanks

**Comment by anshooarora** [comment]
Can you update to 3.0.4 and try `AnalysisStrategy.SUITE`?

**Comment by email2vimalraj** [comment]
@ravindrababukalvala : The issue had been addressed as part of v3.0.5. Kindly update to the latest version.

Refer: http://extentreports.com/docs/versions/3/java/#whats-new

Feel free to reopen in case you feel the issue still exists.

**Comment by ravindrababukalvala** [comment]
Observing the same issue

**Comment by email2vimalraj** [comment]
@ravindrababukalvala : What did you try? Can you post the sample with v3.0.4 and the current screenshot if possible?

**Comment by ravindrababukalvala** [comment]
I tried with version 3.0.4 seeing the same report as before

**Comment by email2vimalraj** [comment]
@ravindrababukalvala : Need the sample code to reproduce and post the screenshot if possible.
