### ISSUE TITLE
Missing Test Step Name column

### ISSUE THREAD

**Issue by ssimakurthy** [anshooarora/extentreports-java#834]
Hi Anshoo,

I am using v2.41.1 till now in my automation suites. But after looking at the new version of extent report 3.0.3 and new features of extent report, I started migrating to the new version.

In the previous version (v2.41.1) we have STEP NAME column and I am not able to add this step name with extent 3.0.0.

Could you please help me to resolve this issue. 

Attaching the screenshot for your reference.

Regards
Sireesha S

## Summary

Test Step Detail column in Extent 3.0.0

## Expected Behavior
Request your help to add Step Name column in the latest version
![screen shot 2017-03-30 at 11 29 54 am](https://cloud.githubusercontent.com/assets/18742950/24520886/dfd75070-153e-11e7-83a1-ac71a288c658.png)

## Current Behavior
In the previous version (v2.41.1) we have STEP NAME column and I am not able to add this step name with extent 3.0.0.

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used: 3.0.3
* Operating System and version: Mac
* JDK Version: 1.8

**Comment by email2vimalraj** [comment]
@anshooarora : What is your view on this issue? Do we really need to support adding the step name.

In my opinion, this can be easily achieved using `createTableMarkup` feature.

**Comment by ssimakurthy** [comment]
Hi,

If it can easily achievable, can you please to include the step name in the reports. 

Regards,
Sireesha S

**Comment by email2vimalraj** [comment]
@ssimakurthy : This is not easily achievable because many of the underlying things has to be changed. You could easily achieve the same behaviour using `createTable` markup helper.

```java
String[][] data = new String[2][2];
data[0][0] = "Step Name";
data[0][1] = "Details;
data[1][0] = "Step name value";
data[1][1] = "Details value";

Markup m = MarkupHelper.createTable(data);
test.info(m);
```

The above could should help you.

**Comment by ssimakurthy** [comment]
Thank you for the work around @email2vimalraj

**Comment by email2vimalraj** [comment]
@ssimakurthy : Hope this solves your issue. Hence, closing this issue. Kindly re-open in case you need further help.
