### ISSUE TITLE
Category can't be clicked and filtered

### ISSUE THREAD

**Issue by lehoanglu0ng** [anshooarora/extentreports-java#838]
## Summary

The Category filter and tag work fine on version 2+ but they don't work on version 3+

## Current Behavior

1. Click on category tag in the test node can't filter the category.
2. Category filter doesn't work if a test node has more than 1 category. 

## Environment Details

* Extent report Version used: 3.0.3
* Operating System and version: macOS 10.12.3
* JDK Version: 1.8

**Comment by mayurgoenka** [comment]
In addition to this, consider the following scenario:

You have a parent node which doesnt have any category.

If there is only child node to this parent node and a category is assigned to the child node, the Category Filter works perfectly fine.

If there is more than one child node to this parent node and even if assign the same category to all the child nodes, we are not able to use the filter.
