### ISSUE TITLE
Extent Reports 3 - how to add company logo to the report

### ISSUE THREAD

**Issue by anitaippalav** [anshooarora/extentreports-java#842]
Hi,

I am working on a Selenium - V3, TestNG project with Extent reports 3.0. I need to add Company logo on the extentReport.html. 

Issues :
1. Can you Please guide me what code I need  to add in Selenium Java code - Extent reports 3  to add the image on report.

2. I have added config file to the project  but generated extentReport.html is  not taking the values from Config file even though I have added in code 
htmlreporter.loadConfig(System.getProperty("user.dir")+"/extent-config.xml");

Please refer to the Extent project attatched
ExtentLog.Java file 
ExtentReport.html generated  which not reading values from extent-config.xml file
extent-config.xml
Logo file which I want to be in header of ExtentReport.html

[Extent.zip](https://github.com/anshooarora/extentreports-java/files/901577/Extent.zip)
![capgemini_logo_high_res](https://cloud.githubusercontent.com/assets/26473485/24739624/44e5dbd4-1ae0-11e7-9a61-e52f4af15dc6.jpg)

Many Thanks, Anita

**Comment by email2vimalraj** [comment]
@anitaippalav : We have the issue template which you can use for raising the issue.

You could use javascript to override the logo: `htmlreporter.config().setJS("js-string");`

The `js-string` should be replaced with the actual javascript code which can override the logo.

**Comment by anitaippalav** [comment]
[Uploading Extent.zip…]()
