### ISSUE TITLE
Is it possible to customize the extent report dashboard and email it?

### ISSUE THREAD

**Issue by ShwetaSuvarna** [anshooarora/extentreports-java#843]
I need to add some results in tabular structure on dashboard something like below

![image](https://cloud.githubusercontent.com/assets/25083019/24826816/0dcea004-1c5c-11e7-86cf-e01801585dbc.png)

and then email the dashboard. Is it possible?

**Comment by email2vimalraj** [comment]
@ShwetaSuvarna : Unfortunately you cannot add this table in the dashboard view. However you can add this information in the System environment table using `setSystemInfo` method.

Refer [here](http://extentreports.com/docs/versions/3/java/#add-system-info)
