### ISSUE TITLE
If my test FAILS before assertion due to  logical error then extent report show the test as pass in report. i am using 2.05 jar for creating extents report.please help for this??

### ISSUE THREAD

**Issue by reshmabhosale** [anshooarora/extentreports-java#845]
## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by email2vimalraj** [comment]
@reshmabhosale : Please help us reproduce the problem. Kindly note that the issue template is meant to provide as much as information for us to understand the issue, just the issue title will not help us. This will certainly delay helping you or might be your issue will be unnoticed.

**Comment by karthikbhatnagar** [comment]
Are you using testng or junit?

**Comment by reshmabhosale** [comment]
TestNG....

**Comment by karthikbhatnagar** [comment]
You can catch the exception in AfterMethod.

**Comment by reshmabhosale** [comment]
No....actually I made structure in dat
1. Common function( package1)- excel read,excelwrite,login page details are
given..

2. Package 2:
Main logic -(dropdown selection nd main logic) is put in this class(java)

3. Package 3:
Test cases(class -TestNG) ..in dat i have made one class for "webdriverpass"
  2nd Classs( I have create object and called main logic class which is in
2nd package) is extend webdriver class.

How i put this exception ??

**Comment by karthikbhatnagar** [comment]
Trap and report in AfterMethod.

**Comment by reshmabhosale** [comment]
i am not able to generate log of two class using parallel test(V2.41.2).. only first class log is showing in report...

Class1:
package TestCases;

import java.io.File;

import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.DisplayOrder;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import com.relevantcodes.extentreports.NetworkMode;

import Technical.Filter;


public class FilterTest extends WebDriverPass{
	ExtentReports report;
	ExtentTest test;
	Filter w = new Filter();
	
	@BeforeSuite
	 public void starttest(){
	
		//ExtentReports report= new ExtentReports ("C:\\Users\\sa\\workspace\\Worklist\\Report.html",false);
		report=new ExtentReports(System.getProperty("user.dir")+"/test-output/WorklistReport14.html",true,DisplayOrder.NEWEST_FIRST, NetworkMode.OFFLINE);
		report.addSystemInfo("HostName","R")
		.addSystemInfo("Environment","QA");
		report.loadConfig(new File(System.getProperty("user.dir")+"/worklist-config.xml"));

	}
	
  @Test(priority=1)
  public void WokrlistModule() throws InterruptedException {
	  test=report.startTest("WokrlistModule");	  
	   w.worklistindexFilter(driver);
	   Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	//  report.endTest(test);
	  
	    
 
  }
  @Test(priority=2)
  public void Filter1() throws InterruptedException {
	  test=report.startTest("counting New job created in last 24HRS");		  
	  w.Filter1(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	//  report.endTest(test);
	  	    
 
  }
  @Test(priority=3)
  public void Filter2() throws InterruptedException {
	  	  
	  test=report.startTest("Folloup/response recevied fromvessels in last 24");
	  w.Filter2(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	//  report.endTest(test);
	  
	 	    
 
  }
  @Test(priority=4)
  public void Filter3() throws InterruptedException {
	  	  
	  test=report.startTest("NCR response in last 7 days");
	  w.Filter3(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	//  report.endTest(test);
	  
	 	    
 
  }
  @Test(priority=5)
  public void Filter4() throws InterruptedException {
	  	  
	  test=report.startTest("Jobs compleded in last 7days");
	  w.Filter4(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	 // report.endTest(test);
	  
	 	    
 
  }
  @Test(priority=6)
  public void Filter5() throws InterruptedException {
	  	  
	  test=report.startTest("jobs compleded but not verified");
	  w.Filter5(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	 // report.endTest(test);
	  
	 	    
 
  }
  
  
  @Test(priority=7)
  public void Pending() throws InterruptedException {
	  	  
	  test=report.startTest("counting Pending jobs");
	  w.Pending(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	//  report.endTest(test);
	  
	 	    
 
  }
  
  
  @Test(priority=8)
  public void Completed() throws InterruptedException {
	  	  
	  test=report.startTest("counting Completed jobs");
	  w.Completed(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	//  report.endTest(test);
	  
	 	    
 
  }
  
  @Test(priority=9)
  public void  Reworkes() throws InterruptedException {
	  	  
	  test=report.startTest("counting Re-workes jobs");
	  w. Reworkes(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	 // report.endTest(test);
	  
	 	    
 
  }
  @Test(priority=10)
  public void   Verified() throws InterruptedException {
	  	  
	  test=report.startTest("counting Verified jobs");
	  w.  Verified(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	 // report.endTest(test);
	  
	 	    
	  
  }
  @Test(priority=11)
  public void   overdue() throws InterruptedException {
	  	  
	  test=report.startTest("counting overdue jobs");
	  w. overdue(driver);
	  Assert.assertTrue(true);
      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	 // report.endTest(test);
	  
  }
  @AfterMethod
	public void afterMethod(ITestResult result) {
	    if (result.getStatus() == ITestResult.FAILURE) {
	        test.log(LogStatus.FAIL, "Test failed " + result.getThrowable());
	    } else if (result.getStatus() == ITestResult.SKIP) {
	        test.log(LogStatus.SKIP, "Test skipped " + result.getThrowable());
	    } else {
	        test.log(LogStatus.PASS, "Test passed");
	    }

	    report.endTest(test);
}
	 @AfterTest
	  public void endReport()
	  {
		  report.flush();
		  report.close();
	  }
	 }

class2:
package TestCases;

import java.io.File;

import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.DisplayOrder;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import com.relevantcodes.extentreports.NetworkMode;

import Technical.AddNewJob;

public class AddNewJobTest extends WebDriverPass {
	ExtentReports report;
	ExtentTest test;
	AddNewJob w = new AddNewJob();

	@BeforeSuite
	 public void starttest(){
		
		//ExtentReports report= new ExtentReports ("C:\\Users\\sa\\workspace\\Worklist\\Report.html",false);
		report=new ExtentReports(System.getProperty("user.dir")+"/test-output/WorklistReport14.html",true,DisplayOrder.NEWEST_FIRST, NetworkMode.OFFLINE);
		report.addSystemInfo("HostName","abc")
		.addSystemInfo("Environment","QA");
		report.loadConfig(new File(System.getProperty("user.dir")+"/worklist-config.xml"));
		
	}
	
	@Test(priority = 12)
	public void worklistindex() throws Exception {
		test=report.startTest("worklistindex");  
		w.worklist(driver);
		Assert.assertTrue(true);
   	   test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	  // report.endTest(test);

	}

	@Test(priority = 13)
	public void alerthandling() throws Exception {
		test=report.startTest("alerthandling");  
		w.alerthandling(driver);
		Assert.assertTrue(true);
	   test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
	  // report.endTest(test);
	}
	 @AfterMethod
		public void afterMethod(ITestResult result) {
		    if (result.getStatus() == ITestResult.FAILURE) {
		        test.log(LogStatus.FAIL, "Test failed " + result.getThrowable());
		    } else if (result.getStatus() == ITestResult.SKIP) {
		        test.log(LogStatus.SKIP, "Test skipped " + result.getThrowable());
		    } else {
		        test.log(LogStatus.PASS, "Test passed");
		    }

		    report.endTest(test);
	 }
		 @AfterTest
		  public void endReport()
		  {
			  report.flush();
			  report.close();
		  }
		  
	 }
	 
class3
package TestCases;

import java.io.File;

import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.DisplayOrder;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import com.relevantcodes.extentreports.NetworkMode;

import Technical.EditJob;

public class EditJobTest extends WebDriverPass{
	ExtentReports report;
	ExtentTest test;
	EditJob w=new EditJob();
	
	@BeforeSuite
	 public void starttest(){
	
	//	ExtentReports report= new ExtentReports ("C:\\Users\\sa\\workspace\\Worklist\\Report.html",false);
		report=new ExtentReports(System.getProperty("user.dir")+"/test-output/WorklistReport14.html",true,DisplayOrder.NEWEST_FIRST, NetworkMode.OFFLINE);
		report.addSystemInfo("HostName","")
		.addSystemInfo("Environment","QA");
		report.loadConfig(new File(System.getProperty("user.dir")+"/worklist-config.xml"));
		
	}
	
	  @Test(priority=14)
	  public void WorklistModule() throws Exception  {
		  test=report.startTest("WokrlistModule");
	      w.worklistindex(driver);
	      Assert.assertTrue(true);
	      test.log(LogStatus.PASS, "Assert pass as condtion is true"); 
		 // report.endTest(test);
	  }
	  @AfterMethod
		public void afterMethod(ITestResult result) {
		    if (result.getStatus() == ITestResult.FAILURE) {
		        test.log(LogStatus.FAIL, "Test failed " + result.getThrowable());
		    } else if (result.getStatus() == ITestResult.SKIP) {
		        test.log(LogStatus.SKIP, "Test skipped " + result.getThrowable());
		    } else {
		        test.log(LogStatus.PASS, "Test passed");
		    }

		    report.endTest(test);
	 }
		 @AfterTest
		  public void endReport()
		  {
			  report.flush();
			  report.close();
		  }
	  }
