### ISSUE TITLE
ExtentReports 2.41.0 is not able to generate fresh reports overriding old reports on Linux in offline mode.

### ISSUE THREAD

**Issue by rupamchakraborty** [anshooarora/extentreports-java#851]
## Summary
I'm using ExtentReports 2.41.0 for a project and it has been working flawless on Win OS for 4 months now.
However recently we have set up a CI server, which is a Linux box and when I fire my tests via CI, I see that Extent Reports API is not able to generate fresh reports after the execution on the Linux Box.
I'm using offline mode.

## Current Behavior
I ran the tests on Linux box on 6th April(First ever attempt on this system) - Extent reports were created
Henceforth when I run tests, the existing report is not overridden.
If I delete the existing html report and rerun the test, the html gets created BUT the data it shows is of the test run on 6th april.

## Expected Behavior
I expect the reports to work as it does on my local Win system, i.e. overriding everytime a new test is run.

## Sample
Sorry couldn't provide a reproducible sample, since it's more of an OS issue. Please let me know if anything specific is needed from my end.

## Environment Details
* Extent report Version used: 2.41.0
* Operating System and version: Linux
* JDK Version: 1.8

**Comment by email2vimalraj** [comment]
@rupamchakraborty : After deleting also, you are able to see the existing report sounds very strange. Since we cannot reproduce this problem from our end, I would recommend to seek help from your system administrator and also recommend you to try from another machine which has linux.

Feel free to re-open in case you need further help.

**Comment by rupamchakraborty** [comment]
@email2vimalraj  : Sorry for a wrong observation, here's what is happening
1. I have a html file pushed to svn, named ExtentReport.html (this contains stale test run report)
2. The CI server downloads this file and starts running new test on Linux box
3. After the execution is over, the html file is not overriden.

**Since every-time a build is triggered it downloads the html file containing stale data, i was fooled to believe that it was generated with stale data.  Sorry about this.**

So the problem is -  Extent report is not getting generated at all.
I have ensured that the html file has rwx permissions set on it, but still no go.

Could you please tell me if you're making any specific configuration while testing with Linux at your end?

**Comment by email2vimalraj** [comment]
The report is platform agnostic. It should work exactly same way how it works in windows. And I'm a Linux user using this report almost everyday. There should be something must be happening which is preventing the report to be generated. Just a guess, do you flush at the end of the execution which actually generates the report.

Thanks
Vimalraj

**Comment by rupamchakraborty** [comment]
Yes, I do a flush after all test executions are done, I have a debug statement after the flush which gets printed as well.

Is there a way I can see Extent Report logs to find out more or any debug step you might suggest here?

Thanks,
Rupam.
