### ISSUE TITLE
Can we add a table having the information related to test case pass,fail count

### ISSUE THREAD

**Issue by ManikantaGG** [anshooarora/extentreports-java#852]
Hi  Anshoo,

I have a requirement of showing the below info in a separate table on Extent report dashboard.

Total No of cases
Total Passed
Total Failed
Pass Percentage

Also I need to place this table on the top of dashboard

Can you please guide me on this.

**Comment by ManikantaGG** [comment]
Any help please?

**Comment by email2vimalraj** [comment]
@ManikantaGG : The graphical representation already shows all this information. Adding this table in the dashboard is just a duplicated information.

**Comment by ManikantaGG** [comment]
Thanks for the reply email2vimalraj. Can we hide the chart in dashboard.

**Comment by email2vimalraj** [comment]
You can write your own javascript and hide the chart. Refer [here](http://extentreports.com/docs/versions/3/java/#htmlreporter-configuration).

Ex: `htmlReporter.config().setJS("js string");`
