### ISSUE TITLE
Screenshots not displayed on the same line

### ISSUE THREAD

**Issue by sudhir-shetty** [anshooarora/extentreports-java#855]
## Summary

Screenshots are not on the same line when the screenshot is take, instead its shown on the end of the report.

## Sample

public void LoginAsUser1_Calendar_CorrectDate()
      {
            ExtentTest test = this.extent.CreateTest("DemoReportPass");
            AuthenticationHelper.LoginUser1(Driver);
            test.Log(Status.Pass,"Login successfull.");
            test.Log(Status.Info,"SS"+ test.AddScreenCaptureFromPath(Capture(Driver, "2creenShotName")));
            NavigateTo.CalendarPage(Driver);
            test.AddScreenCaptureFromPath(Capture(Driver, "2creenShotName2"));
            Driver.FindElement(CalendarSelectors.LevelOptionLand).Click();
}

## Environment Details

* Extent report Version used: 3.0.2.0 C#
* Operating System and version: windows 10
* JDK Version:

## Screenshots
![screenshot](https://cloud.githubusercontent.com/assets/3128101/25137221/6658de26-2457-11e7-92df-98094a6fb618.png)

**Comment by anshooarora** [comment]
Simply insert the screenshot at the log level.  [link](http://extentreports.com/docs/versions/3/java/#insert-screenshots)

```
// adding screenshots to log
test.fail("details", MediaEntityBuilder.createScreenCaptureFromPath("screenshot.png").build());

// or:
MediaModelProvider mediaModel = MediaEntityBuilder.createScreenCaptureFromPath("screenshot.png").build();
test.fail("details", mediaModel);
```

**Comment by SwathiReddygovind** [comment]
@anshooarora 
Hi,
Can I have column image next to Details .if so could please tell me how it is possible
