### ISSUE TITLE
How to add custom table to the report?

### ISSUE THREAD

**Issue by vrajan785** [anshooarora/extentreports-java#856]
I want a custom table with tr,td to be added to report. 
I have defined the html table in extent-config.xml but not useful. Is there any way to use this feature.

Actually, i want the report will show the content as below in tabular format:

![image](https://cloud.githubusercontent.com/assets/25080594/25277663/3e094d94-26bd-11e7-90ec-04cacb90ed9d.png)

I have n- number of records to show in the report. How to do it in extent. 
I tried to add the custom html in extent-config.xml file with the below code. But it adds to div class test steps. I want this to be declared separately. 

```
 <!-- custom javascript -->
    <scripts>
<![CDATA[
			$('<table><tr><th><td><b>Name</b></td></th><th><td><b>Employee ID</b></td></th><th><td><b>Phone</b></td></th><th><td><b>STATUS</b></td></th></tr></table>').appendTo( '.test-steps' );
		]]>
 </scripts>
```

Please provide your inputs as it is required on urgent.

**Comment by email2vimalraj** [comment]
@vrajan785 : Kindly raise the issue with the given issue template. Because we are not sure which version are you using?

Edit your issue and format based on the issue template.

**Comment by vrajan785** [comment]
I am using extent report 2.40

**Comment by email2vimalraj** [comment]
@vrajan785 : Are you not comfortable with the [issue template](https://github.com/anshooarora/extentreports-java/blob/master/ISSUE_TEMPLATE.md) which is in place?

It would be great for us to improve based on your feedback.

**Comment by vrajan785** [comment]
I have created new issue template. https://github.com/anshooarora/extentreports-java/issues/860

**Comment by email2vimalraj** [comment]
Closing this in favor of #860
