### ISSUE TITLE
Applet Warning message

### ISSUE THREAD

**Issue by garlapati99** [anshooarora/extentreports-java#859]
Hi

I am trying to run selenium 2.53.1 with extent reports 2.05 and i am getting the below warning message everytime

the applet is attempting to invoke the java/lang/system.getproperty() operation on user.name

On Allow it works fine. How to remove this applet warning. 

Thanks

**Comment by email2vimalraj** [comment]
As far as I know, ExtentReport is not using Applet anywhere.

@anshooarora : Can you please assist this?

**Comment by anshooarora** [comment]
@email2vimalraj  -  I think this is possibly because some of the system variables are written to the report such as "user.name".  

@garlapati99  -  Are you on Windows?  What variant, x86 x64?  Is your Java version the same as your OS version?
