### ISSUE TITLE
How to add custom table to extent report?

### ISSUE THREAD

**Issue by vrajan785** [anshooarora/extentreports-java#860]
## Summary

I want a custom table with tr,td to be added to report.
I have defined the html table in extent-config.xml but not useful.

**extent-config.xml**
```
 <!-- custom javascript -->
    <scripts>
<![CDATA[
			$('<table><tr><th><td><b>Name</b></td></th><th><td><b>Employee ID</b></td></th><th><td><b>Phone</b></td></th><th><td><b>STATUS</b></td></th></tr></table>').appendTo( '.test-steps' );
		]]>
 </scripts>
```
## Expected Behavior

Actually, i want the report will show the content as below in tabular format:

image

I have n- number of records to show in the report. How to do it in extent.
I tried to add the custom html in extent-config.xml file with the below code. But it adds to div class test steps. I want this to be declared separately. 

![image](https://cloud.githubusercontent.com/assets/25080594/25469538/6637c86e-2b3a-11e7-9b25-672852471a69.png)

The behaviour should be like : 
test.addTable(no. of rows, no of columns, "HTML tag to be added with css element defined in extent-config.xml file");
test.addRowToTable("dynamic-row-id", "row data", "test case pass/fail status");

## Current Behavior
The table is not added properly with extent config.xml modification.

I tried to add the table but it gets added like below : 

![image](https://cloud.githubusercontent.com/assets/25080594/25469752/e65779e4-2b3b-11e7-9327-6eb3dcba76b8.png)

## Environment Details
* Extent report Version used: 2.40
* Operating System and version: Windows 7
* JDK Version: 1.8

**Comment by email2vimalraj** [comment]
@vrajan785 : From 3.x, extent report gives you the capability to create the table using Markup. You could try this:

```java
test.log(MarkupHelper.createTable(String[][] data));
```

Please refer (here)[http://extentreports.com/docs/versions/3/java/#markup-helpers]

Kindly re-open in case you need more help.

**Comment by amithmahi** [comment]
Can i add a new field along with Status,TimeStamp and Details

Like Status, TimeStamp, Details, Comments 

Also i have columns spannign more than one 1 columns , createTable doesnt allow for more than one column. how can i address this
