### ISSUE TITLE
No getReportId method found in extent reports v3.0.5

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentreports-java#862]

**Comment by anshooarora** [comment]
Ouch.  It seems to have been removed with one of the recent commits.  Marking as bug, feature to be available in 3.0.6.  ExtentXReporter to implement:

```
    public ObjectId getProjectId() {		
        return projectId;		
     }		
 			
    public ObjectId getReportId() {		
        return reportId;		
    }
```

**Comment by kvaghani87** [comment]
Hi Anshoo,

I am getting NULL return value on getReportId. can you please help me I am calling as following

ExtentXReporter extentxReporter = null;
System.out.print("\n REPORT extentxReporter.getReportId : " + extentxReporter.getReportId());

**Comment by anshooarora** [comment]
Your reporter is null:

```
ExtentXReporter extentxReporter = null;
```
