### ISSUE TITLE
Unable to See the pass percentage graph in Dashboard 

### ISSUE THREAD

**Issue by ManikantaGG** [anshooarora/extentreports-java#863]
Hi, @anshooarora @email2vimalraj ,
I am using extent report version 3.0.5 and i am not seeing the Pass Percentage in the dashboard. In Earlier versions it was showing.

Can you please help me on this.

THanks,
Manikanta

**Comment by anshooarora** [comment]
If you do a mouseover on the element in the dashboard, you will see these percentages.

![passpercentage](https://cloud.githubusercontent.com/assets/4107384/25719635/182a82f8-30d8-11e7-9d7d-24a65258f8e7.png)
