### ISSUE TITLE
Parallel Execution of Cucumber-Junit Tests is over writing test results

### ISSUE THREAD

**Issue by TDAngOMSQA** [anshooarora/extentreports-java#866]
Parallel Execution of Cucumber-Junit Tests is over writing test results

I'm using Extent Reports with our Cucumber-Jnuit Tests. I have several Cucumber features which we run using Junit runners. Each Junit runner invokes a Base Test Class where the Extent Report is Instantiated. 
When I run these tests in sequence Results are appended correctly in the Extent Report. However, when I run them in parallel, I only see the results of the last Junit Test.

## Expected Behavior
Results of all Junit Tests appended to one report

## Current Behavior
Results of from last junit run is only available when tests are run in parallel. Running them in sequence gives desired results

## Sample
Extent Manager Class-->
public class ExtentManager {
	
	static Map<Integer, ExtentTest> extentTestMap = new HashMap<Integer, ExtentTest>();
	
    public static ExtentReports reports;
    public static ExtentTest test;
   
    public static ExtentReports createInstance(String location, String fileName) {
        
    	ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(location + fileName + ".html");
        htmlReporter.setAppendExisting(true);
        htmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
        htmlReporter.config().setChartVisibilityOnOpen(true);
        htmlReporter.config().setTheme(Theme.STANDARD);
        htmlReporter.config().setDocumentTitle("NGOMS CLIENT API TEST RESULTS");
        htmlReporter.config().setEncoding("utf-8");
        htmlReporter.config().setReportName(fileName);
       
        reports = new ExtentReports();
        reports.attachReporter(htmlReporter);
        
        return reports;
    }
    
    public static  ExtentTest getTest() {
        return extentTestMap.get((int) (long) (Thread.currentThread().getId()));
    }

    public static  ExtentTest startTest(String testName) {
        ExtentTest test = reports.createTest(testName);
        extentTestMap.put((int) (long) (Thread.currentThread().getId()), test);

        return test;
    }
}

Jnuit Test Classes

@RunWith(Cucumber.class)
@CucumberOptions(
		features = "src/main/java/features/smoke/orderentry/OrderEntryAdvanced.feature",
		format = { "pretty","html:target/OrderEntryAdvanced","json:target/OrderEntryAdvanced.json" },
		tags = {"@OrderEntryAdvanced"},
		glue = "stepdefinitions.orderentry.advanced")
public class OrderEntryAdvanced  {

	@BeforeClass
	public static void setUp() throws IOException, Exception{

		TestVariable.testType = "smoke";
		TestVariable.testSet = "AdvancedOrder";
		TestVariable.suiteName = "OrderEntry";
		BaseTest.testSetup("OrderEntry", "OrderEntry");
	}
}

@RunWith(Cucumber.class)
@CucumberOptions(
		features = "src/main/java/features/smoke/orderentry/OrderEntryEquityCashAccount.feature",
		format = { "pretty","html:target/OrderEntryEquityCashAccount","json:target/OrderEntryEquityCashAccount.json" },
		tags = {"@OrderEntryEquity"},
		glue = "stepdefinitions.orderentry.equity")
public class OrderEntryEquityCashAccount  {

	@BeforeClass
	public static void setUp() throws IOException, Exception{

		TestVariable.testType = "smoke";
		TestVariable.testSet = "EquityOrder";
		TestVariable.suiteName = "OrderEntry";
		BaseTest.testSetup("OrderEntry", "OrderEntry");
	}
}

Extent Manager Invocation in BaseTest class-->

	public static void testSetup(String suiteName, String feature) throws Exception{
		
TestVariable.resultDirectory = TestVariable.getConfig().get("resultDirectory")+"/"+suiteName+"/";
			ExtentManager.reports = ExtentManager.createInstance(TestVariable.resultDirectory, feature);
			ExtentManager.reports.setSystemInfo("Details", TestVariable.testType+"|"+TestVariable.prodAM+"|"+TestVariable.environment);
	}

## Environment Details
* Extent report Version used: 3.0.5
* Operating System and version: Windows 7
* JDK Version: 1.8.0_121

**Comment by anshooarora** [comment]
```
ExtentManager.reports = ExtentManager.createInstance(TestVariable.resultDirectory, feature);
```

So you need a different report for each feature, correct?

**Comment by TDAngOMSQA** [comment]
Appreciate your quick response.
No, I would like to get one report for a set of features. Able to generate separate report for each feature without any issues. It appends to the report correctly if i run the tests in sequence. However, when I run the tests in parallel using Maven forked profile i only see the tests pertaining to last feature in the report.

In the above code I have attached. Suppose, I run EquityOrder and AdvancedOrder feature in sequence I see all test cases for each feature correctly in report. But, when i run them in parallel I see report has only test cases for the feature which finished last.

**Comment by anshooarora** [comment]
Replace this:

```
ExtentManager.reports = ExtentManager.createInstance(TestVariable.resultDirectory, feature);
```

with:

```
if (ExtentManager.getInstance() == null)
    ExtentManager.createInstance(TestVariable.resultDirectory, feature);

ExtentManager.getInstance().setSystemInfo("Details", TestVariable.testType+"|"+TestVariable.prodAM+"|"+TestVariable.environment);
```

**Comment by TDAngOMSQA** [comment]
So, i made these changes

added getInstance method to ExtentManager class
public static ExtentReports getInstance(){ return reports; }

and this change but still same result. Only last runs results are in report.
			if (ExtentManager.getInstance() == null){
				ExtentManager.reports =   ExtentManager.createInstance(TestVariable.resultDirectory, feature);
				ExtentManager.getInstance().setSystemInfo("Details", TestVariable.testType+"|"+TestVariable.prodAM+"|"+TestVariable.environment);
			}

**Comment by anshooarora** [comment]
Did the above changes work?

Also,  you don't need to do this:

```
ExtentManager.reports = ExtentManager.createInstance(TestVariable.resultDirectory, feature);
```

only:

```
ExtentManager.createInstance(TestVariable.resultDirectory, feature);
```

`reports` should be a private member of the class.  You shouldn't access it directly as you are doing.

**Comment by TDAngOMSQA** [comment]
Changed as per your suggestion. Still the same results. It only reports last test results.
Added a print statement while initializing the report. Its trying to create a new instance of the report with each test.

		if (ExtentManager.getInstance() == null){
			ExtentManager.createInstance("TestResult/OrderEntry/", "Test");
			
			System.out.print("\n Test 2 Instance is NULL");
		}

**Comment by anshooarora** [comment]
Can you use this:  https://github.com/email2vimalraj/CucumberExtentReporter.  It will be much easier to build reports.. 

With TestNG, you can use any of the approaches outlined here:  http://extentreports.com/docs/versions/3/java/#testng-examples
