### ISSUE TITLE
How to add Beforeclass/BeforeMethod or AfterClass or Aftermethod failures info to extent report?

### ISSUE THREAD

**Issue by sridharreddy123** [anshooarora/extentreports-java#867]
How to add Beforeclass/BeforeMethod or AfterClass or Aftermethod failures info to extent report?

**Comment by anshooarora** [comment]
Can you inject `ITestResult` in `@AfterClass` and see if that works?  Or mark your test as `alwaysRun=true`.  If it still doesn't work, I would recommend checking StackOverflow or TestNG repo as this is a TestNG question.
