### ISSUE TITLE
TestNG's Parallel Testing and Extent Reports

### ISSUE THREAD

**Issue by Chardeezus** [anshooarora/extentreports-java#868]
Hi, I'm new to both Automation and TestNG

I was able to generate a report using ExtentReports but when I implemented the parallel testing, only the last driver are recorded in my reports

```
`public class VerifyLaraAdminLogin2 {
	
	ExtentReports report;
	ExtentHtmlReporter html;
	ExtentTest test;
	WebDriver driver;
	DateFormat dateformat = new SimpleDateFormat("MM-dd-yyyy HHmmss");
	Date date = new Date();
	WebDriverWait wait;
	String newDir = "C://Java//Java_Tutorial//Page_Object_Model//Screenshots//"+dateformat.format(date);
	
	@BeforeClass
	@Parameters("browser")
	public void initialize(String browser)
	{
		
		html = new ExtentHtmlReporter("C:/Java/Java_Tutorial/Page_Object_Model/Reports/MyOwnReport"+dateformat.format(date)+".html");
		report = new ExtentReports();
		report.attachReporter(html);
		html.config().setTheme(Theme.DARK);
		html.config().setDocumentTitle("Lara Admin Login Test");
		File dir = new File(newDir);
		dir.mkdir();
		
		if(browser.equalsIgnoreCase("firefox"))
		{
			driver = new FirefoxDriver();
		}
		else if(browser.equalsIgnoreCase("chrome"))
		{
			System.setProperty("webdriver.chrome.driver", "C:/Webdrivers/chromedriver.exe");
			driver = new ChromeDriver();
		}
		
	}`
```

that above is how i instantiate my reports but the testNG settings is like this

```
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Lara Admin Test Suites">
  <test name="Lara Admin Firefox">
        <parameter name="browser" value="firefox"/>
    <classes>

      <class name="com.laraadmin.TestScripts.VerifyLaraAdminLogin2"/>
    </classes>
  </test> <!-- Lara Admin -->
  <test name="Lara Admin Chrome">
  
        <parameter name="browser" value="chrome"/>
    <classes>
      <class name="com.laraadmin.TestScripts.VerifyLaraAdminLogin2"/>
    </classes>
  </test> <!-- Lara Admin -->  
</suite> <!-- Lara Admin Test Suites -->

```

how do i instantiate only once while the testNG calls my classes twice?

**Comment by Chardeezus** [comment]
I tried having a dynamic test name but it really only records my last driver execution

```
	@Test
	@Parameters("browser")
	public void verifyValidLogin(String browserName)
	{
		
		String testName = "Invalid Login for "+browserName; 
		test = report.createTest(testName);
		
		wait = new WebDriverWait(driver,5);
		
		driver.get("http://dev.backoffice.com/login");
}
```

**Comment by anshooarora** [comment]
What you need to do is:

```
public class ExtentManager {
    
    static ExtentReports extent;
    
    public static ExtentReports getInstance() {	
        return extent;
    }
    
    public static synchronized ExtentReports createInstance(String fileName) {
        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(fileName);
        htmlReporter.config().setTestViewChartLocation(ChartLocation.BOTTOM);
        htmlReporter.config().setChartVisibilityOnOpen(true);
        htmlReporter.config().setTheme(Theme.DARK);
        htmlReporter.config().setDocumentTitle("Lara Admin Login Test");
        htmlReporter.config().setEncoding("utf-8");
        htmlReporter.config().setReportName(fileName);

        extent = new ExtentReports();
        extent.attachReporter(htmlReporter);
        
        return extent;
    }
    
}

public class ExtentTestManager {

    private static ThreadLocal<ExtentTest> extentTest;
    private static ExtentReports extent = ExtentManager.getInstance();

    public synchronized static ExtentTest getTest() {
        return extentTest.get();
    }

    public synchronized static ExtentTest createTest(String name, String description, String category) {
        ExtentTest test = extent.createTest(name, description);

        if (category != null && !category.isEmpty())
            test.assignCategory(category);

        extentTest.set(test);

        return getTest();
    }

    public synchronized static ExtentTest createTest(String name, String description) {
        return createTest(name, description, null);
    }

    public synchronized static ExtentTest createTest(String name) {
        return createTest(name, null);
    }

    public synchronized static void log(String message) {
        getTest().info(message);
    }

}

public class VerifyLaraAdminLogin2 {
	
	ExtentReports report;
	ExtentHtmlReporter html;
	ExtentTest test;
	WebDriver driver;
	DateFormat dateformat = new SimpleDateFormat("MM-dd-yyyy HHmmss");
	Date date = new Date();
	WebDriverWait wait;
	String newDir = "C://Java//Java_Tutorial//Page_Object_Model//Screenshots//"+dateformat.format(date);
	
	@BeforeClass
	@Parameters("browser")
	public void initialize(String browser)
	{
		if (ExtentManager.getInstance() == null)
			ExtentManager.createInstance("C:/Java/Java_Tutorial/Page_Object_Model/Reports/MyOwnReport"+dateformat.format(date)+".html");

		File dir = new File(newDir);
		dir.mkdir();
		
		if(browser.equalsIgnoreCase("firefox"))
		{
			driver = new FirefoxDriver();
		}
		else if(browser.equalsIgnoreCase("chrome"))
		{
			System.setProperty("webdriver.chrome.driver", "C:/Webdrivers/chromedriver.exe");
			driver = new ChromeDriver();
		}
		
	}
	
}
```

and then, in your test:

```
@Test
@Parameters("browser")
public void verifyValidLogin(String browserName)
{
	
	String testName = "Invalid Login for "+browserName; 
	ExtentTestManager.createTest(testName);
	
	wait = new WebDriverWait(driver,5);
	
	driver.get("http://dev.backoffice.com/login");
}
```

in `@AfterMethod`:

```
@AfterMethod
public synchronized void afterMethod(ITestResult result) {
	if (result.getStatus() == ITestResult.FAILURE)
		ExtentTestManager.getTest().fail(result.getThrowable());
	else if (result.getStatus() == ITestResult.SKIP)
		ExtentTestManager.getTest().skip(result.getThrowable());
	else
		ExtentTestManager.getTest().pass("Test passed");

	ExtentManager.getInstance().flush();
}
```

**Comment by Suvin1987** [comment]
Hi Anshoo,

I was following your approach and I am getting null pointer exception while setting  extentTest.set(test) in createTest method. Can you please help me with this?

**Comment by harsh976** [comment]
Can some one help solving the parallel execution and generating the extent report or share the sample code .
I am stuck on getting the child object to test class.

I am using Ittestlistner so bascially on test start i am creating the parent and adding chid to it.

What i want is get the child object in test class so that i can append the extent steps fot my test cases.

Currently running parallel it overites the child object when i try to return the same

@anshooarora please help

**Comment by harsh976** [comment]
@Override
	public synchronized void onTestStart(ITestResult result) {
		ExtentTest child = parentTest.get().createNode(result.getMethod().getMethodName());
test.set(child);

I want this child in my test class as i want to add steps 
Can someone give some suggestion

**Comment by VasaviUppada** [comment]
Im having the same issue. 
When I'm not using threadlocal, all reports looks good for sequential execution. when Im trying to run tests in parallel, all extent reports logs are mixing up. 
Then I started creating ThreadLocal. 

@Override
public synchronized void onTestStart(ITestResult result) {
	ExtentTest child = parentTest.get().createNode(result.getMethod().getMethodName());
test.set(child);

My tests are failing at this point as a NullPointerException & it is not creating any nodes.

**Comment by VasaviUppada** [comment]
I tried above code....
it is failing at **extentTest.set(test);**
Null Pointer Exception

**Comment by t-node** [comment]
Any update on this issue @anshooarora , I am also getting null pointer exception. I have to run my tests in parallel.

**Comment by HemaChaith** [comment]
Hi  @anshooarora / All   - Even struck with same issue , is there any progress on this / solution for this , same as above getting null pointer exception

**Comment by t-node** [comment]
@HemaChaith:, try with  private static ThreadLocal<ExtentTest> extentTest=new ThreadLocal<>(); inside the extenttestmanager. It worked for me that way

**Comment by gseera002c** [comment]
Its working fine when i add this ThreadLocal extentTest=new ThreadLocal<>(); @HemaChaith @Chardeezus

**Comment by sa-lkarenski** [comment]
@t-node or @gseera002c can you please share final code, I can't make it work for me (getting bunch of TestNG errors). 
Thanks!

**Comment by t-node** [comment]
import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;

import java.util.*;
import com.aventstack.extentreports.Status;
import org.apache.commons.lang3.tuple.Triple;
import org.apache.log4j.Logger;

public class ExtentTestManager {
    private static final Logger logger = Logger.getLogger(ExtentTestManager.class);
    private static ThreadLocal<ExtentTest> extentTest=new ThreadLocal<>();
    private static ExtentReports extent = ExtentManager.getInstance();
    private static ThreadLocal<List<String>> listOfScreenshots=new ThreadLocal<>();

    public synchronized static ExtentTest getTest() {
        return extentTest.get();
    }
    public synchronized static List<String> getScreenShotLst() {
        return listOfScreenshots.get();
    }

    public synchronized static ExtentTest createTest(String name, String description, String category) {

        ExtentTest test = extent.createTest(name, description);

        List<String> screenShotsLst=new ArrayList<String>();
        listOfScreenshots.set(screenShotsLst);
        if (category != null && !category.isEmpty())
            test.assignCategory(category);

        extentTest.set(test);

        return getTest();
    }

    public synchronized static ExtentTest createTest(String name, String description) {
        return createTest(name, description, null);
    }

    public synchronized static ExtentTest setAuthorInfo(Triple authorInfo ){
        ExtentTestManager.getTest().assignAuthor(authorInfo.getMiddle().toString());
        return getTest();
    }
    public synchronized static ExtentTest createTest(String name) {
        return createTest(name, null);
    }

    public synchronized static void log(Status s1,String message) {
        getTest().log(s1,message);
    }
    public synchronized static void logWithScreenShot(Status s1,String message,String path) {
       try {
           getTest().log(s1, message).addScreenCaptureFromPath(path,"title");
       }
       catch (Exception e){
           e.printStackTrace();
       }

    }
}

**Comment by t-node** [comment]
@sa-lkarenski 

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;

import java.util.*;
import com.aventstack.extentreports.Status;
import org.apache.commons.lang3.tuple.Triple;
import org.apache.log4j.Logger;

public class ExtentTestManager {
    private static final Logger logger = Logger.getLogger(ExtentTestManager.class);
    private static ThreadLocal<ExtentTest> extentTest=new ThreadLocal<>();
    private static ExtentReports extent = ExtentManager.getInstance();
    private static ThreadLocal<List<String>> listOfScreenshots=new ThreadLocal<>();

    public synchronized static ExtentTest getTest() {
        return extentTest.get();
    }
    public synchronized static List<String> getScreenShotLst() {
        return listOfScreenshots.get();
    }

    public synchronized static ExtentTest createTest(String name, String description, String category) {

        ExtentTest test = extent.createTest(name, description);

        List<String> screenShotsLst=new ArrayList<String>();
        listOfScreenshots.set(screenShotsLst);
        if (category != null && !category.isEmpty())
            test.assignCategory(category);

        extentTest.set(test);

        return getTest();
    }

    public synchronized static ExtentTest createTest(String name, String description) {
        return createTest(name, description, null);
    }

    public synchronized static ExtentTest setAuthorInfo(Triple authorInfo ){
        ExtentTestManager.getTest().assignAuthor(authorInfo.getMiddle().toString());
        return getTest();
    }
    public synchronized static ExtentTest createTest(String name) {
        return createTest(name, null);
    }

    public synchronized static void log(Status s1,String message) {
        getTest().log(s1,message);
    }
    public synchronized static void logWithScreenShot(Status s1,String message,String path) {
       try {
           getTest().log(s1, message).addScreenCaptureFromPath(path,"title");
       }
       catch (Exception e){
           e.printStackTrace();
       }

    }
}
