### ISSUE TITLE
Unable to get Feature and Scenarios pie chart in the dashbord

### ISSUE THREAD

**Issue by karthikeselene** [anshooarora/extentreports-java#869]
Hi Vimalraj,

I'm unable to get Feature and Scenarios pie chart in the dashbord. Shall I made any mistakke???

below one was sample report from extentreport BDD

![b2fcea74-2a9c-11e7-8aff-4feaa7d4a616](https://cloud.githubusercontent.com/assets/20849273/25793682/3b753814-33eb-11e7-99d1-a64ae86f1550.png)

**Comment by anshooarora** [comment]
Are you using https://github.com/email2vimalraj/CucumberExtentReporter?

**Comment by karthikeselene** [comment]
Yeap! @anshooarora I am using those report only

**Comment by anshooarora** [comment]
Can you please post here and seek Vimal's help?  https://github.com/email2vimalraj/CucumberExtentReporter

He is the developer of this plugin and may be able to assist you much better.  You can upgrade to the latest version and give it a shot before posting.  Cheers.
