### ISSUE TITLE
How can we set default view in left hand side menus?

### ISSUE THREAD

**Issue by neajay** [anshooarora/extentreports-java#872]
## Expected Behavior

I am using extent 2.41 version. When I open the report by default it’s opening in the Tests menu tab. Will it possible to change this default viewing. That means I want open default view as dash board view. Please let me know how can I achieve this one or higher versions having this feature? 

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by lol666666** [comment]
mark

**Comment by anshooarora** [comment]
Add this to your configuration js:

```
$('a.dashboard-view').click();
```
