### ISSUE TITLE
BDD Report:  Add an additional level for ScenarioOutline

### ISSUE THREAD

**Issue by anshooarora** [anshooarora/extentreports-java#874]
## Summary

At present, for the BDD report there is no way to add another level in case of a scenario outline.  A new level is required in the template to enable this.

## Expected Behavior

ScenarioOutline and its dedicated tree must be available.

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:  3+
* Operating System and version:  All
* JDK Version:  8

**Comment by prasanta-biswas** [comment]
@anshooarora can you add some sample code?

**Comment by anshooarora** [comment]
See here:  https://github.com/email2vimalraj/CucumberExtentReporter/pull/49.  You can run the tests here and see the output being created.
