### ISSUE TITLE
Anyone here, how to change body background extentreports version 3.0.6 ?

### ISSUE THREAD

**Issue by VirTuanNguyen** [anshooarora/extentreports-java#880]
in version 3.0.6, the background is too dark.
I have to tried to changed it using:

## m_HtmlReporter.config().setCSS(css);

--> It isn't working.

Please., thanks

**Comment by anshooarora** [comment]
What do you mean? Are you using the dark theme or standard?  Please share config.xml.

**Comment by VirTuanNguyen** [comment]
Hi anshooarora, it's great! below is the details of code:

private static void initHTMLReports() {
	m_HtmlReporter = new ExtentHtmlReporter("PantheraReport.html");
	m_HtmlReporter.config().setDocumentTitle("Panthera");
	m_HtmlReporter.config().setEncoding("UTF-8");
	m_HtmlReporter.config().setProtocol(Protocol.HTTPS);
	m_HtmlReporter.config().setReportName("PantheraTestReport");
	m_HtmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
	m_HtmlReporter.config().setTheme(Theme.DARK);

	String css = "body { background: #eceff5; font-size: 13px; height: 100%; overflow: hidden; };";
	m_HtmlReporter.config().setCSS(css);
}

Expected: Background of body will change.
I don't know how to get it.
Thanks anshooarora.

**Comment by anshooarora** [comment]
Simply remove this line:

```m_HtmlReporter.config().setTheme(Theme.DARK);```

or use:

```
m_HtmlReporter.config().setTheme(Theme.STANDARD);
```
