### ISSUE TITLE
How to update previous step in extent Report

### ISSUE THREAD

**Issue by KalveeduVijay** [anshooarora/extentreports-java#881]
Here is a sample scenario.

Step 1: Open gmail.com
Step 2: Input username.
Step 3: Input password.
Step 4: Click on button.

Note: I'm appending screenshot in report for every step.

Assume, I'm or my pointer is on step 3. At this point, it is understandable that till step 2 has been executed.  Now for some reason, if I'm willing to update my screenshot in step 2( Like Previous step or navigating back to previous step ) , is it achievable in extentReport? 
Any other suggestions which can possible make it happen?

I may be crazy, but any suggestions or thoughts is highly appreciable.  You may even respond if it is an impossible one and not recommended etc etc...

**Comment by anshooarora** [comment]
Version?

**Comment by KalveeduVijay** [comment]
I'm currently using 2.41.1 free version. I can ok to upgrade to 3.0 if I have option to use it...

**Comment by anshooarora** [comment]
I would recommend upgrading to version 3.  You can:

```
ExtentTest test = extent.createTest("MyTest");
test.pass("Step 1");
test.pass("Step 2");

// update Step 1
test.getModel().getLogContext().get(0).setDetails("New Details");
```

**Comment by KalveeduVijay** [comment]
Hi @anshooarora ,

Thank you so mucn for your time. Apologize for my ignorance. I'm using start test and end test. What's the purpose of createTest? what do you mean by test.pass etc-> is that about logging.
May I request your time to have a look into way I log the report? Can you guide me with required changes?

	    public static void generateReport(String status){
	    	
	    	if(status.contains("Passed")){
	    		
	    		
	    		logger.debug("Status marked in Pass block : " + statusFlag);
	    		constants.extentTest.log(Log.PASS, useCase   , "<font size="+3+" color='#7CFC00'>"+statusFlag +"</font>"+ " <br />" +expectedResult);
	    		
	    	}else if(status.contains("Fail"))
	    	{
	    		String 	q= status;
	    		String screenshotPath= reusuableFunctions.captureScreenshot();
	    		String imageOfFailed = constants.extentTest.addScreenCapture(screenshotPath);
	    		logger.debug(imageOfFailedScenario);
	    		logger.debug("Status marked in Fail block : " + status);
	    		constants.extentTest.log(LogStatus.FAIL, 
	    								 useCase, 
	    								 "<span  title='"+constants.status.replaceAll("'", "&#39;")+"'><a href='"+constants.logsPath+"/Framework.log'><font size="+3+" color='#DC143C'>FAILED</font></a></span>"+
	    								  imageOfFailed);
	    		
	    	
	    		
	    	}else{
	    		
	    		logger.debug("skipped" + statusFlag); 
	    		constants.extentTest.log(LogStatus.SKIP, useCase, status);
	    	}
	    	
	    }

**Comment by KalveeduVijay** [comment]
@anshooarora , My use is to update the screenshot of previous step.

**Comment by KalveeduVijay** [comment]
@anshooarora  : I totally understand my ignorance. Your time and help will matter a lot... Can you spend a minute for me?

**Comment by anshooarora** [comment]
Please see version 3 docs:

http://extentreports.com/docs/versions/3/java/

```
ExtentTest test = extent.createTest("MyTest");
test.pass("Step 1");
test.pass("Step 2");

// update Step 1
test.getModel().getLogContext().get(0).setDetails("New Details");

// update Step 2
test.getModel().getLogContext().get(1).setDetails("New Details");
```

My previous example shows how you can update step 1 after reporting it.  You can use `.fail` `.error` depending on the status you want to report, using `.pass` was just an example.

To insert an image, see here:  http://extentreports.com/docs/versions/3/java/#insert-screenshots

**Comment by KalveeduVijay** [comment]
Hi,
Sorry to reply late. I tried with 3.0.6.
I'm encountering classNotFoundExeption in extent.flush() method .Let me know if I'm missing anything
