### ISSUE TITLE
Not able to copy content from Extent Report HTML file because of category shortcut

### ISSUE THREAD

**Issue by manojkumargudala** [anshooarora/extentreports-java#886]
## Summary

As a general user when we try to copy some content from Extent HTML file using COMMAND+C(General copy shortcut in MAC) instead of copy it is going to category-view as we are setting the C for category view

## Expected Behavior

User should be able to copy any content from report

## Current Behavior

When I press COMMAND+C it is going to category-view instead of copying the content

## Environment Details

* Extent report Version used: 3.0.6
* Operating System and version: MAC

**Comment by apetkova** [comment]
Hello,

I see the issue is supposed to be fixed, but I'm using version 3.1.3 and I am still experiencing it. Am I doing something wrong, or is this reverted somehow in the latest versions?

**Comment by anshooarora** [comment]
OS?

**Comment by apetkova** [comment]
OSX Sierra

**Comment by anshooarora** [comment]
Can you send a pull request for this?

https://github.com/anshooarora/extentreports-java/blob/master/dist/js/extent.js#L95

**Comment by apetkova** [comment]
Thanx, can try to do so next week.
