### ISSUE TITLE
ExtentReport 3.0 NOT creating a new HTML file

### ISSUE THREAD

**Issue by rkmatrix** [anshooarora/extentreports-java#888]
I'm using extent report 3.0.6.

My scenario is to generate a new html log file whenever I run a test.

Till extent report 2.45, a new html file is created by new ExtentReports(filepath, false);

But in 3.0.6 html file is not getting created when I give a new file path. I need to create a file using new File(log.html) and then create a new extentreport.

**Comment by saikiran40cs** [comment]
@rkmatrix I guess this can be of your help
https://github.com/saikiran40cs/KiranExtentFramework/blob/master/src/operations/ExtentManager.java

It is just a sample and to call the extentmanager
refer https://github.com/saikiran40cs/KiranExtentFramework/blob/master/src/reUsableFunctions/RegressionFunc.java

If in case the above does not solve your issue.
Refer the documentation of extentreports has much more information than this.

**Comment by anshooarora** [comment]
Closing as no response from OP.
