### ISSUE TITLE
How to log request and params sent to restassured framework in extent report.

### ISSUE THREAD

**Issue by NaveenAutomate** [anshooarora/extentreports-java#889]
I am trying to use extent report with restassured.

In reatassured there is default logConfig as syatem.out and to print request and params we have to rely on RestAssured, i am not able to put that log in extent report.

Response object we get so i am able to log into extent report.

**Comment by NaveenAutomate** [comment]
i figured out a way by overriding PrintStream. Closing this issue

**Comment by Naimadnap** [comment]
@NaveenAutomate could you share the solution?

**Comment by NaveenAutomate** [comment]
public class OverridePrintStream extends PrintStream{
	public OverridePrintStream(PrintStream original) {
		super(original);
	}

	@Override
	public void println(String line) {
		StackTraceElement[] stack = Thread.currentThread().getStackTrace();
		// Element 0 is getStackTrace
		// Element 1 is println
		// Element 2 is the caller
		StackTraceElement caller = stack[2];
		ExtentTest extnTest3_0 = TestBase.getExtentTestV3X();//get the test object 
		if(extnTest3_0!=null){
			String prettyPrint = line.replace("\n", "<br>");
			extnTest3_0.info("<pre>" + prettyPrint + "</pre>");
		}
		super.println(caller.getClassName() + ": " + line);
	}
}

and you have use System.setout(PrintStream.out) in your test classes.

**Comment by ansonliao** [comment]
@NaveenAutomate 
Hi sir, could you provide more details about your solution?
I found it is failed to `System.setOut(PrintStream.out)`.

Could you advise?

**Comment by NaveenAutomate** [comment]
in class where you want the syso to be on extent, please use below statement.

System.setOut(new OverridePrintStream(System.out));

**Comment by ansonliao** [comment]
@NaveenAutomate thanks for your reply, I found my root cause of my custom `PrintStream` as no method call `fluen()` `ExtentReports` finally, so no html report export

**Comment by dzygmuntowiczATsiili** [comment]
@NaveenAutomate or @ansonliao have some of you why it didn't work in AfterClass method?
I have this same initializing code in before and after class method but it works only in before class.
