### ISSUE TITLE
How to change the Graph Heading(Step View)/ How to filter the graphs on the basic of selected Test

### ISSUE THREAD

**Issue by RahulNautiyal3110** [anshooarora/extentreports-java#890]
Hi,

I want to change the Heading of the Step view Graph and want the Graphs to be filter if particular test case are selected.
If it is possible how to do that as in my project we need to change the graphs based on the selected test cases.
v2.40.

**Comment by anshooarora** [comment]
This can be done using custom javascript and including it in your config file:

http://extentreports.com/docs/versions/2/java/#configuration
