### ISSUE TITLE
 How to add image (Logo) to the extent Report - 2.4

### ISSUE THREAD

**Issue by hemmarkit14** [anshooarora/extentreports-java#894]
Hi Anshoo,

I am not able to add company logo , have added js code  and image tag under reportName

Please find the below xml file

<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
  <configuration>
    
    
    <theme>dark</theme>
  
    
    
    <encoding>UTF-8</encoding>
    
    
    
    <protocol>https</protocol>
    
    
    <documentTitle>Sample CATS ExtentReports </documentTitle>
    
    
    <reportName>
		<image id="image-zoom">
			<![CDATA[	
			<img src='C:\CATS\logo.png'/>
			]]>
		</image>
		
    </reportName>
    
    
    <reportHeadline>CATS TEST AUTOMATION</reportHeadline>
    
    
    
    <dateFormat>yyyy-MM-dd</dateFormat>
    
    
    
    <timeFormat>HH:mm:ss</timeFormat>
    
    
    <scripts>
      <![CDATA[
        $(document).ready(function() {
          $("#image-zoom").src("src",src);
		  $("#image-zoom").append("src",src);
        });
      ]]>
    </scripts>
    
    
    <styles>
       <![CDATA[
                .report-name { padding-left: 120px; } .report-name > img { float: left;height: 90%;margin-left: 120px;margin-top: 2px;width: auto; }
            ]]>
    </styles>
  </configuration>
</extentreports>

Please` tell what else need's to be done

**Comment by hemmarkit14** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
  <configuration>
    
    
    <theme>dark</theme>
  
    
    
    <encoding>UTF-8</encoding>
    
    
    
    <protocol>https</protocol>
    
    
    <documentTitle>Sample CATS ExtentReports </documentTitle>
    
    
    <reportName>
		<image id="image-zoom">
			<![CDATA[	
			<img src='C:\CATS\logo.png'/>
			]]>
		</image>
		
    </reportName>
    
    
    <reportHeadline>CATS TEST AUTOMATION</reportHeadline>
    
    
    
    <dateFormat>yyyy-MM-dd</dateFormat>
    
    
    
    <timeFormat>HH:mm:ss</timeFormat>
    
    
    <scripts>
      <![CDATA[
        $(document).ready(function() {
          $("#image-zoom").src("src",src);
		  $("#img").append("src",src);
        });
      ]]>
    </scripts>
    
    
    <styles>
       <![CDATA[
                .report-name { padding-left: 120px; } .report-name > img { float: left;height: 90%;margin-left: 120px;margin-top: 2px;width: auto; }
            ]]>
    </styles>
  </configuration>
</extentreports>

**Comment by hemmarkit14** [comment]
Hi Anshoo,

Can you please comment over here, there is a demo planned

**Comment by anshooarora** [comment]
Remove the CData section and use this:

```
<reportName>
	<image id="image-zoom">
		 <img src='C:/CATS/logo.png' />
	</image>
</reportName>
```
