### ISSUE TITLE
Method for get total pass/fail count

### ISSUE THREAD

**Issue by sumit-global** [anshooarora/extentreports-java#895]
Hi Anshoo Arora,

Is there any method available in v2.41.1 which returns total pass/fail count.

**Comment by anshooarora** [comment]
No, this feature is not available in version 2.

**Comment by sumit-global** [comment]
Thanks for your reply...
I created methods that will return total,pass and fail count....

**Comment by harsh976** [comment]
@sumt-global
Can you post those methods and also are showing those count on extent report any where?

**Comment by harsh976** [comment]
@sumit-global

**Comment by sumit-global** [comment]
@harsh976 i am not showing anywhere on Extent Report as it is already shown on it's Dashboard.

**Comment by harsh976** [comment]
Ok cool
