### ISSUE TITLE
Request for changing of the dashboard view, class name  "card-panel categories" should be  define for the categories section.

### ISSUE THREAD

**Issue by VitPer** [anshooarora/extentreports-java#896]
In  some cases the list of  **Environment** parameters and list of **Categories** can be very long
![2017-06-14_08h34_09](https://user-images.githubusercontent.com/26621876/27119826-a9d832d0-50e1-11e7-9849-456afb300a06.png)
 and user should have a possibility to customize this two section on **DASHBOARD VIEW**  with css settings.
It possible now only  for the section "Environment"  with class name **_card-panel environment_**: 
  `<div class='col s4'>
	<div class='card-panel environment'>`
Would be nice to have the same code for "Categories" `<div class='col s4'>
				<div class='card-panel'>
					<span class='right label cyan white-text'>Categories</span><p>&nbsp;</p>`
Need only define  class name **_card-panel categories**.
## Sample
![2017-06-14_08h32_01](https://user-images.githubusercontent.com/26621876/27120049-6be6cbb6-50e2-11e7-8307-00f09bf87877.png)

Example of css for Environment :
`.card-panel.environment {width: 99%;overflow: auto; height: 250px;}
.card-panel.environment > table  { border-collapse: collapse; rules:cols;border-style:solid; }
.card-panel.environment > table td {border-style:solid;font-size: 75%}
.card-panel.environment > table th {border-style:solid;}`

![2017-06-14_09h20_26](https://user-images.githubusercontent.com/26621876/27120298-4a743a3a-50e3-11e7-8b5c-e917a9b1e393.png)

**Comment by anshooarora** [comment]
Please use classes:

```
dashboard-*
dashboard-environment
dashboard-categories
```

**Comment by VitPer** [comment]
Is it included in to 3.0.6 release or should be available in 3.0.7 ?

**Comment by anshooarora** [comment]
It will be included in 3.0.7.  But you can also use the [latest build](https://github.com/anshooarora/extentreports-java/commit/2a343139345ad9b8563afa18ea8fc622b5666a45) and compile.

**Comment by harsh976** [comment]
@anshooarora

Expected date for 3.0.7?
