### ISSUE TITLE
Error in method invocation: Method attachReporter not found

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports-java#898]
When i call a attachReporter, return a exception **(import com.aventstack.extentreports . . . '' : Error in method invocation: Method attachReporter( com.aventstack.extentreports.reporter.ExtentHtmlReporter ) not found in class'com.aventstack.extentreports.ExtentReports' )**

## Sample
My code is:

```
ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(props.get("Path") + "//Results.html");

ExtentReports extent = new ExtentReports();

extent.attachReporter(htmlReporter);  <- Error in this line

ExtentTest test = extent.createTest("MyFirstTest", "Sample description");

test.log(Status.INFO, "This step shows usage of log(status, details)");

test.info("This step shows usage of info(details)");        

test.fail("details", MediaEntityBuilder.createScreenCaptureFromPath("screenshot.png").build());
        
test.addScreenCaptureFromPath("screenshot.png");  
      
extent.flush();
```

## Environment Details

* Extent report Version used: 3.0.6
* Operating System and version: Windows 7 64 bits.
* JDK Version: 1.8.0_131

**Comment by email2vimalraj** [comment]
@MaxiTalenti : Unable to reproduce your issue. 

<img width="1253" alt="screen shot 2017-06-26 at 11 29 17 pm" src="https://user-images.githubusercontent.com/1214686/27553122-5c8537fe-5ac7-11e7-93b4-8a7c1abc48f3.png">

**Comment by anshooarora** [comment]
Closing as no response from OP.

**Comment by SunainaVijay** [comment]
@anshooarora I having the above issue. The method attachReporter(ExtentHtmlReporter) is undefined for the type ExtentReports. I have tried to delete my repository and re-download all dependencies. 
I am using version 3.1.5 of Extent Reports.

**Comment by netravm** [comment]
I have the same issue.
