### ISSUE TITLE
How to print Test name in extent 

### ISSUE THREAD

**Issue by ajaygzb10** [anshooarora/extentreports-java#899]
we have method to print test description i.e. test.getDescription()
that prints value description from extent.startTest("Name","Description");
is there any method to print Name value of extent test

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by email2vimalraj** [comment]
@ajaygzb10 : Kindly fill the environment details atleast for us to understand your issue better.

**Comment by anshooarora** [comment]
Closing as no response from OP.
