### ISSUE TITLE
Features for adding comment in the report once report is generated

### ISSUE THREAD

**Issue by sureshdubey** [anshooarora/extentreports-java#900]
**Enhancement** - Is it possible to provide feature where user can add notes/comment in the report after the report is generated. When we analyze report we have different findings, so it will be really great if we have option to put notes or comment (for each methods & classes which are failing) . and off-course we should be able to save the comment along with the same report html file. So that anyone can see those comments.

**Comment by email2vimalraj** [comment]
@sureshdubey : The report generated is the simple plain html report with no server attached to it. So saving the comment in the same html file is not at all possible.
