### ISSUE TITLE
Merge multiple test reports

### ISSUE THREAD

**Issue by jun1983** [anshooarora/extentreports-java#903]
## Summary

I am running Cucumber tests with Maven+Surefire+Junit combination in parallel mode. Each test class will generate a test report. Do you have any advice how I can merge all these reports? Otherwise, I am wondering if any setting allows me to append test report to existing file.

## Expected Behavior

When indicate a test report file. Multiple tests running in parallel can append to the test report file in sequence.

## Current Behavior

I looked into the source code of ExtentHtmlReporter. parseReportBuildTestCollection happens in start() at the beginning of the test. I am supposing if it can resolve my problem by moving it to flush().
Please correct me if misunderstand anything.

## Sample

```java
// Sample code goes here
@Override
    public void start() {
        if (templateMap != null) {
            return;
        }
        
        templateMap = new HashMap<String, Object>();
        templateMap.put("report", this);
        templateMap.put("Icon", new Icon());
        
        BeansWrapperBuilder builder = new BeansWrapperBuilder(Configuration.VERSION_2_3_23);
        BeansWrapper beansWrapper = builder.build();
        
        try {
            TemplateHashModel fieldTypeModel = (TemplateHashModel)beansWrapper.getEnumModels().get(Status.class.getName());
            templateMap.put("Status", fieldTypeModel);
        } 
        catch (TemplateModelException e) {
            logger.log(Level.SEVERE, "", e);
        }
        
        if (appendExisting && filePath != null)
        	parseReportBuildTestCollection();
    }

**Comment by anshooarora** [comment]
Version?  Are you using the Cucumber formatter plugin?

**Comment by jun1983** [comment]
Yes. I am using Cucumber formatter plugin. But I only copied the code into my project rather than add a dependency.  The code I checked is in the master branch, not sure what version.

**Comment by anshooarora** [comment]
The master branch should indicate the version, if not, check the pom.xml and it should be there.  

Append in parallel mode will not work.  I would suggest creating and using a single instance of ExtentReports for all the parallel tests.  Like here:  https://github.com/anshooarora/extentreports-java/blob/master/src/test/java/com/aventstack/extentreports/common/ExtentManager.java

I am not sure how CucumberFormatter allows this, but you may want to check with https://github.com/email2vimalraj/CucumberExtentReporter for more information.
