### ISSUE TITLE
Getting an error importing com.reports.util in ExtentTestNgFormatter.java

### ISSUE THREAD

**Issue by jazz5982** [anshooarora/extentreports-java#905]
## Summary

Hi everyone

I was trying to implement extentReports plugin in my project and after adding all the required dependencies and ect. to the pom.xml file I still cannot compile the "ExtentTestNgFormatter" class.

Those 3 imports cannot be resolved:

import com.reports.util.EmailReporter;
import com.reports.util.NodeName;
import com.reports.util.SystemInfo;

I've tried looking around the web for this particular dependency and unfortunately came up with nothing. Any suggestions?

Thanks!

Yair

**Comment by anshooarora** [comment]
See here:

https://github.com/anshooarora/extentreports-java/blob/master/src/test/java/com/aventstack/extentreports/common/ExtentTestNGListener.java
