### ISSUE TITLE
Unable to set Append to Exisiting Report in 3.0.2 for .net

### ISSUE THREAD

**Issue by shanmukha27** [anshooarora/extentreports-java#907]
## Summary
I'm facing with an issue in  Exisitng Report in 3.0.2 using .net.
I'm unable to generate the html logs to the exisitng report it is clearing every time after running a test case.
I have used the below code:
htmlReporter.AppendExisting = true;
Looks like it is not working as well.. Can you help on this...

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used: 3.0.2
* Operating System and version:
* .Net

**Comment by anshooarora** [comment]
Closing as this is the Java repo.  

PS.  This feature is not yet implemented.
