### ISSUE TITLE
ExtentReports v3 - HTML report when emailed is broken

### ISSUE THREAD

**Issue by wamiquem** [anshooarora/extentreports-java#910]
Hi Anshoo,
I am not using Jenkins.

When the generated extentreport HTML is viewed directly on my machine, everything seems fine. But when I am sending email using JAVA, the HTML is completely broken.

Best Regards
Wamique

**Comment by anshooarora** [comment]
The HTML report is not compatible with email clients.   The email report is available in the professional version only.
