### ISSUE TITLE
Screenshots Issue, while attaching to the report using Reporter Class

### ISSUE THREAD

**Issue by mkamora** [anshooarora/extentreports-java#911]
## Summary
@anshooarora  Please advice
So i just started using Extent Reports, and it is exactly what i needed for my project, we are not using any CI tools so using Cucumber Json Report is not feasible for me, so Extent Reports is perfect since i am using Cucumber and i need something to take notes and screenshots on Steps whenever i need it to.

## Expected Behavior
the code is suppose to take a screenshot, move it to the folder, then attach it to the report,
and it should be clickable inside the report

## Current Behavior

The code is taking screenshot, Moving it, and attaching it but the attachment is always empty or corrupted dont know which is it. 

Please advice 

// Sample code goes here

```
public static String createScreenShot() {

		try {

			File scrFile = ((TakesScreenshot) Driver.getInstance()).getScreenshotAs(OutputType.FILE);
			String timeStamp = LocalDateTime.now().toString().replaceAll(":", "");
			String filePath = "./target/ExtentReport/Screenshots/ScreenShot" + timeStamp + ".png";
			FileUtils.copyFile(scrFile, new File(filePath));

			return filePath;

		} catch (WebDriverException unSupportedPlatform) {

			System.out.println("UnSupportedPlatform Exception occured while attempting to take ScreenShot");
			unSupportedPlatform.printStackTrace();
			return null;

		} catch (ClassCastException cce) {

			System.out.println("ClassCast Exception occured while attempting to take ScreenShot");
			cce.printStackTrace();
			return null;

		} catch (Exception e) {
			System.out.println("No Screenshot was Found ! Page Line 85");
			e.printStackTrace();
			return null;
		}

	}

	public static void takeScreenShot() {

		try {

			Reporter.addStepLog("Current URL IS :-" + Driver.getInstance().getCurrentUrl());
			Reporter.addScreenCaptureFromPath((createScreenShot()), Driver.getInstance().getTitle());
		} catch (IOException e) {
			System.out.println("No ScreenShot Taken!!");
			e.printStackTrace();
		}
	}
```

## Environment Details

* Extent report Version used = 3.0.6 :
* Cucumber-extentsreport = 3.0.6
* Operating System and version: Windows 7 64
* JDK Version: Java 8

## Screenshots
![image](https://user-images.githubusercontent.com/27563425/28274819-1b823c42-6ae0-11e7-88fa-ccc5b81d53b5.png)

**Comment by mkamora** [comment]
@anshooarora  Please advice

**Comment by harsh976** [comment]
@mkamora Try this:

public static String createScreenShot() {

        try {

            File scrFile = ((TakesScreenshot) Driver.getInstance()).getScreenshotAs(OutputType.FILE);
            File destination = null;
            String timeStamp = LocalDateTime.now().toString().replaceAll(":", "");
            
            String filepath = System.getProperty("user.dir") + File.separator + "target/ExtentReport/Screenshots/ScreenShot" +timeStamp + ".png";
            destination = new File(filepath);
            FileUtils.copyFile(scrFile, new File(filePath));
            
            return String.valueOf(destination.getAbsolutePath());
            

            

        } catch (WebDriverException unSupportedPlatform) {

            System.out.println("UnSupportedPlatform Exception occured while attempting to take ScreenShot");
            unSupportedPlatform.printStackTrace();
            return null;

        } catch (ClassCastException cce) {

            System.out.println("ClassCast Exception occured while attempting to take ScreenShot");
            cce.printStackTrace();
            return null;

        } catch (Exception e) {
            System.out.println("No Screenshot was Found ! Page Line 85");
            e.printStackTrace();
            return null;
        }

    }

**Comment by mkamora** [comment]
@harsh976  
Bro you the Man, can you explain what did you do exactly ! ?

**Comment by harsh976** [comment]
Did that work?

**Comment by mkamora** [comment]
yes it worked

**Comment by harsh976** [comment]
So basically it needs the absolute path.
./ won't work.

**Comment by mkamora** [comment]
oh okay well thank you sir

**Comment by harsh976** [comment]
Welcome

**Comment by anshooarora** [comment]
From the report's standpoint, is this path valid?

```
String filePath = "./target/ExtentReport/Screenshots/ScreenShot" + timeStamp + ".png";
```

If the report is created in `test-output` folder for instance, your path would become:

```
../target/ExtentReport/Screenshots/...
```

**Comment by harsh976** [comment]
@anshooarora 
Does this mean the path was not correct ?
As I had also came accross the same issue and had got it fixed with the one mentioned above I am not sure on default screenshot going to the test-output directory or the one defined by us.
