### ISSUE TITLE
Add local file link to Extent Report

### ISSUE THREAD

**Issue by anbajaj** [anshooarora/extentreports-java#912]
Dear Anshoo,

We are using Extent Report with Cucumber Bdd & wanted to add a link to file which is located on a local system. Could you kindly advice?

Thanks,
Anuj

**Comment by anbajaj** [comment]
This is what we have tried. It is showing a link on the report however it's not clickable & not opening the file.
`Reporter.addStepLog("<a href='file:\\C:\\Users\\anbajaj\\Desktop\\test.xml'>Response</a>");`

**Comment by anshooarora** [comment]
this will work:

```
 Reporter.addStepLog("<a href='file:///C:/Users/anbajaj/Desktop/test.xml'>Response</a>"); 
```

**Comment by kamleshchoudhry** [comment]
I tried this  Reporter.addStepLog("<a href='file:///C:/Users/anbajaj/Desktop/test.xml'>Response</a>");  it is not working for me, able to see the "Response" link but after clicking nothing is happening.
