### ISSUE TITLE
How to show grouping of Test methods in Extent reports based on TEST groups

### ISSUE THREAD

**Issue by Mayukh-saha** [anshooarora/extentreports-java#915]
## Summary

Please refer to the sample testng.xml file below.

```
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Main Test Suite" verbose="2">
    <test name="Sample registration tests">
        <classes>
            <class name="com.Practice.PracticeTest1" />
        </classes>
    </test> 
    <test name="Sample login tests">
        <classes>
            <class name="com.Practice.PracticeTest2" />
        </classes>
    </test> 
</suite>`

```
The file contains 2 Test Groups named **Sample registration tests** and **Sample login tests** and under that 1 test class in each group. Now I have configured Extent reports for my project and when running the reports are coming fine. But all the test methods in the 2 classes are coming sequentially.

I want to show the test methods grouped under the Test groups. Like all the methods of **PracticeTest1** test class will come under **Sample registration tests** Test group and like that.

## Screenshots
[
![extent_report](https://user-images.githubusercontent.com/12016179/28463691-5c90df74-6e3f-11e7-90ee-f7c3fc7b6360.png)
](url)

**Comment by anshooarora** [comment]
Your expected view is "Category" view.  Please see under that view and all tests will show up under groups.

**Comment by raghavilatha** [comment]
I too have same requirement, Can anyone help me?

**Comment by raghavilatha** [comment]
I am running the same class with different test data . Let say there is a Login Test, I am runng it for multiple countries. I an starting the extent reports with Class name + Country. and registration Test + country.

I wanna to group these test cases based on COuntry.
is there any way to do that?
any help would become  great help to me.
