### ISSUE TITLE
Jenkins with publish HTML report plugin and ExtentReport

### ISSUE THREAD

**Issue by pete2121** [anshooarora/extentreports-java#916]
Hello,

I am using HTML report plugin in order to export and display the Extent report.
Extent report is displayed properly. However I have some links inside the report that navigate into some folder. When click this link into eclipse or into artifacts (ws path) then I can navigate correctly.
When I click this link from HTML report plugin then I cannot navigate it.

![image](https://user-images.githubusercontent.com/17945344/28628080-4626f4d0-722c-11e7-9035-546e9b01e702.png)

**Comment by anshooarora** [comment]
duplicate #290

**Comment by Maheswarareddygade** [comment]
selenium html
