### ISSUE TITLE
CND URL Connection timeout

### ISSUE THREAD

**Issue by Enderyu** [anshooarora/extentreports-java#917]
Hi，I come to China，I visit the following links have a problem
![image](https://user-images.githubusercontent.com/18453612/28630919-329317be-725e-11e7-955e-cc16fadaf72b.png)
Request URL:https://cdn.rawgit.com/anshooarora/extentreports-java/0ef94479b1fc7c18041d6bbf1a8cfbfa321edc0a/dist/css/extent.css
Request URL:https://cdn.rawgit.com/anshooarora/extentreports-java/29d2d3ec024c953e6341cb3e19e31b1035a8f556/dist/js/extent.js
Can Extent be configured to download .CSS resources from local network?

**Comment by lgw8186** [comment]
Is that settled?   i  have the same problem

**Comment by the2ndindec** [comment]
怎么设置本地的css和js呢

**Comment by anshooarora** [comment]
This is probably because the CDN is being blocked.  You can try this:

```
htmlReporter.config().setResourceCDN(ResourceCDN.EXTENTREPORTS);
```

**Comment by neto1603** [comment]
Hi, I tried using that line of code but it didn't work, the request is still using the values above to render the report. Here's what I have:

        htmlReporter = new ExtentHtmlReporter(filepath);
        htmlReporter.config().setResourceCDN(ResourceCDN.EXTENTREPORTS);
        Instance = new ExtentReports();
        Instance.attachReporter(htmlReporter);
        Instance.setReportUsesManualConfiguration(true);
        reportFilePath = Paths.get(filepath);

**Comment by hshaktawat** [comment]
Connect via some other network it worked fine. I believe it was due to the CDN being blocked.
