### ISSUE TITLE
Blank screenshots are captured during running in Jenkins

### ISSUE THREAD

**Issue by wildpioneer** [anshooarora/extentreports-java#918]
## Summary
Have a script to capture screenshots. It works well locally. But when I run the script in Jenkins get blank screensots everytime. The Jenkins runs on remote server.
After run I checked the captured files, they are all blank.

## Expected Behavior
The screenshots capture works on remote pc.

## Current Behavior
The screenshots capture doesn't work on remote pc. All screenshots are blank.

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by anshooarora** [comment]
This is generally because the screenshots are not accessible at the remote pc.  I would suggest using relative path for images in the report and saving the images along with the report to be accessible by jenkins.

```
report.html
    /screenshots
        1.png
        2.png
```

Relative path in report:

```
screenshots/1.png
screenshots/2.png
```
