### ISSUE TITLE
Extent Report fails the automatic testing and the HTML is broken in Jenkins

### ISSUE THREAD

**Issue by Geekays** [anshooarora/extentreports-java#919]
## Summary

Extent Report fails the automatic testing and the HTML is broken in Jenkins

## Expected Behavior

The HTML and the referred CSS works as expected and the html report works with the frame and two tabs for dashboard and details.

## Current Behavior

> The CSS does not load correctly. 
> The report is not showing the data properly

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by anshooarora** [comment]
duplicate #290
