### ISSUE TITLE
How to add our custom CSS

### ISSUE THREAD

**Issue by Geekays** [anshooarora/extentreports-java#920]
We want to add custom CSS or download the existing CSS and add to the folder so that the extent report shows up correctly when internet connectivity is not available.

**Comment by anshooarora** [comment]
To use offline resources with your report, you must upgrade to the professional version.

To add custom css, simply add it in your config.xml (inside styles).  See [here](http://extentreports.com/docs/versions/3/java/#config-xml-community).

**Comment by Geekays** [comment]
I tried adding the CSS and it worked. However the javascript addition failed as the script contains character combinations like '%>' or '<%'

Can you please guide if we need to do something for this?

**Comment by anshooarora** [comment]
Why would they show up?  Just add your style tags here.

```
<!-- custom styles -->
        <styles>
            <!-- here -->
            <![CDATA[
                 <!-- orhere -->               
            ]]>
        </styles>

```
