### ISSUE TITLE
Merging multiple extent html reports to single report

### ISSUE THREAD

**Issue by HarithaMadhuri** [anshooarora/extentreports-java#921]
Please help me  with a code sample to generate a single Extent Report for maven multi module project(For Example **Application1**,**Application2**,**Application3** etc) where we can categorise by module wise(Application1,Application2).
No much documentation available for new versions.

## Expected Behavior

Need to merge and embed the individual reports (Application1.html,Application2.html)into single report(Application.html contains both Application1 and Application2 reports).

## Current Behavior
currently able to generate the report for individual modules(Application1.html,Application2.html)

## Sample

	
```
	ExtentHtmlReporter  htmlreporter = new ExtentHtmlReporter(System.getProperty("user.dir")+"/ExtentReports.html");	
		
     ExtentReports extent = new ExtentReports();
	 extent.attachReporter(htmlreporter);
	 htmlreporter.setAppendExisting(true);
	 htmlreporter.config().setTheme(Theme.STANDARD);
```

## Environment Details
* Extent report Version used: 3.0.6
* Operating System and version: Windows 7
* JDK Version:  Java 1.8
JUNIT : 4.12

```

**Comment by anshooarora** [comment]
I would advice to use a singleton approach for `ExtentReports` object.  Like [here](https://github.com/anshooarora/extentreports-java/blob/master/src/test/java/com/aventstack/extentreports/common/ExtentManager.java).  

If projects are run in different sessions, sequentially, use `appendExisting` flag as `true`.  See [here](http://extentreports.com/docs/versions/3/java/#append-to-htmlreporter).

**Comment by HarithaMadhuri** [comment]
Thanks for your suggestion anshooarora.
with singleton approach and setting the flag to true I am able to generate the Single report(appending to existing report).
But my requirement is like below.
http://relevantcodes.com/Tools/ExtentReports2/ExtentMerge.html
In the above report format in place of reports column by date,I need to attach individual report by name(Example :App1.html,App2.html)
 Can you Please suggest on this.

**Comment by anshooarora** [comment]
You can integrate ExtentX in this case.

**Comment by HarithaMadhuri** [comment]
Is it requires a server?

**Comment by anshooarora** [comment]
@HarithaMadhuri ExtentX itself is a server.  You would require MongoDB and NodeJs to be installed.

**Comment by surajprsd** [comment]
@HarithaMadhuri @anshooarora  how to print console error on to extent?
