### ISSUE TITLE
[DEBUG] [freemarker.cache ] for extent reports

### ISSUE THREAD

**Issue by GiriManas** [anshooarora/extentreports-java#924]
Getting some Debug logs .... How do I suppress it or how do I resolve the issue. I am using extent reports 3.0.6 and log4j

5336 [2017-07-31 19:18:14,883] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "index.ftl"("en", UTF-8, parsed); will try to load it.
5339 [2017-07-31 19:18:14,886] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("index_en.ftl"): Not found
5343 [2017-07-31 19:18:14,890] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("index.ftl"): Found
5344 [2017-07-31 19:18:14,891] [DEBUG] [freemarker.cache ] - Loading template for "index.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/index.ftl"
5817 [2017-07-31 19:18:15,364] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "head.ftl"("en", UTF-8, parsed); will try to load it.
5818 [2017-07-31 19:18:15,365] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("head_en.ftl"): Not found
5820 [2017-07-31 19:18:15,367] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("head.ftl"): Found
5820 [2017-07-31 19:18:15,367] [DEBUG] [freemarker.cache ] - Loading template for "head.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/head.ftl"
5826 [2017-07-31 19:18:15,373] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "nav.ftl"("en", UTF-8, parsed); will try to load it.
5829 [2017-07-31 19:18:15,376] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("nav_en.ftl"): Not found
5835 [2017-07-31 19:18:15,382] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("nav.ftl"): Found
5836 [2017-07-31 19:18:15,383] [DEBUG] [freemarker.cache ] - Loading template for "nav.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/nav.ftl"
5857 [2017-07-31 19:18:15,404] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "test-view/test-view.ftl"("en", UTF-8, parsed); will try to load it.
5859 [2017-07-31 19:18:15,406] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/test-view_en.ftl"): Not found
5860 [2017-07-31 19:18:15,407] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/test-view.ftl"): Found
5862 [2017-07-31 19:18:15,409] [DEBUG] [freemarker.cache ] - Loading template for "test-view/test-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/test-view/test-view.ftl"
5908 [2017-07-31 19:18:15,455] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "test-view/standard.ftl"("en", UTF-8, parsed); will try to load it.
5914 [2017-07-31 19:18:15,461] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/standard_en.ftl"): Not found
5915 [2017-07-31 19:18:15,462] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/standard.ftl"): Found
5915 [2017-07-31 19:18:15,462] [DEBUG] [freemarker.cache ] - Loading template for "test-view/standard.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/test-view/standard.ftl"
5987 [2017-07-31 19:18:15,534] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "test-view/test-view-charts.ftl"("en", UTF-8, parsed); will try to load it.
5988 [2017-07-31 19:18:15,535] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/test-view-charts_en.ftl"): Not found
5989 [2017-07-31 19:18:15,536] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/test-view-charts.ftl"): Found
5990 [2017-07-31 19:18:15,537] [DEBUG] [freemarker.cache ] - Loading template for "test-view/test-view-charts.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/test-view/test-view-charts.ftl"
6008 [2017-07-31 19:18:15,555] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "category-view/category-view.ftl"("en", UTF-8, parsed); will try to load it.
6011 [2017-07-31 19:18:15,558] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("category-view/category-view_en.ftl"): Not found
6012 [2017-07-31 19:18:15,559] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("category-view/category-view.ftl"): Found
6012 [2017-07-31 19:18:15,559] [DEBUG] [freemarker.cache ] - Loading template for "category-view/category-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/category-view/category-view.ftl"
6020 [2017-07-31 19:18:15,567] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "author-view/author-view.ftl"("en", UTF-8, parsed); will try to load it.
6021 [2017-07-31 19:18:15,568] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("author-view/author-view_en.ftl"): Not found
6022 [2017-07-31 19:18:15,569] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("author-view/author-view.ftl"): Found
6022 [2017-07-31 19:18:15,569] [DEBUG] [freemarker.cache ] - Loading template for "author-view/author-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/author-view/author-view.ftl"
6031 [2017-07-31 19:18:15,578] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "exception-view/exception-view.ftl"("en", UTF-8, parsed); will try to load it.
6033 [2017-07-31 19:18:15,580] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("exception-view/exception-view_en.ftl"): Not found
6036 [2017-07-31 19:18:15,583] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("exception-view/exception-view.ftl"): Found
6038 [2017-07-31 19:18:15,585] [DEBUG] [freemarker.cache ] - Loading template for "exception-view/exception-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/exception-view/exception-view.ftl"
6046 [2017-07-31 19:18:15,593] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "dashboard-view/dashboard-view.ftl"("en", UTF-8, parsed); will try to load it.
6047 [2017-07-31 19:18:15,594] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("dashboard-view/dashboard-view_en.ftl"): Not found
6048 [2017-07-31 19:18:15,595] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("dashboard-view/dashboard-view.ftl"): Found
6048 [2017-07-31 19:18:15,595] [DEBUG] [freemarker.cache ] - Loading template for "dashboard-view/dashboard-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/dashboard-view/dashboard-view.ftl"
6100 [2017-07-31 19:18:15,647] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "logs-view/testrunner-logs-view.ftl"("en", UTF-8, parsed); will try to load it.
6103 [2017-07-31 19:18:15,650] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("logs-view/testrunner-logs-view_en.ftl"): Not found
6104 [2017-07-31 19:18:15,651] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("logs-view/testrunner-logs-view.ftl"): Found
6105 [2017-07-31 19:18:15,652] [DEBUG] [freemarker.cache ] - Loading template for "logs-view/testrunner-logs-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/logs-view/testrunner-logs-view.ftl"
6125 [2017-07-31 19:18:15,672] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "index.ftl"("en", UTF-8, parsed); will try to load it.
6126 [2017-07-31 19:18:15,673] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("index_en.ftl"): Not found
6127 [2017-07-31 19:18:15,674] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("index.ftl"): Found
6129 [2017-07-31 19:18:15,676] [DEBUG] [freemarker.cache ] - Loading template for "index.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/index.ftl"
6144 [2017-07-31 19:18:15,691] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "head.ftl"("en", UTF-8, parsed); will try to load it.
6171 [2017-07-31 19:18:15,718] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("head_en.ftl"): Not found
6172 [2017-07-31 19:18:15,719] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("head.ftl"): Found
6172 [2017-07-31 19:18:15,719] [DEBUG] [freemarker.cache ] - Loading template for "head.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/head.ftl"
6212 [2017-07-31 19:18:15,759] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "nav.ftl"("en", UTF-8, parsed); will try to load it.
6213 [2017-07-31 19:18:15,760] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("nav_en.ftl"): Not found
6213 [2017-07-31 19:18:15,760] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("nav.ftl"): Found
6213 [2017-07-31 19:18:15,760] [DEBUG] [freemarker.cache ] - Loading template for "nav.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/nav.ftl"
6224 [2017-07-31 19:18:15,771] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "test-view/test-view.ftl"("en", UTF-8, parsed); will try to load it.
6225 [2017-07-31 19:18:15,772] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/test-view_en.ftl"): Not found
6226 [2017-07-31 19:18:15,773] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/test-view.ftl"): Found
6226 [2017-07-31 19:18:15,773] [DEBUG] [freemarker.cache ] - Loading template for "test-view/test-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/test-view/test-view.ftl"
6260 [2017-07-31 19:18:15,807] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "test-view/test-view-charts.ftl"("en", UTF-8, parsed); will try to load it.
6260 [2017-07-31 19:18:15,807] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/test-view-charts_en.ftl"): Not found
6261 [2017-07-31 19:18:15,808] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/test-view-charts.ftl"): Found
6262 [2017-07-31 19:18:15,809] [DEBUG] [freemarker.cache ] - Loading template for "test-view/test-view-charts.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/test-view/test-view-charts.ftl"
6275 [2017-07-31 19:18:15,822] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "test-view/standard.ftl"("en", UTF-8, parsed); will try to load it.
6279 [2017-07-31 19:18:15,826] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/standard_en.ftl"): Not found
6280 [2017-07-31 19:18:15,827] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("test-view/standard.ftl"): Found
6280 [2017-07-31 19:18:15,827] [DEBUG] [freemarker.cache ] - Loading template for "test-view/standard.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/test-view/standard.ftl"
6300 [2017-07-31 19:18:15,847] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "category-view/category-view.ftl"("en", UTF-8, parsed); will try to load it.
6303 [2017-07-31 19:18:15,850] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("category-view/category-view_en.ftl"): Not found
6304 [2017-07-31 19:18:15,851] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("category-view/category-view.ftl"): Found
6304 [2017-07-31 19:18:15,851] [DEBUG] [freemarker.cache ] - Loading template for "category-view/category-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/category-view/category-view.ftl"
6312 [2017-07-31 19:18:15,859] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "author-view/author-view.ftl"("en", UTF-8, parsed); will try to load it.
6313 [2017-07-31 19:18:15,860] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("author-view/author-view_en.ftl"): Not found
6313 [2017-07-31 19:18:15,860] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("author-view/author-view.ftl"): Found
6313 [2017-07-31 19:18:15,860] [DEBUG] [freemarker.cache ] - Loading template for "author-view/author-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/author-view/author-view.ftl"
6333 [2017-07-31 19:18:15,880] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "exception-view/exception-view.ftl"("en", UTF-8, parsed); will try to load it.
6334 [2017-07-31 19:18:15,881] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("exception-view/exception-view_en.ftl"): Not found
6334 [2017-07-31 19:18:15,881] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("exception-view/exception-view.ftl"): Found
6339 [2017-07-31 19:18:15,886] [DEBUG] [freemarker.cache ] - Loading template for "exception-view/exception-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/exception-view/exception-view.ftl"
6349 [2017-07-31 19:18:15,896] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "dashboard-view/dashboard-view.ftl"("en", UTF-8, parsed); will try to load it.
6349 [2017-07-31 19:18:15,896] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("dashboard-view/dashboard-view_en.ftl"): Not found
6350 [2017-07-31 19:18:15,897] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("dashboard-view/dashboard-view.ftl"): Found
6350 [2017-07-31 19:18:15,897] [DEBUG] [freemarker.cache ] - Loading template for "dashboard-view/dashboard-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/dashboard-view/dashboard-view.ftl"
6362 [2017-07-31 19:18:15,909] [DEBUG] [freemarker.cache ] - Couldn't find template in cache for "logs-view/testrunner-logs-view.ftl"("en", UTF-8, parsed); will try to load it.
6364 [2017-07-31 19:18:15,911] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("logs-view/testrunner-logs-view_en.ftl"): Not found
6364 [2017-07-31 19:18:15,911] [DEBUG] [freemarker.cache ] - TemplateLoader.findTemplateSource("logs-view/testrunner-logs-view.ftl"): Found
6365 [2017-07-31 19:18:15,912] [DEBUG] [freemarker.cache ] - Loading template for "logs-view/testrunner-logs-view.ftl"("en", UTF-8, parsed) from "jar:file:/C:/Users/ggouda/.m2/repository/com/aventstack/extentreports/3.0.6/extentreports-3.0.6.jar!/com/aventstack/extentreports/view/html-report/logs-view/testrunner-logs-view.ftl"

**Comment by ulmanA** [comment]
Duplication
 #640
