### ISSUE TITLE
addScreenCapture(path) issue?

### ISSUE THREAD

**Issue by EmanueleGirani** [anshooarora/extentreports-java#925]
## Summary

I cannot see the screenshots that I took in the extent reports. Images have not been uploaded.

I've just started to use extentreports. Am I probably missing something?

// Sample code goes here

	
@AfterMethod
	public void afterEachTest(ITestResult result) throws Exception {
                
                ExtentTest logger = null;
                TakesScreenshot sshot = null;
		
                String testName = result.getName();
		boolean testResult = result.isSuccess();
		
		if(testResult) {
			logger.log(LogStatus.PASS, "Test Case : "+testName+" is PASSED ..");		
			
                        // StepByStep to take screenshot

			sshot = (TakesScreenshot) driver;
			File inputFile=sshot.getScreenshotAs(OutputType.FILE);
			String currTime= getDateTimeAppender();
			String fname = currTime+"_"+testName;
			String screenShotPath= "./screenshots/"+fname+".jpeg";	
			File outputFile=new File(screenShotPath);
			Files.copy(inputFile.toPath(), outputFile.toPath());
			                                                                                                                logger.log(LogStatus.PASS, "Snapshot below: "+ logger.addScreenCapture(screenShotPath)); 
	
		}
		else {
			logger.log(LogStatus.FAIL, "Test Case : "+testName+" is FAILED .!!."); 
			}
		report.endTest(logger); 
		report.flush();

		
	}

## Environment Details

* Extent report Version used: 2.41.2
* Operating System and version: OSX El Capitan 10.11.6
* JDK Version: 1.8

## Screenshots

![screenshot_153](https://user-images.githubusercontent.com/29218099/28818324-209f3102-76ee-11e7-81ff-6a91a50d75ec.jpg)

![screenshot_154](https://user-images.githubusercontent.com/29218099/28818359-38eceace-76ee-11e7-8926-22efdd7227cd.jpg)

**Comment by anshooarora** [comment]
Does this work:

```
String screenShotPath= "../screenshots/"+fname+".jpeg";	
```

**Comment by EmanueleGirani** [comment]
Hi, 
firstly thank you to answer my question.
Unfortunately 

String screenShotPath= "../screenshots/"+fname+".jpeg";

does not take any screenshot. So I tried:

String screenShotPath= "./screenshots/"+fname+".jpeg";

In this way, I can see the pictures .jpeg on my folder but the report still does not load the image.

Waiting for another idea.

Thank you

Emanuele

**Comment by anshooarora** [comment]
I had provided the path that is relative to the report.  Another way is to save the screenshots as a child folder of the report folder.  I would recommend doing this:

```
String screenShotPath= "screenshots/"+fname+".jpeg";	
File outputFile=new File(screenShotPath);
Files.copy(inputFile.toPath(), outputFile.toPath());
```

**Comment by EmanueleGirani** [comment]
Unfortunately, both cases that you suggested did not work.

**Comment by harsh976** [comment]
@EmanueleGirani 

Try this:
String screenShotPath= System.getProperty("user.dir") + File.separator + "/screenshots/"+fname+".jpeg";	
 logger.log(LogStatus.PASS, "Snapshot below: "+ logger.addScreenCapture(screenShotPath));

**Comment by EmanueleGirani** [comment]
Yes, it is working 👍  What is the explanation of this: System.getProperty("user.dir") + File.separator 

Thank you very much, guys 👍

**Comment by harsh976** [comment]
Gives you the current working directory and file seperator is nothing but (slash / )

This is in short absolute path.
