### ISSUE TITLE
How to capture all runs in extent report from parameterized class having a single @Test method

### ISSUE THREAD

**Issue by munnamachine** [anshooarora/extentreports-java#928]
## Summary
I have a parameterized class file created in junit, with only one @Test method in it, I am passing input arguments to that test using @Parameters. I have also configured extent report logging in the class.

For each array list input entry @Test will be executed and then the browser will be closed and instantiated again for the next entry, in this process the old html report is replaced with the latest one.

How to have all the runs (with all test data) data captured in the html, please help me with this

## Expected Behavior
I need to have all the runs data for this @Test with different data captured in a single html file.

## Current Behavior
Only the last run data is captured.

## Sample

This is my code. (Here in this case, only the login with C3978782_Add_Login_GCPL alone is captured in html)

    ExtentReports report = new ExtentReports("src/../reports/Report3.html", true);
	ExtentTest test = report.startTest("Add Users to the Project");
    
    @Parameters(name = "TesDetails")
    public static Collection<Object[]> data() {
        return Arrays.asList(new Object[][]
        		{
        	
        		{"Sheet1", "C3978776_Add_Login_Sub"},
        		{"Sheet1", "C3978777_Add_Login_Scanner"},
           		{"Sheet1", "C3978782_Add_Login_GCPL"}        	
        		
        		});
    											}
	

	@Test
	public void addUserToProj() throws  Exception {
			
	 	tData = m_readdatafile.getData(filePath, Sheetname, tcname);
		m_driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
		m_loginPage.loginToSubEX(tData.get("AdminID"), tData.get("password"));
		
		if(m_driver.findElements(By.xpath("//span[text() = 'Project Index1']")).size()==0){
			String path = capture(m_driver);
			test.log(LogStatus.FAIL, "Login to SE for adding "+tData.get("Role"), test.addScreenCapture(path)+"Login Failed");
		} else {
		test.log(LogStatus.PASS, "Login to SE for adding "+tData.get("Role"), "Login Successful");}
		
		m_projectIndexPage.searchAndSelectProj("wah", 6 );
		m_projectTeamPage.addUser(tData.get("Company"), tData.get("emailid"), tData.get("password"), tData.get("Role"));
		if(m_driver.getPageSource().contains(tData.get("emailid"))){
			String path = capture(m_driver);
			test.log(LogStatus.PASS, "Adding "+tData.get("Role")+" Project Team tab", test.addScreenCapture(path)+"User addition Successful");
		} else {
			String path = capture(m_driver);
			test.log(LogStatus.FAIL, "Adding "+tData.get("Role")+" in Project Team tab", test.addScreenCapture(path)+"User addition failed");
		}
		
		report.endTest(test);
		report.flush();
	}
	

## Environment Details

Selenium: 2.43
* Extent report Version used: v2.41.1
* Operating System and version:
* JDK Version: 8

## Screenshots

I have removed the if conditions from code, before capturing the screenshot, to make the code visible in single snap. (Complete code is there above.)

![capture](https://user-images.githubusercontent.com/30766432/29001166-f13a0f86-7a9e-11e7-8010-c57428f49c72.JPG)
![capture2](https://user-images.githubusercontent.com/30766432/29001167-f13ce846-7a9e-11e7-891c-c6f027cff917.JPG)

**Comment by harsh976** [comment]
Can you share the complete code ?

**Comment by munnamachine** [comment]
@harsh976  below is my complete code of that class file
----------------------

package come.oracle.pgbu.oppm.testcases;


import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import com.oracle.pgbu.common.By;
import com.oracle.pgbu.common.pagefactory.CustomPageFactory;
import com.oracle.pgbu.common.utils.ApplicationProperties;
import com.oracle.cegbu.se.testdata.ReadDataFile;
import com.oracle.cegbu.sepages.LoginPageSE;
import com.oracle.cegbu.sepages.ProjectIndexPageSE;
import com.oracle.cegbu.sepages.ProjectTeamPageSE;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

@RunWith(value = Parameterized.class)
public class LoginAddUser_DDT extends BaseTestCase{
	LoginPageSE m_loginPage;
	ProjectIndexPageSE m_projectIndexPage;
	ProjectTeamPageSE m_projectTeamPage;
	ReadDataFile m_readdatafile;
	
	ExtentReports report = new ExtentReports("src/../reports/Report6.html", true);
	ExtentTest test = report.startTest("Add Users to the Project");
	
	int appWaitTime = ApplicationProperties.getInstance().getWaitTime();
	
	//HashMap for accessing the excel sheet data
	HashMap<String, String> tData;
	
	public void presetup() {
		// To ensure no exceptions remain in the test during retry of failed tests

		this.clearExceptions();
		m_loginPage = CustomPageFactory.initElements(LoginPageSE.class);
		m_projectIndexPage = CustomPageFactory.initElements(ProjectIndexPageSE.class);
		m_projectTeamPage = CustomPageFactory.initElements(ProjectTeamPageSE.class);
		m_readdatafile = CustomPageFactory.initElements(ReadDataFile.class);
	
	}
	
	//Parameters for passing test case names to @Test
    private String Sheetname;
    private String tcname;
     
    public LoginAddUser_DDT(String Sheetname , String tcname ) {
        
        this.Sheetname = Sheetname;
        this.tcname = tcname;
        
    }
    
    @Parameters(name = "TesDetails")
    public static Collection<Object[]> data() {
        return Arrays.asList(new Object[][]
        		{
        	
        		{"Sheet1", "C3978776_Add_Login_Sub"},
        		{"Sheet1", "C3978777_Add_Login_Scanner"},
        		{"Sheet1", "C3978778_Add_Login_GC"},
        		{"Sheet1", "C3978779_Add_Login_Consultant"},
        		{"Sheet1", "C3978780_Add_Login_ArchFinal"},
        		{"Sheet1", "C3978780_Add_Login_ArchProjLead"},
        		{"Sheet1", "C3978781_Add_Login_Owner"},
        		{"Sheet1", "C3978782_Add_Login_GCPL"}        	
        		
        		});
    											}
	

	@Test
	public void addUserToProj() throws  Exception {
			
	 	tData = m_readdatafile.getData(filePath, Sheetname, tcname);
		m_driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
		m_loginPage.loginToSubEX(tData.get("AdminID"), tData.get("password"));
		
		if(m_driver.findElements(By.xpath("//span[text() = 'Project Index1']")).size()==0){
			String path = capture(m_driver);
			test.log(LogStatus.FAIL, "Login to SE for adding "+tData.get("Role"), test.addScreenCapture(path)+"Login Failed");
		} else {
		test.log(LogStatus.PASS, "Login to SE for adding "+tData.get("Role"), "Login Successful");}
		
		//m_projectIndexPage.searchAndSelectProj("Project for SmokeTest-Wah - 006", 0 );
		m_projectIndexPage.searchAndSelectProj(tData.get("ProjectName"), 0 );
		
		m_projectTeamPage.addUser(tData.get("Company"), tData.get("emailid"), tData.get("password"), tData.get("Role"));
		if(m_driver.getPageSource().contains(tData.get("emailid"))){
			String path = capture(m_driver);
			test.log(LogStatus.PASS, "Adding "+tData.get("Role")+" Project Team tab", test.addScreenCapture(path)+"User addition Successful");
		} else {
			String path = capture(m_driver);
			test.log(LogStatus.FAIL, "Adding "+tData.get("Role")+" in Project Team tab", test.addScreenCapture(path)+"User addition failed");
		}
		
		//report.endTest(test);
		report.flush();
	}
	
	
	
}

**Comment by harsh976** [comment]
@munniamachine 

Delete following :

**ExtentReports report = new ExtentReports("src/../reports/Report6.html", true);
ExtentTest test = report.startTest("Add Users to the Project");**

Then do this:

static ExtentReports report;
static ExtentTest test;


@BeforeClass
    public static void setup() {
        if (report == null) {
            report = new ExtentReports("src/../reports/Report6.html", true);
            test = report.startTest("Add Users to the Project");    
        }
        
    }

**Comment by harsh976** [comment]
@munnamachine 

Did u try ?

**Comment by munnamachine** [comment]
@harsh976 ... sorry for late response..... since yesterday night I am facing issue with project build, my class files are not getting generated, just now the issue got resolved.

By the way I am using junit, so instead of @BeforeClass I have used @Before and placed it before @Test, it worked perfectly.

Thank you so much :-)
![capture3](https://user-images.githubusercontent.com/30766432/29024183-7778f482-7b8e-11e7-94a2-212b5383c52c.JPG)

**Comment by harsh976** [comment]
@munnamachine Gr8

**Comment by harsh976** [comment]
@anshooarora you can close this.

**Comment by munnamachine** [comment]
Sure
