### ISSUE TITLE
Custom script not working

### ISSUE THREAD

**Issue by Geekays** [anshooarora/extentreports-java#930]
## Summary

I needed to run the Extent Report in an environment where Internet connectivity is not available. So I added the default CSS as custom style as described here: [http://extentreports.com/docs/versions/3/java/#config-xml-community](http://extentreports.com/docs/versions/3/java/#config-xml-community)

However, I tried the same with the Javascript. Downloaded and tried to add as custom script. But as the script contains characters that conflicts with CDATA block ('%>' and '<%'), the script stops working.

## Expected Behavior

The default javascript code when added as custom script, it should work.

## Current Behavior

The custom script is not working.

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by anshooarora** [comment]
You need to put your javascript here:

```
<!-- custom javascript -->
        <scripts>
            <![CDATA[
                // here
                $(document).ready(function() {
                    // or here
                });
            ]]>
        </scripts>
```
