### ISSUE TITLE
Is there any way of transferring a local extent report to extentx server

### ISSUE THREAD

**Issue by hemano** [anshooarora/extentreports-java#932]
I've a local extent report and extentx reports. Both works fine.

Requirement: I want to transfer some reports which are **only on** local to extentx reports to the server.

**Comment by anshooarora** [comment]
No, its not possible.  It must be done when the HTML report is created by also [initializing](http://extentreports.com/docs/versions/3/java/#basic-usage) the ExtentXReporter.
