### ISSUE TITLE
Need to write a report based on the test case status in the report

### ISSUE THREAD

**Issue by pravekdadhwal** [anshooarora/extentreports-java#933]
Dear Anshoo,

First of all, let me thank you for helping us with such a good reporting library. I have been using it for a while now :)
I just have one question please. 

After running a test suite of say 100 test cases, I am creating a report. Now, I need to email that report to PM's (I have automated this, and it will email report to PM's everyday). Problem is, at some point of time they might start ignoring emails, since they are receiving it everyday. I want to know, if I can check the report beforehand for the failed test cases (if any) and then only trigger email?? Its like, I want to email report only if something has failed in it.

Thanks in anticipation!

-Pravek

**Comment by anshooarora** [comment]
Yes, you can use this to find out of there are any failures:

```
boolean hasFailures = htmlReporter.getTestList().stream().anyMatch(x -> x.getStatus() == Status.FAIL);
```

**Comment by pravekdadhwal** [comment]
Hi Anshoo,

Unfortunately I am not able to get it work. I dont see getTestList() method in htmlReporter class.

I tried something like this : bool hasFailures = htmlReporter.TestList.Any(x => x.Status == Status.Fail); but its throwing {"Object reference not set to an instance of an object."}. I am using Selenium with C# and ExtentReport version 3.0.2.

**Comment by pravekdadhwal** [comment]
Also, I am using it in TestCleanup() method, please let me know if this cannot be used like this -

public void TestCleanup()
        {
            log4net.Info("########## End of " + testCaseName + " execution ##########");
            driver.Quit();
            driver.Dispose();
                       
            string flag = ApplicationSettings.applicationConfig.ReportWriting;
            if (flag == "yes")
            {
                bool test = htmlReporter.TestList.Any(x => x.Status == Status.Fail);
                extent.Flush();                
            }            
        }
