### ISSUE TITLE
Extent Report - How to show the suite name as header under that test cases should come with status and the header should not counted for chart?

### ISSUE THREAD

**Issue by sugithanandan** [anshooarora/extentreports-java#934]
## Summary

I am having 2 suites named as Suite A and Suite B and each suite having 5 test cases. I am going to run the test cases with suites of suite concept (Suite C = SuiteA +Suite B) and the listener will be placed in the master suite (Suite C).

## Expected Behavior

I am looking for the report which should show me the suite name without status under that the test cases should come with status.

## Current Behavior

under the Tests the report showing all the testcases with status.

// Sample code goes here
public class ExtentReporterNG implements IReporter {

	private ExtentReports extent;

	ExtentTest test;

	public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
		extent = new ExtentReports(outputDirectory + File.separator + "ExtentReportTestNG.html", true);

		for (ISuite suite : suites) {
			Map<String, ISuiteResult> result = suite.getResults();

			for (ISuiteResult r : result.values()) {

				String[] part = r.toString();				
				**test = extent.startTest("Suite Name : " + part[1], "Suite Test");			
				extent.endTest(test);**   // part[1] is returning the suite name. I dont know how to print the suite name as header.
				ITestContext context = r.getTestContext();
				buildTestNodes(context.getPassedTests(), LogStatus.PASS);
				buildTestNodes(context.getFailedTests(), LogStatus.FAIL);
				buildTestNodes(context.getSkippedTests(), LogStatus.SKIP);
			}

		}

		extent.flush();
		extent.close();
	}

## Environment Details

* Extent report Version used:  3.0.6
* Operating System and version: windows 10 
* JDK Version: 1.8

## Screenshots

<img width="960" alt="extentreport_issue" src="https://user-images.githubusercontent.com/24190443/29526051-2ff578c2-86b2-11e7-9a3d-d7561cc3c9e9.png">

**Comment by anshooarora** [comment]
This is not possible.  I would recommend adding the suite name as a category/tag and filtering accordingly.
