### ISSUE TITLE
Screenshots updated in addBase64ScreenShot with Base64 string is filled in red color

### ISSUE THREAD

**Issue by Muthuvignesh1991** [anshooarora/extentreports-java#937]
## Summary
when using Base64screenshot method to attach screenshot in extent report, it fills the image in red color

## Expected Behavior
Ideally the screenshot after attached in extent must be same as that of the original screenshot

## Current Behavior
But, now it is highlighted in red clor

## Sample

```java
// Sample code goes here
Syntax: test.log(LogStatus.INFO, test.addBase64ScreenShot("data:image/jpeg;base64,"+EncodeImage.convertImageToBase64String("D:\\Path\\filename.jpg")));
```

## Environment Details

* Extent report Version used: 2.41.0
* Operating System and version: Windows 10, chrome 53
* JDK Version: 1.8

## Screenshots
![image](https://user-images.githubusercontent.com/31307682/29659277-622fca4c-88db-11e7-860f-0442254122b7.png)

**Comment by anshooarora** [comment]
Can you open this image outside of extentreports and check once?

**Comment by Muthuvignesh1991** [comment]
Yes, and the screenshot looks proper outside Extent
![siteoverview](https://user-images.githubusercontent.com/31307682/29696966-dbeb45b2-8969-11e7-94c5-ce3d8dce4d40.jpg)

**Comment by anshooarora** [comment]
I mean open the base64 string outside of extent reports. Does it work correctly?

**Comment by Muthuvignesh1991** [comment]
Looks like the problem happened while decoding using the tools mentioned in your above comment. Seems that problem happening when the encryption happens for Base64String script. Can you suggest any scripts, which does the same

**Comment by Muthuvignesh1991** [comment]
Also, please suggest the latest opensource version of extent which supports base64 appending in report, such that it can be mailed with screenshots attached

**Comment by Muthuvignesh1991** [comment]
Its working now, when i use the png format. Below is the code, but it consumes lot of size. Any ideas, how we can reduce the size.

ByteArrayOutputStream baos=new ByteArrayOutputStream(1000);
		BufferedImage img=ImageIO.read(new File(imageFile));
		ImageIO.write(img, "png", baos);
 
		String base64String=Base64.encode(baos.toByteArray());
		System.out.println(base64String.toString());
		baos.flush();
		baos.close();
		return base64String;
