### ISSUE TITLE
Extent report is capturing last executed class only.

### ISSUE THREAD

**Issue by shirishnagarnz** [anshooarora/extentreports-java#938]
## Summary

 Extent report is not capturing all executed TestNG classes in extent report

## Expected Behavior

It should capture all executed classes

## Current Behavior

Having multiple TestNG classes under different packages.

If I run all those classes separately as a TestNG class, it executes successfully, extent report captures the execution for all ran classes i.e. extent report gets ammended after each TestNG class execution, which is as expected.

But

If I run TestNG classes as a suite i.e. more than 1 @TestNG classes from different packages in 1 testng xml, it executed successfully without any error but in extent report, it captures the last executed class result only.

Any solution?

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

## Screenshots

![image](https://user-images.githubusercontent.com/31267418/29696298-05011fa8-899c-11e7-8721-5490a20490e0.png)

**Comment by anshooarora** [comment]
Are you creating a new instance of ExtentReports in BeforeSuite?

**Comment by shirishnagarnz** [comment]
No, 

I am calling instance in every testng class.

Please correct if its a wrong practice. Learning selenium :)

Thanks for quick response.

-Shirish

**Comment by anshooarora** [comment]
Here is the problem:

> I am calling instance in every testng class.

You need something like [this](https://github.com/anshooarora/extentreports-java/blob/master/src/test/java/com/aventstack/extentreports/common/ExtentManager.java) to ensure you only have 1 instance of `ExtentReports` to guarantee only 1 report being created.
