### ISSUE TITLE
Question: ExtentReports_2.4 if support Chinese to display the string in the html page?

### ISSUE THREAD

**Issue by bensir213** [anshooarora/extentreports-java#940]
Hi Anshooarora,
Very appreciate you provide this for us.
My question is the report if support Chinese to display the string in the html page? Actually, i try to log the details in Chinese but the report display messy code for Chinese. Please refer to below the attach files:

![messycode](https://user-images.githubusercontent.com/31264776/29740911-7ba02930-8a94-11e7-8835-ba05f4a4c509.png)

Thanks
Ben

**Comment by anshooarora** [comment]
Yes..  you will have to change the encoding.  You can do this using [config.xml](http://extentreports.com/docs/versions/3/java/#config-xml-community) or:

```
// encoding, default = UTF-8
htmlReporter.config().setEncoding("gbk");
```

**Comment by bensir213** [comment]
Thanks，issue fixed.
