### ISSUE TITLE
Unable to add xml data for the report under the info section

### ISSUE THREAD

**Issue by newgithubaccount** [anshooarora/extentreports-java#946]
## Summary
Trying to print xml data in to the report using the info section but it is escaping the xml tags and priting only the data.But my project requirement is we need to print the request and response of a sop request

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by newgithubaccount** [comment]
piece of code which we are using to format an xml string 


  public String format(String unformattedXml) {
      try {
          final Document document = parseXmlFile(unformattedXml);

          OutputFormat format = new OutputFormat(document);
          format.setLineWidth(65);
          format.setIndenting(true);
          format.setIndent(2);
          Writer out = new StringWriter();
          XMLSerializer serializer = new XMLSerializer(out, format);
          serializer.serialize(document);

          return out.toString();
      } catch (IOException e) {
          throw new RuntimeException(e);
      }
  }

piece of code where we are using with extent reports

 public void logSOAPXML(String xml) {
	  String formattedxml = format(xml);
	  QALogger.getInstance().info(formattedxml);
	  DefaultTest.getTestInstance().log(LogStatus.INFO, formattedxml);
}
 DefaultTest.getTestInstance() gives me extenttest object


    Extent report Version used:2.41.0
    Operating System and version:windows 7
    JDK Version:1.8.0_144

**Comment by anshooarora** [comment]
Sis you try using MarkupHelper?

https://github.com/anshooarora/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/markuputils/MarkupHelper.java

```
Markup m = MarkupHelper.createCodeBlock(code);

test.pass(m);
// or
test.log(Status.PASS, m);

```

**Comment by newgithubaccount** [comment]
BUt which version of extent reports is having the markup class as i was unable to locate this class using 2.41.0

**Comment by anshooarora** [comment]
Version 3.  In version 2, you can try to output xml like this:

```
String html = "<textarea>" + yourXmlString + "</textarea>";
DefaultTest.getTestInstance().log(LogStatus.INFO, html);
```
