### ISSUE TITLE
Skipped Tests are not displayed on ExtentReports

### ISSUE THREAD

**Issue by abhi90901** [anshooarora/extentreports-java#948]
@AfterMethod
         public void getResult(ITestResult result){
	  if(result.getStatus() == ITestResult.FAILURE){
		logger.log(LogStatus.FAIL, "Test Case Failed is "+result.getName());
		logger.log(LogStatus.FAIL, "Test Case Failed is "+result.getThrowable());
		String imagePath=TakeaScreenShot();
		logger.log(LogStatus.FAIL, "SnapShot Below: "+ logger.addScreenCapture(imagePath));
	}else if(result.getStatus() == ITestResult.SUCCESS){
		logger.log(LogStatus.PASS, "Test Case Passed is "+result.getName());
	}else if(result.getStatus() == ITestResult.SKIP){
		logger.log(LogStatus.SKIP, "Test Case Skipped is "+result.getName());
	}

       }

       @Test
    public void TS_A() throws IOException, InterruptedException{
		Assert.assertTrue(false);
	}
            @Test
         public void TS_B(dependsOnMethods={"A"}) throws IOException, InterruptedException{
		Assert.assertTrue(false);   //doesn't matter
	}

The Extent report shows only A as fail.. reason being for the second one the AfterMethod will never be invoked Please help me on this.. as how to get the skipped test case in Report

**Comment by harsh976** [comment]
@abhi90901

Temp fix can be :
u can add soft dependacies here like : @Test(alwaysRun = true, dependsOnMethods = { "A" })

This creates a soft dependency, i.e. the annotated test should be executed even if the tests it depends on failed/threw an exception and it will invoke in after method.

Permanent fix implement listener:

creating a class that will catch all your ITestResult even the skipped one and then you can implement want to do like that :

public class TestListener implements ITestListener {
   public void onTestSkipped(ITestResult result) {
       // do your stuff here
   } 
}
and to use it in your test do it like that :

@Listeners ({TestListener.class})
public class Example{

    @Test
    public void testabc() {
    }
}

**Comment by anshooarora** [comment]
Thanks. Examples for ITestListener and IReporter are available in the official docs also.
