### ISSUE TITLE
addScreenCaptureFromBase64String Method not found in 3.0.7

### ISSUE THREAD

**Issue by harsh976** [anshooarora/extentreports-java#950]
@anshooarora 

Unable to find addScreenCaptureFromBase64String method even after updating the jar to 3.0.7

please let me know whether this is available in community version or not ?

**Comment by harsh976** [comment]
@anshooarora any update here ?

**Comment by anshooarora** [comment]
Version 3.0.7:

```
extent.
    createTest("test")
    .pass("base64", MediaEntityBuilder.createScreenCaptureFromBase64String(""));
```

**Comment by harsh976** [comment]
Community or open source ?

**Comment by anshooarora** [comment]
Both are same,  and supported.

https://github.com/anshooarora/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/MediaEntityBuilder.java#L47
