### ISSUE TITLE
Custom columns for TESTS

### ISSUE THREAD

**Issue by richmondkaalia** [anshooarora/extentreports-java#953]
Hi,
Recently got to know about ExtentReports. Thanks, Anshoo for providing this fabulous feature!
I wanted to know if there's a way to add new columns or change the "Stepname" column that gets displayed for TESTS (Status, Timestamp, Stepname, Details) ?
I was hoping to add columns between Timestamp and Details like below:
Status, Timestamp, **customColumn1**, **customColumn2**, **customColumn3**, Details

Please let me know if this is possible.

**Comment by anshooarora** [comment]
It is currently not possible but I am working on a feature to convert a pojo to a custom table.

**Comment by richmondkaalia** [comment]
Thanks! Looking forward to it!

**Comment by anshooarora** [comment]
In the meantime, you can insert a custom table from Object[][]:

https://github.com/anshooarora/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/markuputils/MarkupHelper.java#L18

```
Markup m = MarkupHelper.createTable(new String[] { "", "" });
test.pass(m);
```

**Comment by richmondkaalia** [comment]
Is this for Pro version only? I'm getting the below in Eclipse.
"The method pass(Markup) is undefined for the type ExtentTest"

**Comment by anshooarora** [comment]
Your version?

**Comment by richmondkaalia** [comment]
3.0.7

**Comment by anshooarora** [comment]
Community 3.0.7:

```
extent
    .createTest("test")
    .pass(MarkupHelper.createTable(new String[][] { {"A"}, {"B"} }));
```

**Comment by richmondkaalia** [comment]
Thanks, Anshoo!
I was expecting it to show between Timestamp and Details, but it's showing up as something different (see attached).

![2017-09-21 15_46_20-extentreports](https://user-images.githubusercontent.com/32167209/30715435-58a52fac-9ee4-11e7-9566-e3f12370d84d.png)
