### ISSUE TITLE
GherkinKeyword Scenario Outline Not Working

### ISSUE THREAD

**Issue by rajatthareja** [anshooarora/extentreports-java#956]
https://github.com/anshooarora/extentreports-java/blob/ba4629db779eb9e2cc3b4c14c4eedf4c3625daa8/src/main/java/com/aventstack/extentreports/GherkinKeyword.java#L66

`new GherkinKeyword("Scenario Outline")
 or 
new GherkinKeyword("scenario outline")`
**Throws Exception:** 
*java.lang.ClassNotFoundException: com.aventstack.extentreports.gherkin.model.Scenario Outline*

`new GherkinKeyword("ScenarioOutline") or new GherkinKeyword("scenarioOutline")`
**Throws Exception:** 
*java.lang.ClassNotFoundException: com.aventstack.extentreports.gherkin.model.Scenariooutline*

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**Comment by anshooarora** [comment]
Merged PR
