### ISSUE TITLE
Extent Reports - All logs of previous Tests appears at the last Tests

### ISSUE THREAD

**Issue by msedhu** [anshooarora/extentreports-java#959]
@anshooarora 
Hi Anshoo,

**Summary**
Logs are empty in Extent Reports for all Tests except last executed Test . Attached below is the screen shot of the same. 
![nologs_extent](https://user-images.githubusercontent.com/32335163/30921154-c52776c4-a373-11e7-8ca5-2b507866cc37.png)

Also last executed test has all previous executed logs. I would like to know what is incorrect in my implementation. I am using Extent Reports 3.0.7 version with Maven. 

![mergeextentlogs](https://user-images.githubusercontent.com/32335163/30921251-020a080e-a374-11e7-9651-220aa88dcf19.png)

@BeforeSuite
	public void reportSetup() {
			htmlReporter = new ExtentHtmlReporter(".//test-output/AutomationReport.html");
			htmlReporter.setAppendExisting(true);
			extent = new ExtentReports();
			extent.setSystemInfo("OS","Windows");
			extent.setSystemInfo("Browser",browser);
		//	extent.setReportUsesManualConfiguration(true);
			extent.attachReporter(htmlReporter);
			htmlReporter.config().setChartVisibilityOnOpen(true);
			htmlReporter.config().setDocumentTitle("IUHealth Automation Report");
			htmlReporter.config().setReportName("IUHealth Execution Report");
			htmlReporter.config().setTestViewChartLocation(ChartLocation.TOP);
			htmlReporter.config().setTheme(Theme.STANDARD);
			htmlReporter.config().setCSS("body:not(.default) {overflow: scroll !important;}");
		}
@AfterMethod
	public void getResult(ITestResult result) throws Exception{ 
		if(result.getStatus()== ITestResult.FAILURE){
			String screenshotpath = GetFullPageScreenShot.capture(driver, "screenshotname");
			test.log(Status.FAIL,MarkupHelper.createLabel(result.getName()+" Test Case FAILED due to below issues:", ExtentColor.RED));
			test.fail(result.getThrowable());
			test.fail("Snapshot below: "+test.addScreenCaptureFromPath(screenshotpath));
		}
		else if(result.getStatus()==ITestResult.SUCCESS){
			test.log(Status.PASS, MarkupHelper.createLabel(result.getName()+" Test Case PASSED",ExtentColor.GREEN));
		}
		else{
			test.log(Status.SKIP, MarkupHelper.createLabel(result.getName()+" Test Case SKIPPED",ExtentColor.ORANGE));
			test.skip(result.getThrowable());
		}
	}

@AfterSuite
	public void reportTeardown() {
		extent.flush();
	}

![extent_fewmore](https://user-images.githubusercontent.com/32335163/30921707-1b634dfa-a375-11e7-8a7b-921f8b052756.png)

**Comment by anshooarora** [comment]
I would suggest going over the documentation once, especially the [examples section](http://extentreports.com/docs/versions/3/java/#examples).
