### ISSUE TITLE
New feature Request - Adding HTML table to dashboard for test environment information

### ISSUE THREAD

**Issue by ssirekumar** [anshooarora/extentreports-java#96]
Hi Extentreports,

If we have feature like adding a HTML table to dashboard, This table have all the information about test environment to crate this at java side we give parameter as "ArrayLIst<<ArrayList<String>>", Map object,

And same as above we need to have one more user friendly HTML table creation to add in the dashboard, this may be helpful for user to add any thing related to his application information. 

with this feature we can remove what we have existing one like individual box's in the report. "We are including smaller information why we need to waste our report space". 
![2015-10-04_13-52-07](https://cloud.githubusercontent.com/assets/10174519/10267037/2583096c-6a9f-11e5-9b84-761a02a5bd0c.png)

Please find the link what exactly the tester is looking.
![2015-10-04_13-38-31](https://cloud.githubusercontent.com/assets/10174519/10267035/e25d13bc-6a9e-11e5-98d4-89f2948fa0db.png)

**Comment by anshooarora** [comment]
I like your suggestion.  The currently beta is very close to the final release so will add this in the later releases.

**Comment by anshooarora** [comment]
The latest sample here:  http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html

It now shows the system info as a table.

**Comment by ssirekumar** [comment]
Yes its good, I want to add one more thing for this same one can be added by user? i mean user want to add some table to dashboard like he want to add the information regarding on his application. If you give this kind of capability it would be great. If already there how can we add this?

**Comment by anshooarora** [comment]
What would be a good design to implement this from a user perspective?  Create an overloaded function and allow the user to select the table?  I am just concerned that if the design changes tomorrow to a new view, the overloaded methods may get deprecated.  Would like to hear your thoughts on this.

**Comment by ssirekumar** [comment]
Yes you are right, We have to think in longer run. In this my opinion is any way we are maintaining a base method for adding environment information why don't we create new method for user to add his information. call the base method in new created method. With this if the base method have any changes this will effect the user method too. But keep the limitations for table each table can add only 6-8 rows of data this will give us a dashboard would be clean and clear. If the user want to add more he have to call this new method one more time.

**Comment by anshooarora** [comment]
This is now available in 2.40b.

**Comment by vijaykamagar** [comment]
Hi Anshoo,

I am using extent report of version 2.41 and I want to add couple of columns in the dashboard.You have mentioned here.. This enhancement is available in 2.40.Could you please let me know how can I add new columns to Result dashboard please.

**Comment by email2vimalraj** [comment]
@vijaykamagar : You cannot add new columns, however the new rows can be added by using `report.setSystemInfo(key, value)`.

**Comment by email2vimalraj** [comment]
Closing this since the reported feature had been done.

**Comment by rajeshkumarvalakonda** [comment]
@anshooarora : I want put values in table format in extent report. Could you please let me know how to print it. i have tried by giving html table code but its not printing in table format. 

Thanks,
Rajesh

**Comment by email2vimalraj** [comment]
@rajeshkumarvalakonda : Could you please share the code which you have tried?

**Comment by RajeshValakonda** [comment]
Hi @email2vimalraj : Please find the code which i tried

if (KeyValues.containsKey(excelValueMap.keySet().toArray()[i])) {
                if (excelValueMap.get(excelValueMap.keySet().toArray()[i]).equals(KeyValues.get(excelValueMap.keySet().toArray()[i]))) {
                    System.out.println("PASS");
                    System.out.println("Parameter:" + excelValueMap.keySet().toArray()[i] + "Expected:" + excelValueMap.get(excelValueMap.keySet().toArray()[i]) + "Actual:" + KeyValues.get(excelValueMap.keySet().toArray()[i]));
                    test.log(LogStatus.INFO, "<table><tr><td>" + excelValueMap.keySet().toArray()[i] + "</td><td>" + excelValueMap.get(excelValueMap.keySet().toArray()[i]) + "</td><td>" + KeyValues.get(excelValueMap.keySet().toArray()[i]) + "</td><td>"+ "PASS"+"</td></tr></table>");
                } else {
                    System.out.println("==========FAIL=========");
                    System.out.println("Parameter:" + excelValueMap.keySet().toArray()[i] + "Expected:" + excelValueMap.get(excelValueMap.keySet().toArray()[i]) + "Actual:" + KeyValues.get(excelValueMap.keySet().toArray()[i]));
                    test.log(LogStatus.INFO, "<table><tr><td>" + excelValueMap.keySet().toArray()[i] + "</td><td>" + excelValueMap.get(excelValueMap.keySet().toArray()[i]) + "</td><td>" + KeyValues.get(excelValueMap.keySet().toArray()[i]) + "</td><td>"+ "PASS"+"</td></tr></table>");
                    
                }
            }	
			

Thanks in advance. Please let me know if you need any more details

Thanks,
Rajesh

**Comment by RajeshValakonda** [comment]
@email2vimalraj Any Updates on above??
