### ISSUE TITLE
Not able to get the pass percentage in report

### ISSUE THREAD

**Issue by prakashvivek89** [anshooarora/extentreports-java#962]
Hi @anshooarora 

Hope you must be fine :)

I'm not able to get the pass percentage in the html report.
![no pass percentage](https://user-images.githubusercontent.com/25686921/31380248-6436ee7a-adce-11e7-87a9-c0eee6096db9.png)

**Comment by anshooarora** [comment]
If you hover over the passed tests below the chart, you should see it.
