### ISSUE TITLE
How to display start time, End time and time taken in the report

### ISSUE THREAD

**Issue by nayanaith** [anshooarora/extentreports-java#963]
## Summary
In the extent report it is not displaying Start, End and Total time taken in the report as it is displaying in http://relevantcodes.com/Tools/ExtentReports2/Extent.html.
Can you tell me how to configure it so that those are displayed in the top section of the report?

## Expected Behavior
(http://relevantcodes.com/Tools/ExtentReports2/Extent.html)

## Current Behavior
![extntrport](https://user-images.githubusercontent.com/8453660/31580496-c4314596-b116-11e7-88b6-64082f8eb0a6.jpg)

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used:
* Operating System and version:
* JDK Version:

**Comment by anshooarora** [comment]
This is not possible, but you can start the report with the dashboard view enabled first. To do so, use:

```
configureView(-1);chartsView('dashboard');
```

under scripts tag in config.xml, or use `config().setJS(str)`;
