### ISSUE TITLE
How to display the categories only for the project selected

### ISSUE THREAD

**Issue by pujaranichand** [anshooarora/extentreports-java#968]
Hi Anshoo,

   I want to view the categories only for the project selected on the extentXReporter. Currently it is displaying all the categories from all the projects. 

![image](https://user-images.githubusercontent.com/24644827/31703542-a47937ea-b3fa-11e7-889d-01428ad4b8f8.png)

**Comment by anshooarora** [comment]
ExtentX is deprecated. Please use Klov instead.

You would need to upgrade to version 3.1.0 of the API (both pro and community).
