### ISSUE TITLE
How to insert company logo in the extentXReporter3.0

### ISSUE THREAD

**Issue by pujaranichand** [anshooarora/extentreports-java#969]
Hi Anshoo,

    How to insert the company logo in the extentXReporter3.0?
I tried to follow the steps mentioned here but it does not work:
https://github.com/anshooarora/extentreports-java/issues/54

Thanks
Puja

**Comment by anshooarora** [comment]
ExtentX is deprecated.  Please use Klov instead.

If you want to do this though, do it from this file:

https://github.com/anshooarora/extentx/blob/master/views/partials/sidenav.ejs
