### ISSUE TITLE
Change X-Axis of the performance report to build number

### ISSUE THREAD

**Issue by pujaranichand** [anshooarora/extentreports-java#971]
Hi Anshoo,

   I would like to change the X-Axis of the performance report to display the build number. Can you let me know how to change that?

![image](https://user-images.githubusercontent.com/24644827/31933064-aa116b80-b8c5-11e7-847e-e8ff31088c73.png)

**Comment by anshooarora** [comment]
You can click the tool on the top-right hand side of the box and check report name there.
