### ISSUE TITLE
The time in the test performance summary and the report summary are not in showing correctly

### ISSUE THREAD

**Issue by pujaranichand** [anshooarora/extentreports-java#972]
Hi Anshoo,

    If you look at the screenshot. The time in the performance analysis and the report report list are not showing the same. The time in the report summary is the correct one.  Please let me know how I can rectify this.
![image](https://user-images.githubusercontent.com/24644827/31937326-a777cc00-b8d1-11e7-877f-996bb5e1fd5a.png)

**Comment by anshooarora** [comment]
The time is the same in both the chart and the table.  What am I missing?
