### ISSUE TITLE
ExtentReport 3.0.7 - Output file (.html) not Created

### ISSUE THREAD

**Issue by WhatUGit** [anshooarora/extentreports-java#974]
## Expected Behavior

Running the attached code should create test-output folder and create a html extent file.  As I understand the Extent Reports, the file should be created if it does not already exist.

## Current Behavior

The folder "test-output" is created but the file is missing. The output indicates file not found Error. Output screen shot attached.  If I manually create a file, then the correct results are appended to the file.  But occasionally, after repeatedly running TestNG, it appears to successfully create the file.

## Sample

[ExtentDemo.txt](https://github.com/anshooarora/extentreports-java/files/1419414/ExtentDemo.txt)

```

## Environment Details

* Extent report Version used: 3.0.7
* Operating System and version: Windows 10 - 1703
* JDK Version:  jdk1.8.0_144

## Screenshots
![image](https://user-images.githubusercontent.com/32855693/32067303-94c405f8-ba37-11e7-8581-f0a2a2e2b85e.png)

**Comment by anshooarora** [comment]
Can you share your startup code for `ExtentHtmlReporter`?

**Comment by anshooarora** [comment]
In your startup code, use this:

```
htmlReporter = new ExtentHtmlReporter("test-output/myExtentReport.html");
```

**Comment by WhatUGit** [comment]
Hi Anshoo,
Thanks for the request. i had help figuring out the issue. The Folder, Test-output , was created after the file creation so I just wrote a few lines to add the folder if it doesnt exist. That fixed the issue. The working file is below.  Thanks

*********************************************************************************

package AdvacerReports;

import java.io.File;

import org.junit.Assert;
import org.testng.ITestResult;
import org.testng.SkipException;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.markuputils.ExtentColor;
import com.aventstack.extentreports.markuputils.MarkupHelper;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
 
public class copiedExtent {
 ExtentReports report;
 ExtentHtmlReporter htmlReporter;
 ExtentTest logger;
 
 @BeforeTest
 public void startTest() {
 
     File OutputFolder = new File("./test-output");
     if (!OutputFolder.exists()) {
    	 if(OutputFolder.mkdir()) {
             System.out.println("Directory is created!");
    	 }
    	 else  {   System.out.println("Failed to create Directory");
          } 
      }else {System.out.println("Diretory already exists");
      }
     
     
     
	 
     report = new ExtentReports();
 // Provide the Report Path
		 htmlReporter = new ExtentHtmlReporter(System.getProperty("user.dir") + "//test-output//happyReport.html");
		 report.attachReporter(htmlReporter);
		 report.setSystemInfo("Host Name", "MSi");
		 report.setSystemInfo("Env", "Automation Testing");
		 report.setSystemInfo("User", "Malkit Sidhu");
	 }
 
		 @Test
		 public void demoTestPass(){
		 logger = report.createTest("demoTestPass");
		 Assert.assertTrue(true);
		 logger.pass("Assert pass as Condition is Pass"); 
		 
		 logger.log(Status.INFO, MarkupHelper.createLabel("*************** Using Labels ***************", ExtentColor.RED));
	     logger.log(Status.INFO, MarkupHelper.createLabel("This is Test Logger 1", ExtentColor.BLUE));
	     logger.log(Status.INFO, MarkupHelper.createLabel("This is Test Logger 2", ExtentColor.BLUE));
	     logger.log(Status.INFO, MarkupHelper.createLabel("This is Test Logger 3", ExtentColor.BLUE));
	     logger.log(Status.INFO, MarkupHelper.createLabel("This is Test Logger 4", ExtentColor.BLUE)); 

	}
 
		 @Test
		 public void demoTestFail(){
		 logger = report.createTest("demoTestFail");
		 Assert.assertTrue(false);
		 logger.pass("Assert Fail as Condition is False"); 
	 }
 
		 @Test
		 public void demoTestSkip(){
		 logger = report.createTest("demoTestSkip");
		 throw new SkipException("Skipping As Test is not ready");
	}
 
/*		 @AfterMethod
		 public void getTestResult(ITestResult result){
		 if(result.getStatus()==ITestResult.FAILURE)
		 {
		 logger.fail(result.getName());
		 logger.fail(result.getThrowable());
		 }else if(result.getStatus() == ITestResult.SKIP){
		 logger.skip("Test Case Skipped is "+result.getName());
		 } 
	 }
 */
		 @AfterMethod
			public void getResult(ITestResult result)
			{
				if (result.getStatus()==ITestResult.FAILURE) {
						logger.log(Status.FAIL, MarkupHelper.createLabel(result.getName()+ " ========= Failure due to following issues ========", ExtentColor.GREEN));
						//logger.log(Status.FAIL, MarkupHelper.createLabel(result.getName(), ExtentColor.PURPLE));

						logger.fail(result.getThrowable());
						//+ "Test Case Failed due to below issues"
					}
					
				if (result.getStatus()==ITestResult.SUCCESS) {
						logger.log(Status.PASS, MarkupHelper.createLabel(result.getName()+ "  ========Massive Success========= ", ExtentColor.GREEN));
						//logger.log(Status.PASS, MarkupHelper.createLabel(result.getName(), ExtentColor.ORANGE));
						//+ "Test Case Passed "
					} 
				
				else  {
						logger.log(Status.SKIP, MarkupHelper.createLabel(result.getName()+ "  We are Skipping This", ExtentColor.GREEN));
						logger.skip(result.getThrowable());
						
						//logger.log(Status.SKIP, MarkupHelper.createLabel(result.getName(), ExtentColor.CYAN));//+ "Test Case SKIPPED "
					}
			}
		 
		 
		 @AfterTest
		 public void endreport()
		 {
							 
		 report.flush();
		 }
}

**Comment by 15d6d** [comment]
Hi Anshoo
Can we email .html report in cucumber junit.
