### ISSUE TITLE
Extent Report V 3.0.3

### ISSUE THREAD

**Issue by krishna8181** [anshooarora/extentreports-java#975]
**Issue:
[ExtentReport.zip](https://github.com/anshooarora/extentreports-java/files/1428404/ExtentReport.zip)
** 
Hi Anshoo,
thank you so much for your guidance , i have managed to generate extent report with the screen shots, but when i send the same report to my manager, the screen shots are missing in the report. Even though i have screen shots and reports zipped in the same folder, when i sent it across the images are missing.

**Expected**: Screen shots of Test execution should be visible on Extent report when mailed.

**please find my Screen shot capture code**

try
		{
			TakesScreenshot ts =(TakesScreenshot)driver;
			File  source = ts.getScreenshotAs(OutputType.FILE);
			String dest = "/Users/IJ/ScreenShots/screenshot"+"_"+logFilename+".png";
			File destination = new File(dest);
			FileUtils.copyFile(source, destination);
			System.out.println("screen shot taken" + screenshotname );
			return dest;
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
			return e.getMessage();
		}   

P.S: I have attached my extent report, kindly can you guide me

**Comment by anshooarora** [comment]
Use a relative path such as

```
ScreenShots/screenshot"+"_"+logFilename+".png";
```

And place all your screenshots in the ScreenShots folder at the same level as the report.
