### ISSUE TITLE
In testView Categories filter not working , Status filter working when Status color not changing to Red

### ISSUE THREAD

**Issue by arshwarsi** [anshooarora/extentreports-java#976]
## Summary

By the way , Thanks a lot for this Awesome API you have given to community. Great Work. Not enough my 1 line for your work.

In testView , Categories filter not working at all.

In testView, Status filter working , but when we select any filter in Status, color not changing.

In testView , inside node , childTest (node) category is not showing.

## Expected Behavior

In testView, Status filter working , its header "Status" color should change to Red color indicating any Status filter is selected. when cleared Status filter it should come back to Blue.

In testView , inside node , childTest (node) should also show category.

## Environment Details

Using latest ExtentReport Java api 3.0.7 and java 1.8

## Screenshots
![categoriesinnode](https://user-images.githubusercontent.com/3313990/32209034-9ed4f69c-be1f-11e7-8a72-e015acc8f1c3.PNG)
![extentfilters](https://user-images.githubusercontent.com/3313990/32209040-a80fed2a-be1f-11e7-814b-727e767264e0.PNG)

**Comment by anshooarora** [comment]
Can you share a sample report?
