### ISSUE TITLE
Extent Report generated for TestNG using listener not listing Testng Reporter.log() details in the result for each test cases as a Step.

### ISSUE THREAD

**Issue by anilkale99** [anshooarora/extentreports-java#977]
i am able to generate a extent report using listener for extent report which uses ireporter. But, I am not been able to get logs ie. each steps detail for which I used Reporter.log() in the extent report of kindly help

its my code for the listener

@override
public void generateReport(List xmlSuites, List suites, String outputDirectory) {

	extent = new ExtentReports(new File("extentreport").getAbsolutePath() + "/"+ "index.html", true);
    
    
    extent.loadConfig(new File(new File("config").getAbsolutePath() + "/" + "config.xml"));  
    
    for (ISuite suite : suites) {
        Map<String, ISuiteResult> result = suite.getResults();

        for (ISuiteResult r : result.values()) {
             
        	ITestContext context = r.getTestContext();

            buildTestNodes(context.getPassedTests(), LogStatus.PASS);
            buildTestNodes(context.getFailedTests(), LogStatus.FAIL);
            buildTestNodes(context.getSkippedTests(), LogStatus.SKIP);
          
        }
    }

    extent.flush();
    extent.close();
}

public  void buildTestNodes(IResultMap tests, LogStatus status) {
   

    if (tests.size() > 0) {
        for (ITestResult result : tests.getAllResults()) {
            test = extent.startTest(result.getMethod().getMethodName());

            test.getTest().setStartedTime(getTime(result.getStartMillis()));
            test.getTest().setEndedTime(getTime(result.getEndMillis()));

            for (String group : result.getMethod().getGroups())
            {   
            test.assignCategory(group);
            }
            
            
            message = "Test " +status.toString().toLowerCase() + "ed";
            
            if (result.getThrowable() != null)
            {
            	message = result.getThrowable().toString();//getMessage();
                    
            }
            
            test.log(status, message);
            
         
            extent.endTest(test);
            
            
            
        }
    }
}

private  Date getTime(long millis) {
    Calendar calendar = Calendar.getInstance();
    calendar.setTimeInMillis(millis);
    return calendar.getTime();        
}

**Comment by anshooarora** [comment]
They will not appear under tests but you can report them to fall under the TestRunnerLogs view.

```java
        for (String s : Reporter.getOutput()) {
            extent.setTestRunnerOutput(s);
        }
```
