### ISSUE TITLE
Extent Reports 3.0.7v : End time and Duration of overall test is incorrect 

### ISSUE THREAD

**Issue by AnushaGovindan** [anshooarora/extentreports-java#978]
Hi Anshoo,

The End Timestamp and Duration displayed as overall result is incorrect (highlighted below).
Whereas, the duration of each individual test is shown correctly and the timestamp on each step is also correct.

Could you please take a look? Its version 3.0.7.

![extrpt_start_end_time_issue](https://user-images.githubusercontent.com/25835346/32387769-eb9c46b4-c09b-11e7-83ea-ecc8ef3ca633.PNG)

Sample Code:

public class SampleExtentReportTests {
    protected static ExtentReports extentRpt;
    protected static ExtentTest extentTest;
    protected static ExtentTest childMethod;

    private static ExtentReports createInstance(String fileName) {
        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(fileName);
        htmlReporter.loadXMLConfig("extent-config.xml");
        extentRpt = new ExtentReports();
        extentRpt.attachReporter(htmlReporter);
        extentRpt.setReportUsesManualConfiguration(true); 
        extentRpt.setAnalysisStrategy(AnalysisStrategy.SUITE);
        return extentRpt;
    }

    @BeforeSuite
    public void htmlReportSetup() throws Exception {
        extentRpt = createInstance("Extent-Report.html");
    }

    @BeforeTest
    public void startExtentReports(ITestContext iTstCntxt) throws Exception {
        extentTest = extentRpt.createTest(iTstCntxt.getName());
    }

    @BeforeMethod
    public void beforeTestMethod(Method method) {
        Test test = method.getAnnotation(Test.class);
       childMethod = extentTest.createNode("TestName: " + method.getName()); 
        childMethod.log(Status.INFO, ("Testing functionality:: " + test.description()));
    }

    @AfterMethod
    public void getResult(ITestResult result, Method method) {
        if (result.getStatus() == ITestResult.FAILURE) {
            childMethod.log(Status.FAIL, MarkupHelper.createLabel("Test Case:: " + result.getName() + " FAILED. " + result.getThrowable(), ExtentColor.RED));
        } else if (result.getStatus() == ITestResult.SUCCESS) {
            childMethod.log(Status.PASS, "Test Case:: " + result.getName() + " PASSED.");
        } else {
            childMethod.log(Status.SKIP, MarkupHelper.createLabel("Test Case:: " + result.getName() + " SKIPPED.", ExtentColor.ORANGE));
        }
        extentRpt.flush();
    }

    @Test(description = "Testing Extent Reports, Start and End Time with duration...")
    public void testStartAndEndTimeOnReports() throws Exception {
        try {
            childMethod.log(Status.INFO, "Start Test !!");
            Thread.sleep(3000);
            childMethod.log(Status.INFO, "Test in Progress...");
            Thread.sleep(3000);
            childMethod.log(Status.INFO, "Test Completed !!");
            childMethod.log(Status.PASS, "Test Passed");

        } catch (Exception ex) {
            Assert.fail("Exception occurred: " + ex.getMessage());
        }

    }

}

Thanks.

**Comment by anshooarora** [comment]
Remove this line from your code:

```
extentRpt.setReportUsesManualConfiguration(true);
```

**Comment by AnushaGovindan** [comment]
Thanks Anshoo. Works now.

![extrpt_start_end_time_issue-fixed](https://user-images.githubusercontent.com/25835346/32514960-8616de38-c3cc-11e7-86d5-92f725589082.PNG)
