### ISSUE TITLE
htmlReporter.setStarttime is not setting the time correctly

### ISSUE THREAD

**Issue by pujaranichand** [anshooarora/extentreports-java#980]
Hi Anshoo,

    htmlReporter.setStartTime and htmlReporter.setEndTime is not setting the time correctly.  As a result of which the time showing on the dashboard is not showing correctly.

I have two tests and one of them takes 10secs and the other some milli seconds, but on the dashboard, the correct values are not showing. 

Please take a look at my project. 

Thanks so much Anshoo
[ExtentReport.zip](https://github.com/anshooarora/extentreports-java/files/1447169/ExtentReport.zip)

**Comment by anshooarora** [comment]
It shows 10,329ms on the dashboard (which is equivalent to 10 seconds).  

I see the startTime as:  10:35:29 PM
and endTime: 10:35:40 PM

A gap of over 10 seconds.  These look correct..
