### ISSUE TITLE
HtmlReporter Icons missing from Report

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports-java#982]
## Summary

The icons are missing from the ExtentReports 3.1.0 report generated by the ExtentHtmlReporter class

## Expected Behavior

When the ExtentHtmlReporter generates a new report, the icons on the Dashboard and sub-tabs are missing and showing just the icon name placeholders.

## Current Behavior

Same

## Environment Details

ExtentReports 3.1.0
Java 8
Linux OS

## Screenshots
![extentreports3 1 0](https://user-images.githubusercontent.com/14335696/32664624-e22655c0-c5ff-11e7-8b12-fcd626f8386f.png)

**Comment by anshooarora** [comment]
Do the icons work if you go to a lower version, 3.0.7 for instance?  I would assume they would work and the resource itself may be getting blocked from being downloaded.

**Comment by carlc986** [comment]
Hi Anshoo, I’ll try that version now, are the cons part of the JAR file or if not, where are they coming from, I can have IT check the firewall settings?

Carl

**Comment by carlc986** [comment]
FYI - The icons are missing when I use 3.0.7 also. Where are they getting picked up from?

Carl


From: Carl Cocchiaro <Carl.Cocchiaro@rsa.com<mailto:Carl.Cocchiaro@rsa.com>>
Date: Monday, November 13, 2017 at 8:34 AM
To: anshooarora/extentreports-java <reply@reply.github.com<mailto:reply@reply.github.com>>, anshooarora/extentreports-java <extentreports-java@noreply.github.com<mailto:extentreports-java@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: Re: [anshooarora/extentreports-java] HtmlReporter Icons missing from Report (#982)

Hi Anshoo, I’ll try that version now, are the cons part of the JAR file or if not, where are they coming from, I can have IT check the firewall settings?

Carl

**Comment by shubicus** [comment]
carlc986  --> add the name and version of a browser to **Environment Details**, plz.

PS: It could be your local problem. I use the same stack: ExtentReports 3.1.0, Java 8(151), Debian OS - and there no problems.

**Comment by anshooarora** [comment]
Icons are downloaded from googleapis.com:

https://fonts.googleapis.com/icon?family=Material+Icons

Please check with IT, this link may be getting blocked.

**Comment by carlc986** [comment]
Hi Anshooarora, you were right, it was out firewall blocking it, we needed to install a new Security Cert in our browsers.

One other thing, I noticed the “Time Taken” is in total ms, and the previous report had it in hours, minutes, seconds, and ms, is there anyway to change this to use that format again?

Carl

**Comment by anshooarora** [comment]
yes, it is possible to change the format and can be done using either JavaScript or changing it from the template. I will try to add this in the upcoming version.

**Comment by carlc986** [comment]
Hi Anshoo, many way you can give me a code sample of how to convert the time to HH:MM:SS:MS? Also, it seems the Timestamp is incorrect for the individual test methods, it is using the same end time each test method run? I can send a bitmap if necessary. If you can give me some direction on the total elapsed time conversion that would be great and can it be done in the report or does it have to be in the extent config file?
 Thanks.

Carl


From: Carl Cocchiaro <Carl.Cocchiaro@rsa.com<mailto:Carl.Cocchiaro@rsa.com>>
Date: Monday, November 20, 2017 at 7:23 AM
To: anshooarora/extentreports-java <reply@reply.github.com<mailto:reply@reply.github.com>>, anshooarora/extentreports-java <extentreports-java@noreply.github.com<mailto:extentreports-java@noreply.github.com>>
Subject: Re: [anshooarora/extentreports-java] HtmlReporter Icons missing from Report (#982)

Hi Anshooarora, you were right, it was out firewall blocking it, we needed to install a new Security Cert in our browsers.

One other thing, I noticed the “Time Taken” is in total ms, and the previous report had it in hours, minutes, seconds, and ms, is there anyway to change this to use that format again?

Carl
