### ISSUE TITLE
Lightbox displays full size screen capture instead of thumbnail when using base64

### ISSUE THREAD

**Issue by MkernerTW** [anshooarora/extentreports-java#983]
## Summary
"createScreenCaptureFromBase64String" does not create an inline thumbnail image.

## Expected Behavior

I am using "MediaEntityBuilder.createScreenCaptureFromBase64String" to capture screenshots for reporting with the expectation that an inline thumbnail is generated within the Lightbox and then expanded to full scale when clicked upon.  

## Current Behavior

Currently, the inline image that is generated is displayed at full scale.  I may very well be utilizing this incorrectly, however I would expect this to function similar to "createScreenCaptureFromPath" in that the Lightbox creates an inline thumbnail and then expands to full scale when clicked.  

## Sample

```java
localTest.get().info("", MediaEntityBuilder.createScreenCaptureFromBase64String(base64ScreenshotString).build());
```

## Environment Details

* Extent report Version used: ExtentReports Pro - 3.0.5 
* Operating System and version: Mac - El Capitan
* JDK Version: 8

**Comment by anshooarora** [comment]
This fix will be available in version 3.1.1.

**Comment by sarthak2990** [comment]
This issue is still present on version 3.1.1 and 3.1.2

**Comment by anshooarora** [comment]
@MkernerTW version 3.1.1-pro is now available for download.

**Comment by anshooarora** [comment]
@sarthak2990 this issue was reported for the pro version. Please open a new ticket for the community version,  thank you.

**Comment by MkernerTW** [comment]
@anshooarora Testing this out with pro version 3.1.1, the inline thumbnail continues to display at full size.  I've attempted a number of implementations based on your samples.  Would you be able to share additional samples that you used to test this fix?
