### ISSUE TITLE
HTML report don't deal with special HTML characters that may be present in log messages

### ISSUE THREAD

**Issue by fragonib** [anshooarora/extentreports-java#985]
## Summary

If you report a _log_ inside a _test node_ with a message having a special HTML character, that message is interpreted by browser.

## Expected Behavior

Log messages should be escaped on HTML report. Escaping wouldn't affect to _log detail_ that use custom markup. Custom markup wouldn't be escaped.

## Sample

```java
test.log(Status.PASS, "When I run <first> step");
```

## Environment Details

Extent report Version used: ExtentReports - 3.1.0
Operating System and version: Windows 10
JDK Version: 8

## Screenshot

![unescaped](https://user-images.githubusercontent.com/3868431/32805315-568ad08a-c989-11e7-9c9a-4424b593653a.png)

**Comment by anshooarora** [comment]
You can use:

```
test.info(MarkupHelper.createCodeBlock("<special> character"));
```

This will not escape the special characters.

**Comment by fragonib** [comment]
That renders it differently, isn't it? Should I use that strategy for all the text that user may have used with special character included? Wouldn't the HTML generating template be in charge of that? (For every user text but for markup)

**Comment by anshooarora** [comment]
The problem with escaping such tags is its impossible to determine which to escape.  For example, you will notice many users passing g HTML to these events to render correctly.  There may be `img` `span` etc tags or any other tag that the user wants to pass.  Escaping everything will break the current behavior.

**Comment by fragonib** [comment]
Ok, I see that point. 

Just a another question. Shouldn't someone who want to report markup use this flavour:

`test.log(status, markup)`

instead of 

`test.log(status, detail)`

that would be a good point for _ExtentReports_ to tell different uses apart. Isn't it?

**Comment by anshooarora** [comment]
The above will not render HTML but show it as-is.  2nd is what users will use to highlight elements using tags.  This is why the 1st approach was created.  As for usage, you can simply check what you are logging, for example, any string containing < and > should be passed as a codeblock.
