### ISSUE TITLE
Can add summary test result (pass/failed) for category section, dashboard

### ISSUE THREAD

**Issue by ansonliao** [anshooarora/extentreports-java#986]
Can add summary test result information for category section, dashboard page?

Check the screenshot below, check "Category" section, whether can add a summary column next to 
"Others" that display each category's test result in summary?
For example:
 Total test case number | passed test case number | failed test case number | Passed rate in Green

![image](https://user-images.githubusercontent.com/6060224/32822862-7e7fe92c-ca15-11e7-8730-0c854ed74f9e.png)

**Comment by anshooarora** [comment]
This can be added as an enhancement.

**Comment by ansonliao** [comment]
@anshooarora 
Thanks for your reply.
