### ISSUE TITLE
Extent reports provides null value for soft assertions

### ISSUE THREAD

**Issue by maheshcts97** [anshooarora/extentreports-java#988]
I am running selenium tests in Eclipe from maven. I am using extent reports for reporting. I see a strange behaviour in extent reports for the soft assertion.

Code snipped I have used:

public void verifytest() {
	  
	    logger = extent.createTest("verifytest");
	    UtilFunctions.InvokeBrowser();
	    UtilFunctions.LaunchURL("http://demo.guru99.com/selenium/newtours/");
	    softAssert.assertEquals(UtilFunctions.GetTitle(), "Welcome: Mercury Tours1");
	    softAssert.assertAll();
	
  }

**Output in Extent Reports:**
_java.lang.AssertionError: The following asserts failed: null_

But When I run the same tests in eclipse from testng,

**output in Extent Reports is as follows:**

_java.lang.AssertionError: The following asserts failed: expected [Welcome: Mercury Tours1] but found [Welcome: Mercury Tours]_

**Details of Testng and extent reporting and maven versions I am using**.

**maven-compiler-plugin**
        <version>3.7.0</version>
**maven-surefire-plugin**
    	<version>2.20.1
**com.aventstack**
        <version>3.0.7
**testng**
  	<version>6.8
**org.seleniumhq.selenium**
  	 <version>3.6.0
  

Is it any compatibility issue between Maven and extent Reports?

Can anyone helpme to resolve this issue?

**Comment by anshooarora** [comment]
It is displaying only the information that is being passed from the code usage.  You will have to check what is being passed and why the exception is null. Once you resolve the value of exception, it will display correctly.

**Comment by maheshcts97** [comment]
Hi Anshooarora,

For the same code logic, I get the error message in extent reports when running from testNg.

I get null in extent reports only when I run the tests from maven.

Please let me know if I am not clear enough.
