### ISSUE TITLE
Not able to see screenshots in Extent report (with Jenkins)

### ISSUE THREAD

**Issue by malikkunal** [anshooarora/extentreports-java#990]
## Summary
 I am not able to see screenshots in extent report upon integration with Jenkins.
Screenshots are visible in reports on my local machine.
Have tried giving both absolute and relative path for screenshots. 
Even kept the report and screenshot in same folder.

Code snippet:

extent=new ExtentReports(System.getProperty("user.dir")+"/Report/"+"extent.html",true); 

Screenshot attached with log step

String path = TestUtil.TakeScreenShot(driver);
test.log(LogStatus.FAIL, result.getName()+ " : Failure reason - "+ result.getThrowable());
test.log(LogStatus.FAIL, "Snapshot below: " + test.addScreenCapture(path));

Method for capturing screenshot

TakesScreenshot ts = (TakesScreenshot)driver; 
File src= ts.getScreenshotAs(OutputType.FILE);
String dest = System.getProperty("user.dir")+"\\Report\\"+"screenshot.png";
File destination = new File (dest);
FileUtils.copyFile(src, destination); 
return dest;

## Environment Details

* Extent report Version used: 2.41.2

**Comment by anshooarora** [comment]
Similar:

https://github.com/anshooarora/extentreports-java/issues/100
https://github.com/anshooarora/extentreports-java/issues/468
https://github.com/anshooarora/extentreports-java/issues/590

**Comment by akashsukheja1192** [comment]
@anshooarora The issue is specific to Jenkins, If we open the HTML file locally, the screenshot is visible in the report. However, With HTML Publisher Plugin, the screenshot present in log is not loading.
Getting below error on chrome browser console:
`Not allowed to load local resource: file:///C:/Users/abc.jpg`
