### ISSUE TITLE
categories UI broken

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports-java#991]
@anshooarora categories is broken on latest version 

<img width="1400" alt="screen shot 2017-11-24 at 8 14 23 am" src="https://user-images.githubusercontent.com/4045041/33201075-fb2139f6-d0ee-11e7-9904-e5db7bb677d8.png">

When the window size is 90% it's fine.

**Comment by anshooarora** [comment]
fixed as part of #986 - increased the size of this div to 6 blocks instead of 4.  It will span until the TimeTaken div above.
