### ISSUE TITLE
Extent 3.1.0 Report Time Taken is in total milliseconds

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports-java#999]
## Summary
 When building an IReporter Extent HTML Report, the Dashboard page has the Time Taken in total milliseconds. It used to be in Hours: Minutes:Seconds:Milliseconds, which is more useful.

## Expected Behavior

 The Time Taken for a total suite run should be in format Hours: Minutes:Seconds:Milliseconds, it is not useful to be in total MS, cannot determine how long it took unless converting it with a calculator.

## Current Behavior
MS

## Sample

```java
// Sample code goes here
```

## Environment Details

* Extent report Version used: 3.1.0
* Operating System and version: Linux
* JDK Version: 1.8
![screen shot 2017-12-05 at 8 53 08 am](https://user-images.githubusercontent.com/14335696/33610530-c84c0c3c-d999-11e7-9eea-b111d786ea58.png)

**Comment by carlc986** [comment]
Hi Anshoo, do you have a release date for the fix you added for this issue?

**Comment by SuraiyaMulani** [comment]
Hi Anshoo

i am using 3.1.3 community version - **setSystemInfo**() method adding same key multiple times in html report.
addSystemInfo() method in earlier 2.x versions  was overriding values for same key . 
I need to add browser details but my browser gets launched in before method so for each method its adding same details again and again.


Can someone give me solution for same.

![extent system info](https://user-images.githubusercontent.com/35719582/45611892-c0514f80-ba7e-11e8-84ed-5e727962f4a7.png)
